### ISSUE TITLE
suggestion on project layout

### ISSUE THREAD

**Issue by ialbert** [mothur/mothur#1]
First off thanks for making this a github project, I hope to contribute in the future.

One suggestion I would have is to create a project layout where the source code in in a separate directory like src rather than in the main repository. 

Then one could have another directory called doc (for documentation, the wiki pages should go there), and contrib (for people contributing other related tools), scripts (for say R scripts that visualize outputs) etc.

thanks again for the porting it to GitHub.

best,

Istvan

**Comment by mothur-westcott** [comment]
Linked to #16.
