### ISSUE TITLE
Merge.groups

### ISSUE THREAD

**Issue by mothur-westcott** [mothur/mothur#105]
Add method parameter.  Options are sum, average, median. sum=default which is mothur's current option.

**Comment by mothur-westcott** [comment]
@pschloss What do you want to do with the average and median options when there are OTUs of low abundance.  For example you may have a count table or shared OTU that looks like:

1 0 0 2 0 2 0 0 1 0 0  Given the merging of the groups as:

1 0 0 - average = 0 median = 0
2 0 - average = 1 median = 1
2 0 0 - average = 0 median = 0
1 0 0 - average = 0 median = 0

Do you want to round up for the average? A ceiling on the int? Another approach?

**Comment by pschloss** [comment]
Ugh, I really don't like average and median when people have different numbers of sequences per group. For average can we give the float? And for median can you remove the column?

**Comment by mothur-westcott** [comment]
For the average I could give a float and return a relabund file instead of a shared file, but that wouldn't work for the count table since the count table requires an integer.  Maybe we don't allow average for the count table?? For the median in a shared file, I could remove zero otus.  For the median in the count table, remove sequences that zero out and produce an accnos file you could use to remove those sequences from your other files. Your thoughts??

**Comment by pschloss** [comment]
How about this...

For average and median, check that all of the groups have the same number of sequences, if not - throw an error and stop the command.

Don't use average for a count table. For median, can we force them to provide the fasta file and do the remove.seqs step on the fasta file at the same time?

**Comment by mothur-westcott** [comment]
Completed with commit f487554fd796bf8068353dfd68401eb874e2c85b
