### ISSUE TITLE
Unique.seqs add format parameter

### ISSUE THREAD

**Issue by mothur-westcott** [mothur/mothur#125]
Option: format=count-name

unique.seqs(fasta=yourFasta, format=count)
unique.seqs(fasta=yourFasta, format=name)
unique.seqs(fasta=yourFasta, count=filename) format defaults to count, name not allowed
unique.seqs(fasta=yourFasta, name=filename) format defaults to name, allowed to be count
unique.seqs(fasta=yourFasta)  Default= ?? @pschloss

**Comment by pschloss** [comment]
I'd keep format=name as the default for now

**Comment by mothur-westcott** [comment]
unique.seqs(fasta=yourFasta, count=filename, format=name) - allow for this and treat it like we do in deunique.seqs with a count file.

**Comment by mothur-westcott** [comment]
Completed with commit 7590792ac46837bf3320598ce27ef246dd75f22b
