### ISSUE TITLE
Rename.seqs - shorten names

### ISSUE THREAD

**Issue by mothur-westcott** [mothur/mothur#132]
Create a shorten version of names to avoid corrupted file issues with extremely large distance files.

http://www.mothur.org/forum/viewtopic.php?f=4&t=2647

**Comment by mothur-westcott** [comment]
@pschloss Do we want to add an option to make.contigs to run rename.seqs with this new shorten option so the names are small to start with?

**Comment by pschloss** [comment]
sure. what will the default be? I'm fine with it always changing it to the shortened name unless told not to.

**Comment by mothur-westcott** [comment]
I think default to shorten names would be good.  It would reduce the size of all of the files.  I could add a feature to rename.seqs to output a *.map file that maps the shortened name to the original name.  Then allow the command to accept that file as input.  If the *.map file is given, the names could be returned to the original. What do you think?

**Comment by mothur-westcott** [comment]
Completed with commit b94234ca7537edc758abdd0b563d5cc667a8e99c
