### ISSUE TITLE
set.dir not working correctly

### ISSUE THREAD

**Issue by tracykteal** [mothur/mothur#139]
There seems to be something with set.dir where if you run it more than once, then it won't set the directories the second time you run it. It will output that you did it, but if you look at get.current() you can see that it's not set. 

Details below. 

e.g. 

mothur > set.dir(input=../data/MiSeq_SOP)
Mothur's directories:
inputDir=/Users/tracyt/Desktop/mothur-project/data/MiSeq_SOP/

mothur > set.dir(output=../analyses/)
Mothur's directories:
outputDir=/Users/tracyt/Desktop/mothur-project/analyses/

mothur > get.current()

Current files saved by mothur:

Current output directory saved by mothur: /Users/tracyt/Desktop/mothur-project/analyses/

Current default directory saved by mothur: ./

Current working directory: /Users/tracyt/Desktop/mothur-project/mothur/

Then gives:

mothur > make.contigs(file=stability.files, processors=8)
Unable to open stability.files. Trying default ./stability.files
Unable to open ./stability.files. Trying output directory /Users/tracyt/Desktop/mothur-project/analyses/stability.files
Unable to open /Users/tracyt/Desktop/mothur-project/analyses/stability.files

But if I set the output dir and then the input dir, then I get 

get.current()

mothur > get.current()

Current input directory saved by mothur: /Users/tracyt/Desktop/mothur-project/data/MiSeq_SOP/

Current default directory saved by mothur: ./

Current working directory: /Users/tracyt/Desktop/mothur-project/mothur/

Then, make.contigs(file=stability.files, processors=8) works, but it writes the files out to the input directory.

**Comment by mothur-westcott** [comment]
You need to set the input and output in the same command. Mothur clears the the values that are not set when set.dir is run.  

mothur > set.dir(input=../data/MiSeq_SOP, output=../analyses/)

You can also set the input and output directories on any command.

mothur > make.contigs(file=stability.files, processors=8, inputdir=../data/MiSeq_SOP, outputdir=../analyses/)

**Comment by tracykteal** [comment]
It still seems like something isn't right with set.dir, or maybe something
else. Going through different commands, it seems it would randomly start
looking in other directories or finding files that weren't the right ones.
I was teaching and this was the experience of many people in the class.

Also if this set.dir behavior could be added to the documentation, that
would be great. Happy to edit the wiki directly if the accounts work.

**Comment by mothur-westcott** [comment]
Can you post the

**Comment by tracykteal** [comment]
Using the most recent version. I had just freshly downloaded it. 

I can't recreate the error right now, but I think the problem is coming from the behavior that it doesn't first look in the directory you set as the input directory. It first looks in other defaults, and then it seems to be finding something that it thinks matches, but it's not the right file, so then it throws an error. Multiple people were running in to this problem. 

I guess I just don't understand this command that well and what's really going on behind the scenes enough to troubleshoot when things go wrong. I've really only had consistently good luck putting all the input, output and reference files in the same directory. This is OK, but not optimal project setup. It's probably what I'll do in the future for teaching though. Maybe this is how most people do things, so I'm not sure how high a priority this issue is.

**Comment by mothur-westcott** [comment]
Thanks for leaving a detailed description of the issue.  When mothur is trying to find a file without a full path here are the order of searches.

1. Default path 
2. Output directory  
3. Input directory

The output directory is listed before the input directory because many of mothur's command create files that then are used as inputs on the next command.
