### ISSUE TITLE
mothur MiSeq SOP wiki

### ISSUE THREAD

**Issue by tracykteal** [mothur/mothur#140]
I know this isn't the right place for this issue, but I couldn't create an account on the mothur wiki. I get 

Catchable fatal error: Argument 1 passed to MailAddress::newFromUser() must be an instance of User, string given, called in /Library/WebServer/Documents/w/includes/User.php on line 4204 and defined in /Library/WebServer/Documents/w/includes/mail/MailAddress.php on line 59

I wanted to fix the remove.seqs and remove.lineage commands, because the new version of chimera.uchime puts 'precluster.denovo.uchime' in the output file name, rather than just 'precluster.uchime'

**Comment by mothur-westcott** [comment]
@pschloss can you take a look at the account issue? I will fix the wiki pages.
