### ISSUE TITLE
Add Readme to each folder in Git source

### ISSUE THREAD

**Issue by mothur-westcott** [mothur/mothur#146]
This was suggested in the Git class I took.  A way to describe how to add code and collaborate with the project.  Links to wiki? Like for the commands folder, links to all the commands?? @pschloss, your thoughts?

**Comment by pschloss** [comment]
sounds good - i've also seen on some github-hosted projects links to how to make a pull request and the style / approach that we take. Of course, I can't find it now :)

**Comment by mothur-westcott** [comment]
I found this one really helpful while trying to familiarize myself with their source, https://github.com/torognes/vsearch/blob/master/README.md

**Comment by pschloss** [comment]
agreed - it is pretty thorough

**Comment by mothur-westcott** [comment]
Covered in #183
