### ISSUE TITLE
summary.seqs() error in 1.36 and 1.36.1 on Ubuntu 12

### ISSUE THREAD

**Issue by jooolia** [mothur/mothur#150]
Hi,

I'm running into an error when I try to run summary.seqs on version 1.36 and 1.36.1 on Ubuntu 12.04.5 LTS (GNU/Linux 3.2.0-29-generic x86_64). The command works fine on mothur 1.35 and earlier versions. I saw that there were some old forum posts talking about this error, but the only resolution seemed to be newer versions of mothur. Any ideas on this? Thanks for a great program! 

```
mothur > summary.seqs(fasta=stability.trim.contigs.good.unique.align)

Using 1 processors.
Illegal instruction (core dumped)

```

**Comment by mothur-westcott** [comment]
Did you download our prebuilt executable or build from source? Building from source for 1.36, requires you to install the boost library.  The instructions are in the INSTALL.md file.  If you download the prebuilt executable, did you try the Mothur.cen_64.noReadline.zip version?

**Comment by jooolia** [comment]
Sorry for delay, didn't get github notification. I was using the prebuilt executable. I get the same error with both the Mothur.cen_64.noReadLine.zip and with the Mothur.cen_64.zip.

**Comment by gonzalezem** [comment]
Hello, joining in... Did you finally make it work? I have the same issue on the same OS:

mothur > make.contigs(file=samples.files, processors=10)
Illegal instruction (core dumped)

I tried the different 1.36.1 releases of Mothur.cen, but I did not have any success about it.

**Comment by mothur-westcott** [comment]
Can you try the Mothur.cen_64.noOpt.zip version, https://github.com/mothur/mothur/releases/tag/v1.36.1?

**Comment by gonzalezem** [comment]
Thanks for the answer, I already tried those three without any success
Mothur.cen_64.noOpt.zip
Mothur.cen_64.noReadLine.noOpt.zip
Mothur.cen_64.zip

What I ended up doing is running the 1.35.1 release which works fine on my machine (Ubuntu 12.04.5)

**Comment by mothur-westcott** [comment]
We have been unable to reproduce this error yet.  Could you tell me are you running on an amd processor?

**Comment by gonzalezem** [comment]
Intel(R) Xeon(R) CPU  E5620  @ 2.40GHz

**Comment by jooolia** [comment]
I've had other people e-mail saying that they are also having this problem. 

We're running AMD Opteron(tm) Processor 6128 2.0gHz with 16 cores.

**Comment by mothur-westcott** [comment]
Okay, I think I have narrowed down the issue.  Mothur's Linux version (prebuilt) was optimized for the Intel chip set.  Can you try the latest generic version I unloaded, Mothur.linux_64.zip?

**Comment by gonzalezem** [comment]
Thanks! It works well for me now.

**Comment by mothur-westcott** [comment]
Great! Thanks for helping us resolve this issue.  In case you are curious... Our prebuilt version used the compile flag mtune=native which optimized the source for an Intel chip.  The mtune flag should have been set to "generic" to allow for all chip sets.  The reason 1.35 worked is with the removal of source the compiler will optimize the code in slightly different ways.
