### ISSUE TITLE
Command line mode doesn't return exit-code to indicate failure.

### ISSUE THREAD

**Issue by bsmith89** [mothur/mothur#151]
I'm trying to incorporate some mothur commands into a Makefile using the `mothur "#some.command()"` syntax (http://www.mothur.org/wiki/Command_line_mode).

At least for all of the examples I've tried (e.g. `mothur "#not.a.command()"`), the exit code is always 0.  This leads to problems when the remaining steps in the pipeline execute.

I realize I'm trying to use mothur in a way it was not designed, but I'm hoping it's not a difficult patch.  I'd also like a command-line option to turn off the welcome screen, but that's a different issue.

**Comment by bsmith89** [comment]
I see this has been discussed before: http://mothur.org/forum/viewtopic.php?f=10&t=2699

**Comment by pschloss** [comment]
Thanks Byron - we've been working on adding a few more command line options in the recent releases. We'll add a flag to remove the welcome screen. Also we'll have mothur rerun a 1 on successful completion and a 0 if there's an error. 

We appreciate the suggestions!
Pat

**Comment by bsmith89** [comment]
Maybe that was a typo, but just in case: the normal "success" exit code on UNIX is 0, other numbers indicate failure.

**Comment by pschloss** [comment]
I see, you want it to be 1 if there's an error - right?

**Comment by bsmith89** [comment]
Yep, exactly.  Some people will use different exit codes to mean different
things, but just returning "1" will work perfectly for my needs.

**Comment by mothur-westcott** [comment]
If you want to skip the welcome screen you can run mothur in "quiet" mode.

./mothur "#myCommand(...);" -q

**Comment by bsmith89** [comment]
Oh, I didn't realize that.  Thanks for the tip!

**Comment by mooreryan** [comment]
I know this is an older issue, but I am running into the same problems as @bsmith89

**Comment by mothur-westcott** [comment]
Thanks for hitting this thread again, :).  In version 1.37 we added output to the log file indicating the number of errors and warnings.  The 1.38.0 branch includes the return codes you are looking for.  If the log file indicates errors the return code will be set to 1, otherwise 0.
