### ISSUE TITLE
version 1.36.1 doesn't work on Mac OS X version 10.8.x

### ISSUE THREAD

**Issue by tracykteal** [mothur/mothur#152]
I think you know this already, but version 1.36.1 doesn't work on Mac OS X version 10.8.x  It appears that version 1.35.x also doesn't work on 10.8.x. I know you can't support all OSes, but it might be nice to have this documented somewhere on the downloads page. 

Also, could an older version that does work on 10.8.x be available as a binary rather than something that has to be compiled from source? Or is the idea that you want to stop having people use older versions? I know it does get confusing from the perspective of having documentation and SOPs that don't match the older versions.

**Comment by pschloss** [comment]
Hey Tracy,

As you've gathered this is a frustration of ours. The other one is people wanting us to maintain 32 bit versions, which they probably can't use to do much of anything with next generation sequence data. 

Anyway, the mac problem is that we just can't maintain the older OSs. Also I suspect that if the users hardware can't support the more recent releases, they probably will be limited in what they can analyze. Do you know of a compiler or service that allows us to compile in 10.10 for code to be run on 10.8? 

Thanks for the feedback!
Pat

**Comment by tracykteal** [comment]
I agree that you can't maintain the older OSs, and you're right that the only time they would really be doing things on their own machine is in a teaching context. 

Would it be possible to update the documentation on the Downloads page to say what OSs are supported, or ones that you know the newest release doesn't support? The main problem was that I wasn't aware of the issue, so didn't plan accordingly when it wasn't working for people, and people couldn't immediately figure out what was going wrong.

**Comment by mothur-westcott** [comment]
Sure, this is a good suggestion.  We can add it to our release notes.

**Comment by tracykteal** [comment]
Thanks! Can it also be added on the Download web site.
http://www.mothur.org/wiki/Download_mothur
I'm not sure which OSes it works or doesn't work on, so I don't want to add
it myself.

**Comment by mothur-westcott** [comment]
:+1:

**Comment by tracykteal** [comment]
W00t! Thank you. :+1:
