### ISSUE TITLE
Add permute option to get.sharedseqs

### ISSUE THREAD

**Issue by mothur-westcott** [mothur/mothur#155]
We've been asked this a few times.

http://www.mothur.org/forum/viewtopic.php?f=3&t=3867&sid=11cea02d8a4d425c9754b2b7d700a008

What do you think? @pschloss

**Comment by pschloss** [comment]
Sure, sounds good.

**Comment by pschloss** [comment]
I'm revising my thoughts on this... this seems like something that people could get out of dist.shared or via scripting.
