### ISSUE TITLE
Filter.seqs / Screen.seqs - sequences are not the same length error

### ISSUE THREAD

**Issue by mothur-westcott** [mothur/mothur#160]
Rare occurrence.  Need to take a closer look.

**Comment by mothur-westcott** [comment]
2 reports with use of summary file.  Not sure if this is the only way the bug occurs. Number of processors has no effect.

screen.seqs(fasta=seqs.trim.contigs.good.unique.align, count=seqs.trim.contigs.good.count_table, summary=seqs.trim.contigs.good.unique.summary, optimize=end-start-maxhomop, criteria=95, minlength=400)

**Comment by mothur-westcott** [comment]
screen.seqs with summary file overwrites summary file with new screened summary file.  Could this be causing issues if rerun? Either way we should change it.

**Comment by mothur-westcott** [comment]
One user reported low hard drive space as the cause of the issue.

**Comment by mothur-westcott** [comment]
RAM issue caused the problem for another user.  The process failed with no error and appended unprocessed reads.  She was a windows users.  Investigate adding GetLastError() function. https://msdn.microsoft.com/de-de/library/windows/desktop/ms679360(v=vs.85).aspx

**Comment by mothur-westcott** [comment]
Completed with 24d445d05ab45fb7e3b7b6cce9cc6cbd63c37849

**Comment by SophieS9** [comment]
Hi! I'm working with a researcher who is experiencing this error with mothur (version 1.39.0) when running the following:
```
filter.seqs(fasta=Samples.makecontigsfile.trim.contigs.good.unique.good.align, vertical=T, trump=.)
```

They've tried with both 80G and 160G memory and after some time it crashes with the following error:

```
[ERROR]: Sequences are not all the same length, please correct.
```

Can't see where it's going wrong. I've attached the four log files produced so far, unfortunately the last command doesn't come up on the log. 

Any ideas welcome!! 

[mothur.1492684290.logfile.txt](https://github.com/mothur/mothur/files/954766/mothur.1492684290.logfile.txt)
[mothur.1492690230.logfile.txt](https://github.com/mothur/mothur/files/954765/mothur.1492690230.logfile.txt)
[mothur.1492690374.logfile.txt](https://github.com/mothur/mothur/files/954767/mothur.1492690374.logfile.txt)
[mothur.1493110766.logfile.txt](https://github.com/mothur/mothur/files/954764/mothur.1493110766.logfile.txt)

**Comment by mothur-westcott** [comment]
Have you tried this with our current version, 1.39.5? If you still have an error, can you try running the filter.seqs command in debug mode?

mothur > set.dir(debug=t)
mothur > filter.seqs(...)

**Comment by SophieS9** [comment]
Thanks for getting back to me. Unfortunately we're stuck with version 1.39.0 because of the cluster system we work on, but if this is going to be the only fix I can push admin to upgrade! 

I've attached the log file from running the command in debug mode. It's mostly blank lines but there is output at the end of the file. The majority of the sequences showed length 50,000 but there are five that are different. Although the filter.seqs command finished, the filtered fasta file wasn't produced. 

[mothur.1493196199.logfile.txt](https://github.com/mothur/mothur/files/957891/mothur.1493196199.logfile.txt)

**Comment by crivaldi** [comment]
Hi mothur folks, 
I'm using 1.39.5 and coming up with the same error after filter.seqs. I've attached the debug report (please note I added the commented out sections to omit a large section of very similar lines, can re-upload with these lines included if necessary). I am working on a linux redhat cluster (64-bit) and have >200G of available hard disk space. No files were produced (aside from the logfile). This completes in less than a second.

For what it's worth, I'm running through the pipeline with only one sample before I use my whole dataset (total sequences ~10m). 

Thanks for any ideas/thoughts you might have. 

[mothur_debug.txt](https://github.com/mothur/mothur/files/1741748/mothur_debug.txt)
