### ISSUE TITLE
Replace CatchAll

### ISSUE THREAD

**Issue by pschloss** [mothur/mothur#164]
CatchAll is a pain to support. It's also the only command where we require users to download separate tools to use. I would like to remove it from mothur.

We would then replace it with a new command - to be named - that would have very similar functionality, by incorporating code from Chris Quince. Chris developed the algorithms behind shhh.flows and get.communitytype. He has code up here:

http://userweb.eng.gla.ac.uk/christopher.quince/Software/BDES.html

The original citation is here:

http://userweb.eng.gla.ac.uk/christopher.quince/Papers/Quince2008.pdf

For the user interface, I wonder how difficult it would be to implement the various methods as calculators within the summary.single/collect.single/rarefaction.single commands. One concern is that they take too long to be run in this manner. Perhaps we just have it as a separate command where the output is three files that look like tables 1-3 from the pdf linked above.

Another possible problem includes his use of the GNU Scientific Library. I think the GSL functions he uses would be pretty simple to implement separate from the GSL.

**Comment by mothur-westcott** [comment]
@pschloss, do you want to include this in 1.42.0?

**Comment by pschloss** [comment]
You mean remove it? Yeah that would be good. 

Sent frim my iPhone, expext more typos then nirmal

**Comment by mothur-westcott** [comment]
To do - Install GSL

**Comment by mothur-westcott** [comment]
Add each diversity estimator as a calc in mothur:

* [ ] erarefaction
* [ ] igabundance
* [ ] igrarefaction
* [ ] lnabundance
* [ ] lnrarefaction
* [ ] lnshift
* [ ] lsabundance
* [ ] lsrarefaction
* [ ] metrolognormal
* [ ] metrologstudent
* [ ] metrosichel
* [ ] siabundance
* [ ] sirarefaction
* [ ] sishift
