### ISSUE TITLE
Make.contigs - name mismatch BUG

### ISSUE THREAD

**Issue by mothur-westcott** [mothur/mothur#167]
http://www.mothur.org/forum/viewtopic.php?f=4&t=3892&p=11629#p11629

@A1
CCAGC
+
ABBCB
@A2
CCAGC
+
CCCCC
@A3
CCAGC
+
CCCCB

$ mothur '#make.contigs(ffastq=not_working_R1.fastq, rfastq=not_working_R2.fastq, processors=2)'
Using 2 processors.
Making contigs...
3
[WARNING]: name mismatch in forward and reverse fastq file. Ignoring, A4.
1

However, changing the sequence names in the two files to "A1", "B2", "C3", "D4", "E5" allows the file to be properly processed. I can provide working and non-working example files if needed.

**Comment by mothur-westcott** [comment]
http://www.mothur.org/forum/viewtopic.php?f=3&t=4087

make.contigs(file=stability.files, processors=8)

I get an error saying that a sequence is in my R1 file that is not in my R2 file and to remove these sequences using remove.seqs.

The error message is from the splitting process.  Not sure if it matters but the sequence names contain '-' characters.

**Comment by mothur-westcott** [comment]
@pschloss, how do you want to handle this bug? Coding around it will slow the command.  We currently look for an exact match, then look for a match with the last char dropped to account for mismatches like:

/**
 * checks for minor diffs @MS7_15058:1:1101:11899:1633#8/1 @MS7_15058:1:1101:11899:1633#8/2 should match
 */

If both of these fail we then start the skipping reads make matches and process.  This seems like a rare case.  Should we ignore it or should I dive in?

**Comment by pschloss** [comment]
Can you remind me what they should look like?

**Comment by mothur-westcott** [comment]
Completed with b55bcc8e1b065729321aab452af5badc2d65d0c8.
