### ISSUE TITLE
Add Quikr to mothur

### ISSUE THREAD

**Issue by mothur-westcott** [mothur/mothur#174]
This will be a new method for the classify.seqs command. 

If you want to take a quick look at mothur’s classes that are similar to yours to see if they may be helpful for you in any way.  Here is a short list where I can see we may have some overlap.

In the containers folder:
kmerdb.hpp 
kmerdb.cpp - The constructor takes a fasta file and a kmer size and creates a database.  This can be searched to find the closest number of X sequences to a given sequence.  Upon reading a reference file a shortcut file is created, so if the same reference file is given again the kmer database is read in instead of generated. There is an example of this database be created in classify.cpp lines 39-68.
kmer.hpp
kmer.cpp - Used by kmerdb to find kmers for sequences or convert kmers to sequences
sequence.hpp
sequence.cpp - Container class for fasta sequence.  

In the source folder:
mothurout.h
mothurout.cpp - Utility class for mothur.  This is a static class that can be instantiated from anywhere. All of mothur’s classes create an instance. Handles signal interrupts, all logging, file handling, math functions, string manipulations, ect.  Might be a convenient way to add some mothur conventions.  Also includes mothur.h so you could probably clean up some of your includes if you want.

**Comment by pschloss** [comment]
Let's close this for now until we hear back from the original investigators
