### ISSUE TITLE
Demultiplex sff file

### ISSUE THREAD

**Issue by GiBacci** [mothur/mothur#176]
Hi everyone,
I'm trying to demultiplex an sff file for SRA submission. I'm using the "sffinfo" command of the mothur platform giving a "oligos" file with all barcodes and likers. Unfortunately, the command produces a single file containing all demultiplexed sequences. I would like to know if there is a way for keeping the sff files separated (one file per sample).
Thanks in advance

Giovanni

**Comment by mothur-westcott** [comment]
Are you using our current version? If you are working towards a SRA submission, have you tried the make.sra command, http://www.mothur.org/wiki/Make.sra?

**Comment by GiBacci** [comment]
Hi and thanks for the quick reply!
You were right, I was using an old version of mothur! I'm currently trying to compile the newest version from github but I'm having some troubles. Do you know if it is possible to download a pre-compiled version of the software?

Thanks in advance

Giovanni

**Comment by mothur-westcott** [comment]
You can generate a MIMARK file with the get.mimarkspackage command, http://www.mothur.org/wiki/Get.mimarkspackage.  To limit the fields to those required, set requiredonly=t.  These are the basic fields that are required for a SRA submission and you will need them whether you use mothur to generate a submission or not.

As to the sffinfo splitting issue, what is the error you are getting from mothur?
