### ISSUE TITLE
Mothur: Clearcut Program

### ISSUE THREAD

**Issue by shalabhsuman** [mothur/mothur#177]
Hey,

We have been attempting to generate a phylogenetic tree using the "clearcut" program inside mothur. The job is running on our compute for few days now, however I neither see any Error nor do I notice any progress. <b>Is it normal for this to take several days to finish?</b>

<code> clearcut(phylip=stability.trim.contigs.good.unique.good.filter.precluster.pick.pick.phylip.dist) </code>

Our phylip-distance-matrix is ~150GB, and the compute node has 256GB RAM and 20 cores.

Shalabh Suman

**Comment by pschloss** [comment]
Yeah, I suspect that will take a very long time - 150GB is just huge. Sorry, I'm not sure how much longer it will take. If it hasn't sucked up all of your RAM, I'd just let it keep trucking along.
