### ISSUE TITLE
Make Testing Units Available

### ISSUE THREAD

**Issue by wwood** [mothur/mothur#196]
Hi,

I'm looking to package mothur for the GNU Guix package manager. I see that there is tests in the `TestMothur` directory and GitHub issues suggesting that these are alive, but there does not appear to be a make target that runs these tests, Would it be possible to add a check target, or more simply outline in the install notes the recommended testing procedure please?

I'm keen to make sure tests are used where possible. This also might help in the maintenance of mothur as its dependencies are updated, since this translates into a rerun of the mothur test.

Thanks,
ben

**Comment by pschloss** [comment]
Thanks, Ben. In the past we've had a rather complicated testing process. As you've gathered were in the process of making it public and integrating it into a Travis-ci build. We're on it!

**Comment by wwood** [comment]
OK, great, thanks.
