### ISSUE TITLE
align.seqs issues with mothur v.1.36.1 while not with 1.35.1

### ISSUE THREAD

**Issue by FMKerckhof** [mothur/mothur#207]
Dear, 

I am experiencing issues using the align.seqs command in mothur v 1.36.1 (compiled from source) while the same command runs flawlessly in v.1.35.1 on the same linux machine.

It appears to be occurring every time I run the command so I think this is a bug. 

My mothur logfile is the following:

    Linux version
    Using ReadLine
    Running 64Bit Version
    mothur v.1.36.1
    Last updated: 7/27/2015
    by
    Patrick D. Schloss
    Department of Microbiology & Immunology
    University of Michigan
    pschloss@umich.edu
    http://www.mothur.org
    When using, please cite:
    Schloss, P.D., et al., Introducing mothur: Open-source, platform-independent, community-   supported software for describing and comparing microbial communities. Appl Environ Microbiol, 2009. 75(23):7537-41.
    Distributed under the GNU General Public License
    Type 'help()' for information on the commands that are available
    Type 'quit()' to exit program
     Interactive Mode

     mothur > align.seqs(fasta=ecoli341f785routside.fasta,reference=silva.seed_v123.align,processors=10)
     [ERROR]:  has occurred in the MothurOut class function mothurConvert. Please contact Pat Schloss at mothur.bugs@gmail.com, and be sure to include the mothur.logFile with your inquiry.

The file I am trying to align to is the silva release 123 recreated seed downloaded from the mothur wiki and the file I am trying to align is an _E. coli_ sequence downloaded from RDP which was trimmed to my primer region. 
```
>S000004313 Escherichia/Shigella coli (T); ATCC 11775T; X80725
CCTACGGGAGGCAGCAGTGGGGAATATTGCACAATGGGCGCAAGCCTGATGCAGCCATGCNGCGTGTATGAAGAAGGCCTTCGGGTTGTAAAGTACTTTCAGCGGGGAGGAAGGGAGTAAAGTTAATACCTTTGCTCATTGACGTTACCCGCAGAAGAAGCACCGGCTAACTCCGTGCCAGCAGCCGCGGTAATACGGAGGGTGCAAGCGTTAATCGGAATTACTGGGCGTAAAGCGCACGCAGGCGGTTTGTTAAGTCAGATGTGAAATCCCCGGGCTCAACCTGGGAACTGCATCTGATACTGGCAAGCTTGAGTCTCGTAGAGGGGGGTAGAATTCCAGGTGTAGCGGTGAAATGCGTAGAGATCTGGAGGAATACCGGTGGCGAAGGCGGCCCCCTGGACGAAGACTGACGCTCAGGTGCGAAAGCGTGGGGAGCAAACAGGATTAGATACCCTGGTAGTC
```

The alignment ran flawlessly with the previous release of mothur on the same machine. With the obtained alignment from 1.35.1 I tried to align my Illumina reads to the "trimmed" silva release 123 seed but got exactly the same error message upon crash with 1.36.1.

My linux machine runs ubuntu 14.04.3 LTS with the 3.13.0-57-generic kernel.

**Comment by FMKerckhof** [comment]
additionally, calling `summary.seqs` on the silva.seed v123 (downloaded from the mothur wiki) after trimming it to my primers mothur v 1.36.1 also crashes while v 1.35.1 doesn't. This must mean that something inside this alignment makes mothur v 1.36.1 crash. I used pcr.seqs on silva.seed_v123.align with the following references positions: start=6388, end=25316 with keepdots=F. Maybe some text sanitization or the likes is missing or causing errors in v 1.36.1?

**Comment by mothur-westcott** [comment]
Thanks for reporting this bug.  When we added the option to seed random in version 1.36, we did not account for "seed" being part of a filename.  We have fixed this issue and the change will be part of the next release.  As a workaround you can change the name of the reference to not include the word seed.

mothur > align.seqs(fasta=ecoli341f785routside.fasta,reference=silva.seed_v123.align,processors=10)

could be:

mothur > align.seqs(fasta=ecoli341f785routside.fasta,reference=silva.v123.align,processors=10)

**Comment by FMKerckhof** [comment]
Thank you, I'm looking forward to the next release!
