### ISSUE TITLE
Mothur 1.36.1: make.contigs: stability.contigs.groups file 0 size

### ISSUE THREAD

**Issue by shalabhsuman** [mothur/mothur#211]
I have been giving ```make.contigs``` uncompressed **fastq.gz** files as input, but I have noticed the output **stability.contigs.groups** is 0 size, after I am done running the ```make.contigs``` command. 

I am using ```Mothur v.1.36.1``` and the **stabililty.files** looks like this:

```
CS01922_0200	SB974231_S1_L001_R1_001.fastq.gz	SB974231_S1_L001_R2_001.fastq.gz
CS01630_0201	SB974240_S13_L001_R1_001.fastq.gz	SB974240_S13_L001_R2_001.fastq.gz
```
Shalabh

**Comment by mothur-westcott** [comment]
Thanks for reporting this bug.  We have resolved it and the change will be part of 1.37.0 releasing soon.  In the meantime you can workaround the bug by decompressing your fastq files and rerunning the command.  Sorry for the inconvenience.

CS01922_0200    SB974231_S1_L001_R1_001.fastq    SB974231_S1_L001_R2_001.fastq
CS01630_0201    SB974240_S13_L001_R1_001.fastq   SB974240_S13_L001_R2_001.fastq
