### ISSUE TITLE
Output shared file in binary feather format

### ISSUE THREAD

**Issue by pschloss** [mothur/mothur#219]
This would be useful for people that take output and then run with it in R or Python...

https://github.com/wesm/feather

This is new and is generating some buzz, would be worth investigating further.

**Comment by mothur-westcott** [comment]
@pschloss, do you want to add this to the 1.42.0 list or remove it?

**Comment by pschloss** [comment]
Let’s keep it on ice for now

Sent frim my iPhone, expext more typos then nirmal

**Comment by pschloss** [comment]
I'd rather see us make more R-friendly output in tidy structure first before worrying about this
