### ISSUE TITLE
sens.spec should be able to use a count file

### ISSUE THREAD

**Issue by pschloss** [mothur/mothur#225]
Currently it takes in a names file, but not a count file. Also, to run this the user will need a distance file. If they run cluster.split, a composite distance file is not generated so we need to concatenate the distance files for each split.

**Comment by mothur-westcott** [comment]
I don't think we need the count file, do we?  The name file is used to preprocess the list file to remove the dups, but when you create a list file with a count file it doesn't contain dups.

**Comment by pschloss** [comment]
That's right - then I guess we need to turn off the requirement that a names file be provided? Can you double check that we get the same result generating a list file with and without using a count file?

**Comment by mothur-westcott** [comment]
I think we want to leave the names file.  So right now you can cluster in 2 ways:

1. list and names
2. list and count - the count file is needed for average neighbor to have the right abundances

If you clustered with a names file then you would need to provide it so we can remove the duplicate sequences.  If you clustered with a count file then the list file is already unique.

The list files are different based on whether you cluster with a name or count file, but the shared file generated by the list and group or list and count are the same.  Make sense?

**Comment by pschloss** [comment]
But this command doesn't use a shared file - it uses a list file, dist file, and currently a count file

**Comment by mothur-westcott** [comment]
I thought it used a list, dist and names??

**Comment by pschloss** [comment]
right sorry - list, dist, and names 

Sent frim my iPhone, expext more typos then nirmal

**Comment by mothur-westcott** [comment]
Added count file to work with opti method results
