### ISSUE TITLE
count.groups, make shared resulting in segmentation fault after update to 1.37 while not in previous version

### ISSUE THREAD

**Issue by FMKerckhof** [mothur/mothur#227]
Dear, 

I tried to upgrade mothur on my ubuntu server from v. 1.36 to 1.37 by pulling the repository, updating the makefile to fit my system (i.e. boost location) and running the make command. 
To evaluate if everything works correctly I subsequently ran a variation of the MiSeq SOP on a small dataset which worked on the previous version. However, I am experiencing some very unusual behavior. The first is that mothur appears to have issues using "current" or unspecified options. For instance, when I was trying to run `count.groups()` as a quick check following `unique.seqs()` in the MiSeq SOP, mothur tried to use the generated names file from the `unique.seqs` command as the group parameter, followed by a `Segmentation fault (core dumped).` Running the command with the specified group file (see file below) also resulted in a segfault. 
[cw.contigs.good (3).zip](https://github.com/mothur/mothur/files/221119/cw.contigs.good.3.zip)

I also observed very weird behaviour with `set.current`: when running the command:

     set.current(fasta=cw.trim.contigs.good.unique.fasta,group=cw.contigs.good.groups,name=cw.trim.contigs.good.names,processors=12,summary=cw.trim.contigs.good.summary)

I am receiving the following output:

Using 12 processors.
```
Current files saved by mothur:
fasta=cw.trim.contigs.good.unique.fasta
name=cw.contigs.good.groups
processors=12
summary=cw.trim.contigs.good.summary
Output File Names:
current_files.summary
```
Which is clearly incorrect as I explicitely listed both a name and a group file. Subsequently running ` summary.seqs(name=current)` also resulted in some inexplicable behavior:

```
[WARNING]: no file was saved for name parameter.
Using cw.trim.contigs.good.unique.fasta as input file for the fasta parameter.

Using 12 processors.

                Start   End     NBases  Ambigs  Polymer NumSeqs
Minimum:        1       402     402     0       3       1
2.5%-tile:      1       402     402     0       3       587
25%-tile:       1       405     405     0       4       5864
Median:         1       422     422     0       5       11727
75%-tile:       1       427     427     0       5       17590
97.5%-tile:     1       428     428     0       7       22866
Maximum:        1       482     482     0       10      23452
Mean:   1       417.732 417.732 0       4.72395
# of Seqs:      23452

Output File Names:
cw.trim.contigs.good.unique.summary

It took 0 secs to summarize 23452 sequences.
```

Finally, mothur appears to be unable to get my total amount of ram (192 GB) when running `get.current`:
```
[WARNING]: Cannot determine number of physical pages

Current RAM usage: 0.0110207 Gigabytes. Total Ram: 0 Gigabytes.
```

I tried circumventing the issue with using the full names rather than current for each command and I could follow the MiSeq SOP until make.shared which inevitably resulted again in the same issue. 
Is this a known bug? What can I do to resolve it?

My system is running Ubuntu 14.04.4 LTS (GNU/Linux 3.16.0-70-generic x86_64) and I am trying to run the pipeline using 12 processors on a 24 core dell poweredge server with 192 GB RAM.

**Comment by FMKerckhof** [comment]
As an update: also on the executable (64bit linux) version mothur was not able to determine my total amount of RAM (same warning as above) however, the other issues appeared to have gone away. I have included the Makefile i was using after pulling the repo to compile from source below:
 [Makefile2.zip](https://github.com/mothur/mothur/files/221227/Makefile2.zip)

**Comment by FMKerckhof** [comment]
Additional update: upon quitting (both with the executable and after compiling from source) a weird message was displayed in the terminal:

> quit()


```
<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<^>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<^>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<^>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
Detected 4 [WARNING] messages, please review.
<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<^>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<^>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<^>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
```

**Comment by mothur-westcott** [comment]
Hi Frederiek,
    I am glad you were able to resolve the issues.  Just a thought.  Strange things can happen if you don’t "make clean" and then “make” if you have built previous versions of mothur. Could that have been the case?  In version 1.37 we added a summary of warning and errors.  This is intended to help you review warnings or errors you may have missed.  You can choose to ignore the output if you wish.
Kindly,
  Sarah

**Comment by FMKerckhof** [comment]
Hi Sarah,

Thank you for getting back to me so soon. Indeed, using the linux executable version solved some issues though still mothur was not able to determine the total amount of RAM. I have tried your suggestion and employed `make clean` before using `make`, which appeared to solve the other issues.... I'm really sorry for my ignorance in this matter.

So the only thing that I'd still like to report in this issue is that for one reason or another mothur cannot determine my physical memory size. Other software (such as python) is able to determine the total amount of  physical memory on the machine.  

Kind regards,

FM

**Comment by mothur-westcott** [comment]
Thanks for letting me know about the incorrect output of the total RAM available.  Mothur doesn't use this information for allocation so no need to worry about errors.  I will create a separate issue for this.

**Comment by FMKerckhof** [comment]
thank you Sarah. I'll close this issue then.
