### ISSUE TITLE
mothur-based rename.file command

### ISSUE THREAD

**Issue by pschloss** [mothur/mothur#229]
Would be good to have a `rename.file` command that copies the file and allows the user to rename it. We currently do this in the SOP, but it doesn't update the `current` value.

http://www.mothur.org/forum/viewtopic.php?f=5&t=4208

**Comment by mothur-westcott** [comment]
Completed with commit 1e7e703ffdcb366445e133b7fbf5f51a59d888a1

**Comment by pschloss** [comment]
I like this solution as a possible additional feature:
http://www.mothur.org/forum/viewtopic.php?f=5&t=4208

I think we'd want to leave out the reference files

**Comment by mothur-westcott** [comment]
Added deleteold and prefix parameters to rename.file
