### ISSUE TITLE
make.contigs bug in 1.37?

### ISSUE THREAD

**Issue by Shellfishgene** [mothur/mothur#230]
Hi,

I just downloaded 1.37 and tried to run make.contigs, as the previous version had the bug with the missing groups file. However with this version I get a different error:

```
mothur > make.contigs(file=foo.txt)

Using 1 processors.

>>>>>	Processing file pair 192_R1.fastq.gz - 192_R2.fastq.gz (files 1 of 1)	<<<<<
[ERROR]: Could not open 192_R2.fastq.gz
[WARNING]: Blank fasta name, ignoring read.
[WARNING]: missing sequence for , ignoring.[WARNING]: expected a name with + as a leading character, ignoring.[WARNING]: missing quality for , ignoring.Making contigs...
[WARNING]: name mismatch in forward and reverse fastq file. Ignoring, HWI-M01755_238__1_1101_7958_7964.
[WARNING]: name mismatch in forward and reverse fastq file. Ignoring, HWI-M01755_238__1_1101_23768_26221.
[WARNING]: name mismatch in forward and reverse fastq file. Ignoring, HWI-M01755_238__1_1102_5344_7070.
[WARNING]: name mismatch in forward and reverse fastq file. Ignoring, HWI-M01755_238__1_1102_25178_16973.
[WARNING]: name mismatch in forward and reverse fastq file. Ignoring, HWI-M01755_238__1_1102_24636_23919.
(many more of the same warning)
```
The files are both there, and running the exact same command in the same directory does not result in an error using mothur 1.36.1.
This is with a bunch of different files, gzipped or not gzipped. The names in my files match, at least the part before the space and the 1:N: / 2:N: stuff (MiSeq data).

Cheers

**Comment by mothur-westcott** [comment]
Sorry for the inconvenience and thanks for reporting this bug.  We will be releasing an updated version with a fix shortly.  In the meantime, decompressing your files will allow you to work around the bug.

**Comment by mothur-westcott** [comment]
https://github.com/mothur/mothur/releases/tag/v1.37.2
