### ISSUE TITLE
Make.file suggested update

### ISSUE THREAD

**Issue by marcsze** [mothur/mothur#243]
Hey Sarah and Pat

When files are downloaded from the SRA the _R1 and _R2 parts of the file name are replaced with simply _1 and _2.  The make.file command does not recognize this in mothur version 1.37.0 and I am not sure if this is something that has changed in the latest version available (1.37.4).  However, if it is not it might be a good idea to have this functionality added.

**Comment by mothur-westcott** [comment]
Completed with commit 48c527d9714b54f6df0b564a97bbaf651d229ad4.
