### ISSUE TITLE
make.contigs error with .gz files

### ISSUE THREAD

**Issue by shalabhsuman** [mothur/mothur#245]
The same issue shows up again with Version 1.37.5:

http://www.mothur.org/forum/viewtopic.php?f=4&t=4210&sid=8303c7614b85114d0587fc03fa3fefce

Shalabh Suman

**Comment by mothur-westcott** [comment]
Thanks for putting this back on our radar.  It seems the fix got overwritten with version 1.37.3. We will be sure to include in the next release.  
Kindly,
 Sarah

**Comment by eriklysoe** [comment]
The same problem is in 1.39.5

Cheers
Erik
