### ISSUE TITLE
screen.seqs alignreport maxsim feature request

### ISSUE THREAD

**Issue by rec3141** [mothur/mothur#247]
How hard would it be to implement a maxsim option in screen.seqs? I am interested in looking specifically at the high distance sequences and it would be nice to do it within mothur rather than piecing together some bash scripts. Thanks

**Comment by mothur-westcott** [comment]
@pschloss what are your thoughts?

**Comment by pschloss** [comment]
maximum similarity to what?

**Comment by mothur-westcott** [comment]
I think its like the minsim parameter.  The minsim parameter is used with the align report file to screen the sequences based on their similarity to the template sequence.
