### ISSUE TITLE
Retain ':' in fastq deflines when using make.sra

### ISSUE THREAD

**Issue by erg55** [mothur/mothur#252]
The SRA's process requires ':' to remain in the defline and mothur automatically changes them to '_'.

**Comment by mothur-westcott** [comment]
Could you explain further? We haven't seen any issues uploading files from mothur?

**Comment by erg55** [comment]
When I upload mothur-processed fastq files to the SRA, I get this error ":syntax error, unexpected fqENDLINE" due to the ':'s in the defline of the fastq files automatically being replaced by '_'s. 

The make.sra command warns me after finishing that it has replaced all these colons to ensure no errors occur in downstream processing "[WARNING]: your sequence names contained ':'.  I changed them to '_' to avoid problems in your downstream analysis." but that does not seem necessary when depositing fastq files to the SRA. 

The SRA curator has had to manually fix this problem for me.

**Comment by erg55** [comment]
From the SRA curator: 

"Our automated fastq loader expects standard defline formats, and is sensitive to any departure from these expectations. Your deflines contained underscores instead of the standard colons separating the Illumina sequence identifiers. "

**Comment by erg55** [comment]
I think this is a vestige of the make.contigs remaining in the make.sra command which until recently also removed barcodes automatically from the fastq files (also not appropriate for the SRA)

**Comment by marcsze** [comment]
Would it not be possible to upload the fastq files that come directly from the MiSeq instead of uploading the mothur processed fasta/fastq?

**Comment by erg55** [comment]
Well in my case, I wanted sample specific fastq files from a multiplexed Illumina dataset (which also included data from a separate experiment). The make.sra option is perfect for this except for this issue I posted about.

**Comment by marcsze** [comment]
Hmmm...I thought you can demultiplex your samples as part of the Illumina sequencing workflow and get individual R1 and R2 fastq files for each sample.  Perhaps we are talking about two different things?

**Comment by marcsze** [comment]
Ahhh....I think I understand what you want now from your GItHub page. It makes sense now to me...

**Comment by erg55** [comment]
Possibly, but I was provided with the raw still-multiplexed fastq files and used mothur to process the data not any Illumina workflow.  

Maybe, I'm the only one who has had this problem? Still, I think even adding a parameter to not automatically change those characters would be useful.

**Comment by marcsze** [comment]
I don't think you are the only one that has had this problem.  I've never experienced this because I've always worked with samples that have been demultiplexed as part of the Illumina sequencing pipeline.  So these files would not be edited by mothur (which was why I commented originally).  But you definitely taught me something about the SRA today.

**Comment by mothur-westcott** [comment]
Thanks for bringing this to my attention.  I will add it to the list of feature updates.

**Comment by mothur-westcott** [comment]
You can shut off this feature in mothur using the set.dir command, http://www.mothur.org/wiki/Set.dir#modifynames.
