### ISSUE TITLE
Runtime errors with classify.rf

### ISSUE THREAD

**Issue by mothur-westcott** [mothur/mothur#253]
@azmfaridee would you be willing to take a look at your random forest code? When I upgraded to Xcode 7 it compiles fine, but is giving runtime errors.  I have attached our test files.  I'm afraid if we can't resolve the issues we may have to bench the command.

[stability.an.0.03.subsample.shared.zip](https://github.com/mothur/mothur/files/372317/stability.an.0.03.subsample.shared.zip)
[mouse.time.design.zip](https://github.com/mothur/mothur/files/372318/mouse.time.design.zip)

**Comment by mothur-westcott** [comment]
mothur > classify.rf(shared=stability.an.0.03.subsample.shared, design=mouse.time.design)
Unable to open stability.an.0.03.subsample.shared. Trying default /Users/sarahwestcott/desktop/release/stability.an.0.03.subsample.shared
Unable to open mouse.time.design. Trying default /Users/sarahwestcott/desktop/release/mouse.time.design
0.03
[ERROR]: vectorRAM used: 0.524593Gigabytes . Total Ram: 24Gigabytes.

 has occurred in the AbstractDecisionTree class function getSplitPopulation. Please contact Pat Schloss at mothur.bugs@gmail.com, and be sure to include the mothur.logFile with your inquiry.

**Comment by azmfaridee** [comment]
@mothur-westcott, thanks for letting me know I'll try to take a look :)

**Comment by azmfaridee** [comment]
@mothur-westcott I was able to reproduce the issue on master, but not on a consistent basis, I'm getting two other types of errors as well. I'm trying to find the main cause of the error nonetheless.

### Error Logs
Here is the error you mentioned.

```
mothur > set.dir(debug=f)

mothur > classify.rf(shared=/Users/azmfaridee/Documents/Development/Bioinformatics/mothur-workspace/datasets/stability.an.0.03.subsample.shared, design=/Users/azmfaridee/Documents/Development/Bioinformatics/mothur-workspace/datasets/mouse.time.design, numtrees=100)
0.03
[ERROR]: vectorRAM used: 0.00322723Gigabytes . Total Ram: 16Gigabytes.

 has occurred in the AbstractDecisionTree class function getSplitPopulation. Please contact Pat Schloss at mothur.bugs@gmail.com, and be sure to include the mothur.logFile with your inquiry.
Program ended with exit code: 1
```

Another one with pointers
```
mothur > set.dir(debug=f)

mothur > classify.rf(shared=/Users/azmfaridee/Documents/Development/Bioinformatics/mothur-workspace/datasets/HumanCRC.final.shared, design=/Users/azmfaridee/Documents/Development/Bioinformatics/mothur-workspace/datasets/HumanCRC.design, numtrees=100)
0.03
mothur(35494,0x10278a000) malloc: *** error for object 0x102d04c00: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
(lldb)
```

Another one that does not print anything on the console but the debugger shows SIGKILL midway through the run.

<img width="1792" alt="screenshot 2016-07-24 23 07 43" src="https://cloud.githubusercontent.com/assets/97716/17085265/e5622676-51f5-11e6-92bf-78177e7ddd5b.png">
