### ISSUE TITLE
help convenience functions

### ISSUE THREAD

**Issue by rec3141** [mothur/mothur#257]
It would be nice to alias "?commandName", "help(commandName)", and "man commandName" to "commandName(help)"

It would also be nice to put some spacing in the list of commands given by "help()", which is very difficult to read and scan when looking for a command without any whitespace.

**Comment by mothur-westcott** [comment]
Great suggestion, thanks!  In the meantime the wiki is a good source of command documentation.  You can search by command name or the list of commands can be found here, http://www.mothur.org/wiki/Category:Commands.

**Comment by mothur-westcott** [comment]
Completed with commit a7d353d3ae08038a38e118b179e96a0e370b2379

**Comment by rec3141** [comment]
yes the wiki is great! unfortunately I'm working mostly offline at the moment. you might consider packaging the wiki up as a standalone html doc package to add to the releases. thanks
