### ISSUE TITLE
align.seqs(..., align=noalign) produces .align file

### ISSUE THREAD

**Issue by rec3141** [mothur/mothur#258]
I'm not sure if this is a bug but it seems inefficient to produce an .align file that has nothing but dots, e.g. when I am searching against silva_nr

**Comment by mothur-westcott** [comment]
Could you post the command you ran?

**Comment by rec3141** [comment]
Using mothur v1.38.0

I'm just doing kmer matching so I don't need an alignment, but when I do 

align.seqs(fasta=tmp.fasta, align=noalign, reference=silva.seed_v123.align)

I get an all-blank alignment file output.

On a side note, I found that if you use a file with suffix ".align" as the fasta input into align.seqs, it silently overwrites it and crashes because it can't find the input file.

**Comment by mothur-westcott** [comment]
Thanks for letting us know about the silent overwrite issue. You can ignore the *.align file when using the align=noalign method.

**Comment by rec3141** [comment]
thanks -- yes I can ignore it but if it is not needed then as a user I
would rather it is not produced because when I'm searching against SILVA NR
it's 50kb x N where N can be thousands -- writing a file that big takes a
lot of time and disk space.
