### ISSUE TITLE
classify.seqs default cutoff now 80 instead of 0 (update documentation)

### ISSUE THREAD

**Issue by rrohwer** [mothur/mothur#267]
Hi, a note about the newest version of mothur (v.1.38.0) and it's documentation.  The `classify.seqs()` command used to by default specify `cutoff = 0`, but now the default cutoff appears to be `80`.  This conflicts with the documentation page: http://www.mothur.org/wiki/Classify.seqs#cutoff
thanks!

**Comment by mothur-westcott** [comment]
Thanks for bringing this to our attention. I have updated the wiki documentation.
