### ISSUE TITLE
Hill's diversity

### ISSUE THREAD

**Issue by ghost** [mothur/mothur#268]
Could you implement a diversity metric that is based on effective species numbers? It is very easy to convert Shannon's entropy into such a metric, simply by taking the exponent of the Shannon index value (= Hills diversity). Of course anyone could do this themselves, but few people appreciate how non-intuitive Shannon's index is to interpret, and simply providing an improved index would lead to more people reporting more easily understandable results.

See Hill et al. 2003. Using ecological diversity measures with bacterial communities. FEMS Microbiol Ecol 43:1-11.

**Comment by mothur-westcott** [comment]
@pschloss, what are your thoughts?

**Comment by pschloss** [comment]
Sure that sounds great.

**Comment by m-bakker** [comment]
I can write the wiki page when the time comes.

**Comment by FMKerckhof** [comment]
I think adding the option to integrate species similarity into the effective numbers as suggested by Leinster & Cobbold (2012) would be interesting as well. However, indeed this will be a bit more difficult to implement if methods like cluster.split are used (and hence no distance matrix is available). Of course representative OTU sequences could be used there, to reduce computational load. Ultimately, generating diversity profiles could be a nice addition here as well.

See: Leinster, T., & Cobbold, C. A. (2012). Measuring diversity: the importance of species similarity. Ecology, 93(3), 477-489.

**Comment by mothur-westcott** [comment]
Completed in 2014 with the addition of the shannonrange calculator.
