### ISSUE TITLE
Create sra.info command

### ISSUE THREAD

**Issue by mothur-westcott** [mothur/mothur#27]
sra.info - command to convert sra files into sff files

**Comment by pschloss** [comment]
Updating... not so much for converting to sff files, but dump out fastq files

https://www.ncbi.nlm.nih.gov/books/NBK158900/
https://trace.ncbi.nlm.nih.gov/Traces/sra/sra.cgi?view=toolkit_doc&f=fastq-dump

**Comment by mothur-westcott** [comment]
Add functionality in script, https://github.com/SchlossLab/Schloss_Singletons_XXXXX_2019/blob/master/code/datasets_download.sh

**Comment by mothur-westcott** [comment]
* Input is accnos file containing sample names

* run prefetch to get sra files

* run fasterq_dump to extract fastq files

* run gzip to compress if requested

* create files file

**Comment by mothur-westcott** [comment]
Need to resolve: 

1. SRA tools versions. Version 2.9 has bug in prefetch for mac version, perhaps other versions. 
2. version 2.10 resolves bug, but only available downloads are for Linux.
