### ISSUE TITLE
Get.sharedseqs - check for shared sequences without a list file

### ISSUE THREAD

**Issue by mothur-westcott** [mothur/mothur#28]
http://www.mothur.org/forum/viewtopic.php?f=3&t=3208&p=9113#p9113

**Comment by mothur-westcott** [comment]
How do you want to implement this? Without a list or shared file, what would define "shared sequences"? Should I run a series of commands as indicated in your forum post and then output the results, or do you want me to update the wiki documentation to give an explanation how to do this with mothur's current commands. @pschloss

**Comment by pschloss** [comment]
Hmmm. I feel like I answered his question with a doable workflow using existing components.

**Comment by mothur-westcott** [comment]
:thumbsup:
