### ISSUE TITLE
set.logfile() is apparently not working in linux

### ISSUE THREAD

**Issue by fjossandon** [mothur/mothur#281]
Hello,
The versions I will referring to are:
https://github.com/mothur/mothur/releases/download/v1.38.1.1/Mothur.mac_64.OSX-10.11.zip
https://github.com/mothur/mothur/releases/download/v1.38.1.1/Mothur.linux_64.zip

I'm using mothur v.1.38.1, and after starting using Mothur on a script in MacOS I quickly noted the cumulating logfiles. Since they use a random number in the name, I added a fixed name to the input parameters using "set.logfile" (e.g. `set.logfile(name=tmp/sequence_1.mothur.log)` to remove it later, and it worked perfectly.

The command I was using:

```
command = 'mothur "#set.logfile(name=%s); align.seqs(seed=clear, candidate=%s, template=%s, processors=%i, flip=t)"' % (mothur_log, seqfile, reference, threads)
```

Then I started to use the same script in a Linux server and the script crashed because it could not find the logfile to remove it. So I added a check to not remove if it could not find the logfile. After running Mothur several times with many consecutive files, I started to notice that:
1) Mothur was generating the logfiles with random names instead of using the one I specified ("mothur.1477518678.logfile" files were appearing during execution).
2) The log files were being automatically deleted after execution, instead of being kept like in MacOS.

So because of those 2 unexpected behaviors, the script was running fine in MacOS while crashing in Linux. I don't mind logfiles deleting themselves, but `set.logfile(name=%s)` is not working as described in documentation, and if the auto-deletion is a feature, I would like to know why it was triggered in Linux and not in MacOS.

Mothur output does not give me a clue for this inconsistent behavior, it shows the specified logfile command, even if it looks like the filename its not being set:

```
mothur > set.logfile(name=_log_mothur_1.log)

mothur > align.seqs(seed=clear, candidate=tmp_saver/sequence_1.fasta, template=./data/template.align, processors=1, flip=t)
Setting random seed to 1477518746.
...
```

**Comment by mothur-westcott** [comment]
Mothur creates a log file with a generic name when it starts.  This is done because logging starts before the first command.  When you run the set.logfile command, mothur saves the name you inputted for your log file. Then when mothur quits normally the generic log file is renamed to your inputted name.
