### ISSUE TITLE
Mothur MiSeq SOP i get no data after filter.seq please help

### ISSUE THREAD

**Issue by joyceleyn** [mothur/mothur#282]

**Comment by pschloss** [comment]
This normally happens because the start and end positions used in screen.seqs didn't work right. Can you post the output of running summary.seqs before and after screen.seqs along with the exact command you are using for screen.seqs?

**Comment by joyceleyn** [comment]
Hi I notice i dint put start and stop positions mine start and end at the same position. After filter.seqs i get no sequences.

Summary before screen
summary.seqs(fasta=stability.trim.contigs.good.unique.align, count=stability.trim.contigs.good.count_table)

                Start   End     NBases  Ambigs  Polymer NumSeqs
Minimum:        0       0       0       0       1       1
2.5%-tile:      14943   22568   222     0       3       12650
25%-tile:       14943   22568   223     0       3       126495
Median:         14943   22568   223     0       4       252989
75%-tile:       14943   22568   223     0       4       379483
97.5%-tile:     14943   22568   224     0       5       493328
Maximum:        43116   43116   271     0       136     505977
Mean:   15023.1 22559.8 220.294 0       3.85197
# of unique seqs:       183632
total # of seqs:        505977


Screen command

screen.seqs(fasta=stability.trim.contigs.good.unique.align, count=stability.trim.contigs.good.count_table, summary=stability.trim.contigs.good.unique.summary, maxhomop=8, processors=16)

summary after screen

		Start	End	NBases	Ambigs	Polymer	NumSeqs
Minimum:	0	0	0	0	1	1
2.5%-tile:	14943	22568	222	0	3	12650
25%-tile:	14943	22568	223	0	3	126492
Median: 	14943	22568	223	0	4	252984
75%-tile:	14943	22568	223	0	4	379476
97.5%-tile:	14943	22568	224	0	5	493318
Maximum:	43116	43116	271	0	8	505967
Mean:	15023.2	22559.8	220.294	0	3.85012
# of unique seqs:	183622
total # of seqs:	505967


summary after filter

	Start	End	NBases	Ambigs	Polymer	NumSeqs
Minimum:	0	0	0	0	1	1
2.5%-tile:	-1	-1	0	0	1	12650
25%-tile:	-1	-1	0	0	1	126492
Median: 	-1	-1	0	0	1	252984
75%-tile:	-1	-1	0	0	1	379476
97.5%-tile:	-1	-1	0	0	1	493318
Maximum:	-1	-1	0	0	1	505967
Mean:	3.64584e+13	3.64584e+13	0	0	1
# of unique seqs:	1
total # of seqs:	505967

**Comment by pschloss** [comment]
Yeah - that's the problem - you probably want to use `start=14943` and `end=22568`

**Comment by joyceleyn** [comment]
okay thanks let me give that a try asap then revert if i still get the issue the Mothur wiki page is down so im without any place to reference thanks for getting in touch

**Comment by joyceleyn** [comment]
Hi Pat Schloss

I have been running cluster.split on 15million contigs its running for 6 days now and im using 16 cores is this normal ..... the temp files it is wriitng are continually increasing in size now at 16G

command used below
mothur "#cluster.split(fasta=stability.trim.contigs.good.unique.good.filter.unique.precluster.pick.pick.fasta, count=stability.trim.contigs.good.unique.good.filter.unique.precluster.uchime.pick.pick.count_table, taxonomy=stability.trim.contigs.good.unique.good.filter.unique.precluster.pick.pds.wang.pick.taxonomy, splitmethod=classify, taxlevel=4, cutoff=0.15, processors=16)"

Joyce

**Comment by pschloss** [comment]
I suspect that if you have 15 million unique reads it will never finish and you won’t possibly have sufficient RAM to finish the job. This usually happens because of a data quality issue. I would encourage you to check out this blog post I wrote on the issue…

http://blog.mothur.org/2014/09/11/Why-such-a-large-distance-matrix/

Pat

**Comment by joyceleyn** [comment]
unique reads are 4 million, 11 is the total number of contigs. I will have a look at the blog thanks
Meanwhile i tried running the command again interactively as opposed to in a batch script it seems to be running abit faster 

thanks
