### ISSUE TITLE
Website/wiki/forum down? 

### ISSUE THREAD

**Issue by steph43** [mothur/mothur#283]
I am have difficulties with the cluster.split command in mothur - where the cutoff is being changed to a lower cutoff when using the average neighbor algorithm. From a google search, I can see that other people have had similar issues, and there's even a FAQ about it. But, it seems that the mothur website, the wiki, and the forums are all offline, and I haven't been able to track down the solutions anywhere else. Is there any word on when  the wiki and forums will be back online?

**Comment by FMKerckhof** [comment]
I experience similar issues

**Comment by pschloss** [comment]
We're working on it. Try searching for mothur.org at archive.org
