### ISSUE TITLE
Count File

### ISSUE THREAD

**Issue by akknight** [mothur/mothur#284]
Hi,

I'm getting stuck on screen.seqs: 

screen.seqs(fasta=stability.trim.contigs.pick.good.unique.align, count=stability.trim.contigs.pick.good.count_table, summary=stability.trim.contigs.pick.good.unique.summary, start=1, end=18928, maxhomop=8)

And have been getting this error:

Your count file does not include the sequence M00171_11_000000000-A please correct.
Your count file does not include the sequence M00171_12_00M00171_15_000000000-ANT72_1_2117_2300_15305 please correct.
Your count file does not include the sequence M00171_15_000000000-ANT72_1_1105_13220M00171_19_000000000-AR15U_1_1106_7803_7819 please correct.
Your count file does not include the sequence M00171_19_000000000-M00171_10_000000000-ANUW1_1_2109_16131_18580 please correct.
Your count file does not include the sequence M00171_20_000000000-ANUYV_1_11M00171_11_000000000-ANTL3_1_2116_15765_9526 please correct.
Your count file does not include the sequence M00171_32_000000000M00171_32_000000000-AH3FL_1_2102_13707_16761 please correct.
Your count file does not include the sequence M00171_38_000000000-AHC4K_1_1108_6438_14695M00171_12_000000000-ANUVE_1_2104_28114_8711 please correct.
Your count file does not include the sequence M00M00171_36_000000000-AHPFD_1_1116_15576_14287 please correct.

I've also been getting this error:

[ERROR]: found 11935337 sequences in your fasta file, and 10431303 sequences in your summary file, quitting.

Is there a way to fix this?

Best,

Anna

Full code:

#make.contigs(file=stability.files, processors=64)

#list.seqs(fasta=./data/PregnancyMicrobiome_091416/PTB_0816/stability.trim.contigs.fasta)
#get.seqs(fasta=./data/PregnancyMicrobiome_091416/PTB_0816/stability.trim.contigs.fasta, group=./data/PregnancyMicrobiome_091416/PTB_0816/stability.contigs.groups)

#summary.seqs(fasta=stability.trim.contigs.pick.fasta)

#screen.seqs(fasta=stability.trim.contigs.pick.fasta, group=stability.contigs.pick.groups, maxambig=0, maxlength=466)

#unique.seqs(fasta=stability.trim.contigs.pick.good.fasta)

#count.seqs(name=stability.trim.contigs.pick.good.names, group=stability.contigs.pick.good.groups)

#summary.seqs(count=stability.trim.contigs.pick.good.count_table)

#summary.seqs(fasta=silva.v34.fasta)

#align.seqs(fasta=stability.trim.contigs.pick.good.unique.fasta, reference=silva.v34.fasta, flip=T)

summary.seqs(fasta=stability.trim.contigs.pick.good.unique.align, count=stability.trim.contigs.pick.good.count_table)

screen.seqs(fasta=stability.trim.contigs.pick.good.unique.align, count=stability.trim.contigs.pick.good.count_table, summary=stability.trim.contigs.pick.good.unique.summary, start=1, end=18928, maxhomop=8)

filter.seqs(fasta=stability.trim.contigs.pick.good.unique.good.align, vertical=T, trump=.)

unique.seqs(fasta=stability.trim.contigs.pick.good.unique.good.filter.fasta, count=stability.trim.contigs.pick.good.good.count_table)

**Comment by mothur-westcott** [comment]
This looks like a file corruption due to lack of memory in the beginning steps of the pipeline.

**Comment by DuyDN** [comment]
Hi, we encountered the same problem, do you have any idea how to check if the memmory suitable for  in the beginning steps of the pipeline. since we did not see any error in previous steps. Thank

**Comment by mothur-westcott** [comment]
Are you using our current version? Are you running the screen.seqs command with a summary file as well? Could you post the commands you ran @DuyDN?

**Comment by DuyDN** [comment]
Thank you for quick reply. 
We used the lastest version. 
We solved our problem. In fact, it was not because of the memmory in our case,  but the error from our group file, which might because we did not have/use the right group file. We run again from begining then it worked. 
Best regards 
Duy DN
