### ISSUE TITLE
Error (name mismatch in pcr.seqs) using oligos option

### ISSUE THREAD

**Issue by khyox** [mothur/mothur#287]
In mothur v.1.38.1, this is running perfectly on a GNU/Linux box:
`pcr.seqs(fasta=silva.nr_v123.align, start=11894, end=25319, keepdots=F, processors=64)`
(...)
`It took 9 secs to screen 172418 sequences.`

...but this:
`pcr.seqs(fasta=silva.nr_v123.align, oligos=myoligosfile.oligos, keepdots=F, processors=`2^n`)`

...is failing with several "`[ERROR]: name mismatch in pcr.seqs.`", tested for n=6 to 0, trying the possible solution pointed by @pschloss in [mothur forum](https://mothur.org/forum/viewtopic.php?t=3212). The oligos file has been used successfully several times with `make.contigs` command, so I guess the problem is not coming from there (at least concerning its format). 

Any hints? Thanks in advance!

**Comment by mothur-westcott** [comment]
Could you send your oligos file to mothur.bugs@gmail.com so I can troubleshoot it for you?
