### ISSUE TITLE
cannot run get.lineage in batch mode

### ISSUE THREAD

**Issue by rrohwer** [mothur/mothur#290]
The syntax for the `get.lineage` call includes semicolons, leading to errors if you run it in batch mode because at each semicolon mothur thinks you've entered a new command and gives an error that you're missing parentheses. The only way it can be run in batch is at kingdom level without the semicolons (as far as I can tell).

ex:
```
# this fails but follows your syntax exactly:
mothur "#get.lineage(taxonomy=example.tax, taxon=Bacteria;-Archaea;, fasta=example.fasta)"
# this works but I don't know how I'd add lower taxa levels:
mothur "#get.lineage(taxonomy=example.tax, taxon=Bacteria-Archaea, fasta=example.fasta)"
``` 

Thanks!
Robin Rohwer

**Comment by mothur-westcott** [comment]
Mothur assumes in script mode that the ; separates commands. You can use ' characters to indicate to mothur to ignore the semicolons within the command parameters. 

Try this:
mothur "#get.lineage(taxonomy=example.tax, taxon='Bacteria;-Archaea;', fasta=example.fasta)"
