### ISSUE TITLE
Mixed direction reads in both files - make.contigs

### ISSUE THREAD

**Issue by mothur-westcott** [mothur/mothur#294]
I am getting more and more emails like this.  Files for make.contigs with forward and reverse reads mixed in both files.  Make.contigs can't handle this in it's current state neither can make.sra.  How do we want to handle it? A few options I've been mulling around for version 1.40.0:

1. Modify make.contigs to check for more combinations for barcodes and primers when you have a failure.  Or perhaps we have a parameter like checkorient that gets added to say check for more combinations. This would increase the time needed to run the command. 

2. Make a new command that "cleans up" the files, if you have files like these.  I could see an advantage here, because then we wouldn't have to code around this in other areas in mothur.  Also, if someone wants to use their reads outside of mothur they could correct the format.

3. Maybe both options??

What are your thoughts? @pschloss

**Comment by mothur-westcott** [comment]
Discussed and decided to create new command to preprocess the files.

**Comment by mirzaabidpp** [comment]
Hi Sarah!
I am working on my data analysis at large scale, now i need to wait for mothur Version 1.41.0??

**Comment by mothur-westcott** [comment]
@mirzaabidpp, could you send me some sample files with the mixed reads in them?

**Comment by mirzaabidpp** [comment]
Thank you Sarah! My problem is solved now.
