### ISSUE TITLE
invalid next size (fast)

### ISSUE THREAD

**Issue by rnjv** [mothur/mothur#300]
I egt the following, when I run random forest of MiSeq_SOP on my dataset:

*** glibc detected *** mothur: free(): invalid next size (fast): 0x00000000022e4430 ***

**Comment by mothur-westcott** [comment]
Thank you for reporting this bug.  The classify.rf command is not currently working.  It will be benched in our next release, until we can resolve the issue. https://github.com/mothur/mothur/issues/253
