### ISSUE TITLE
bug in pre.cluster (v.1.39.0)

### ISSUE THREAD

**Issue by m-bakker** [mothur/mothur#301]
pre.cluster doesn't seem to handle multiple processors (called in an earlier command) if no group information is provided. Sometimes seems to require running the exact same command twice, with explicit option that 'processors=1', before it will work.

**mothur log file copied below:**

Linux version
Using ReadLine
Running 64Bit Version
mothur v.1.39.0
Last updated: 1/23/2017
by
Patrick D. Schloss
Department of Microbiology & Immunology
University of Michigan
http://www.mothur.org

When using, please cite:
Schloss, P.D., et al., Introducing mothur: Open-source, platform-independent, community-supported software for describing and comparing microbial communities. Appl Environ Microbiol, 2009. 75(23):7537-41.

Distributed under the GNU General Public License
Type 'help()' for information on the commands that are available
For questions and analysis support, please visit our forum at https://www.mothur.org/forum
Type 'quit()' to exit program
Interactive Mode

mothur > set.dir(input=~/Desktop/scratch, output=~/Desktop/scratch)
Mothur's directories:
outputDir=/home/mbakker/Desktop/scratch/
inputDir=/home/mbakker/Desktop/scratch/

mothur > summary.seqs(fasta=test.fasta, name=test.names, processors=4)

Using 4 processors.
		Start	End	NBases	Ambigs	Polymer	NumSeqs
Minimum:	5	759	233	0	3	1
2.5%-tile:	5	759	253	0	4	251
25%-tile:	5	759	253	0	4	2501
Median: 	5	759	253	0	5	5001
75%-tile:	5	759	253	0	5	7501
97.5%-tile:	5	759	254	0	8	9751
Maximum:	5	759	257	0	10	10000
Mean:	5	759	253.046	0	5.0171
# of unique seqs:	5854
total # of seqs:	10000

Output File Names: 
/home/mbakker/Desktop/scratch/test.summary

It took 0 secs to summarize 10000 sequences.

mothur > pre.cluster(fasta=test.fasta, name=test.names)

Using 4 processors.
When using running without group information mothur can only use 1 processor, continuing.
5854	1	5853
Total number of sequences before precluster was 5854.
pre.cluster removed 5853 sequences.

It took 1 secs to cluster 5854 sequences.

Output File Names: 
/home/mbakker/Desktop/scratch/test.precluster.fasta
/home/mbakker/Desktop/scratch/test.precluster.names
/home/mbakker/Desktop/scratch/test.precluster.map

mothur > pre.cluster(fasta=test.fasta, name=test.names, processors=1)

Using 1 processors.
5854	1	5853
Total number of sequences before precluster was 5854.
pre.cluster removed 5853 sequences.

It took 1 secs to cluster 5854 sequences.

Output File Names: 
/home/mbakker/Desktop/scratch/test.precluster.fasta
/home/mbakker/Desktop/scratch/test.precluster.names
/home/mbakker/Desktop/scratch/test.precluster.map

mothur > pre.cluster(fasta=test.fasta, name=test.names, processors=1)
Using 1 processors.
5854	4442	1412
Total number of sequences before precluster was 5854.
pre.cluster removed 1412 sequences.

It took 8 secs to cluster 5854 sequences.

Output File Names: 
/home/mbakker/Desktop/scratch/test.precluster.fasta
/home/mbakker/Desktop/scratch/test.precluster.names
/home/mbakker/Desktop/scratch/test.precluster.map

mothur > quit()

**Comment by m-bakker** [comment]
Now on the first issuance of the command, I'm getting all sequences (erroneously) preclustered together. Upon re-issuance of the identical command, mothur crashes with 'Segmentation fault (core dumped)'

**Comment by mothur-westcott** [comment]
This is corrected with version 1.39.1
