### ISSUE TITLE
make.contigs working in 1.36.1, broken in 1.39.0

### ISSUE THREAD

**Issue by didillysquat** [mothur/mothur#303]
Hi There,

I'm having an issue with 1.39.0 when running make.contigs. I am getting the following warning for _every_ read in each of the fastQ pairs:
[WARNING]: name mismatch in forward and reverse fastq file. Ignoring, M1_1_000000000-ATGNP_1_1110_17465_1593/1.

Looking at the names of the forward and rev reads they match in all cases that the warning occurred except for .../1 or .../2 (i.e. fwd and rev).

Funnily enough, the exact same stability.files runs just fine in mothur 1.36.1.

**Comment by mothur-westcott** [comment]
Can you give 1.39.1 a try?

**Comment by didillysquat** [comment]
Hi Sarah,

I gave it a run yesterday - sorry I didn't get back to you. Problem is
solved!

Thanks,

Ben
