### ISSUE TITLE
bug in chimera.vsearch (1.39.1)

### ISSUE THREAD

**Issue by m-bakker** [mothur/mothur#306]
When using chimera.vsearch with a reference database, the flagged .accnos are missing the last digit of the group name for renamed contigs.
chimera.vsearch with self as reference doesn't have this problem.

**Comment by mothur-westcott** [comment]
Thanks for reporting this.  It will be fixed in our next release.

**Comment by mothur-westcott** [comment]
Thanks for reporting this issue and helping me work towards a solution.  We have fixed it with the 1.39.2 release, https://github.com/mothur/mothur/releases/tag/v1.39.2.  Can you give that a try?

**Comment by m-bakker** [comment]
Yes - seems fine now (1.39.3). Thanks!
