### ISSUE TITLE
Possible bug in classify.seqs

### ISSUE THREAD

**Issue by cedwardson4** [mothur/mothur#307]
I'm running classify.seqs in v1.39.2 (Linux 64-bit) and get the error: "Mismatch with taxonomy and template files. Cannot continue." and mothur exits to the command line. I found a similar error posted in the forum from 2011 (https://www.mothur.org/forum/viewtopic.php?f=4&t=1199) but no satisfying solution (it was not an issue with the location of the reference files).

Running the exact same command in v1.38.1 works just fine on the same dataset.

Logfile contents:

mothur > classify.seqs(fasta=OWNew.trim.contigs.good.unique.good.filter.unique.precluster.pick.fasta, count=OWNew.trim.contigs.good.unique.good.filter.unique.precluster.denovo.vsearch.pick.count_table, reference=silva.nr_v123.align, taxonomy=silva.nr_v123.tax, cutoff=80, processors=4)

Using 4 processors.
Generating search database...    DONE.
It took 243 seconds generate search database. 

Reading in the silva.nr_v123.tax taxonomy...	DONE.
Calculating template taxonomy tree...     DONE.
Calculating template probabilities...     DONE.
It took 592 seconds get probabilities. 
Classifying sequences from OWNew.trim.contigs.good.unique.good.filter.unique.precluster.pick.fasta ...
[WARNING]: LH442_3594397 could not be classified. You can use the remove.lineage command with taxon=unknown; to remove such sequences.
[WARNING]: LH398_4381152 could not be classified. You can use the remove.lineage command with taxon=unknown; to remove such sequences.
[WARNING]: LH379_625 could not be classified. You can use the remove.lineage command with taxon=unknown; to remove such sequences.
[WARNING]: LH420_1669797 could not be classified. You can use the remove.lineage command with taxon=unknown; to remove such sequences.
[WARNING]: LH398_7638593 could not be classified. You can use the remove.lineage command with taxon=unknown; to remove such sequences.
[WARNING]: LH442_3596743 could not be classified. You can use the remove.lineage command with taxon=unknown; to remove such sequences.
[WARNING]: LH379_1116 could not be classified. You can use the remove.lineage command with taxon=unknown; to remove such sequences.
[WARNING]: LH398_7654199 could not be classified. You can use the remove.lineage command with taxon=unknown; to remove such sequences.
[WARNING]: LH409_4027925 could not be classified. You can use the remove.lineage command with taxon=unknown; to remove such sequences.
[WARNING]: LH398_4491155 could not be classified. You can use the remove.lineage command with taxon=unknown; to remove such sequences.
[WARNING]: LH379_7361 could not be classified. You can use the remove.lineage command with taxon=unknown; to remove such sequences.
[WARNING]: LH409_4518826 could not be classified. You can use the remove.lineage command with taxon=unknown; to remove such sequences.
[WARNING]: LH442_5913240 could not be classified. You can use the remove.lineage command with taxon=unknown; to remove such sequences.
[WARNING]: LH398_7569061 could not be classified. You can use the remove.lineage command with taxon=unknown; to remove such sequences.
[WARNING]: LH409_6282225 could not be classified. You can use the remove.lineage command with taxon=unknown; to remove such sequences.
[WARNING]: LH379_13144 could not be classified. You can use the remove.lineage command with taxon=unknown; to remove such sequences.
[WARNING]: LH398_4445869 could not be classified. You can use the remove.lineage command with taxon=unknown; to remove such sequences.
Mismatch with taxonomy and template files. Cannot continue.
[WARNING]: LH442_3575954 could not be classified. You can use the remove.lineage command with taxon=unknown; to remove such sequences.
[WARNING]: LH409_1137055 could not be classified. You can use the remove.lineage command with taxon=unknown; to remove such sequences.
[WARNING]: LH379_17913 could not be classified. You can use the remove.lineage command with taxon=unknown; to remove such sequences.
Mismatch with taxonomy and template files. Cannot continue.
Mismatch with taxonomy and template files. Cannot continue.
[WARNING]: LH403_528052 could not be classified. You can use the remove.lineage command with taxon=unknown; to remove such sequences.
[WARNING]: LH403_642694 could not be classified. You can use the remove.lineage command with taxon=unknown; to remove such sequences.
[WARNING]: LH403_2775914 could not be classified. You can use the remove.lineage command with taxon=unknown; to remove such sequences.
[WARNING]: LH414_7035620 could not be classified. You can use the remove.lineage command with taxon=unknown; to remove such sequences.
[WARNING]: LH413_6860535 could not be classified. You can use the remove.lineage command with taxon=unknown; to remove such sequences.
Mismatch with taxonomy and template files. Cannot continue.

**Comment by nickp60** [comment]
+1
I am working on Ubuntu14.04; I don't get the  `Mismatch with taxonomy and template files. Cannot continue.`
error, but I get the `[WARNING]: readX could not be classified. You can use the remove.lineage command with taxon=unknown; to remove such sequences.`, and all of the sequences are unclassified.  After deleting the database and trying the same classify.seqs command in version 1.36.1, it works fine with no warnings, and properly classified sequences.

**Comment by mothur-westcott** [comment]
Thanks for reporting this! I have uploaded version 1.39.3 which corrects it.  You can download it here: https://github.com/mothur/mothur/releases/tag/v1.39.3.

**Comment by nickp60** [comment]
You all are fantastic, thanks for getting that sorted so quickly!
