### ISSUE TITLE
Multiple sequences with same name after screen.seqs. unique.seqs gives multiple sequence error.

### ISSUE THREAD

**Issue by kvgunten** [mothur/mothur#308]
Hi all,

I am using mothur following the Schloss' MiSeq SOP.
I execute the **make.contigs(file=stability.files)** command and get a **stability.trim.contigs.fasta** file. After creating a summary file and running the following command:

**screen.seqs(fasta=stability.trim.contigs.fasta, group=stability.contigs.groups, summary=stability.trim.contigs.summary, maxambig=0, maxlength=350)**

I try to merge equal sequences using:

**unique.seqs(fasta=stability.trim.contigs.good.fasta)**

However, I get thousands of errors such as this one:

_You already have a sequence named M02251_109_000000000-B2NR5_1_2117_16503_18923 in your fasta file, sequence names must be unique, please correct._

After that I cannot continue with the SOP.
If I check the **stability.trim.contigs.good.fasta** file, I see that each sequence is present 2 times, however one of them is only 11 bases long, the other is 300 or longer.
Does anyone know why I get duplicate sequences and how to solve this problem?

Thank you in advance,
Konstantin

**Comment by mothur-westcott** [comment]
Are there any duplicate filenames in the file file?

**Comment by kvgunten** [comment]
Hello, thanks for the reply.
I think I figured it out now. The problem was that I had a folder in the actual working folder, where I stored backup data, such as various fasta files. Mothur was then including the files in this subfolder in the operations creating weird merged files. After removing this folder, the mentioned commands work fine and no duplicate sequences are produced.
Thanks.
