### ISSUE TITLE
Select reference database for 18S rRNA samples sequences

### ISSUE THREAD

**Issue by sekhwal** [mothur/mothur#310]
Hi..Please let me know which reference database should select to align 18S rRNA samples sequences. Thanks

**Comment by pschloss** [comment]
I already answered this by email to the OP

Sent frim my iPhone, expext more typos then nirmal

**Comment by sekhwal** [comment]
Hi Pat, Could you suggest which one reference database i should use to align 18s RNA samples sequences in fastq. I have tried with different Silva databases distinctly such as Silva.seed_v123.align, silva.nr_v123.align, silva.eukarya.fasta. However, i am not getting sure which one is better to select. Thanks..

**Comment by pschloss** [comment]
I'd probably go with silva.nr_v123.align

**Comment by sekhwal** [comment]
Hi, Because the reference database Silva.nr_v123.align is big size. i am trying pcr.seqs command. However, i don't have oligos file, only have primer information of 18s RNA::::::
Please let me know how to reduce of Silva.nr_v123.align with primer in fasta. 
Thanks for helping............ 

Primers::::::::
TAReuk454FWD1 (5'-TCGTCGGCAGCGTCAGATGTGTATAAGAGACAGCCAGCASCYGCGGTAATTCC-3')and 
TAReukREV3 (5'-GTCTCGTGGGCTCGGAGATGTGTATAAGAGACAGACTTTCGTTCTTGATYRA-3').

**Comment by pschloss** [comment]
Could you post this question to the forum?

Sent frim my iPhone, expext more typos then nirmal

**Comment by sekhwal** [comment]
Ok, Sure...
