### ISSUE TITLE
What criteria to remove shorter and longer of contigs sequence using screen.seqs

### ISSUE THREAD

**Issue by sekhwal** [mothur/mothur#312]
Hi, What length i should choose for screen.seqs command from my contigs in below summary . We used  V4 region of 18S, using general eukaryotic primers. I am not getting about length to select usually for 16s RNA it ~250bp but here contigs showing length 348bp to 602bp. Thanks   

----------------------------------------------------------------------------------------------------------------
mothur > 
summary.seqs(fasta=stability.trim.contigs.fasta)

Using 4 processors.

		Start	End	NBases	Ambigs	Polymer	NumSeqs
Minimum:	1	35	35	0	2	1
2.5%-tile:	1	348	348	0	4	7630
25%-tile:	1	418	418	0	5	76297
Median: 	1	421	421	2	6	152593
75%-tile:	1	427	427	9	6	228889
97.5%-tile:	1	567	567	29	7	297556
Maximum:	1	602	602	118	300	305185
Mean:	1	427.682	427.682	6.03693	5.69793
# of Seqs:	305185

**Comment by pschloss** [comment]
Sorry, we really don't have much experience with 18S. You need to trim the silva reference collection to the V4 region amplified by your primers and then run that through summary.seqs.

Pat
