### ISSUE TITLE
nmds funciton returning only 1 axis

### ISSUE THREAD

**Issue by campenr** [mothur/mothur#313]
Hello

I am finding that the nmds function is no longer giving me what I would consider the correct output. Specifically, when using the function:

> nmds(phylip=my.lt.dist, mindim=1, maxdim=3)

What I get returned is an output stating there was only 1 axis, the lowest stress is 0, and the R-squared is 0. This issue is new going from 1.39.3 to 1.39.4. A pastebin of the logfile can be found [here](http://pastebin.com/HwuS2KR2).

I am running mothur 1.39.4 on 64-bit Windows 10.

Let me know what else I can provide to help identify the cause of this issue.

Cheers
Richard

**Comment by mothur-westcott** [comment]
In version 1.39.4 we changed how we generate random numbers.  This change was made to give better distribution of the random numbers generated by Windows.  I was able to reproduce the issue you are having and I made a few modifications.  Can you re download version 1.39.4?

**Comment by campenr** [comment]
I have tested the new version 1.39.4 and the nmds funciton is again giving me the expected results.

Additionally, the sub sampling is also still working.

Thanks for the fix!

Cheers
Richard

**Comment by mothur-westcott** [comment]
Great, thanks for your help in finding and fixing this!
