### ISSUE TITLE
"source/mothurout.h:373: error: ‘mt19937_64’ does not name a type" while making Mothur 1.39.5

### ISSUE THREAD

**Issue by indiancinema** [mothur/mothur#321]
I am trying to build and install Mothur 1.39.5 and I get the following error while making:  

In file included from source/datastructures/sparsedistancematrix.h:13,
                 from source/cluster.hpp:4,
                 from source/averagelinkage.cpp:5:
source/mothurout.h:373: error: ‘mt19937_64’ does not name a type
source/mothurout.h: In member function ‘void MothurOut::setRandomSeed(unsigned int)’:
source/mothurout.h:219: error: ‘mersenne_twister_engine’ was not declared in this scope
source/mothurout.h: In constructor ‘MothurOut::MothurOut()’:
source/mothurout.h:363: error: ‘mersenne_twister_engine’ was not declared in this scope
make: *** [source/averagelinkage.o] Error 1

Compiling using GCC 5.3.0 and Boost 1.55.0. 

Is there anything I am missing? 

Thanks

**Comment by mothur-westcott** [comment]
Does the make file contain this line?

CXXFLAGS += -DRELEASE_DATE=${RELEASE_DATE} -DVERSION=${VERSION} **-std=c++0x**
LDFLAGS += **-std=c++0x**

**Comment by indiancinema** [comment]
Yes.

**Comment by mothur-westcott** [comment]
Can you try this instead?

CXXFLAGS += -DRELEASE_DATE=${RELEASE_DATE} -DVERSION=${VERSION} -std=c++11
LDFLAGS += -std=c++11

**Comment by indiancinema** [comment]
Thanks. Works now. It turns our the issue was over at my end(issues with gcc libraries that are of my own doing). 

Thanks for the help. Take care.
