### ISSUE TITLE
Count.seqs step taking too long

### ISSUE THREAD

**Issue by sjschmitz3** [mothur/mothur#324]
Hi mothur crew, 

I've recently ran into trouble having count.seqs finish for a 6.2 GB fasta file of 16S gene sequence data. I've ran the step for smaller fasta files, less than 2 GB, but have not gotten it to finish with the full dataset. The code I have for the step is: 

`mothur "#count.seqs(name=tang.itag.trim.contigs.good.names, group=tang.itag.contigs.good.groups)"`

In order to get around this I have decided to go ahead with some processing steps I normally do with the .count_table file to try and decrease the number of sequences before completing count.seqs. Do you think I would have any problems with my data if I did the following steps? 

1. ` mothur "#screen.seqs(fasta=tang.itag.trim.contigs.good.unique.align, name=tang.itag.trim.contigs.good.names, group=tang.itag.contigs.good.groups, start=8, end=13792, processors=5)"`

2. `mothur "#filter.seqs(fasta=tang.itag.trim.contigs.good.unique.good.align, vertical=T, trump=., processors=5)"`

3.  `mothur "#unique.seqs(fasta=tang.itag.trim.contigs.good.unique.good.filter.fasta, name=tang.itag.trim.contigs.good.good.names, group=tang.itag.contigs.good.good.groups)"`

4. `mothur "#count.seqs(name=tang.itag.trim.contigs.good.unique.good.filter.unique.names, group=tang.itag.contigs.good.unique.good.filter.groups)"`

5. Then going on to use the output .count_table file for the rest of my analysis

It would be great if you had any advice, suggestions, or feedback! 
Thanks, 
Sam

**Comment by mothur-westcott** [comment]
What version of mothur are you running and how much RAM does your machine have?

**Comment by sjschmitz3** [comment]
I'm running on version 1.39.0 which I believe is the most updated. For RAM, I'm running on a High Throughput server and I requested 80 GB of memory, which I think is the RAM? I may be confusing that though.


-Sam

________________________________

**Comment by mothur-westcott** [comment]
Our latest version is 1.39.5, https://github.com/mothur/mothur/releases/tag/v1.39.5, but it doesn't sound like that is the problem.  I would recommend upgrading regardless.  Could you send the names and group file to mothur.bugs@gmail.com so I can try to track down the issue?

**Comment by mothur-westcott** [comment]
Could you try running it with processors=1?

**Comment by sjschmitz3** [comment]
Yeah sure thing! I just started a job with processors=1 included and I'll let you know what happens.
-Sam

Envoyé de mon iPhone

Le 10 avr. 2017 à 10:02, Sarah Westcott <notifications@github.com<mailto:notifications@github.com>> a écrit :


Could you try running it with processors=1?

**Comment by sjschmitz3** [comment]
Hey Sarah,


Sorry I dropped off the face of the Earth. I tried doing what you suggested (using processors=1)for the count.seqs issue and it is still not working. Any other suggestions?


-Sam Schmitz

________________________________

**Comment by mothur-westcott** [comment]
You can create the count file at anytime in the processing of your dataset.  Have you tried the commands you listed above?

**Comment by sjschmitz3** [comment]
I actually found out the issue! Somehow my fasta file got truncated so it couldn't match up the fasta & groups file. Thanks for the help!
-Sam

Envoyé de mon iPhone

Le 23 juin 2017 à 12:12, Sarah Westcott <notifications@github.com<mailto:notifications@github.com>> a écrit :


You can create the count file at anytime in the processing of your dataset. Have you tried the commands you listed above?
