### ISSUE TITLE
Biom file with a selected number of OTUs to run Picrust

### ISSUE THREAD

**Issue by Vieira34** [mothur/mothur#326]
Hi Sarah,

I have a question, maybe is a dumb question but.. I'm trying to make a biom file into mothur and I would like to make this file with top 20 OTUs (I've 4 samples). So, is possible select the top 20 OTUs before making the biom file? I mean, selecting these OTUs in list file or shared file...

Thank you for your time and attention,

best,
Fabricio.

**Comment by mothur-westcott** [comment]
Yes, here's how:

mothur > list.otulabels(shared=yourSharedFile) - list all the OTU labels in shared file. https://mothur.org/wiki/List.otulabels

Manually edit accnos file to include only the OTUs you would like selected. The top 20 should be the first 20.

mothur > get.otus(shared=yourSharedFile, accnos=yourEdittedAccnosFile) - select OTUs from shared file.  If you want to include the OTU taxonomy assignments, include the constaxonomy file as well. https://mothur.org/wiki/Get.otus

mothur > make.biom(shared=current) - Include the selected *cons.taxonomy file if desired.
