### ISSUE TITLE
make.files confused if enclosing folders have underscore

### ISSUE THREAD

**Issue by rrohwer** [mothur/mothur#328]
If any folders, even several levels up, contain an underscore in them then the `make.files` command comes up with incorrect sample names. This is easy enough to fix by naming all folders without underscores, but fairly opaque to figure out. Example:

If file structure looks like this:
`~/Desktop/MyData/first_2/fastqfolder/`
and fastq folder is your working directory that contains your first 2 samples' fastq files, you end up with a `.files` file that looks like:
```
first	/Users/athena/Desktop/MyData/first_2/fastqfolder/SRR1697762_1.fastq	/Users/athena/Desktop/MyData/first_2/fastqfolder/SRR1697762_2.fastq	
first	/Users/athena/Desktop/MyData/first_2/fastqfolder/SRR1697763_1.fastq	/Users/athena/Desktop/MyData/first_2/fastqfolder/SRR1697763_2.fastq	
```
instead of the correct format (that separates your sample names) that you get if you remove the underscore in the folder two levels up:
```
SRR1697762	/Users/athena/Desktop/JoshDatasets/Erie/first/fastqfolder/SRR1697762_1.fastq	/Users/athena/Desktop/JoshDatasets/Erie/first/fastqfolder/SRR1697762_2.fastq	
SRR1697763	/Users/athena/Desktop/JoshDatasets/Erie/first/fastqfolder/SRR1697763_1.fastq	/Users/athena/Desktop/JoshDatasets/Erie/first/fastqfolder/SRR1697763_2.fastq	
```
Note that these sample names are the default names coming from NCBI's SRA database downloads. 

Thanks for all you do!!

**Comment by mothur-westcott** [comment]
Thanks for reporting this.  It will be fixed in version 1.40.0.
