### ISSUE TITLE
errors in cluster split  M ..........is not in your count table

### ISSUE THREAD

**Issue by gracelaimail** [mothur/mothur#336]
When I run the 

cluster.split(fasta=stability.trim.contigs.good.unique.good.filter.unique.precluster.pick.pick.fasta, count=stability.trim.contigs.good.unique.good.filter.unique.precluster.denovo.uchime.pick.pick.count_table, taxonomy=stability.trim.contigs.good.unique.good.filter.unique.precluster.pick.pds.wang.pick.taxonomy, splitmethod=classify, taxlevel=4, cutoff=0.15,)
.......................................
after making the dist files, an error show up 

Clustering stability.trim.contigs.good.unique.good.filter.unique.precluster.pick.pick.fasta.30.dist
********************#****#****#****#****#****#****#****#****#****#****#
Reading matrix:     |||||||||||||||||||||||||||||||||||||||||||[ERROR]: [M04377_5                                          _00000M04377_5_000000000-ATAA5_1_1101_16457_2077 is not in your count table](url). Please correct.
Cutoff was 0.15 changed cutoff to 0.11

Reading stability.trim.contigs.good.unique.good.filter.unique.precluster.pick.pick.fasta.46.dist
********************#****#****#****#****#****#****#****#****#****#****#
Reading matrix:     |||||||||||||||||||||||||||||||||[ERROR]: M04377_30_0000M04377_30_000000000-B99TL_1_1102_15152_18712 is not in your count table. Please correct.
angel@s1:~/ISF/Samson/mothur$ |||||||[ERROR]: M04377_30_000000000-B99TL_1M04377_                                          30_000000000-B99TL_1_2115_9268_2451 is not in your count table. Please correct.

seems the M04377_30_000000000-B99TL_1 is duplicate in the begining.

 Any one can help to solve the error ?

**Comment by mothur-westcott** [comment]
How many unique sequences are you trying to cluster? How much RAM do you have? What version of mothur are you running? You can download our latest version here, https://github.com/mothur/mothur/releases.  Version 1.39 includes our new clustering method which creates better quality OTUs while using less time and memory.  You can read about it in our paper, http://msphere.asm.org/content/2/2/e00073-17.

**Comment by mirzaabidpp** [comment]
I am also facing cluster.split problem while using mothur 1.39 version. Error is "Your sequences are not the same length, aborting" while using ITS data. Would you please help me to solve this issue?

**Comment by mothur-westcott** [comment]
https://github.com/mothur/mothur/issues/334

If you run the pairwise.seqs command mothur will create a distance matrix for you based on the pairwise alignments of the sequences.  You can use that distance matrix with the cluster or cluster.split commands.

mothur > pairwise.seqs(fasta=yourFasta, cutoff=0.03)
mothur > cluster(column=current, count=yourCountFile)

**Comment by talraz1** [comment]
Hi,

I'm analyzing Illumina MiSeq data by using the MiSeq SOP. I have an error in the cluster.split step.
This is the command I used:

cluster.split(fasta=final.fasta, count=final.count_table, taxonomy=final.taxonomy, taxlevel=4, cutoff=0.03)

When I analyzed the full data (100 samples), it initially went well- split into 186 groups, and saved files eventually up to 'final.185.dist' (this part took about 20hr, using 24GB RAM, swamp=6GB, prosessors=16. mothur v.1.48.0). 
However, immediately after that, I got the following error message (and all the .temp files were deleted):  

/******************************************/
/******************************************/
Finding singletons (ignore 'Removing group' messages):

Running command: remove.seqs()
[ERROR]: MN00371_330_000H is not in your count table. Please correct.
/******************************************/
[ERROR]: Could not open final.singletons.temp

I was looking at the ‘final.count_table’ file, and I see lines like these:
MN00371_330_000H2KWVN_1_12101_14525_14333       1       7,1
MN00371_330_000H2KWVN_1_12103_18577_5199        1       16,1
MN00371_330_000H2KWVN_1_21101_4124_19781        1       88,1
MN00371_330_000H2KWVN_1_13103_12662_6662        1       35,1
MN00371_330_000H2KWVN_1_21102_12699_8286        1       37,1

Interestingly, when I analyzed only a section of my data (18 samples), the process went well (the data was split into 149 groups; the 'final.dist' file is 27GB). 

I appreciate any relevant input.
Thanks!

**Comment by talraz1** [comment]
A brief update: 
I also tried to run the analysis (using the entire data of 100 samples) with cluster=f, using the following command:
cluster.split(fasta=final.fasta, count=final.count_table, taxonomy=final.taxonomy, taxlevel=4, cluster=f, cutoff=0.03)
Again, as you can see below, I got a similar error (this time: 'MN0037 is not in your count table'), no output files, and all the temp files were deleted.  

/******************************************/
/******************************************/
Finding singletons (ignore 'Removing group' messages):

Running command: remove.seqs()
[ERROR]: MN0037 is not in your count table. Please correct.
/******************************************/
[ERROR]: Could not open final.singletons.temp


Thanks!

**Comment by talraz1** [comment]
A brief update to my question: 
I also tried to run the analysis (using the entire data of 100 samples) with cluster=f, using the following command:
cluster.split(fasta=final.fasta, count=final.count_table, taxonomy=final.taxonomy, taxlevel=4, cluster=f, cutoff=0.03)
Again, as you can see below, I got a similar error (this time: 'MN0037 is not in your count table'), no output files, and all the temp files were deleted.  

/******************************************/
/******************************************/
Finding singletons (ignore 'Removing group' messages):

Running command: remove.seqs()
[ERROR]: MN0037 is not in your count table. Please correct.
/******************************************/
[ERROR]: Could not open final.singletons.temp


Thanks!
