### ISSUE TITLE
Num Maximun of ambiguous

### ISSUE THREAD

**Issue by selucote** [mothur/mothur#337]
Hi! I've one doubt about the number of ambiguous bases in the reads. 
How many ambiguous bases in our reads we could accept? I mean, I've more than 274,000 illumina PE300 reads, but when I trimmmed using maxambig = 0, my sequences were reduced to 56,000. This is not a quality problem of reads since the FASTC quality analyses offer a good overall quality.
I've read that it could keep up to 5 ambigs. What's your opinion about that?

Thanks!

**Comment by pschloss** [comment]
We suggest zero. This is a problem with the 2x300 cycle kit as we argue here:

http://blog.mothur.org/2014/09/11/Why-such-a-large-distance-matrix/

We are still advocating that people sequence the V4 region with the 2x250 nt V2 chemistry.
