### ISSUE TITLE
fastq.info fails to set the right current files

### ISSUE THREAD

**Issue by khyox** [mothur/mothur#339]
mothur v.1.39.5 running on a GNU/Linux box. Using `fastq.info` with _oligos_ flag fails to set correctly the current files when the separation of fastq files by barcode and primers is not feasible:

```
mothur v.1.39.5
Last updated: 3/20/2017
(...)
Type 'quit()' to exit program

mothur > fastq.info(fastq=barcoding_test.fastq, oligos=barcoding_test.oligos)
9342

Output File Names:
barcoding_test.fasta
barcoding_test.qual
barcoding_test.scrap.fastq
barcoding_test.scrap.fasta
barcoding_test.scrap.qual

mothur > get.current()

Current files saved by mothur:
fasta=barcoding_test.B81.AMP1500BP_CCTGCCATTCGC.GAGTTTGATCNTGGCTCAG.fasta
oligos=barcoding_test.oligos
qfile=barcoding_test.B81.AMP1500BP_CCTGCCATTCGC.GAGTTTGATCNTGGCTCAG.qual

Output File Names:
current_files.summary

mothur > summary.seqs()
Using barcoding_test.B81.AMP1500BP_CCTGCCATTCGC.GAGTTTGATCNTGGCTCAG.fasta as input file for the fasta parameter.

Using 1 processors.
Error opening file: No such file or directory
[ERROR]: Could not open barcoding_test.B81.AMP1500BP_CCTGCCATTCGC.GAGTTTGATCNTGGCTCAG.fasta
Error in reading your fastafile, at position -1. Blank name.
```
It seems the current variables are wrongly updated before `fastq.info` checks that the separation of fastq files by barcode and primers is really feasible with the current oligos file and tolerance parameters (allowed differences in the barcode, primers, linkers and spacers).

**Comment by mothur-westcott** [comment]
You are correct the current files saved by fastq.info are the problem.  Thanks for reporting this issue!  I will add it to our list.

**Comment by khyox** [comment]
Thanks for the quick reply Sarah! Always happy to contribute to this fabulous project named mothur doing my (tiny) bit. :)

**Comment by mothur-westcott** [comment]
😄
