### ISSUE TITLE
temp files not created in tempdefault

### ISSUE THREAD

**Issue by rec3141** [mothur/mothur#344]
after setting set.dir(tempdefault=/tmp) I would expect temporary files to be created in /tmp, but e.g. make.contigs and count.seqs still create .temp and .num.temp files in the mothur executable directory using mothur v.1.39.5.

**Comment by mothur-westcott** [comment]
Thanks for bringing this to our attention.  We will add it to the list.

**Comment by mothur-westcott** [comment]
* Add scratch parameter to set.dir to set location of temp files
* Find all places in source mothur creates files and adjust locations

**Comment by mothur-westcott** [comment]
Instead of scratch, all files will be created in the outputdir. 
If this outputdir not set, output files are created in the location of the input file.
