### ISSUE TITLE
summary.shared failing with double free

### ISSUE THREAD

**Issue by Takadonet** [mothur/mothur#347]
Getting the following error when  using this specific dataset.

*** Error in `mothur': double free or corruption (!prev): 0x0000000002421050 ***
....

dataset:  https://raw.githubusercontent.com/galaxyproject/tools-iuc/master/tools/mothur/test-data/amazon.an.shared 

summary.shared( shared=otu.dat, calc=sharedsobs-sharedchao-sharedace-jclass-jest-sorclass-sorest-jabund-sorabund-thetan-thetayc, all=false, distance=false, subsample=10, iters=42, output=lt, processors=1)

It will not with any value for calc parameter. Cheers

**Comment by mothur-westcott** [comment]
Thanks for reporting this issue. We are working on a fix.
