### ISSUE TITLE
Installation make issues

### ISSUE THREAD

**Issue by TreeT2** [mothur/mothur#355]
Hi,

Im trying to install mothur locally on a HPC. Im using boost/1.59.0, gcc/4.9.2 and python/2.7.5.

I keep getting the following error: 
g++ -DBIT_VERSION -O3 -DRELEASE_DATE="\"3/20/2017\"" -DVERSION="\"1.39.5\"" -std=c++11 -DUSE_READLINE -DUSE_BOOST -I "\"Enter_your_boost_include_path_here\"" -I.  -I source/  -I source/calculators/  -I source/chimera/  -I source/classifier/  -I source/clearcut/  -I source/commands/  -I source/communitytype/  -I source/datastructures/  -I source/metastats/  -I source/randomforest/  -I source/read/  -I source/svm/   -c -o source/averagelinkage.o source/averagelinkage.cpp
In file included from source/datastructures/sparsedistancematrix.h:12:0,
                 from source/cluster.hpp:4,
                 from source/averagelinkage.cpp:5:
source/mothur.h:21:52: fatal error: boost/iostreams/filtering_stream.hpp: No such file or directory
     #include <boost/iostreams/filtering_stream.hpp>
                                                    ^
compilation terminated.
make: *** [source/averagelinkage.o] Error 1

I have tried the suggestion in issue #321  but it is still not working. 

Thanks

**Comment by mothur-westcott** [comment]
Mothur is looking for the path to the boost directory.  In the makefile you will see:

#
# Macros
#
# 64BIT_VERSION - set to no if you are using a 32bit arch.
# OPTIMIZE - yes will increase speed of executable.
# USEREADLINE - link with readline libraries.  Must have readline installed. Windows set to no.
# USEBOOST - link with boost libraries. Must install boost. Allows the make.contigs command to read .gz files.
# BOOST_LIBRARY_DIR - location of boost libraries
# BOOST_INCLUDE_DIR - location of boost include files
# MOTHUR_FILES - default location for mothur to look for input files at runtime. Most often used for reference files.

64BIT_VERSION ?= yes
OPTIMIZE ?= yes
USEREADLINE ?= yes
USEBOOST ?= yes
**BOOST_LIBRARY_DIR="\"Enter_your_boost_library_path_here\""
BOOST_INCLUDE_DIR="\"Enter_your_boost_include_path_here\""**
MOTHUR_FILES="\"Enter_your_default_path_here\""
RELEASE_DATE = "\"3/20/2017\""
VERSION = "\"1.39.5\""

You need to edit the makefile to include the location of boost directories.  For example, on my local machine the boost directory is in /usr/local, so my makefile looks like:

...
BOOST_LIBRARY_DIR="\"/usr/local/boost/lib\""
BOOST_INCLUDE_DIR="\"/usr/local/boost/include\""
...
