### ISSUE TITLE
Dist.seqs - sequences are not the same length error 

### ISSUE THREAD

**Issue by mirzaabidpp** [mothur/mothur#356]
Hi,
I am working with sequence data related to microbial diversity (fungi and bacteria) in soil. I used mothur for 16S analysis of my sequenced data and completed different steps, when i used dist.seqs command then i received an error, "sequences are not the same length error". I read your comments about filter.seqs so upgraded my mothur-1.38.0 to mothur-1.39.5. The error remained same then i tried set.dir(debug=t) but did not succeed. I need your valuable suggestions to overcome this problem.
@mothur-westcott

**Comment by mothur-westcott** [comment]
The error you are getting indicates your sequences are not aligned.  Are your sequences aligned?

**Comment by mirzaabidpp** [comment]
Yes sequences are aligned

**Comment by mothur-westcott** [comment]
Could you send the fasta and log file to mothur.bugs@gmail.com?

**Comment by mirzaabidpp** [comment]
I have sent email. Please check
