### ISSUE TITLE
Error when running get.groups() with groups=Mock

### ISSUE THREAD

**Issue by paulos84** [mothur/mothur#358]
I am following the MiSeq_SOP on the Mothur wiki page. I have downloaded all the datasets and set up the directories as described. I have copy and pasted all the commands, so it should be word-for-word correct. However, on a number of commands such as get.groups when I pass in groups=Mock  I get the following error message. I am using mothur v.1.39.5 and have tried following the SOP numerous times but always get the same error.

mothur > get.groups(count=stability.trim.contigs.good.unique.good.filter.unique.precluster.denovo.vsearch.pick.pick.count_table, fasta=stability.trim.contigs.good.unique.good.filter.unique.precluster.pick.pick.fasta, groups=Mock)

Mock is not a valid group, and will be disregarded. You provided no valid groups. I will run the command using all the groups in your file. Selected 1328 sequences from your fasta file. Selected 117919 sequences from your count file.

**Comment by paulos84** [comment]
This is the first command where I get an output which is slightly different to that shown on MiSeq_SOP page. It is the command prior to classify.seqs()

mothur > summary.seqs(fasta=current, count=current)
Using /home/pauldavis/MiSeq_SOP/stability.trim.contigs.good.unique.good.filter.unique.precluster.denovo.vsearch.pick.count_table as input file for the count parameter.
Using /home/pauldavis/MiSeq_SOP/stability.trim.contigs.good.unique.good.filter.unique.precluster.pick.fasta as input file for the fasta parameter.

Using 32 processors.

		Start	End	NBases	Ambigs	Polymer	NumSeqs
Minimum:	1	376	249	0	3	1
2.5%-tile:	1	376	252	0	3	2953
25%-tile:	1	376	252	0	4	29521
Median: 	1	376	252	0	4	59041
75%-tile:	1	376	253	0	5	88561
97.5%-tile:	1	376	253	0	6	115129
Maximum:	1	376	256	0	8	118080
Mean:	1	376	252.464	0	4.37558
# of unique seqs:	1342
total # of seqs:	118080

Output File Names: 
/home/pauldavis/MiSeq_SOP/stability.trim.contigs.good.unique.good.filter.unique.precluster.pick.summary

**Comment by jaberabbaszadeh** [comment]
Could you solve this problem? I'm having the same problem and stuck in this level. It would be very helpful if you share your experience.

**Comment by pschloss** [comment]
Did you sequence a mock community? If so, what did you call it in your files file? If not then you need to skip this step.

**Comment by jaberabbaszadeh** [comment]
I am new to mothur and trying to learn it. Therefore I am following MiSeq_SOP from the wiki page. 
When I run the get.group command in the Windows the error is: **Mock is not in your count table. Please, correct.**
But in the Linux, I encountered another error same as this Issue.
Mock is not a valid group, and will be disregarded. You provided no valid groups. I will run the command using all the groups in your file. Selected 1328 sequences from your fasta file. Selected 117919 sequences from your count file.

Moreover as paulos84 said above running this command: 
_mothur > summary.seqs(fasta=current, count=current)
Using /home/pauldavis/MiSeq_SOP/stability.trim.contigs.good.unique.good.filter.unique.precluster.denovo.vsearch.pick.count_table as input file for the count parameter.
Using /home/pauldavis/MiSeq_SOP/stability.trim.contigs.good.unique.good.filter.unique.precluster.pick.fasta as input file for the fasta parameter.__

 Is where I see a slightly different result compared with the tutorial.

**Comment by HebaAttia** [comment]
Can I know from where I can download the mock community as a reference file?

**Comment by mothur-westcott** [comment]
> Did you sequence a mock community? If so, what did you call it in your files file? If not then you need to skip this step.  If this doesn’t help, please open a new issue.
