### ISSUE TITLE
Mothur crash with classify.seqs

### ISSUE THREAD

**Issue by Jeleys** [mothur/mothur#359]
Using Ubuntu v14.04, mothur 1.39.5 and following the MISEQ pipeline (https://www.mothur.org/wiki/MiSeq_SOP) with the exception of replacing chimera.vsearch with chimera.uchime, I run into the following issue when attempting to run the classify.seqs command:

mothur > classify.seqs(fasta=current, count=current, reference=trainset9_032012.pds.fasta, taxonomy=trainset9_032012.pds.tax, cutoff=80)

Using 170801_leys_stability.trim.contigs.pcr.good.unique.good.filter.unique.precluster.uchime.pick.count_table as input file for the count parameter.
Using 170801_leys_stability.trim.contigs.pcr.good.unique.good.filter.unique.precluster.pick.fasta as input file for the fasta parameter.

Using 24 processors.
Reading template taxonomy...     DONE.
Reading template probabilities...     Segmentation fault (core dumped)
diddyserver@diddyserver:~/Desktop/LEYS_MISEQ_COMBINED_RUNS$ 

Any clarity on resolving this issue would be greatly appreciated.

**Comment by mothur-westcott** [comment]
Can you try deleting the shortcut files mothur creates for the template? *tree.train, *tree.sum

**Comment by mothur-westcott** [comment]
Another thing to consider is the number of processors.  The more processors the more memory needed. (For each processor a copy of the template will be read into memory)

**Comment by Jeleys** [comment]
Deleting the shortcut files did the trick. Thank you for the prompt response; you made my week.
