### ISSUE TITLE
make.contigs([...]) command missing

### ISSUE THREAD

**Issue by bigsuiparty** [mothur/mothur#360]
getting 'invalid command' when I use make.contigs([...]) in mothur (Mothur.mac_64.OSX-10.12.zip, release Version 1.39.5). It doesnt appear in the command list (i.e. Valid commands are: [...]) and I can't find information on mothur.org about a replacement for this command.

**Comment by sandipansamaddar** [comment]
Can you please detail it and also include the detail command.
Thanks,
Sandipan




On Tuesday, August 8, 2017, 8:55 PM, bigsuiparty <notifications@github.com> wrote:


getting 'invalid command' when I use make.contigs([...]) in mothur (Mothur.mac_64.OSX-10.12.zip, release Version 1.39.5). It doesnt appear in the command list (i.e. Valid commands are: [...]) and I can't find information on mothur.org about a replacement for this command.

**Comment by mothur-westcott** [comment]
Most often we see this error when you are using a previous version of accidentally.  This can happen if you have an older version of mothur in your path.  You can check this my using the system command which.

For example on my machine:

Johns-iMac:TARGET_BUILD_DIRTARGET_BUILD_DIR sarahwestcott$ which mothur
/Users/sarahwestcott/Desktop/mothur/TARGET_BUILD_DIRTARGET_BUILD_DIR//mothur

You can also try:

Johns-iMac:TARGET_BUILD_DIRTARGET_BUILD_DIR sarahwestcott$ mothur --version
Mac 64Bit Version
Mothur version=1.39.5
Release Date=3/20/2017

To fix this you can remove the older version or specifically call the newer version by providing a path to it.

Johns-iMac:TARGET_BUILD_DIRTARGET_BUILD_DIR sarahwestcott$ ../../sarahswork/1.37.6/mothur/mothur --version

Mac 64Bit Version
Mothur version=1.37.6
Release Date=6/20/2016
