### ISSUE TITLE
stability.files does not contain group names when i run make.file()

### ISSUE THREAD

**Issue by paulos84** [mothur/mothur#361]
I am following the MiSeq_SOP on the mothur wiki page. I have downloaded all the fastq files in the example dataset. When I run make.file(inputdir=~/MiSeq_SOP, type=fastq, prefix=stability), in the stability.files that is created, for every line in the first column I just have 'MiSeq' instead of the sample group names as should be the case.  

I cannot understand why this is the case, since I have just copy and pasted the command from the wiki page, with the only difference being '~/' in front of the the folder specified by the inputdir argument.

**Comment by mothur-westcott** [comment]
Thanks for reporting this issue.  Mothur is pairing the files correctly, but not creating unique sample names.  We have resolved it and the fix will be part of version 1.40.0 releasing soon.  In the meantime, you can fix this by manually editing the files file to fix the sample names.
