### ISSUE TITLE
Matrix-Count showing individual sequence reads not sample aggregates

### ISSUE THREAD

**Issue by emilycmenard** [mothur/mothur#365]
Hello!
I ran a set of samples through the pipeline, and my matrix-count table showed oligotypes per the individual sequence reads within each sample, not oligotypes by individual samples. What is causing this? How can i coerce mothur into collapsing the reads down by sample? What command generates the Matrix-Count table?

![screen shot 2017-08-24 at 12 31 17 pm](https://user-images.githubusercontent.com/17477477/29724656-487e1146-8997-11e7-871a-0989d661ade5.png)

Best,
Emily

**Comment by mothur-westcott** [comment]
The count table is generated using the count.seqs command, https://mothur.org/wiki/Count.seqs.  Are you looking for the breakdown by OTU and sample? If so, you can use the shared parameter in the count.seqs command.

The results will be something like:

`OTU_Label	total	F003D000	F003D002	F003D004	F003D006	F003D008	F003D142	F003D144	F003D146	F003D148	F003D150
Otu0001	6079	409	992	933	953	346	696	474	436	376	464
Otu0002	4658	384	170	393	419	286	744	584	557	491	630
Otu0003	3969	230	418	442	560	359	595	301	348	388	328
Otu0004	3352	167	88	240	354	779	455	173	449	237	410
Otu0005	2643	183	274	379	370	333	229	212	172	137	354
...
`
