### ISSUE TITLE
Problem with chimera.uchime

### ISSUE THREAD

**Issue by vtardy** [mothur/mothur#366]
Hi, the chimera.uchime function does not work.
the mothur logfile contains :

`mothur v.1.39.5
Last updated: 3/20/2017

by
Patrick D. Schloss

Department of Microbiology & Immunology
University of Michigan
http://www.mothur.org

When using, please cite:
Schloss, P.D., et al., Introducing mothur: Open-source, platform-independent, co
mmunity-supported software for describing and comparing microbial communities. A
ppl Environ Microbiol, 2009. 75(23):7537-41.

Distributed under the GNU General Public License

Type 'help()' for information on the commands that are available

For questions and analysis support, please visit our forum at https://www.mothur
.org/forum

Type 'quit()' to exit program

mothur > chimera.uchime(fasta=Run123.good.unique.good.filter.unique.precluster.f
asta, name=Run123.good.unique.good.filter.unique.precluster.names, dereplicate=t)

Using 1 processors.

uchime by Robert C. Edgar
http://drive5.com/uchime
This code is donated to the public domain.

Checking sequences from Run123.good.unique.good.filter.unique.precluster.fasta .
..
uchime v4.2.40
by Robert C. Edgar
http://drive5.com/uchime
This code is donated to the public domain.

E:\[Irstea 02] - Analyse Mothur\03 - Analyse Run Texas\03 - Alignement\\uchime.exe --input Run123.good.unique.good.filter.unique.precluster.temp --uchimeout Run
123.good.unique.good.filter.unique.precluster.denovo.uchime.chimeras

---Fatal error---
ftello in GetFileSize
[ERROR]: Run123.good.unique.good.filter.unique.precluster.denovo.uchime.chimeras is blank. Please correct.

It took 114 secs to check 0 sequences. 0 chimeras were found.

Output File Names:
Run123.good.unique.good.filter.unique.precluster.denovo.uchime.chimeras
Run123.good.unique.good.filter.unique.precluster.denovo.uchime.accnos`

**Comment by mothur-westcott** [comment]
That's an error from the uchime program. Have you tried the chimera.vsearch command?Vsearch is a open source 64bit version of uchime.

**Comment by vtardy** [comment]
Ok, thank for this solution.
With vsearch program, it works correctly.
