### ISSUE TITLE
Warn or fix "bad" characters in group names

### ISSUE THREAD

**Issue by mothur-westcott** [mothur/mothur#37]
If group name contains "/" or other "bad" characters for filenames removes them?? warn users?? do something because it causes errors in commands that use the names in filenames.

**Comment by pschloss** [comment]
I support having mothur complain if there are spaces, -'s, /'s etc. It would be good to enforce good practices by our users

**Comment by mothur-westcott** [comment]
Competed with commit c82ba512e6f813e410509dcd7b20e02c24f125f1
