### ISSUE TITLE
Make.files incorrectly setting file paths and sample names

### ISSUE THREAD

**Issue by campenr** [mothur/mothur#370]
Hello

When setting `inputdir='.'` for make.files, Mothur correctly identifies the absolute file path to the directories. Normally colons are replaced with underscores which is great, but on Windows it replaces the column following the drive letter i.e. `C:\` with an underscore leading to a broken file path, i.e. `C_\`.

Also, when automatically generating the names for the samples it seems to be splitting the full file path by underscores and taking the first item. Because of this, in the above example, all samples are given the name C. This also appears to be the case when not using relative files paths but rather specifying a directory that contains underscores: i.e. setting `inputdir=Mothur_files` results in all samples being called Mothur.

Cheers
Richard

EDIT: I forgot to mention, I am running Mothur version 1.39.5.

**Comment by mothur-westcott** [comment]
Thanks for reporting this.  It was fixed here, https://github.com/mothur/mothur/issues/328, and the change will be part of version 1.40.0.
