### ISSUE TITLE
forum search

### ISSUE THREAD

**Issue by bernt-matthias** [mothur/mothur#372]
It seems that the forum can not be searched. 
- I could not find a search box anywhere
- Google search as suggested on https://www.mothur.org/forum/viewtopic.php?f=9&t=1697 does not work (I tried the examples)

**Comment by mothur-westcott** [comment]
Is there a question I can help you with?

**Comment by bernt-matthias** [comment]
I just would like to know where I can find detailed information on mothur's tools for cases where the wiki is insufficient. The forum seems to have a category for this, but I can not find a way to search it.

**Comment by FMKerckhof** [comment]
I have similar issues searching the forum. While it is a great resource (as @bernt-matthias indicates), the lack of the search possibility is really a bummer.

**Comment by mothur-westcott** [comment]
@pschloss, do you have a suggestion?

**Comment by pschloss** [comment]
No idea. I can't reproduce it on my computer when I log in as different users.

**Comment by bernt-matthias** [comment]
Two questions: 

- Is there a search box on the forum? I can not find it.
- Do you get any result when executing the google search? I get none.

**Comment by pschloss** [comment]
Sorry, I'm not able to reproduce the bug when I'm logged in as a normal user so we're probably not going to be much help right now.

**Comment by bernt-matthias** [comment]
Thats really sad. The "lack" of detailed information makes it really difficult to use mothur. As a new user it is most important for me to know where to find documentation. Otherwise I can only use it as a blackbox, which is really unsatisfying. 

Currently it appears to me that the only information sources are: 
- the paper (but this is more an announcement that lacks any details -- but still useful for citing mothur) 
- the forum (hardly usable - ~1900 topics can not be searched manually)
- the wiki is great but seems to be gappy in parts (which I hoped to fill with infos from the forum)

Aren't there other possibilities?

**Comment by bernt-matthias** [comment]
Thats really sad. The "lack" of detailed information makes it sometimes really difficult to use mothur. As a new user it is most important for me to know where to find (detailed) documentation. Otherwise I can only use it as a blackbox, which is really unsatisfying. 

Currently it appears to me that the only information sources are: 
- the paper (but this is more an announcement that lacks any details -- but still useful for citing mothur) 
- the forum (hardly usable - ~1900 topics can not be searched manually)
- the wiki is great but seems to be gappy in parts (which I hoped to fill with infos from the forum)

Aren't there other possibilities? 

Furthermore, what do you mean with reproduce? Do you get results from google with `site:mothur.org/forum "screen.seqs"`

**Comment by pschloss** [comment]
Have you posted a question to the forum yet?

Sent frim my iPhone, expext more typos then nirmal

**Comment by bernt-matthias** [comment]
Usually I try to find out if the same question was asked before -- but I can't. 

If I (my username is Matthias) open https://www.mothur.org/forum/search.php I get `Sorry but you are not permitted to use the search system.`

**Comment by bernt-matthias** [comment]
Now I posted a question.. https://mothur.org/forum/viewtopic.php?f=3&t=10721 Feeling bad because  I needed to post a question that is most likely a duplicate.
