### ISSUE TITLE
chimera.uchime() makes blank "*precluster.denovo.uchime.accnos" file.

### ISSUE THREAD

**Issue by tslinux** [mothur/mothur#374]
Hi everyone,

I'm trying to use mothur pipeline to analyze my metagenome data.
I have paired-end sequencing data of 16S rRNA gene.
I performed chimera.uchime() function in mothur.
However, it makes a blank "*precluster.denovo.uchime.accnos" file.
Therefore, I cannot use remove.seqs() function.
Take a look at my STDOUT messages.
-----------------------------------------------------
mothur > chimera.uchime(fasta=/data/mothur/CNU/Sample_FE01/FE01_1.trim.contigs.good.unique.good.filter.unique.precluster.fasta,         count=/data/mothur/CNU/Sample_FE01/FE01_1.trim.contigs.good.unique.good.filter.unique.precluster.count_table, dereplicate=T,processors=12)

Using 12 processors.

uchime by Robert C. Edgar
http://drive5.com/uchime
This code is donated to the public domain.

Checking sequences from /data/mothur/CNU/Sample_FE01/FE01_1.trim.contigs.good.unique.good.filter.unique.precluster.fasta ...
When using template=self, mothur can only use 1 processor, continuing.
uchime v4.2.40
by Robert C. Edgar
http://drive5.com/uchime
This code is donated to the public domain.

00:00  18Mb    0.1% Reading /data/mothur/CNU/Sample_FE01/FE01_1.trim.contigs.good.unique.good.filter.unique.precluster.temp
WARNING: Ignoring gaps in FASTA file '/data/mothur/CNU/Sample_FE01/FE01_1.trim.contigs.good.unique.good.filter.unique.precluster.temp'
00:00  18Mb  100.0% Reading /data/mothur/CNU/Sample_FE01/FE01_1.trim.contigs.good.unique.good.filter.unique.precluster.temp
00:00  18Mb 37 sequences                                                                                                   
00:01 2.2Mb  100.0% 0/36 chimeras found (0.0%)

It took 1 secs to check 37 sequences. 0 chimeras were found.

Output File Names: 
/data/mothur/CNU/Sample_FE01/FE01_1.trim.contigs.good.unique.good.filter.unique.precluster.denovo.uchime.chimeras
/data/mothur/CNU/Sample_FE01/FE01_1.trim.contigs.good.unique.good.filter.unique.precluster.denovo.uchime.accnos

mothur > quit()

mothur v.1.39.5
Last updated: 3/20/2017

by
Patrick D. Schloss

Department of Microbiology & Immunology
University of Michigan
http://www.mothur.org

When using, please cite:
Schloss, P.D., et al., Introducing mothur: Open-source, platform-independent, community-supported software for describing and comparing microbial communities. Appl Environ Microbiol, 2009. 75(23):7537-41.

Distributed under the GNU General Public License

Type 'help()' for information on the commands that are available

For questions and analysis support, please visit our forum at https://www.mothur.org/forum

Type 'quit()' to exit program

mothur > remove.seqs(fasta=/data/mothur/CNU/Sample_FE01/FE01_1.trim.contigs.good.unique.good.filter.unique.precluster.fasta,         accnos=/data/mothur/CNU/Sample_FE01/FE01_1.trim.contigs.good.unique.good.filter.unique.precluster.denovo.uchime.accnos)
[ERROR]: /data/mothur/CNU/Sample_FE01/FE01_1.trim.contigs.good.unique.good.filter.unique.precluster.denovo.uchime.accnos is blank, aborting.
You have no valid accnos file and accnos is required.
[ERROR]: did not complete remove.seqs.

mothur > quit()

************************************************************
************************************************************
************************************************************
Detected 2 [ERROR] messages, please review.
************************************************************
************************************************************
************************************************************

----------------------------------------------------------------
Here is the file list after the error.

/data/mothur$ ll /data/mothur/CNU/Sample_FE01/
total 859364
drwxr-xr-x 2 siyun siyun     12288 Sep 21 16:37 ./
drwxr-xr-x 6 siyun siyun      4096 Sep 19 21:53 ../
-rw-rw-r-- 1 siyun siyun  12757709 Sep 21 16:36 FE01_1.contigs.report
-rw-rw-r-- 1 siyun siyun     50001 Sep 21 16:37 FE01_1.filter
-rw-r--r-- 1 siyun siyun 128620732 Sep 21 16:16 FE01_1.fq
-rw-r--r-- 1 siyun siyun  20358301 Sep 21 16:36 FE01_1.fq.gz
-rw-rw-r-- 1 siyun siyun         0 Sep 21 16:36 FE01_1.scrap.contigs.fasta
-rw-rw-r-- 1 siyun siyun         0 Sep 21 16:36 FE01_1.scrap.contigs.qual
-rw-rw-r-- 1 siyun siyun  10407912 Sep 21 16:36 FE01_1.trim.contigs.bad.accnos
-rw-rw-r-- 1 siyun siyun  98443045 Sep 21 16:36 FE01_1.trim.contigs.fasta
-rw-rw-r-- 1 siyun siyun    151012 Sep 21 16:36 FE01_1.trim.contigs.good.count_table
-rw-rw-r-- 1 siyun siyun   1715463 Sep 21 16:36 FE01_1.trim.contigs.good.fasta
-rw-rw-r-- 1 siyun siyun      3999 Sep 21 16:37 FE01_1.trim.contigs.good.good.count_table
-rw-rw-r-- 1 siyun siyun    304765 Sep 21 16:36 FE01_1.trim.contigs.good.names
-rw-rw-r-- 1 siyun siyun    216677 Sep 21 16:36 FE01_1.trim.contigs.good.summary
-rw-rw-r-- 1 siyun siyun 159400981 Sep 21 16:37 FE01_1.trim.contigs.good.unique.align
-rw-rw-r-- 1 siyun siyun    370132 Sep 21 16:37 FE01_1.trim.contigs.good.unique.align.report
-rw-rw-r-- 1 siyun siyun    160010 Sep 21 16:37 FE01_1.trim.contigs.good.unique.bad.accnos
-rw-rw-r-- 1 siyun siyun   1548765 Sep 21 16:36 FE01_1.trim.contigs.good.unique.fasta
-rw-rw-r-- 1 siyun siyun        46 Sep 21 16:37 FE01_1.trim.contigs.good.unique.flip.accnos
-rw-rw-r-- 1 siyun siyun   4103887 Sep 21 16:37 FE01_1.trim.contigs.good.unique.good.align
-rw-rw-r-- 1 siyun siyun      3917 Sep 21 16:37 FE01_1.trim.contigs.good.unique.good.filter.count_table
-rw-rw-r-- 1 siyun siyun     39885 Sep 21 16:37 FE01_1.trim.contigs.good.unique.good.filter.fasta
-rw-rw-r-- 1 siyun siyun     39885 Sep 21 16:37 FE01_1.trim.contigs.good.unique.good.filter.unique.fasta
-rw-rw-r-- 1 siyun siyun      1786 Sep 21 16:37 FE01_1.trim.contigs.good.unique.good.filter.unique.precluster.count_table
-rw-rw-r-- 1 siyun siyun         0 Sep 21 16:37 FE01_1.trim.contigs.good.unique.good.filter.unique.precluster.denovo.uchime.accnos
-rw-rw-r-- 1 siyun siyun      6670 Sep 21 16:37 FE01_1.trim.contigs.good.unique.good.filter.unique.precluster.denovo.uchime.chimeras
-rw-rw-r-- 1 siyun siyun     17996 Sep 21 16:37 FE01_1.trim.contigs.good.unique.good.filter.unique.precluster.fasta
-rw-rw-r-- 1 siyun siyun     40723 Sep 21 16:37 FE01_1.trim.contigs.good.unique.good.filter.unique.precluster.map
-rw-rw-r-- 1 siyun siyun      5493 Sep 21 16:37 FE01_1.trim.contigs.good.unique.good.summary
-rw-rw-r-- 1 siyun siyun    211646 Sep 21 16:37 FE01_1.trim.contigs.good.unique.summary
-rw-rw-r-- 1 siyun siyun 272680252 Sep 21 16:36 FE01_1.trim.contigs.qual
-rw-rw-r-- 1 siyun siyun  11946588 Sep 21 16:36 FE01_1.trim.contigs.summary
-rw-r--r-- 1 siyun siyun 128620732 Sep 21 16:16 FE01_2.fq
-rw-r--r-- 1 siyun siyun  27648000 Sep 21 16:36 FE01_2.fq.gz
-rw-rw-r-- 1 siyun siyun        11 Sep 21 16:37 length.txt
-rw-rw-r-- 1 siyun siyun      1734 Sep 21 16:36 mothur.1505979377.logfile
-rw-rw-r-- 1 siyun siyun      1248 Sep 21 16:36 mothur.1505979409.logfile
-rw-rw-r-- 1 siyun siyun      1157 Sep 21 16:36 mothur.1505979410.logfile
-rw-rw-r-- 1 siyun siyun       935 Sep 21 16:36 mothur.1505979411.logfile
-rw-rw-r-- 1 siyun siyun      2051 Sep 21 16:37 mothur.1505979412.logfile
-rw-rw-r-- 1 siyun siyun      1375 Sep 21 16:37 mothur.1505979434.logfile
-rw-rw-r-- 1 siyun siyun      1587 Sep 21 16:37 mothur.1505979435.logfile
-rw-rw-r-- 1 siyun siyun      1587 Sep 21 16:37 mothur.1505979436.logfile
-rw-rw-r-- 1 siyun siyun      3718 Sep 21 16:37 summary.log
_________________________________________________________________________________

Pleas, help me to deal with the problem.
Very many thanks

**Comment by mothur-westcott** [comment]
The remove.seqs command is run after the chimera commands to remove any chimeras detected from your dataset.  Mothur's output indicates you did not have any chimeras in your dataset, so the file containing the list of chimeras is blank.  You can skip the remove.seqs command, because there are no chimeras to remove.
