### ISSUE TITLE
Compile error on Ubuntu

### ISSUE THREAD

**Issue by metajinomics** [mothur/mothur#378]
Compile error on Ubuntu 16.04.3 LTS, when compile branch 1.40.0

Here is the error mesage:
/usr/bin/ld: source/summary.o: undefined reference to symbol 'pthread_create@@GLIBC_2.2.5'
//lib/x86_64-linux-gnu/libpthread.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
Makefile:87: recipe for target 'mothur' failed
make: *** [mothur] Error 1

Compliler version
c++ (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Needs -lpthread when linking. This error is not found on OSX, CentOS (Linux) but only Ubuntu(Linux), Adding -lpthread on Makefile does not create error on OSX and CentOS.

**Comment by mothur-westcott** [comment]
Thanks, I will update the makefile
