### ISSUE TITLE
Cluster.split command "stuck"

### ISSUE THREAD

**Issue by shawkr13** [mothur/mothur#389]
Hi everyone,

I'm in the process of attempting to work through the MiSeq SOP pipeline using the V3-V4 region of 16S. I have already created a custom alignment file for this region using Pat's guide here: http://blog.mothur.org/2016/07/07/Customization-for-your-region/.

I am at the point where I am running the cluster.split command, however while this command is running, the number of CPU's I have specified decreases to nearly 0 and the % of RAM that I am using increases to about 95%. I have tried several times to complete this step specifying different numbers of processors and different numbers of sequences, but it never gets any further than the point I have specified below. For example, I have 9 samples that have been running for over a week now using the following command:
___________________________________________________
cluster.split(fasta=NGS_subsample.trim.contigs.good.unique.good.filter.unique.precluster.pick.pick.fasta, count=NGS_subsample.trim.contigs.good.unique.good.filter.unique.precluster.denovo.vsearch.pick.pick.count_table, taxonomy=NGS_subsample.trim.contigs.good.unique.good.filter.unique.precluster.pick.pds.wang.pick.taxonomy, splitmethod=classify, taxlevel=4, cutoff=0.03, processors=5)
___________________________________________________

The following code is what has been on my screen for the majority of that time:
____________________________________________________
Clustering /data/shawn/NGS_subsample/NGS_subsample.trim.contigs.good.unique.good.filter.unique.precluster.pick.pick.fasta.1.dist

tp	tn	fp	fn	sensitivity	specificity	ppv	npv	fdr	accuracy	mcc	f1score
91078935	84562182	7649527	8231162	0.917117	0.917044	0.92252	0.911296	0.0774805	0.917082	0.833988	0.91981

Clustering /data/shawn/NGS_subsample/NGS_subsample.trim.contigs.good.unique.good.filter.unique.precluster.pick.pick.fasta.0.dist
_____________________________________________________

It is as though the program has nearly stopped completely, and I am not sure what to do. The computer I am using has 64GB of RAM and has roughly 6TB of HD space. I am running version 1.39.5 of mothur. Also, I have 179,136 unique sequences and 485,661 total sequences.

Any help would be greatly appreciated, as I don't know what to do at this point to resolve this! My entire project has about 78 samples total, so if 9 is not going to work at the cluster.split step to generate OTU's, I do not know what I will do. 

Shawn

**Comment by mothur-westcott** [comment]
I suspect you are running into this problem, http://blog.mothur.org/2014/09/11/Why-such-a-large-distance-matrix/.  One thing to try is using the cluster and file parameters, https://www.mothur.org/wiki/Cluster.split#file.

**Comment by jevaremdphd** [comment]
Hello! Were you able to resolve this issue? I think I have the same problem. Any help would be appreciated.

**Comment by shawkr13** [comment]
Unfortunately, no. After encountering this problem I decided to go back to my .fastq files and I decided to do some initial quality trimming with Trimmomatic. This cut down on the number of sequences being inputed to mothur and it sped things up a little bit with the early steps of the pipeline, but I still ran into the same issue with the "cluster.split" command. I ended up having a distance matrix of roughly 2.3TB -
 still much too large for my computer to process.

My supervisor suggested that I take a look at QIIME instead, so that's what I've been up to since then.

**Comment by jevaremdphd** [comment]
I see. Thank you for this reply.

I have a different question, somehow related to this question.

In screening for the sequences earlier in the process, how do I determine the "maxlength" parameter?

Thank you.

**Comment by shawkr13** [comment]
Hi, sorry for the delayed response. The 'maxlength' parameter is meant to be slightly longer than the sequence length of interest that you are looking at. It will essentially discard any sequences that are greater than the value that you specify. For example, I am dealing with the 16S V3-V4 region which is roughly 465bp in length so I set my 'maxlength' value to 470bp. This means that I am keeping all sequences that fall below 470bp and am throwing away all others. Running the 'summary.seqs' command before and after filtering will show you how many sequences were eliminated overall.
