### ISSUE TITLE
problem with installation mothur 1.39.5 on macbook pro running IOS10.13

### ISSUE THREAD

**Issue by matrapp** [mothur/mothur#390]
Dear everybody, 

I am trying to install mothur 1.39.5 on my mac book pro running IOS 10.13. I always get some error messages. I have tried few things, which i have found as possible solutions, but none of them worked so far: 

~ user$ ~/mothur/mothur
-bash: /Users/mariliatrapp/mothur/mothur: Permission denied

~ user$ ../mothur/mothur
-bash: ../mothur/mothur: No such file or directory

~ user$ ./mothur/mothur
-bash: ./mothur/mothur: Permission denied

Does anybody have a suggestion about what else i could try?

Thank you in advance 

Best

MArilia

**Comment by matrapp** [comment]
Just fix it...

Not sure if it is the best way, but it worked for me...

If someone has the same problem just download xcode from apple store... and try to instal Mothur again...

source :https://apple.stackexchange.com/questions/254380/macos-sierra-invalid-active-developer-path

**Comment by mothur-westcott** [comment]
Version 1.40.0 is built on 10.13.  It's releasing Friday.
