### ISSUE TITLE
Alignment removing base

### ISSUE THREAD

**Issue by mothur-westcott** [mothur/mothur#391]
Please Note: I re-posting my question from http://blog.mothur.org/2016/07/07/Custo ... ur-region/ 
My intention is to understand about this observation. Thank you. 

Step 1: Obtain the alignment coordinates with respect to silva.seed_v128.align

Align: 16sv4.fasta vs. silva.seed_v128.align
Outcome: Start = 11895, End = 25318, NBases = 292
Using the start and end coordinate information, we trim silva.seed_v128.align database.

Step 2: Align the input 16sv4.fasta against the newly trimmed silva database

Align: 16sv4.fasta vs. silva_seed_v128_16sV4.align ( -> This is the newly Trimmed silva db )
Outcome: Start = 2, End = 13423, NBases = 291

My Question:

Why is the resulting alignment with the trimmed silva database 1-base less ( 291 bases instead of 292 bases ) ?

**Comment by rrohwer** [comment]
FYI I think this is the same bug as issue #348 (*think is keyword*)

**Comment by mothur-westcott** [comment]
I ran the following with the bug fix to pcr.seqs included.  

mothur > pcr.seqs(fasta=silva.seed_v128.align, start=11895, end=25318)

Want to give the alignment another try?

[silva.seed_v128.pcr.align.zip](https://github.com/mothur/mothur/files/1439218/silva.seed_v128.pcr.align.zip)
