### ISSUE TITLE
rename.file wiki example needs updating

### ISSUE THREAD

**Issue by campenr** [mothur/mothur#392]
Hello

The wiki doc for [rename.file](https://www.mothur.org/wiki/Rename.file) has the following broken example:

    mothur > rename.file(input=stability.trim.contigs.good.unique.good.filter.unique.precluster.pick.pick.pick.an.unique_list.shared, output=final.an.shared)

This throws an error (at least in v1.39.5) that `output` is not a valid parameter. According to `help(rename.file)`  the parameter `new` is used to specify the new file name, not `output`.

Therefore, the example should be updated to:

    mothur > rename.file(input=stability.trim.contigs.good.unique.good.filter.unique.precluster.pick.pick.pick.an.unique_list.shared, new=final.an.shared)

Cheers
Richard

**Comment by mothur-westcott** [comment]
Thanks for bringing this to our attention.
