### ISSUE TITLE
Pre.cluster command is not executing

### ISSUE THREAD

**Issue by mirzaabidpp** [mothur/mothur#394]
Hi Sarah!
I am facing problem in pre.cluster command of mothur. I am doing ITS analysis and this command is taking too much time (7 days for about 2,00,000 sequences but it is still running i.e. no output up till now). It is really embarrassing because i have to analyze quite big data but this step is taking too much time. I have 5 more similar type of files for running same command. I have 64 processors and enough disk space but unable to use 16 or 20 processors for quick analysis but it is only using maximum 4 processors. 
Command in use is
pre.cluster(fasta=myfile.fasta, count=myfile.count_table, diffs=2, processors=8)
pre.cluster(fasta=myfile.fasta, count=myfile.count_table, diffs=2, processors=12)
pre.cluster(fasta=myfile.fasta, count=myfile.count_table, diffs=2, processors=16)

I am using mothur version 1.39.5. Few days ago i tried same command and parameters on 234,489 sequences with  processors=8 and it finished working after 142805 seconds but now the case is more worse. I am stuck in only this command from last 20 days I have to do a lot of more analysis.
I need your prompt response in this regard.

Regards,
Abid

**Comment by mothur-westcott** [comment]
How many unique sequences do you have? How many total sequences? Are there other processes competing for processor time?

**Comment by mirzaabidpp** [comment]
In running file I have 2,43,886 sequences while in total I have round about 1.7 million sequences. I have run this command solely while no other process was running. All other commands before pre.cluster step are working fine.

**Comment by mothur-westcott** [comment]
The size of your dataset is likely the cause of the delay.

**Comment by mirzaabidpp** [comment]
I am working only on 2,43,886 sequences, it is running from last 15 days with no output at all.

**Comment by mirzaabidpp** [comment]
Hi Sarah!
I further split my data and tried to run pre.cluster command on individual sample that contains about 64,798 sequences and it is also not executing while running from more than 30 hours. This much time consumption is creating panic. If you need my sample sequences then I can send it to you. Please suggest me suitable solution as I am stuck in this command from last 30 days.

**Comment by pschloss** [comment]
as @mothur-westcott said, the problem is likely that you have too many unique sequences. what region did you sequence? you can either continue to be patient and/or consult [this blog post](http://blog.mothur.org/2014/09/11/Why-such-a-large-distance-matrix/) about what's going on when people have a large number of uniques.

**Comment by mirzaabidpp** [comment]
I have sequences for ITS analysis

**Comment by mirzaabidpp** [comment]
Hi pschloss,
Is there any other option except pre.cluster for ITS sequences analysis. I have seen there are many unique sequences in my file that may be the cause of delay. But I am unable to use 8 or more processors as well as it is embarrassing process with no output uptil now. Please could you suggest me any other step instead of pre.cluster to save my time. I spent alot of time to learn and work with mothur I hope you will understand my situation. I'll be thankful to you for your favorable response. 
Regards, 
Abid
