### ISSUE TITLE
Avoid processing only forward direction reads. Here's why:

### ISSUE THREAD

**Issue by mothur-westcott** [mothur/mothur#396]
We strongly discourage only using forward reads due to the increased error rate and spurious OTUs.  We have found processing datasets like these produces similar results to those outlined in the http://blog.mothur.org/2014/09/11/Why-such-a-large-distance-matrix/blog.  

Here's Pat's thoughts about what you should do?

"In our lab it costs about $5000 to sequence 400 samples on a MiSeq using our protocol. How much is your time worth to you? How much is that extra RAM you’re thinking about buying? How much does time on your university’s superduper computer cost? But really, how much is good data worth to you? I suspect the sum of those questions is more than $5000. What should you do? Resequence the data and do it right. If you can’t find someone to do it right, let me know and I can hook you up with people that can."

But, if you still want to proceed, here's how:

mothur > fastq.info(fastq=yourForwardReadFile) - Create fasta and qual files from your forward reads using the fastq.info command.
mothur > trim.seqs(fasta=current, qual=current, ... parameters to trim based on quality and/or oligos file to trim primers...)

Continue with the summary.seqs command following the make.contigs command in the MiSeq_SOP.

**Comment by Sreejata-mothur** [comment]
Hi Sarah, 
Thanks for this post. 
I am working on a dataset that possibly needs to be sequenced again, but for the moment I am going ahead with analyzing forward reads only. I am following your directions, but since I cannot make contigs, there is no group file for me to use in downstream processing. Also I have generated individual trim.fasta file for each sample, so how to merge them into one fasta file to use the command: summary.seqs(fasta=projectname.trim.fasta? 
Would be grateful for any suggestions,
Thanks so much!

**Comment by mothur-westcott** [comment]
You can create a group file with the make.group command, https://www.mothur.org/wiki/Make.group.  Once you have made the group file you can merge your fasta files with the merge.files command, https://www.mothur.org/wiki/Merge.files.

**Comment by Sreejata-mothur** [comment]
I have about 50 samples so is there a way to specify alphabetically using A-B-C : mothur > make.group(fasta=sample1.fasta-sample2.fasta-sample3.fasta, groups=A-B-C)?

**Comment by mothur-westcott** [comment]
You can name the groups anything you wish.  Try to avoid special characters in the group names.  For example ':' character is a special character in trees. Also '-' is a special separator for mothur.  You can use '_' character, instead.

**Comment by Sreejata-mothur** [comment]
Thanks. This worked!
