### ISSUE TITLE
chimera.vsearch command not being able to read my fasta file

### ISSUE THREAD

**Issue by oroorbach** [mothur/mothur#400]
Hello,

I am fairly new to coding and have been working with mothur for the past year or so. 

I am trying to run the chimera.vsearch file but keep getting this error... Is this due to a mistake make in my precluster fasta file? Or is this the vsearch flow not being able to find the file? 

Using 12 processors.
/home/ross/anaconda2/envs/OR_mothur/bin/mothurvsearch file does not exist. Checking path... 
Found vsearch in your path, using /home/ross/OR_mothur/mothur/ACEdata/CCAseqs/vsearch
Checking sequences from stability.trim.contigs.good.unique.good.filter.unique.precluster.fasta ...
When using template=self, mothur can only use 1 processor, continuing.
/home/ross/OR_mothur/mothur/ACEdata/CCAseqs/vsearch: 1: /home/ross/OR_mothur/mothur/ACEdata/CCAseqs/vsearch: ???????!H__PAGEZERO?__TEX__text__TEXT?????__stubs__TEXTrj?__stub_helper__TEXT???__cstring__TEXT?: not found
/home/ross/OR_mothur/mothur/ACEdata/CCAseqs/vsearch: 2: /home/ross/OR_mothur/mothur/ACEdata/CCAseqs/vsearch: Ֆ?: not found
/home/ross/OR_mothur/mothur/ACEdata/CCAseqs/vsearch: 3: /home/ross/OR_mothur/mothur/ACEdata/CCAseqs/vsearch: Syntax error: "(" unexpected
Error in reading your fastafile, at position -1. Blank name.

Thanks so much!!

**Comment by mothur-westcott** [comment]
I'm wondering if mothur isn't processing the location in the path correctly. Could you try putting the vsearch executable in the same location as the mothur executable and rerun the command?

**Comment by oroorbach** [comment]
Hi,
I did the but then mothur couldn't find vsearch at all, even though I reset the PATH so she would know where to look for the executable.

**Comment by mothur-westcott** [comment]
Could you set the debug command to capture the parameters mothur is passing to vsearch? 

mothur > set.dir(debug=t)
mothur > chimera.vsearch(...your parameters...)

You might also create an issue with the vsearch team to see if they have some suggestions.

**Comment by oroorbach** [comment]
Hi,

Do you know which version of vsearch mothur needs? I ran the debug and am still having the same issues. 

Thanks!
