### ISSUE TITLE
Missing wiki pages for some Mothur tools

### ISSUE THREAD

**Issue by arbernard** [mothur/mothur#401]
Hi everyone !

I recently noticed that the help pages for some tools have been removed from the official Mothur wiki.

Based on Mothur release notes I saw that the missing pages are those of tools that have been removed in recent version of Mothur (Ex: hcluster, get.otulabels).

However, I think that not every users are using the latest version of Mothur.

For example, Galaxy users that are using the Mothur wrappers created by the IUC members are probably using Mothur 1.36.x at the moment (Wrappers for Mothur 1.39.x are currently being developped though).

I know that maintaining a page for every revision of a given tool is not realistic (way too much work and might be confusing for the end users) but would it be possible to keep the latest version of the page of a tool on the wiki even if the tool is being removed from Mothur itself please ?

If so, would you mind restoring the content of the hcluster and get.otulabels pages please ? (and eventually tag/mark them as valid up to version 1.x of Mothur maybe ?)

Thanks in advance :)

**Comment by pschloss** [comment]
Hey, well look into the get.otulabels. if galaxy is still using 1.36 then you should use a different platform that allows you to use the more current version. There have been significant improvements to the algorithms that I would consider critical. Hcluster is a painfully slow algorithm that is worse in terms of performance and otu quality compared to cluster (even in 1.36). You really should be using opti.clust in 1.39. I would strongly discourage the use of hcluster.

**Comment by arbernard** [comment]
Thanks for the fast answer !

Using the latest version of Mothur is indeed the best solution for people that can setup there tools the way they want on the computing ressources they have access to :)

This goal of using the latest version of a tool is the reason why the contributors of the tools-iuc repository are updating the wrappers to switch to Mothur 1.39.x by default (but it takes time).

To clarify my initial message, I'm obviously not asking the Mothur developpers to maintain old deprecated tools in Mothur itself but just to keep the wiki pages of the tools that are being or have been removed in recent version of Mothur if it's possible.

**Comment by mothur-westcott** [comment]
Thanks for the suggestion. The get.otulabels command was renamed to get.otus in later versions.  Here's a link to the edited page, https://www.mothur.org/wiki/Get.otus.
