### ISSUE TITLE
Using BLAST with classify.seqs

### ISSUE THREAD

**Issue by rwinand** [mothur/mothur#403]
Hi,

For some testing I am trying to run Mothur (1.39.1, Ubuntu 14.04) classify.seqs with the search option blast. This always leads to the following errors:

[ERROR]: /testdir/mothur/mothur/blast/bin/formatdb file does not exist. mothur requires formatdb.exe.
[ERROR]: /testdir/mothur/mothur/blast/bin/blastall file does not exist. mothur requires blastall.exe.
[ERROR]: /testdir/mothur/mothur/blast/bin/megablast file does not exist. mothur requires megablast.exe.

The Mothur binary is located in /testdir so creating a softlink to the blast binaries doesn't work as the directory cannot be created. I checked and the location of the blast binaries on my system is in $PATH and I can execute each one on the command line. Is there any way I can manually set the location of the blast binaries?

Best regards
Raf

**Comment by mothur-westcott** [comment]
You can set it with the blastdir parameter. https://mothur.org/wiki/Set.dir#blastdir

**Comment by rwinand** [comment]
Thanks for the reply!

I tried setting it as a parameter in classify.seqs but then I get the following error:

blastdir is not a valid parameter.
The valid parameters are: taxonomy, reference, fasta, name, count, group, output, search, ksize, method, processors, match, printlevel, mismatch, gapopen, gapextend, cutoff, probs, iters, shortcuts, relabund, numwanted, seed, inputdir, and outputdir.

Using 1 processors.
[ERROR]: did not complete classify.seqs.

I also tried running it with the set.dir command itself:

mothur > set.dir(blastdir=/usr/local/bin/blast/2.2.22/)
Mothur's directories:
Blast Location=/usr/local/bin/blast/2.2.22/

But when running classify.seqs again, I get the same error as before. I also downloaded version 1.39.5 to check if this might have been fixed but it has the same issues.

**Comment by mothur-westcott** [comment]
Thanks for reporting this issue.  I am sorry the blastdir parameter is not working as expected.  I will flag this issue for a bug fix.  In the meantime as a workaround you can put the blast directory containing the executables in the mothur folder.

**Comment by rec3141** [comment]
Also having issues with BLAST and classify.seqs. I have 3 problems:

1) I tried putting the latest BLAST executables in the working directory under ./blast and ./blast/bin but it says it can't find them. Should be solved by this bugfix?

2) It also seems to be looking for the now very old legacy versions of BLAST including blastall etc., which haven't been supported since 2012. Is this just that the error messages haven't been updated?

3) After failing to find the executables, mothur won't die using control-c.

Thanks!

```
mothur > classify.seqs(seed=clear,fasta=arctic.trim.contigs.unique.filter.precluster.pick.pick.fasta, reference=silva.nr_v132.align, taxonomy=silva.full_v132.full.tax, cutoff=0, processors=16, method=knn, search=blast)
Setting random seed to 1520203299.

Using 16 processors.
Generating search database...    [ERROR]: /Volumes/work/cryomics/seq_data/Arctic_Seq-66252198/mothur16S_full/blast/bin/formatdb file does not exist. mothur requires formatdb.exe.
[ERROR]: /Volumes/work/cryomics/seq_data/Arctic_Seq-66252198/mothur16S_full/blast/bin/blastall file does not exist. mothur requires blastall.exe.
[ERROR]: /Volumes/work/cryomics/seq_data/Arctic_Seq-66252198/mothur16S_full/blast/bin/megablast file does not exist. mothur requires megablast.exe.
^C
quitting command...
^C
quitting command...
^C
quitting command...
^C
quitting command...
^C
quitting command...
^C
quitting command...
```

**Comment by mothur-westcott** [comment]
1. Could you post the results of 'which blast'?

2. The version of blast needed by mothur is distributed with the mothur executables.  

3. Thanks for reporting this, I will take a look.

**Comment by rec3141** [comment]
there's no executable called 'blast' but `which blastall` gives `/usr/local/bin/blastall`

**Comment by mothur-westcott** [comment]
Are the formatdb and megablast executables located in /usr/local/bin/ as well? If so, the issue is the missing blast directory.  Mothur is expecting to find, /usr/local/bin/blast/blastall.  If you create a blast directory in /usr/local/bin/ and place the blast exes in it you can run:

mothur > set.dir(blastdir=/usr/local/bin)
