### ISSUE TITLE
fastq files not found

### ISSUE THREAD

**Issue by IrshadUlHaq1** [mothur/mothur#404]
I get the following error when using the command:

mothur > make.file(inputdir=Users/irshadulhaq/Desktop/Database/Primer, type=fastq, prefix=stability)
Setting input directory to: Users/irshadulhaq/Desktop/Database/Primer/
[WARNING]: Unable to find any fastq files in your directory.

Output File Names:

**Comment by mothur-westcott** [comment]
Are you able to open the fastq files from other commands in mothur? For example:  

mothur > fastq.info(fastq=Users/irshadulhaq/Desktop/Database/Primer/yourFastqFileName.fastq)
