### ISSUE TITLE
pcr.seqs(fasta=DictDb_v3.fasta, start=11894, end=25319, keepdots=F, processors=8)

### ISSUE THREAD

**Issue by IrshadUlHaq1** [mothur/mothur#406]
It gives me the following error. Even if I change the "end=25319".

mothur > pcr.seqs(fasta=DictDb_v3.fasta, start=11894, end=25319, keepdots=F, processors=8)

Using 8 processors.
[ERROR]: end is longer than your sequence length, aborting.
[ERROR]: end is longer than your sequence length, aborting.
[ERROR]: end is longer than your sequence length, aborting.
[ERROR]: end is longer than your sequence length, aborting.
[ERROR]: end is longer than your sequence length, aborting.
[ERROR]: end is longer than your sequence length, aborting.
[ERROR]: end is longer than your sequence length, aborting.
[ERROR]: end is longer than your sequence length, aborting.

**Comment by mothur-westcott** [comment]
How long are your sequences?
