### ISSUE TITLE
Pre.cluster( ) file mismatch error mothur v.1.39.5

### ISSUE THREAD

**Issue by aemmons90** [mothur/mothur#407]
I am having a file mismatch issue with pre.cluster( ). 
[ERROR]: group " " is not in your count table. please correct. 
This error has occurred after seemingly pre-clustering all of my samples. I have included the most current fasta and count table and have checked over all steps to make sure a mistake was not made according to the SOPs. Could this be due to a bug?  I have rerun the command several times with varying processor quantities. I generally use 16 processors but have also used only 1.

**Comment by mothur-westcott** [comment]
To help us resolve issues quickly, please include the following:

A detailed description of the error. The more specific you can be the easier it is for us to solve the problem. There is no detail too small or insignificant.

The log file - The log file includes important information for us about your hardware, version of mothur and release date. It also shows us the workflow and helps us spot simple errors. The log file helps us diagnose most issues quickly without the need for additional data.

Additional information you are welcome to provide:

The input files use with the command causing the issue. If they are too large to attach often a small sample of the file is enough. To select the first 500 lines from a file you can use the head system command. ex. head -n 500 yourInputFile > newFileNameForSampling

**Comment by aemmons90** [comment]
Thanks for the response! I thought perhaps this may be the wrong forum for this issue and was in the process of activating a mothur forum account?

The error involves a file mismatch (see reported error above); however, everything until this point seems to have run fine. I have rerun pre.cluster multiple times with varying amounts of processors. The latest run used only a single processor;  after reviewing a post concerning a similar problem online, I thought using a single processor may solve the problem. However, this did not fix the issue. Please find the latest log file attached. 
[mothur.1510813469.logfile.txt](https://github.com/mothur/mothur/files/1492509/mothur.1510813469.logfile.txt)

**Comment by mothur-westcott** [comment]
You are welcome to create issues here or ask questions on the forum. The output in the log file looks strange... almost like group name is in the format of a name file??  Could you send me a sample of your fasta file and your count file so I can troubleshoot the issue for you?

**Comment by aemmons90** [comment]
Please find sample fasta and count files attached. Thanks!

[Sample_fasta.fasta.txt](https://github.com/mothur/mothur/files/1492547/Sample_fasta.fasta.txt)
[Sample_count_table.count_table.txt](https://github.com/mothur/mothur/files/1492548/Sample_count_table.count_table.txt)

**Comment by mothur-westcott** [comment]
I am not seeing an error with the files you sent.  Are you able to reproduce the issue with the sample files?

**Comment by aemmons90** [comment]
No, I am not seeing the error with the sample files; these include the first 500 lines of my fasta and count table files. The complete files are very large. Should I try to attach them?

**Comment by mothur-westcott** [comment]
Can you compress them and post them here or send a dropbox invite to mothur.bugs@gmail.com so I can reproduce the issue?

**Comment by aemmons90** [comment]
Does google drive work? Even with compression, the files are too large to post here (maximum size 10MB).

**Comment by mothur-westcott** [comment]
Yes

**Comment by mothur-westcott** [comment]
The count file decompression failed.  Could you resend it?

**Comment by liufangbaishikele** [comment]
[mothur.1512496571.logfile.zip](https://github.com/mothur/mothur/files/1532504/mothur.1512496571.logfile.zip)
[fungi_R1.trim.contigs.good.unique.good.filter.count_table.zip](https://github.com/mothur/mothur/files/1532505/fungi_R1.trim.contigs.good.unique.good.filter.count_table.zip)
[fungi_R1.trim.contigs.good.unique.good.filter.unique.fasta.zip](https://github.com/mothur/mothur/files/1532506/fungi_R1.trim.contigs.good.unique.good.filter.unique.fasta.zip)


I came across same problem. I used mothur for a couple of dataset, it worked just fine for me. BUT this time it stuck at pre.cluster step.
**Error info**: [ERROR]: group M00238_212_000000000-AYCVK_1_1101_15422_1379,M00238_212_000000000-AYCVK_1_1101_12545_1713,....is not in your count table. Please correct.

BUT, I found the group ID in my count_table by ``grep ``command. SO, it just does not make sense for me. I am not sure if it is because I am using a server or not. I tried 8 and 1 processor. Got same error. Please find my log file and input file. Could you help to test if this errors due to our server or a bug? Appreciate for you thoughts!

**Comment by liufangbaishikele** [comment]
I figured out the problem in my case. I downloaded mothur/1.39.5 (same version as I used on our server) and run same command on my Mac. It just worked fine. Hope this information will be helpful for someone. 

I  guess **Something is incompatible between our server and pre.cluster algorithm, I don't know what exactly it is**

**Comment by aemmons90** [comment]
Thanks for the comment! I too am using an advanced computing server on campus. I will retry locally and see if this solves my issue.

**Comment by liufangbaishikele** [comment]
You are welcome!

**Comment by mothur-westcott** [comment]
Thanks for the additional information.

**Comment by aemmons90** [comment]
As @liufangbaishikele suggested, I tried to rerun pre.cluster( ) locally. It failed with multiple processors; however, when I used a single processor it seemed to work. All map files and a single count file and fasta file resulted. However, though the  mothur log file appeared to be normal, the output fasta file in my directory was named stability.files.pc.trim.contigs.good.unique.good.filter.unique.precluster.fastatemp rather than stability.files.pc.trim.contigs.good.unique.good.filter.unique.precluster.fasta. The latter of which was listed in the resulting mothur logfile. I can post this logfile later. It is on my home (Desktop) computer. I think  stability.files.pc.trim.contigs.good.unique.good.filter.unique.precluster.fastatemp may be the final fasta file and perhaps something went wrong while combining temp files and renaming.

**Comment by aemmons90** [comment]
Here is the latest logfile:
[mothur.1512529803.txt](https://github.com/mothur/mothur/files/1543087/mothur.1512529803.txt)

**Comment by mothur-westcott** [comment]
Have you tried running summary.seqs on the output files from pre.cluster to check their validity?

mothur > summary.seqs(fasta=stability.files.pc.trim.contigs.good.unique.good.filter.unique.precluster.fastatemp, count=stability.files.pc.trim.contigs.good.unique.good.filter.unique.precluster.count_table)

Does it run without error? Does the total number of sequences reported by summary.seqs match your total before pre.cluster?

**Comment by aemmons90** [comment]
Yes, the total number of sequences is the same and it runs without an error. I guess the issue is with the number of processors and using a server. Thanks for the help!

**Comment by crivaldi** [comment]
I'm having the same issue using my university's cluster
mothur version 1.39.5, server is a linux redhat, job has been running for a few days. Job was submitted with the use of 180 processors, mothur command specified 180 processors, but as far as I can tell is only using 1.
(I can provide more info when job finishes but just adding data for now. For the record, I've tried running this in an interactive node and got the same message that it would only run on 1 processor when no groups were provided).

**Comment by mothur-westcott** [comment]
The threaded code for the pre.cluster command divides the work by sample.  It uses one processor to divide the work and then uses multiple processors to cluster the samples.  If you only have one sample (no group information provided), then mothur uses 1 processor for the entire command.  The number of processors used cannot exceed the number of groups in your dataset. Could you post the command you ran?

**Comment by crivaldi** [comment]
The threading information is good to know, thank you. Attached is my batch script - I've submitted this in chunks because I was unsure of the total time it would take to run & perhaps lost my group info along the way. It's currently still running (started ~4 days ago). 

[Pre_cluster_script.txt](https://github.com/mothur/mothur/files/1781091/Pre_cluster_script.txt)

**Comment by mothur-westcott** [comment]
Can you look in the stability.files file to make sure you have unique sample names?  https://github.com/mothur/mothur/issues/411

**Comment by crivaldi** [comment]
They are all unique, yes (some differ after a maximum of 12 characters if that is important).

**Comment by crivaldi** [comment]
I'll give this a shot & report back. Thanks!
