### ISSUE TITLE
Error while trying to use picrust

### ISSUE THREAD

**Issue by SantoshThapa1** [mothur/mothur#409]
Hello there,

I am new to mothur, so bare with me for my rudimentary question. I am trying to analyze  my data with picrust.

I downloaded the OTU ID maps from https://www.mothur.org/wiki/Make.biom. The downloaded OTU ID map file has a name- "GG_13_5_otuMapTable". I copied all the files that reads ‘64_otu_map’ to ‘99_otu_map’ in that zip file and pasted in my working folder (along with mothur) and then, I renamed a text file that had “97_otu_map” to  ‘97.gg.otu_map’. And, used the following command:
mothur > make.biom(shared=16S.final.an.unique_list.shared,label=0.03, reftaxonomy=gg_13_5_otuMapTable.zip,constaxonomy=16S.final.an.unique_list.0.03.cons.taxonomy, picrust= 97.gg.otu_map.txt)

The command worked, but got the following error.
0.03
[ERROR]: PK   is missing the final ';', ignoring.
[ERROR]:  må≥R is missing the final ';', ignoring.
[ERROR]: k__Bacteria;p__Proteobacteria;c__Alphaproteobacteria;o__Rickettsiales;f__Rickettsiaceae;g__Rickettsia; is not in taxonomy tree, please correct.

FYI, I am using mothur version 1.39.5.  

Furthermore, do I need to install picrust separately ( I thought that the picrust and reftaxonomy parameters are added in mothur version 1.33.0, and later release. Please correct me, if I am wrong!)?

Would be more than happy for your suggestions.

Thank you,
Santosh

**Comment by mothur-westcott** [comment]
reftaxonomy=gg_13_5_otuMapTable.zip If this file compressed, that could be the source of the errors.

**Comment by SantoshThapa1** [comment]
Hi Sarah,
Thanks for your response. I did unzip the file, but now I got another error as noted below:
COMMAND:
mothur > make.biom(shared=16S.final.an.unique_list.shared,label=0.03, reftaxonomy=gg_13_5_otuMapTable, constaxonomy=16S.final.an.unique_list.0.03.cons.taxonomy, picrust=97.gg.otu_map.txt)

RESULTS:
Unable to open gg_13_5_otuMapTable. 
[ERROR]: the reftaxonomy parameter is required with the picrust parameter, aborting.
[ERROR]: did not complete make.biom.

**Comment by mothur-westcott** [comment]
Could the file have an extension you are missing? Perhaps gg_13_5_otuMapTable.txt??

**Comment by SantoshThapa1** [comment]
Yes, there was an extension of the file with txt. I corrected it. But, now ran into another problem with many many errors as noted below:
OUTPUT: 
 0.03
[ERROR]: ﻿[ is missing the final ';', ignoring.
[ERROR]: Sun is missing the final ';', ignoring.
[ERROR]: 421164_0.00514 is missing the final ';', ignoring.
[ERROR]: 989926_0.00260 is missing the final ';', ignoring.
[ERROR]: 892241_0.00348 is missing the final ';', ignoring.

So, I suspect this error is probably due to the unmatch between the "gg_13_5_otuMapTable"  (that I  downloaded from https://www.mothur.org/wiki/Make.biom) to that of the gg version that I had used to classify my sequence (gg_13_8_99, downloaded from https://www.mothur.org/wiki/Greengenes-formatted_databases) [I found this discrepancies only last night!]. If this is the case, I have no idea how to make otumaptable for gg_13_8_99. Please suggest me. 

 Any thoughts please !
Thanks,

**Comment by mothur-westcott** [comment]
https://picrust.github.io/picrust/tutorials/otu_picking.html

The OTU tables available on the make.biom page are from the picrust team.  Their latest release is 13.5, so you either have to reclassify using the GG 13.5 references or you could contact the picrust team for instructions on how to create the table.

**Comment by SantoshThapa1** [comment]
Thank you for your suggestion.
