### ISSUE TITLE
make.file incorrectly assigning sample names in stability file

### ISSUE THREAD

**Issue by snejosh** [mothur/mothur#411]
Hi,
I am trying to follow the Mothur Miseq_SOP for analyzing my 16s data.
I have a folder with all my R1 and R2 fastq files and when I run the make.file command to generate the stability file, all the samples get the same name (the first word in the folder name). For example if I name my folder Miseq_December, all the samples get Miseq as the sample name in the stability file. I tried running the test data provided and it has the same issue. 
Has anyone faced this before?
Thanks!

**Comment by pschloss** [comment]
Sorry, this is a known bug that we are working on. Can you remove the underscore from the directory name? Perhaps try MiSeqDecember?

**Comment by nagoue** [comment]
Thank you for that tip: changing MiSeq_SOP to MiSeqSOP made it worked.

**Comment by mothur-westcott** [comment]
This is resolved in version 1.40.0.

**Comment by NazishAijaz** [comment]
Iam also suffering same problem but i dont understand how can i solve it i have my all samples name as rpoB.file

**Comment by mothur-westcott** [comment]
Are you using our current version?  Could you post your logfile?
