### ISSUE TITLE
Demultiplexing with checkorient

### ISSUE THREAD

**Issue by anslan** [mothur/mothur#412]
Hi,

I'm using trim.seqs command on mothur 1.39.5 to demultiplex sequences:
>trim.seqs(fasta=input.fasta, oligos=oligos.txt, bdiffs=1, pdiffs=2)

Oligos file contains only forward primer and tags attached to that primer:
forward NNNNNNNNNNN
barcode NNNNNN sample1
…

As half of the sequences in the input.fasta file are also reverse complementary, I make reverse complementary of the input 
>reverse.seqs(fasta=input.fasta)

and run demultiplexing again

>trim.seqs(fasta=input.rc.fasta, oligos=oligos.txt, bdiffs=1, pdiffs=2)

The sum output contains **81771** sequences.

However the question is, when I use **checkorient=t** option 
>trim.seqs(fasta=input.fasta, oligos=oligos.txt, checkorient=t, bdiffs=1, pdiffs=2

the total of all groups are **176438** sequences, which is all of the sequences in the input file (input.scrap.fasta is empty). Could you please explain why checkorient=t finds much more sequences?

**Comment by mothur-westcott** [comment]
The checkorient parameter is helpful with mixed direction reads.  When checkorient=t, mothur looks for the primers and barcodes as you provided in the oligos file, but it also checks for the reverse compliment.  Here's a concrete example:

forward atgctta
barcode aaccta sample1

Mothur would look for barcode 'aaccta' at the beginning of the sequence, if not found then mothur will also look for barcode 'taagcat' at the end of the sequence in case the sequence is the wrong direction.  If mothur finds the barcode in the reverse direction, then the sequence is trimmed and flipped. Does that help?
