### ISSUE TITLE
a dataset mixed with one-direction reading and paired-end reading

### ISSUE THREAD

**Issue by yzz0015** [mothur/mothur#413]
How can I process them together in Mothur? I know for one-direction, I can use fastq.info; and for paired-end, I need to make contigs first... But when they are all in one dataset, how should I do it?

Thanks

**Comment by mothur-westcott** [comment]
I need a little more information about your dataset.

What types of files do you have? 
Are all the reads in one file or are forward and reverse reads separated? 
Since the one direction are mixed in, can you separate them out? ie. Do you know "who" is one direction and who has paired reads, perhaps by sample?

**Comment by yzz0015** [comment]
Hi,

The files are in fastq format, and forward and reverse reads are separated for each sample.

They were all paired end sequenced, but some of the read from either forward or reverse had poor quality. So for these, we want to use the good reads from one direction. Yes, we can tell them by sample name.

Thank you so much!

Yuan

On Jan 2, 2018, at 10:38 AM, Sarah Westcott <notifications@github.com<mailto:notifications@github.com>> wrote:


I need a little more information about your dataset.

What types of files do you have?
Are all the reads in one file or are forward and reverse reads separated?
Since the one direction are mixed in, can you separate them out? ie. Do you know "who" is one direction and who has paired reads, perhaps by sample?

**Comment by mothur-westcott** [comment]
Okay, here's how I would proceed:

mothur > make.contigs(file=yourFileFile) - assemble the reads by sample. You can set quality screening with the insert and deltaq parameters (https://mothur.org/wiki/Make.contigs#insert). Reads that don't meet your quality screening will be put in the scrap file.

mothur > list.seqs(fasta=scrapFastaFileFromMakeContigs) - list names of sequences you want to replace

mothur > get.seqs(accnos=current, fasta=fileWithOneDirectionReads) - select sequences to replace

You can then merge the assemble reads and the good one direction reads files, and proceed with the rest of the SOP.

**Comment by yzz0015** [comment]
Thanks Sarah! I will try them soon.

Yuan


On Jan 2, 2018, at 3:21 PM, Sarah Westcott <notifications@github.com<mailto:notifications@github.com>> wrote:


Okay, here's how I would proceed:

mothur > make.contigs(file=yourFileFile) - assemble the reads by sample. You can set quality screening with the insert and deltaq parameters (https://mothur.org/wiki/Make.contigs#insert). Reads that don't meet your quality screening will be put in the scrap file.

mothur > list.seqs(fasta=scrapFastaFileFromMakeContigs) - list names of sequences you want to replace

mothur > get.seqs(accnos=current, fasta=fileWithOneDirectionReads) - select sequences to replace

You can then merge the assemble reads and the good one direction reads files, and proceed with the rest of the SOP.

**Comment by yzz0015** [comment]
Hi Sarah,

When I try to process make.contigs, it was unsuccessful. Mothur stoped the process because the forward reading of the 1st sample had many sequences that not in the reverse reading…

How should I proceed this?

Thanks,

Yuan





On Jan 2, 2018, at 2:21 PM, Sarah Westcott <notifications@github.com<mailto:notifications@github.com>> wrote:


Okay, here's how I would proceed:

mothur > make.contigs(file=yourFileFile) - assemble the reads by sample. You can set quality screening with the insert and deltaq parameters (https://mothur.org/wiki/Make.contigs#insert). Reads that don't meet your quality screening will be put in the scrap file.

mothur > list.seqs(fasta=scrapFastaFileFromMakeContigs) - list names of sequences you want to replace

mothur > get.seqs(accnos=current, fasta=fileWithOneDirectionReads) - select sequences to replace

You can then merge the assemble reads and the good one direction reads files, and proceed with the rest of the SOP.

**Comment by yzz0015** [comment]
Hi Sarah,

Problem solved.

Thanks.

Yuan

On Jan 10, 2018, at 2:01 PM, Zeng,Yuan <Yuan.Zeng@colostate.edu<mailto:Yuan.Zeng@colostate.edu>> wrote:

Hi Sarah,

When I try to process make.contigs, it was unsuccessful. Mothur stoped the process because the forward reading of the 1st sample had many sequences that not in the reverse reading…

How should I proceed this?

Thanks,

Yuan





On Jan 2, 2018, at 2:21 PM, Sarah Westcott <notifications@github.com<mailto:notifications@github.com>> wrote:


Okay, here's how I would proceed:

mothur > make.contigs(file=yourFileFile) - assemble the reads by sample. You can set quality screening with the insert and deltaq parameters (https://mothur.org/wiki/Make.contigs#insert). Reads that don't meet your quality screening will be put in the scrap file.

mothur > list.seqs(fasta=scrapFastaFileFromMakeContigs) - list names of sequences you want to replace

mothur > get.seqs(accnos=current, fasta=fileWithOneDirectionReads) - select sequences to replace

You can then merge the assemble reads and the good one direction reads files, and proceed with the rest of the SOP.
