### ISSUE TITLE
Cannot update count file due to file mismatch even after using screen.seq(fasta=*.fasta,count=*.count_table)

### ISSUE THREAD

**Issue by lightcoker** [mothur/mothur#414]
Hi everyone
I would like to ask about an file mismatch error which pop when using summary.seq(fasta=*.fasta,count=*.count_table).
I used pre.cluster(fasta=*,names=*,group=*) to generate the current fasta file.Before using pre.cluster(), I have a previous count file.
**Following MiSeq SOP on mothur wiki,I plan to use screen.seq() to update the count file by *.precluster.fasta**

By MiSeq SOP on mothur wiki:
"Note that we need the count table so that **we can update the table for the sequences** we're removing and we're also using the summary file so we don't have to figure out again all the start and stop positions:
mothur > screen.seqs(fasta=stability.trim.contigs.good.unique.align, count=stability.trim.contigs.good.count_table, summary=stability.trim.contigs.good.unique.summary, start=1968, end=11550, maxhomop=8)
mothur > summary.seqs(fasta=current, count=current)"

**But after using screen.seq(fasta=*.fasta,count=*.count_table), the summary.seq() still report error "File mismatch detected, quitting command.**
“[ERROR]: Your count file contains 517431 unique sequences, but your fasta file contains 467156. File mismatch detected, quitting command.”

I also tried using fasta and name file created by pre.cluster() and previous group file to create count file.
After using screen.seq(fasta=*.precluster.fasta,name=*.precluster.names,group=mergegroup), count.seqs(name=current, group=current) still report file mismatch error.

My question is:
**How can I update count file by fasta file?**
Thanks for taking your time again! If you have any suggestions or ideas, I would love to hear it : )

Best wishes,
Coke

Following are some log imformation:

ERROR 1:

mothur > screen.seqs(processors=16,optimize=start-end, criteria=20, fasta=/home/ubuntu/NEW/data/Moving_pictures_of_the_human_microbiome_ID_550/Mothur/totaluniquegoodgoodgoodaligngooduniquegoodprecluster,count=/home/ubuntu/NEW/data/Moving_pictures_of_the_human_microbiome_ID_550/Mothur/totalnamescount_tablegoodgoodgood)

Using 16 processors.
Optimizing start to 13862.
Optimizing end to 21780.

Output File Names:
/home/ubuntu/NEW/data/Moving_pictures_of_the_human_microbiome_ID_550/Mothur/totaluniquegoodgoodgoodaligngooduniquegoodpreclustergood
/home/ubuntu/NEW/data/Moving_pictures_of_the_human_microbiome_ID_550/Mothur/totaluniquegoodgoodgoodaligngooduniquegoodpreclusterbad.accnos
/home/ubuntu/NEW/data/Moving_pictures_of_the_human_microbiome_ID_550/Mothur/totalnamescount_tablegoodgoodgoodgood

It took 3336 secs to screen 1415619 sequences.

mothur > summary.seqs(fasta=current, count=current)
Using /home/ubuntu/NEW/data/Moving_pictures_of_the_human_microbiome_ID_550/Mothur/totalnamescount_tablegoodgoodgoodgood as input file for the count parameter.
Using /home/ubuntu/NEW/data/Moving_pictures_of_the_human_microbiome_ID_550/Mothur/totaluniquegoodgoodgoodaligngooduniquegoodpreclustergood as input file for the fasta parameter.

Using 16 processors.
[ERROR]: Your count file contains 517431 unique sequences, but your fasta file contains 467156. File mismatch detected, quitting command.

ERROR 2:

mothur > count.seqs(name=current, group=current)
Using /home/ubuntu/NEW/data/Moving_pictures_of_the_human_microbiome_ID_550/Mothur/mergegroupsgoodgood as input file for the group parameter.
Using /home/ubuntu/NEW/data/Moving_pictures_of_the_human_microbiome_ID_550/Mothur/totaluniquegoodgoodgoodaligngooduniquegoodprecluster.good.names as input file for the name parameter.

Using 16 processors.
[ERROR]: processes reported processing 1443389 sequences, but group file indicates you have 50195626 sequences. Either you have a file mismatch or a process failed to complete the task assigned to it.

**Comment by mothur-westcott** [comment]
We see this error most often when there's a typo in the filename and the wrong file is used accidentally, or when a process dies and fails to complete processing it's assigned sequences.  Could you check on a few things for me?

Try running summary.seqs on the files you inputted into screen.seqs.
mothur > summary.seqs(fasta=/home/ubuntu/NEW/data/Moving_pictures_of_the_human_microbiome_ID_550/Mothur/totaluniquegoodgoodgoodaligngooduniquegoodprecluster,count=/home/ubuntu/NEW/data/Moving_pictures_of_the_human_microbiome_ID_550/Mothur/totalnamescount_tablegoodgoodgood)

If no errors, then can you try running screen.seqs with 1 processor?

mothur > screen.seqs(processors=1,optimize=start-end, criteria=20, fasta=/home/ubuntu/NEW/data/Moving_pictures_of_the_human_microbiome_ID_550/Mothur/totaluniquegoodgoodgoodaligngooduniquegoodprecluster,count=/home/ubuntu/NEW/data/Moving_pictures_of_the_human_microbiome_ID_550/Mothur/totalnamescount_tablegoodgoodgood)

On a side note the criteria option seems really low.  criteria=20, optimize start will select the position that 20% of your sequences start before. optimize end will set the end position to the position 20% of your sequences end after.  Mothur will remove any sequence that starts after or ends before those positions.

**Comment by merryblues** [comment]
hello
I have exactly the same problem. can you help me


### summary.seqs(fasta=stability.trim.contigs.good.unique.good.align, count=stability.trim.contigs.good.count_table, processors=4)


**### _Using 4 processors.
[ERROR]: Your count file contains 1375906 unique sequences, but your fasta file contains 1371255. File mismatch detected, quitting command._**

i dont know what im doing wrong.

**Comment by mothur-westcott** [comment]
Could you post your complete logfile?

**Comment by Arkadiy-Garber** [comment]
Definitely still getting this error,, which I am sweeping under the rug by manually removing the addition sequences. But this is causing further errors downstream.

**Comment by mothur-westcott** [comment]
What version of mothur are you using? Could you post the logfile?
