### ISSUE TITLE
Cluster.fit command

### ISSUE THREAD

**Issue by mothur-westcott** [mothur/mothur#415]
Fit sequences to existing dataset model.  

* Calc distances needed - Within new data and from new data to model
* Initialize dataset model - sens.spec on existing data model, place new data in singletons  
*  Move new data sequences around until optimal fit is found
* Create new list file

Simple Example:
Old Data:
otu1    otu2   otu3   otu4   otu5
A,B,C,D,E   F,G,H,I   J,K   L   M

New Data:
N  O  P  Q  R

New List:
otu2   otu4  otu5
O,Q,R   N      P

**Comment by mothur-westcott** [comment]
To test cluster.fit to see how well subsampled sequences are fitted to original OTUs.

* sub.sample(fasta=final.fasta, size=1500) - select 1500 random sequences from 3772 originals.
* rename.seqs(fasta=current) - rename them to avoid "name already exists" errors
* cluster.fit(reffasta=final.fasta, refcount=final.count_table, fasta=final.subsample.renamed.fasta, list=final.opti_mcc.list, refcolumn=final.dist) - fit the subsample sequences into existing OTUs
* rename.seqs(list=current, map=final.subsample.renamed_map) - restore names of sequences to easily compare results

**Comment by mothur-westcott** [comment]
./mothur "#sub.sample(fasta=final.fasta, size=10);rename.seqs(fasta=current);cluster.fit(reffasta=final.fasta, refcount=final.count_table, fasta=current, list=final.opti_mcc.list, refcolumn=final.dist, fastamap=final.subsample.renamed_map);bin.seqs(list=current, fasta=final.subsample.fasta);bin.seqs(list=final.opti_mcc.list, fasta=final.fasta);list.seqs(fasta=final.subsample.renamed.opti_mcc.fit.0.03.fasta);sort.seqs(accnos=current, fasta=current);get.seqs(accnos=current, fasta=final.opti_mcc.0.03.fasta);sort.seqs(accnos=current, fasta=current);system(diff /Users/sarahwestcott/desktop/release/final.opti_mcc.0.03.pick.sorted.fasta /Users/sarahwestcott/desktop/release/final.subsample.renamed.opti_mcc.fit.0.03.sorted.fasta);"

**Comment by mothur-westcott** [comment]
Required: model list, fasta and count file as well as the fasta file to fit.  
Optional: model’s distance matrix to save the calc time, name or count file for fit data.
Outputs: Clustered fit data in a list file with OTUlabels from your model data.  If sequences are not fitted to the existing OTUS they are outputted in an *unfitted.list file.

**Comment by krmaas** [comment]
I"m sooooo excited for this option!!!!

**Comment by pschloss** [comment]
shhhh! don't tell anyone, it's ultra-top secret 😄

**Comment by mothur-westcott** [comment]
Add accnos parameter to assign reference sequences.
