### ISSUE TITLE
Variable output desipte setting seed

### ISSUE THREAD

**Issue by campenr** [mothur/mothur#416]
Hello

I'm running into a problem with reproducibility, where the output of my sequence processing pipeline is variable even though I am setting the seed using mothur's `set.seed()` command.

I have not pinned down what commands appear to be causing me issues specifically in my pipeline (which is basically the MiSeq SOP) but I am  getting variable output in my final `.cons.taxonomy` file (although not my `.shared` file) so that indicates that one or more commands in my pipeline is not providing reproducible output despite having a seed set.

I have also confirmed that the `lefse` command is giving me variable output downstream from my sequence processing step, and independent of any other commands that are causing me issues (re ran `lefse()` multiple times on the same shared file and got different results). 

I have tested this on both Windows 10 and Ubuntu 16.04 64-bit with mothur 1.39.5.

Cheers
Richard

**Comment by campenr** [comment]
To add more information, i get variable outcome regardless of whether I set the seed once with `set.seed()` of if I add a `seed` argument to individual mothur commands.

**Comment by mothur-westcott** [comment]
The lefse command sets a specific seed of 1982.  This is done to follow the original lefse program.  It resets the random seed at the end of the command to the current time.  I will update this in our next version to reset the seed to the previous seed before the lefse command.

Could you upload the files and command you ran that gave you inconsistent results for the classify.otu command?

**Comment by campenr** [comment]
I am not sure that solves my LefSe problem. If the lefse command is using the same seed every time (1982 as you say) then should it not produce an identical output every time it is executed with an identical output? This is not what I am finding, I am finding that the lefse command is producing inconsistent outputs.

Regarding the other commands, I have not pinned down exactly what command is being inconsistent in my pipeline yet, but I believe it to most likely be the `classify.seqs` command. I am attempting to narrow it down currently.

**Comment by campenr** [comment]
[Here](https://www.dropbox.com/s/p3y428hsc8ud6kx/seed_test.zip?dl=0) is a zipped file containing two examples of this behavior with the lefse command. The first is setting a seed then running lefse multiple times, the second does not set a seed and runs lefse multiple times.

Lefse is the only command being run (except set.logfile and set.dir, and when applicable set.seed), and the identical input is being used every time. Despite this, if you run `diff` etc. on the lefse summary files you can see they are not identical. 

My problem is that I would have expected these outputs to be identical if a seed has been set and identical inputs have been used.

**Comment by campenr** [comment]
[Here](https://www.dropbox.com/s/1dgoo794szq4fvx/classify.seqs_test.zip?dl=0) is a zip file containing my results from testing the `classify.seqs` command. As above I am using consistent input (same fasta file and count file) and same silva v128 V4 region reference alignment (which is not included for size reasons), setting the same seed before each command, and getting inconsistent outputs. The logfile in the .zip folder shows the exact commands run.

I have also included a .txt file of the output of running diff on the `.wang.taxonomy` files from running `classify.seqs` twice. This file shows that running the exact same `classify.seqs` command with the exact same input and exact same seed is giving different outputs.

Cheers
Richard

**Comment by mothur-westcott** [comment]
Thanks for providing such a detailed description of the issue.  It was very helpful.  I have resolved the classify.seqs issue.  If you would like to try out the fix, it's in the Threads_373 branch.

**Comment by campenr** [comment]
Great, that fixes this bug for me (on linux at least) and I am now getting identical output when using identical input and the same seed for `classify.seqs`.

However, I have found a (new?) bug where running `classify.seqs` more than once is failing (see logfile [here](https://pastebin.com/PDwKYATW)). This error goes away if I delete the `.numNonZero`, `.prob`, `.sum`, `.train`, and `.8mer` files (I don't need to necessarily delete all of these, but if i do bulk delete them it works fine). I don't believe I remember these files being generated in the current v1.39.5?

**Comment by mothur-westcott** [comment]
Those files are generated by mothur for the classify.seqs command in all versions.  They are shortcut files containing the probability data for the reference files.  Mothur looks at the files version number to determine if it needs to remake these shortcut files.  It looks like you added a special version tag, mothur v.1.39.5_Threads_373_classify_seqs_seed_fix.  Mothur is kinda picky about the version tag, and I suspect the parse of your unique tag is causing the crash.

**Comment by campenr** [comment]
Ah I see, I wanted to make sure to differentiate the build from the actual v1.39.5 version build, so that makes sense.

**Comment by campenr** [comment]
I rebuilt the Threads_373 branch without the version tag and I am no longer having that new bug, as you'd predicted.

As far as I can tell my original problem with inconsistent outputs is now completely resolved with both my sequence processing pipeline and with the downstream LefSe analysis, so I am happy for this to be closed if you are.

As a point of clarification, were all commands not using the seed properly? Or was it just a specific or random subset?

**Comment by mothur-westcott** [comment]
Thanks for the update!  Only some of the commands had issues.  The seeded random numbers were being generated correctly, but the processors shared the resource which caused the issue.  Each processor would ask for a random number, and the order was effected by which processor asked first.  The fix localized the resource, allowing each processor to have access to the same random numbers in the same order.
