### ISSUE TITLE
strange behaviour of screen.seqs

### ISSUE THREAD

**Issue by lucacozzuto** [mothur/mothur#421]
I tried to use screen.seqs with parameter start=4965 but I still have sequences starting at 263.
PS: I also see that in the wiki is present this in an example:
https://www.mothur.org/wiki/Screen.seqs#start_.26_end

**Comment by mothur-westcott** [comment]
The start parameter will remove sequences that start AFTER 4965.
The end parameter will remove sequence that end BEFORE xxx position.

What does your summary.seqs output look like?

**Comment by lucacozzuto** [comment]
I see, I was expecting the opposite. So in case I have most of the alignment between 4965 and 21977 and I want to trim here, should I make end=4965 and then start=21977?

**Comment by mothur-westcott** [comment]
A general rule of thumb is to set the start to the summary.seqs 97.5% start value, and the end to the 2.5% end value.  For the example below start=6334, end=25318.

                Start   End     NBases  Ambigs  Polymer NumSeqs
Minimum:        1046    1048    2       0       1       1
2.5%-tile:      6329    25318   446     0       4       17127
25%-tile:       6330    25432   449     0       4       171266
Median:         6332    25434   453     0       5       342532
75%-tile:       6332    25437   469     0       5       513797
97.5%-tile:     6334    25445   476     0       6       667936
Maximum:        43115   43116   500     0       8       685062
Mean:   6345.18 25405.1 457.805 0       4.81758
# of unique seqs:       417058
total # of seqs:        685062
