### ISSUE TITLE
cluster.split creates a "blank" split which causes mothur to hang

### ISSUE THREAD

**Issue by FMKerckhof** [mothur/mothur#423]
When processing a 300-sample Illumina MiSeq 300PE generated with V4 full overlap primers and following along with the MiSeq SOP I ran into an issue that I haven't seen before:
cluster.split created a split which gave rise to a blank dist file:

```
> cluster.split(fasta=current, count=current, taxonomy=current, splitmethod=classify, taxlevel=4, cutoff=0.03)
(... output truncated...)
Running command: dist.seqs(fasta=dataset3.trim.contigs.good.unique.good.filter.unique.precluster.pick.pick.fasta.78.temp, processors=14, cutoff=0.03)
Using 14 processors.
/******************************************/
0	0
1	0
dataset3.trim.contigs.good.unique.good.filter.unique.precluster.pick.pick.fasta.78.dist is blank. This can result if there are no distances below your cutoff.
Output File Names: 
dataset3.trim.contigs.good.unique.good.filter.unique.precluster.pick.pick.fasta.78.dist
It took 0 seconds to calculate the distances for 2 sequences.
```
This caused mothur to hang for almost 10 hours after which I decided to manually kill the command. Is this a known issue? What should I do: specify a higher cutoff for cluster.split? Or set a higher taxlevel for cluster.split? 

Kind regards,

FM

System configuration:
mothur 1.39.5, compiled from source, on Ubuntu server 16.04.3 LTS

If required I can supply logfiles as well.

**Comment by mothur-westcott** [comment]
We haven't seen this before. Mothur can create a blank file if there are not distances for the split file below the cutoff.  It shouldn't hang at that point, but instead flag the sequences in that split as singletons.  Could you send your input files to mothur.bugs@gmail.com so I can take a closer look?

**Comment by FMKerckhof** [comment]
Dear Sarah, sorry for only getting back to you on this now. Apparently what happened is that the drive got full which indeed caused mothur to hang. This is because some of  the cluster.split distance files exceeded 100GB of storage, and my drive was only 1TB large. Now, after cleaning the drive and running the command again I am running into the issue of running out of RAM. I have only got 192 GB of RAM available, and apparently that's not enough. That is to say, `cluster.split` works fine until `sens.spec` needs to be called. I have to say that I am a bit puzzled on what's going on here. This is the first time that I analyze full overlap V4 data (normally we use V3-V4) and I expected it to go a lot smoother.
``` 
Running command: sens.spec(cutoff=0.03, list=Stanley.ppc.05032018.opti_mcc.unique_list.list, column=Stanley.ppc.05032018.dist, count=Stanley.ppc.05032018.count)
```
Cluster.split appears to work fine but when the command above is called by it, it needs to read the `Stanley.ppc.05032018.dist` file which has a size of 178.3 GiB. Theoretically, this should fit into the RAM. However, in practice mothur just hangs for hours on end and does not do much anymore (2-3% processor activity, but nothing is written out to any file). The RAM is full and the Swap has almost completely filled up. 

Did I hit the limits of mothur here? I know 8.904.593 reads to cluster may be a bit much. Nevertheless, what are my options (I am aware of the [large distance matrix blogpost](http://blog.mothur.org/2014/09/11/Why-such-a-large-distance-matrix/))? I feel I did my due diligence and finally got my hands on some real, overlapping, V4 data. 

- Should I even bother running `cluster.split` with large=T?
- How critical is the `sens.spec` step to the whole cluster.split? The documentation on the mothur wiki doesn't tell me what it does, and I already appear to have the list file I was looking for.
- Should I try using another method then opticlust (is the `sens.spec` opticlust specific?).
- Or should I try to get some time on high-memory nodes at the local supercomputer?

System info: mothur latest release (1.39.5) compiled from source on Ubuntu server 16.04.3LTS

**Comment by mothur-westcott** [comment]
Should I even bother running cluster.split with large=T?

I would not recommend using large=t, because that only effects the clustering, not the sens.spec portion. 

How critical is the sens.spec step to the whole cluster.split? The documentation on the mothur wiki doesn't tell me what it does, and I already appear to have the list file I was looking for. I saw in the cluster.split documentation that I can turn it off, but what are the implications of doing so?

The sens.spec portion of cluster.split is not required.  It is meant to give you the overall quality of the merged list file, but you can always run it separately later if you wish. The sens.spec command will be rewritten for version 1.40 to reduce the memory usage.  But for now, you can set the runsensspec parameter to false.

**Comment by FMKerckhof** [comment]
Thank you! I figured so much, running without `runsensspec=false` worked smoothly.
