### ISSUE TITLE
make.file, directory does not exist or is not writable; make.contigs, assemble 0 reads 

### ISSUE THREAD

**Issue by SantoshThapa1** [mothur/mothur#424]
Hi,
I am using mothur v.1.39.5 on Windows PC to process MiSeq generated 16SV4 sequences. I have R1 and R2 files (gz) for each of my samples (n=124).  I used this command:  mothur > make.file(inputdir= fastqtest, type=fastq, prefix=stability), to make my stability files. But, got this message: 
fastqtest\ directory does not exist or is not writable.  File not found - fastqtest\*.fastq 
[ERROR]: fastqtest\fileList.temp is blank. Please correct. 
[WARNING]: Unable to find any fastq files in your directory.” 

BUT, when I changed the file type to gz [ mothur > make.file(inputdir= fastqtest, type=gz, prefix=stability) ], mothur keep saying this: fastqtest\ directory does not exist or is not writable. BUT, got an output as follows. Output File Names: fastqtest\stability.files. 

Can anyone please explain why this happened? 

FYI, my stability.files looks like this:
2017GS1TK	FASTQTEST\2017GS1TK_S54_L001_R1_001.FASTQ.GZ	
                        FASTQTEST\2017GS1TK_S54_L001_R2_001.FASTQ.GZ	
2017GS2TK	FASTQTEST\2017GS2TK_S55_L001_R1_001.FASTQ.GZ	
                        FASTQTEST\2017GS2TK_S55_L001_R2_001.FASTQ.GZ	
2017GS3TK	FASTQTEST\2017GS3TK_S56_L001_R1_001.FASTQ.GZ	
                        FASTQTEST\2017GS3TK_S56_L001_R2_001.FASTQ.GZ.......................

NOW, I am having problem to make.contigs using the stability files that was generated as above.  I used the following command: 

mothur > make.contigs(file=stability.files, processors=1)

Then, the output was:
“ >>>>>   Processing file pair FASTQTEST\2017GS1TK_S54_L001_R1_001.FASTQ.GZ - FASTQTEST\2017GS1TK_S54_L001_R2_001.FASTQ.GZ (files 1 of 124)       <<<<<
[WARNING]: reading ¬ expected a name with @ as a leading character, ignoring read.
[WARNING]: reading ∩d>Ö>»µ½╔₧· expected a name with + as a leading character, ignoring.[WARNING]: names do not match. read ¬ for fasta and ∩d>Ö>»µ½╔₧· for quality, ignoring.[WARNING]: Lengths do not match for sequence ¬. Read 47 characters for fasta and 19 characters for quality scores, ignoring read.[ERROR]: finding negative quality scores, do you have the right format selected? http://en.wikipedia.org/wiki/FASTQ_format#Encoding
[WARNING]: reading ¬ expected a name with @ as a leading character, ignoring read.
[WARNING]: missing sequence for, ignoring.[WARNING]: expected a name with + as a leading character, ignoring.[WARNING]: missing quality for , ignoring.Making contigs...

It took 0 secs to assemble 0 reads. 
It took 11 secs to process 0 sequences. “

So, can anyone please help me out in this matter. 

Thank you,

**Comment by mothur-westcott** [comment]
Unfortunately, the Windows version does not support *.gz files.  Can you decompress the *.gz files and manually edit the stability.files file?

**Comment by SantoshThapa1** [comment]
Thank you for your response. You mean, decompress the *.gz files (I guess my R1 and R2 files?) and manually edit my stability.fies file to fastq? I am little bit confused so can you please clarify it.

**Comment by mothur-westcott** [comment]
Sorry for the confusion.  Yes, decompress the R1 and R2 files, and remove the .gz from the filenames in the stability.files file.

**Comment by SantoshThapa1** [comment]
Thank you Sarah for your quick clarification. Highly appreciated.
