### ISSUE TITLE
Demultiplex reads with multiple primers and barcodes

### ISSUE THREAD

**Issue by koopkaup** [mothur/mothur#427]
We have combined archaea and bacteria in the same library. We used the same barcodes for both libraries but 16S primers were of course different. Is it possible to include both primer pairs in the oligos file and then could mothur use them in combination with barcodes to determine the samples?

For example if my oligos file is like:
primer forwardBacteriaPrimerString reverseBacteriaPrimerString bacteria
primer forwardArchaeaPrimerString reverseArchaeaPrimerString archaea
barcode....

**Comment by koopkaup** [comment]
Mothur (version 1.40.3) gives an error "barcode pair XXXX XXXX is in your oligos file already, disregarding." 
And in the filename.trim.fasta I could see that some sequences have (multipleMatches) in the header line and no archaea samples were found.

**Comment by mothur-westcott** [comment]
Could you post your oligos file?

**Comment by koopkaup** [comment]
This is the oligos file https://drive.google.com/file/d/1wnGk8qOBWciQBkYHHJB8M67ysVs7sueh/view?usp=sharing
Last 4 archaea samples share barcodes with bacterial samples.
One other thing that I noticed is that some sequences (with multipleMatches) end up in the first sample in the oligos file that do not belong to that sample. I manually checked for the barcodes in those sequences and discovered other barcode combinations. Is there a bug in the trim.seqs command?

**Comment by mothur-westcott** [comment]
I'd like to investigate further.  Could you post the following?

1. A sample of the fasta file that includes the "multiple match" sequences you are referring to.
2. The mothur logfile
3. Any other data needed to reproduce the issue.

Thanks, Sarah

**Comment by koopkaup** [comment]
As the raw data file is very big I didn't upload it, but it can be seen in the sample file that most of the forward barcodes are present in the beginning of some sequences.
https://owncloud.ut.ee/owncloud/index.php/s/ohw88jPzrmwYqOk

**Comment by mothur-westcott** [comment]
Could you use the list.seqs and get.seqs commands to extract the original sequences from the untrimmed fasta file?

mothur > list.seqs(fasta=N9.subset.fasta)
mothur > get.seqs(fasta=assembled.fasta, accnos=current)

**Comment by koopkaup** [comment]
I added assembled.pick.fasta file.

**Comment by mothur-westcott** [comment]
Sorry for the delay, I've been out of the office. Yes, I have fixed the issue and a release will be coming out in the next day or two.  Thank you for helping us fix this!
