### ISSUE TITLE
make.contigs num.temp error

### ISSUE THREAD

**Issue by asmlr** [mothur/mothur#428]
I’m a beginner with a (probably) dumb question.  About halfway through the make.contigs command, I run into an error that looks like this:

[ERROR]: Could not open 113256.num.temp
[ERROR]: Could not open 113253.num.temp
[ERROR]: Could not open 113254.num.temp
[ERROR]: Could not open 113250.num.temp
[ERROR]: Could not open 113255.num.temp
[ERROR]: Could not open 113250.num.temp
[ERROR]: Could not open 113253.num.temp

Followed immediately by thousands of these:
[ERROR]:  is in your fasta file more than once. Sequence names must be unique. please correct.
[ERROR]:  is in your fasta file more than once. Sequence names must be unique. please correct.
[ERROR]:  is in your fasta file more than once. Sequence names must be unique. please correct.

The program is working perfectly beforehand, but afterward, every instance of “Processing file pair” goes wonky.  As do commands downstream.  Does anyone have an idea what the problem could be?

(For reference, I’m using the newest version of mothur (v 1.39.5), and am working on a server from my Mac.  I’ve tried both mac and linux versions, but both lead to the same result.)  Thanks!

**Comment by mothur-westcott** [comment]
Could you post the logfile?

**Comment by asmlr** [comment]
[logfile.txt](https://github.com/mothur/mothur/files/1782321/logfile.txt)

**Comment by mothur-westcott** [comment]
This should be resolved in version 1.40.0
