### ISSUE TITLE
Seq.error bug report

### ISSUE THREAD

**Issue by mothur-westcott** [mothur/mothur#43]
reference Joe's email 1/22

**Comment by mothur-westcott** [comment]
mothur > seq.error(fasta=Placenta.analysis.trim.contigs.good.unique.good.filter.unique.precluster.pick.pick.pick.fasta, reference=HMP_MOCK.v35.fasta, aligned=F)


Using 1 processors.
It took 0 to read 32 sequences.
mothur(4699,0x7fff7b1f8310) malloc: *** error for object 0x7f9d13d050d8: incorrect checksum for freed object - object was probably modified after being freed.
*** set a breakpoint in malloc_error_break to debug
Abort trap: 6

**Comment by mothur-westcott** [comment]
Does not occur everytime the command is run.  Does not fail in the same place.  Using the debugger, Xcode flags the fastaFilePos vector pushback as the cause in m->divideFile.  This seems unlikely to be the source since we use that function for almost all paralellized commands.  The inconsistency also leads me to believe there is something else going on.

**Comment by mothur-westcott** [comment]
Still only occasionally occurs. If run works, next command seems to fail regardless of the command.  Unable to figure out what is causing it.

**Comment by pschloss** [comment]
I actually see this with the MiSeq SOP. If I restart mothur and run the command everything is fine.

**Comment by mothur-westcott** [comment]
Fixed in #280
