### ISSUE TITLE
Can I computationally subtract reads from 'blank extraction control' using mothur?

### ISSUE THREAD

**Issue by SantoshThapa1** [mothur/mothur#430]
Hello there,
I did 16SV4 paired-end Illumina MiSeq sequencing of my samples and processed with mothur,  to compare their bacterial profiles. I also have a 'blank extraction control'  that yielded  about 5,000 reads (QC filtered), while my lowest library size is about 40,000 reads, majority of them around 100,000 reads So,  I wanted to computationally subtract the 'blank extraction control'  reads from each of my samples. Is it possible using mothur? If so, can anyone please suggest me in detail  how to proceed? 
Thanks for your help in advance.

**Comment by mothur-westcott** [comment]
You can use the remove.groups command, https://www.mothur.org/wiki/Remove.groups.

mothur > remove.groups(fasta=yourFastaFile, count=yourCountFile, groups=yourControlGroupName)

**Comment by SantoshThapa1** [comment]
Thank you Sarah>

**Comment by mothur-westcott** [comment]
You can use the screen.seqs command to remove blank reads with the numbases parameter.

mothur > screen.seqs(fasta=16S.final.fasta, count=16S.final.count_table, minlength=10) - remove seqs with less than 10 bp.

Recluster and recreate shared and cons taxonomy files.

**Comment by m-bakker** [comment]
It sounds like you want to subtract observations (i.e., counts per OTU) in the negative control samples from each of your biological samples. I expect you'd have to do this post-Mothur processing; for instance, using R for further manipulation of the taxon abundance table after you're done in Mothur.

**Comment by SantoshThapa1** [comment]
Thank you m-bakker for your suggestions. Yes, you got my point. Will give a shot with R. But, I wonder if I can get back the mothur-compatible files from R after doing all these subtractions.  I want these files to do diversity analyses in the corrected biological samples.

**Comment by SantoshThapa1** [comment]
Thank you Sarah for  your suggestions.

**Comment by m-bakker** [comment]
Yes, it is possible to put these tables back into Mothur compatible format... but it would be easier to stay in R and calculate the diversity indices there - for instance, using the package 'vegan'.
