### ISSUE TITLE
Can I remove of OTU reads less than certain number during Clustering stage

### ISSUE THREAD

**Issue by achoubc** [mothur/mothur#431]
This is not an issue per se but a question-
When I cluster my OTUs, is there a parameter where I can command the OTU reads below say '250'reads to be removed? 

Thanks!

**Comment by mothur-westcott** [comment]
You can use the screen.seqs command, https://www.mothur.org/wiki/Screen.seqs, to remove unwanted sequences.

mothur > screen.seqs(fasta=yourFastaFile, ....others files or options..... minlength=250)

**Comment by mothur-westcott** [comment]
You may also be interested in our New User Links, https://github.com/mothur/mothur/issues/216

**Comment by achoubc** [comment]
I meant to say removing OTUs that are less abundant, since I'm not getting any saturation in my rarefaction curves - for instance - remove OTUs that contain less than 200 sequences. Hopefully that makes sense.

**Comment by mothur-westcott** [comment]
You can use the remove.rare or filter.shared commands to do that, but we don't recommend it.

**Comment by achoubc** [comment]
Thanks it worked fine with remove.rare. 
I keep getting 'segmentation (core dump)' with filter.shared commands - this is also happening with 'sub.sample'.. I tried with 'set.dir(debug=T)' as well but still encountering the same problem. 

mothur --version:
Linux 64Bit Version
Mothur version=1.39.5
Release Date=3/20/2017

*** Error in `/usr/local/bin/mothur1.39.5/./mothur': free(): invalid next size (normal): 0x0000000002896080 ***
======= Backtrace: =========
/lib/x86_64-linux-gnu/libc.so.6(+0x777e5)[0x7f7258bd67e5]
/lib/x86_64-linux-gnu/libc.so.6(+0x8037a)[0x7f7258bdf37a]
/lib/x86_64-linux-gnu/libc.so.6(cfree+0x4c)[0x7f7258be353c]
/usr/local/bin/mothur1.39.5/./mothur[0x1159d43]
/usr/local/bin/mothur1.39.5/./mothur[0x11986ec]
/usr/local/bin/mothur1.39.5/./mothur[0x508f3e]
/usr/local/bin/mothur1.39.5/./mothur[0xfea3b8]
/usr/local/bin/mothur1.39.5/./mothur[0xff6a07]
/usr/local/bin/mothur1.39.5/./mothur[0x1006180]
/usr/local/bin/mothur1.39.5/./mothur[0x44f479]
/usr/local/bin/mothur1.39.5/./mothur[0x409b69]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf0)[0x7f7258b7f830]
/usr/local/bin/mothur1.39.5/./mothur[0x40f4f1]
======= Memory map: ========
00400000-01446000 r-xp 00000000 08:21 19529749                           /usr/local/bin/mothur1.39.5/mothur
01645000-01648000 rw-p 01045000 08:21 19529749                           /usr/local/bin/mothur1.39.5/mothur
01648000-0164a000 rw-p 00000000 00:00 0
027a9000-028f3000 rw-p 00000000 00:00 0                                  [heap]
7f7254000000-7f7254021000 rw-p 00000000 00:00 0
7f7254021000-7f7258000000 ---p 00000000 00:00 0
7f725865e000-7f7258936000 r--p 00000000 08:21 11535754                   /usr/lib/locale/locale-archive
7f7258936000-7f725895b000 r-xp 00000000 08:21 21238265                   /lib/x86_64-linux-gnu/libtinfo.so.5.9
7f725895b000-7f7258b5a000 ---p 00025000 08:21 21238265                   /lib/x86_64-linux-gnu/libtinfo.so.5.9
7f7258b5a000-7f7258b5e000 r--p 00024000 08:21 21238265                   /lib/x86_64-linux-gnu/libtinfo.so.5.9
7f7258b5e000-7f7258b5f000 rw-p 00028000 08:21 21238265                   /lib/x86_64-linux-gnu/libtinfo.so.5.9
7f7258b5f000-7f7258d1f000 r-xp 00000000 08:21 21234209                   /lib/x86_64-linux-gnu/libc-2.23.so
7f7258d1f000-7f7258f1f000 ---p 001c0000 08:21 21234209                   /lib/x86_64-linux-gnu/libc-2.23.so
7f7258f1f000-7f7258f23000 r--p 001c0000 08:21 21234209                   /lib/x86_64-linux-gnu/libc-2.23.so
7f7258f23000-7f7258f25000 rw-p 001c4000 08:21 21234209                   /lib/x86_64-linux-gnu/libc-2.23.so
7f7258f25000-7f7258f29000 rw-p 00000000 00:00 0
7f7258f29000-7f7258f3f000 r-xp 00000000 08:21 21238131                   /lib/x86_64-linux-gnu/libgcc_s.so.1
7f7258f3f000-7f725913e000 ---p 00016000 08:21 21238131                   /lib/x86_64-linux-gnu/libgcc_s.so.1
7f725913e000-7f725913f000 rw-p 00015000 08:21 21238131                   /lib/x86_64-linux-gnu/libgcc_s.so.1
7f725913f000-7f7259247000 r-xp 00000000 08:21 21234205                   /lib/x86_64-linux-gnu/libm-2.23.so
7f7259247000-7f7259446000 ---p 00108000 08:21 21234205                   /lib/x86_64-linux-gnu/libm-2.23.so
7f7259446000-7f7259447000 r--p 00107000 08:21 21234205                   /lib/x86_64-linux-gnu/libm-2.23.so
7f7259447000-7f7259448000 rw-p 00108000 08:21 21234205                   /lib/x86_64-linux-gnu/libm-2.23.so
7f7259448000-7f72595ba000 r-xp 00000000 08:21 11534810                   /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.21
7f72595ba000-7f72597ba000 ---p 00172000 08:21 11534810                   /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.21
7f72597ba000-7f72597c4000 r--p 00172000 08:21 11534810                   /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.21
7f72597c4000-7f72597c6000 rw-p 0017c000 08:21 11534810                   /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.21
7f72597c6000-7f72597ca000 rw-p 00000000 00:00 0
7f72597ca000-7f7259807000 r-xp 00000000 08:21 21238244                   /lib/x86_64-linux-gnu/libreadline.so.6.3
7f7259807000-7f7259a07000 ---p 0003d000 08:21 21238244                   /lib/x86_64-linux-gnu/libreadline.so.6.3
7f7259a07000-7f7259a09000 r--p 0003d000 08:21 21238244                   /lib/x86_64-linux-gnu/libreadline.so.6.3
7f7259a09000-7f7259a0f000 rw-p 0003f000 08:21 21238244                   /lib/x86_64-linux-gnu/libreadline.so.6.3
7f7259a0f000-7f7259a10000 rw-p 00000000 00:00 0
7f7259a10000-7f7259a36000 r-xp 00000000 08:21 21234207                   /lib/x86_64-linux-gnu/ld-2.23.so
7f7259c12000-7f7259c19000 rw-p 00000000 00:00 0
7f7259c2d000-7f7259c2e000 rw-p 00000000 00:00 0
7f7259c2e000-7f7259c35000 r--s 00000000 08:21 11808217                   /usr/lib/x86_64-linux-gnu/gconv/gconv-modules.cache
7f7259c35000-7f7259c36000 r--p 00025000 08:21 21234207                   /lib/x86_64-linux-gnu/ld-2.23.so
7f7259c36000-7f7259c37000 rw-p 00026000 08:21 21234207                   /lib/x86_64-linux-gnu/ld-2.23.so
7f7259c37000-7f7259c38000 rw-p 00000000 00:00 0
7ffdafa86000-7ffdafaa7000 rw-p 00000000 00:00 0                          [stack]
7ffdafae7000-7ffdafae9000 r--p 00000000 00:00 0                          [vvar]
7ffdafae9000-7ffdafaeb000 r-xp 00000000 00:00 0                          [vdso]
ffffffffff600000-ffffffffff601000 r-xp 00000000 00:00 0                  [vsyscall]
Aborted (core dumped)

**Comment by mothur-westcott** [comment]
This issue is resolved in version 1.40.0 coming out on Friday.
