### ISSUE TITLE
Problem to create make.contig from make.file

### ISSUE THREAD

**Issue by nikunjx** [mothur/mothur#433]
Hi, I am trying to create a make.contigs file from the generate make.file. To create the make.file, I used this command : make.file(inputdir=C:\Users\nikun\syn,type=fastq,prefix=stability)

Output file = C_\USERS\NIKUN\DESKTOP\SYN\EG-ET-1-A_S151_L001_R1_001.TRIM.CONTIGS.FASTQ
C_\USERS\NIKUN\DESKTOP\SYN\EG-ET-1-B_S163_L001_R1_001.TRIM.CONTIGS.FASTQ
C_\USERS\NIKUN\DESKTOP\SYN\EG-ET-2-A_S128_L001_R1_001.TRIM.CONTIGS.FASTQ
C_\USERS\NIKUN\DESKTOP\SYN\EG-ET-2-B_S140_L001_R1_001.TRIM.CONTIGS.FASTQ
C_\USERS\NIKUN\DESKTOP\SYN\EG-FR-1-A_S104_L001_R1_001.TRIM.CONTIGS.FASTQ
C_\USERS\NIKUN\DESKTOP\SYN\EG-FR-1-B_S116_L001_R1_001.TRIM.CONTIGS.FASTQ
C_\USERS\NIKUN\DESKTOP\SYN\EG-FR-2-A_S176_L001_R1_001.TRIM.CONTIGS.FASTQ
C_\USERS\NIKUN\DESKTOP\SYN\EG-FR-2-B_S188_L001_R1_001.TRIM.CONTIGS.FASTQ
C_\USERS\NIKUN\DESKTOP\SYN\EG-RL-1-A_S175_L001_R1_001.TRIM.CONTIGS.FASTQ
C_\USERS\NIKUN\DESKTOP\SYN\EG-RL-1-B_S187_L001_R1_001.TRIM.CONTIGS.FASTQ
C_\USERS\NIKUN\DESKTOP\SYN\EG-RL-2-A_S152_L001_R1_001.TRIM.CONTIGS.FASTQ
C_\USERS\NIKUN\DESKTOP\SYN\EG-RL-2-B_S164_L001_R1_001.TRIM.CONTIGS.FASTQ
C_\USERS\NIKUN\DESKTOP\SYN\HF-ET-1-A_S105_L001_R1_001.TRIM.CONTIGS.FASTQ
C_\USERS\NIKUN\DESKTOP\SYN\HF-ET-1-B_S117_L001_R1_001.TRIM.CONTIGS.FASTQ
C_\USERS\NIKUN\DESKTOP\SYN\HF-ET-2-A_S177_L001_R1_001.TRIM.CONTIGS.FASTQ
C_\USERS\NIKUN\DESKTOP\SYN\HF-ET-2-B_S189_L001_R1_001.TRIM.CONTIGS.FASTQ
C_\USERS\NIKUN\DESKTOP\SYN\HF-FR-1-A_S153_L001_R1_001.TRIM.CONTIGS.FASTQ
C_\USERS\NIKUN\DESKTOP\SYN\HF-FR-1-B_S165_L001_R1_001.TRIM.CONTIGS.FASTQ
C_\USERS\NIKUN\DESKTOP\SYN\HF-FR-2-A_S130_L001_R1_001.TRIM.CONTIGS.FASTQ
C_\USERS\NIKUN\DESKTOP\SYN\HF-FR-2-B_S142_L001_R1_001.TRIM.CONTIGS.FASTQ
C_\USERS\NIKUN\DESKTOP\SYN\HF-RL-1-A_S129_L001_R1_001.TRIM.CONTIGS.FASTQ
C_\USERS\NIKUN\DESKTOP\SYN\HF-RL-1-B_S141_L001_R1_001.TRIM.CONTIGS.FASTQ
C_\USERS\NIKUN\DESKTOP\SYN\HF-RL-2-A_S106_L001_R1_001.TRIM.CONTIGS.FASTQ
C_\USERS\NIKUN\DESKTOP\SYN\HF-RL-2-B_S118_L001_R1_001.TRIM.CONTIGS.FASTQ
C_\USERS\NIKUN\DESKTOP\SYN\MS-ET-1-A_S146_L001_R1_001.TRIM.CONTIGS.FASTQ
C_\USERS\NIKUN\DESKTOP\SYN\MS-ET-1-B_S158_L001_R1_001.TRIM.CONTIGS.FASTQ
C_\USERS\NIKUN\DESKTOP\SYN\MS-ET-2-A_S123_L001_R1_001.TRIM.CONTIGS.FASTQ
C_\USERS\NIKUN\DESKTOP\SYN\MS-ET-2-B_S135_L001_R1_001.TRIM.CONTIGS.FASTQ
C_\USERS\NIKUN\DESKTOP\SYN\MS-FR-1-A_S99_L001_R1_001.TRIM.CONTIGS.FASTQ
C_\USERS\NIKUN\DESKTOP\SYN\MS-FR-1-B_S111_L001_R1_001.TRIM.CONTIGS.FASTQ
C_\USERS\NIKUN\DESKTOP\SYN\MS-FR-2-A_S171_L001_R1_001.TRIM.CONTIGS.FASTQ
C_\USERS\NIKUN\DESKTOP\SYN\MS-FR-2-B_S183_L001_R1_001.TRIM.CONTIGS.FASTQ
C_\USERS\NIKUN\DESKTOP\SYN\MS-RL-1-A_S170_L001_R1_001.TRIM.CONTIGS.FASTQ
C_\USERS\NIKUN\DESKTOP\SYN\MS-RL-1-B_S182_L001_R1_001.TRIM.CONTIGS.FASTQ
C_\USERS\NIKUN\DESKTOP\SYN\MS-RL-2-A_S147_L001_R1_001.TRIM.CONTIGS.FASTQ
C_\USERS\NIKUN\DESKTOP\SYN\MS-RL-2-B_S159_L001_R1_001.TRIM.CONTIGS.FASTQ
C_\USERS\NIKUN\DESKTOP\SYN\OF-ET-1-A_S97_L001_R1_001.TRIM.CONTIGS.FASTQ
C_\USERS\NIKUN\DESKTOP\SYN\OF-ET-1-B_S109_L001_R1_001.TRIM.CONTIGS.FASTQ
C_\USERS\NIKUN\DESKTOP\SYN\OF-ET-2-A_S169_L001_R1_001.TRIM.CONTIGS.FASTQ
C_\USERS\NIKUN\DESKTOP\SYN\OF-ET-2-B_S181_L001_R1_001.TRIM.CONTIGS.FASTQ
C_\USERS\NIKUN\DESKTOP\SYN\OF-FR-1-A_S145_L001_R1_001.TRIM.CONTIGS.FASTQ
C_\USERS\NIKUN\DESKTOP\SYN\OF-FR-1-B_S157_L001_R1_001.TRIM.CONTIGS.FASTQ
C_\USERS\NIKUN\DESKTOP\SYN\OF-FR-2-A_S122_L001_R1_001.TRIM.CONTIGS.FASTQ
C_\USERS\NIKUN\DESKTOP\SYN\OF-FR-2-B_S134_L001_R1_001.TRIM.CONTIGS.FASTQ
C_\USERS\NIKUN\DESKTOP\SYN\OF-RL-1-A_S121_L001_R1_001.TRIM.CONTIGS.FASTQ
C_\USERS\NIKUN\DESKTOP\SYN\OF-RL-1-B_S133_L001_R1_001.TRIM.CONTIGS.FASTQ
C_\USERS\NIKUN\DESKTOP\SYN\OF-RL-2-A_S98_L001_R1_001.TRIM.CONTIGS.FASTQ
C_\USERS\NIKUN\DESKTOP\SYN\OF-RL-2-B_S110_L001_R1_001.TRIM.CONTIGS.FASTQ

After this I used make.contigs command- make.contigs(file=stability.files, processors=1, checkorient=t)
But I am receiving an error message stating - Unable to open C:\Users\nikun\Desktop\syn\. Trying default C:\Users\nikun\Desktop\syn\
Unable to open C:\Users\nikun\Desktop\syn\. Trying mothur's executable directory C:\Users\nikun\Desktop\syn\
[WARNING]: can't find C:\Users\nikun\Desktop\syn\, ignoring pair.
Unable to open C:\Users\nikun\Desktop\syn\. Trying default C:\Users\nikun\Desktop\syn\
Unable to open C:\Users\nikun\Desktop\syn\. Trying mothur's executable directory C:\Users\nikun\Desktop\syn\
[WARNING]: can't find C:\Users\nikun\Desktop\syn\, ignoring pair.
It took 0 secs to process 0 sequences.

**Comment by mothur-westcott** [comment]
Thanks for reporting this issue.  It has been fixed in version 1.40, releasing later this week.  If you want to use the fix now, you can download and build the master branch.
