### ISSUE TITLE
PCA command

### ISSUE THREAD

**Issue by nikunjx** [mothur/mothur#435]
Hi, 

I am trying to launch PCA command but it is not executing. The command I am using is :- 

> pca(shared=barcodes.final.pick.opti_mcc.0.05.subsample.braycurtis.0.05.lt.dist, label=0.05)

Your file does not include the label
0.05. I will use the next smallest distance.

Processing 4
Too many iterations in qtli

It has been stucked here for 1 hour.. 

Nikunj

**Comment by mothur-westcott** [comment]
pca(**shared**=barcodes.final.pick.opti_mcc.0.05.subsample.braycurtis.0.05.**lt.dist**, label=0.05)

I think you are providing a distance matrix for the shared file.  https://mothur.org/wiki/Shared_file  https://mothur.org/wiki/Phylip-formatted_distance_matrix
