### ISSUE TITLE
Latest release (1.40.0) giving error message

### ISSUE THREAD

**Issue by achoubc** [mothur/mothur#436]
When I first start the new release of mothur, I get this [ERROR] message. 
No matter what command I use after that, I keep getting 1 error message and the program crashing.
I am thinking it's got something to do with permission from the previous version...

[ERROR]: Could not open /usr/local/bin/mothur1.40.0/mothur.1523309554.logfile

mothur > make.contigs(file=stability.file.txt, processors=10)

************************************************************
************************************************************
************************************************************
Detected 1 [ERROR] messages, please review.
************************************************************
************************************************************
************************************************************

**Comment by mothur-westcott** [comment]
Thanks for reporting this issue.  Mothur is trying to write the logfile in the location mothur is installed.  I updated the release to change this, https://github.com/mothur/mothur/releases/tag/v1.40.0.1.

**Comment by ajwnewkirk** [comment]
I followed the link to the minor update above, but it still appears to download v1.40.0 (header when running manually says 1.40.0). I am getting a segmentation fault as well with log files written to mothur's executable directory.

**Comment by achoubc** [comment]
@ajwnewkirk Did you install it anyways and try it? if you look at installation folder, some are updated and the page is tagged. 

I am just curious if it's still buggy because I haven't been able to test myself since my working server is down at the moment.

**Comment by ajwnewkirk** [comment]
@achoubc I ran the most recent version on the website, which was tagged as 1.40.0.1 in the left hand bar but called 1.40.0 on the main header. The program crashed during the make.contigs step after running for a few minutes, and the log file was written to the mothur directory rather than the tempdefault location. I'm guessing that the zip wasn't successfully updated after Sarah made the change.

**Comment by charliep** [comment]
> On Apr 16, 2018, at 10:26, Sarah Westcott <notifications@github.com> wrote:
> 
> By default the logfile is written to the current working directory. 

That is not what we are seeing, the default is where the binary is located.

charlie

**Comment by mothur-westcott** [comment]
Could you try this version, https://github.com/mothur/mothur/releases/tag/v1.40.1?

**Comment by charliep** [comment]
That code (built from source under Centos with gcc 5.2.0 and Boost) opens the logfile in the current working directory. The version string in the startup banner still shows 1.40.0 

Thanks for the quick fix, that saves us from updating a bunch of scripts.

charlie

**Comment by mothur-westcott** [comment]
Great! Thanks for your help in finding this issue!

**Comment by ajwnewkirk** [comment]
Running 1.40.1 on Centos, I'm still getting a segmentation fault during make.contigs when running in script mode.

**Comment by mothur-westcott** [comment]
Are you running make.contigs with compressed (*.gz) files? Could you post your logfile?
