### ISSUE TITLE
merge.files Error

### ISSUE THREAD

**Issue by elizabethmcd** [mothur/mothur#438]
The newest version of mothur v.1.40.0 throws an error when calling `merge.files`. I've only tried merging fasta files, but I tried version v.1.39.5 and it works fine. For my purposes I manually concatenated the fasta files I needed for downstream analyses. The error is:
```
[ERROR]: did not complete merge.files.
```

**Comment by mothur-westcott** [comment]
Can you try downloading this, https://github.com/mothur/mothur/releases/tag/v1.40.0.1

**Comment by elizabethmcd** [comment]
I downloaded the 64-bit version, and still get the same error.

**Comment by mothur-westcott** [comment]
Could you post your logfile?

**Comment by elizabethmcd** [comment]
[mothur-logfile-error.txt](https://github.com/mothur/mothur/files/1916284/mothur-logfile-error.txt)

It still says version 1.40.0.0 but I downloaded the recent version v1.40.0.1 of the 64-bit linux version and still got the same error.

**Comment by mothur-westcott** [comment]
Could you send your input files to mothur.bugs@gmail.com?

**Comment by stahlse** [comment]
We are also experiencing this problem with merging files with the new version of mothur

**Comment by mothur-westcott** [comment]
Have you tried providing the full path name for the input files?

**Comment by mothur-westcott** [comment]
Can you try our latest release, https://github.com/mothur/mothur/releases/tag/v1.40.3?
