### ISSUE TITLE
cluster.split error in v.1.40.0

### ISSUE THREAD

**Issue by elizabethmcd** [mothur/mothur#439]
When I ran the `cluster.split` command, I got the following error: 

```
Cutoff was 0.15 changed cutoff to 0.05
It took 3 seconds to cluster
Merging the clustered files...
[ERROR]: labelRAM used: 0.412949Gigabytes . Total Ram: 96.0484Gigabytes.

 has occurred in the ClusterSplitCommand class function completeListFile. Please contact Pat Schloss at mothur.bugs@gmail.com, and be sure to include the mothur.logFile with your inquiry.
```

I am using the 64Bit linux version of mothur. I ran this on my personal Mac computer which has v.1.39.5 and this command worked fine. I've attached the logfile associated with this run. 

[cluster.split-error.txt](https://github.com/mothur/mothur/files/1900482/cluster.split-error.txt)

**Comment by pschloss** [comment]
This is because you are using method=average. The default as of 1.39 was method=opti, which doesn't change the cutoff like you're seeing here. The explanation is at https://mothur.org/wiki/Frequently_asked_questions#Why_does_the_cutoff_change_when_I_cluster_with_average_neighbor.3F
