### ISSUE TITLE
"your sequences are not the same length, aborting" when I use Cluster.split()

### ISSUE THREAD

**Issue by juanjuanignacio** [mothur/mothur#440]
First, I align and clean the data in pararell then i merge all on a fasta and  I create a count.table but when I use cluster.split, this error appears:

your sequences are not the same length, aborting. And obviously the .list isnot complet

Thats the command:

cluster.split(fasta=input/joined_fasta.unique.fasta, count=input/joined_fasta.count_table, taxonomy=input/joined_fasta.unique.seed_v123.wang.taxonomy, splitmethod=fasta, taxlevel=4, cutoff=0.15, processors=16)

If i do it with a .file with all the samples at first i dont have this error but I want to parallelize the alignment clean and filter.  If you could help me please :D

**Comment by juanjuanignacio** [comment]
Oh, thanks!

I have other question, Is there any way to get a distance matrix or a tree between OTUS? because the tree.shared command gives distances between SAMPLES. Thank you.

**Comment by mothur-westcott** [comment]
You can get a representative sequence using the get.oturep command, https://www.mothur.org/wiki/Get.oturep.
