### ISSUE TITLE
get.coremicrobiome keep crashing in version 40

### ISSUE THREAD

**Issue by amirshams84** [mothur/mothur#445]
./EXECDIR/Linux/mothur/mothur "#get.coremicrobiome(shared=./RESULT/temp.job2.shared, abundance=1)

*** Error in `./EXECDIR/Linux/mothur/mothur': double free or corruption (!prev): 0x0000000002826370 ***
======= Backtrace: =========
/lib64/libc.so.6(+0x7c619)[0x7f32739d7619]
./EXECDIR/Linux/mothur/mothur[0x879d2a]
./EXECDIR/Linux/mothur/mothur[0x87ba94]
./EXECDIR/Linux/mothur/mothur[0x5837cb]
./EXECDIR/Linux/mothur/mothur[0x40a659]
/lib64/libc.so.6(__libc_start_main+0xf5)[0x7f327397cc05]
./EXECDIR/Linux/mothur/mothur[0x411e65]
======= Memory map: ========
00400000-0134e000 r-xp 00000000 00:4d 300572                             /BIOMSLICER/EXECDIR/Linux/mothur/mothur
0154e000-01550000 r--p 00f4e000 00:4d 300572                             /BIOMSLICER/EXECDIR/Linux/mothur/mothur
01550000-01551000 rw-p 00f50000 00:4d 300572                             /mothur
01551000-01556000 rw-p 00000000 00:00 0 
0280e000-02850000 rw-p 00000000 00:00 0                                  [heap]
7f326c000000-7f326c021000 rw-p 00000000 00:00 0 
7f326c021000-7f3270000000 ---p 00000000 00:00 0 
7f3273731000-7f3273756000 r-xp 00000000 08:01 2230893                    /usr/lib64/libtinfo.so.5.9
7f3273756000-7f3273956000 ---p 00025000 08:01 2230893                    /usr/lib64/libtinfo.so.5.9
7f3273956000-7f327395a000 r--p 00025000 08:01 2230893                    /usr/lib64/libtinfo.so.5.9
7f327395a000-7f327395b000 rw-p 00029000 08:01 2230893                    /usr/lib64/libtinfo.so.5.9
7f327395b000-7f3273b13000 r-xp 00000000 08:01 2230651                    /usr/lib64/libc-2.17.so
7f3273b13000-7f3273d13000 ---p 001b8000 08:01 2230651                    /usr/lib64/libc-2.17.so
7f3273d13000-7f3273d17000 r--p 001b8000 08:01 2230651                    /usr/lib64/libc-2.17.so
7f3273d17000-7f3273d19000 rw-p 001bc000 08:01 2230651                    /usr/lib64/libc-2.17.so
7f3273d19000-7f3273d1e000 rw-p 00000000 00:00 0 
7f3273d1e000-7f3273d35000 r-xp 00000000 08:01 2230834                    /usr/lib64/libpthread-2.17.so
7f3273d35000-7f3273f34000 ---p 00017000 08:01 2230834                    /usr/lib64/libpthread-2.17.so
7f3273f34000-7f3273f35000 r--p 00016000 08:01 2230834                    /usr/lib64/libpthread-2.17.so
7f3273f35000-7f3273f36000 rw-p 00017000 08:01 2230834                    /usr/lib64/libpthread-2.17.so
7f3273f36000-7f3273f3a000 rw-p 00000000 00:00 0 
7f3273f3a000-7f3273f4f000 r-xp 00000000 08:01 2759926                    /usr/lib64/libgcc_s-4.8.5-20150702.so.1
7f3273f4f000-7f327414e000 ---p 00015000 08:01 2759926                    /usr/lib64/libgcc_s-4.8.5-20150702.so.1
7f327414e000-7f327414f000 r--p 00014000 08:01 2759926                    /usr/lib64/libgcc_s-4.8.5-20150702.so.1
7f327414f000-7f3274150000 rw-p 00015000 08:01 2759926                    /usr/lib64/libgcc_s-4.8.5-20150702.so.1
7f3274150000-7f3274251000 r-xp 00000000 08:01 2230757                    /usr/lib64/libm-2.17.so
7f3274251000-7f3274450000 ---p 00101000 08:01 2230757                    /usr/lib64/libm-2.17.so
7f3274450000-7f3274451000 r--p 00100000 08:01 2230757                    /usr/lib64/libm-2.17.so
7f3274451000-7f3274452000 rw-p 00101000 08:01 2230757                    /usr/lib64/libm-2.17.so
7f3274452000-7f327453b000 r-xp 00000000 08:01 2759932                    /usr/lib64/libstdc++.so.6.0.19
7f327453b000-7f327473b000 ---p 000e9000 08:01 2759932                    /usr/lib64/libstdc++.so.6.0.19
7f327473b000-7f3274743000 r--p 000e9000 08:01 2759932                    /usr/lib64/libstdc++.so.6.0.19
7f3274743000-7f3274745000 rw-p 000f1000 08:01 2759932                    /usr/lib64/libstdc++.so.6.0.19
7f3274745000-7f327475a000 rw-p 00000000 00:00 0 
7f327475a000-7f3274796000 r-xp 00000000 08:01 2230842                    /usr/lib64/libreadline.so.6.2
7f3274796000-7f3274996000 ---p 0003c000 08:01 2230842                    /usr/lib64/libreadline.so.6.2
7f3274996000-7f3274998000 r--p 0003c000 08:01 2230842                    /usr/lib64/libreadline.so.6.2
7f3274998000-7f327499e000 rw-p 0003e000 08:01 2230842                    /usr/lib64/libreadline.so.6.2
7f327499e000-7f32749a0000 rw-p 00000000 00:00 0 
7f32749a0000-7f32749c1000 r-xp 00000000 08:01 2230627                    /usr/lib64/ld-2.17.so
7f3274bb6000-7f3274bbc000 rw-p 00000000 00:00 0 
7f3274bbe000-7f3274bc1000 rw-p 00000000 00:00 0 
7f3274bc1000-7f3274bc2000 r--p 00021000 08:01 2230627                    /usr/lib64/ld-2.17.so
7f3274bc2000-7f3274bc3000 rw-p 00022000 08:01 2230627                    /usr/lib64/ld-2.17.so
7f3274bc3000-7f3274bc4000 rw-p 00000000 00:00 0 
7ffe396c3000-7ffe396e4000 rw-p 00000000 00:00 0                          [stack]
7ffe39735000-7ffe39737000 r--p 00000000 00:00 0                          [vvar]
7ffe39737000-7ffe39739000 r-xp 00000000 00:00 0                          [vdso]
ffffffffff600000-ffffffffff601000 r-xp 00000000 00:00 0                  [vsyscall]
Aborted

**Comment by mothur-westcott** [comment]
Could you post your logfile and shared file?

**Comment by amirshams84** [comment]
./EXECDIR/Linux/mothur40/mothur '#set.dir(output=./RESULT/); set.logfile(name=mothur.get_coremicrobiome.logfile); set.current(processors=2); get.coremicrobiome(shared=./RESULT/taxonomy_core_microbiome_analysis_shared.txt, abundance=1);'
[taxonomy_core_microbiome_analysis_shared.txt](https://github.com/mothur/mothur/files/1943754/taxonomy_core_microbiome_analysis_shared.txt)

[mothur.get_coremicrobiome.txt](https://github.com/mothur/mothur/files/1943759/mothur.get_coremicrobiome.txt)

**Comment by mothur-westcott** [comment]
Thanks for reporting this bug.  I am tracking it down now.  In the meantime, you can use this workaround.

mothur > get.relabund(shared=yourSharedFile)
mothur > get.coremicrobiome(relabund=current, abundance=1)

**Comment by amirshams84** [comment]
I Started heavily investigate Mothur and going to report any Issues, I hope you are not going to mute me ;)

**Comment by mothur-westcott** [comment]
Can you try our latest version, https://github.com/mothur/mothur/releases/tag/v1.40.3?
