### ISSUE TITLE
How to create a design file ?

### ISSUE THREAD

**Issue by SantoshThapa1** [mothur/mothur#448]
Hi there,
Can anyone please suggest me how to create a design file (indicating which treatment each sample belongs to)? Is it possible to create .design file through Excel?
Thanks,

**Comment by mothur-westcott** [comment]
You can create the file in any text editor or excel.  Just be sure if you are using excel that you save as a tab delimited text file.

**Comment by SantoshThapa1** [comment]
Thank You, Sarah!

**Comment by yichao0126** [comment]
Does .txt file work, or I have to convert into .design file? When I use .txt file, there is an error coming below:mothur > anosim(phylip=Mock.an.jclass.0.03.lt.ave.dist, design=Mock.design)

Unable to open Mock.design. Trying default /share/apps/mothur/mothur-1.39.5-serial/Mock.design
Unable to open /share/apps/mothur/mothur-1.39.5-serial/Mock.design. Trying mothur's location /share/apps/mothur/mothur-1.39.5-serial/Mock.design
Unable to open /share/apps/mothur/mothur-1.39.5-serial/Mock.design
[ERROR]: did not complete anosim.

**Comment by mothur-westcott** [comment]
The *.design is not necessary, mothur does not care what the filename is. I think your issue may be a hidden extension. Could the design file be named Mock.design.txt?? Here are other reasons mothur may be unable to find your file, https://mothur.org/wiki/Frequently_asked_questions#Mothur_can.27t_find_my_input_files.
