### ISSUE TITLE
make.contig

### ISSUE THREAD

**Issue by nikunjx** [mothur/mothur#450]
I am trying to test some files with different fasta and reverse files. 

make.file(inputdir=D:\synaqua\Example_contig_demultiplexing_Mothur, type=fastq, prefix=stability)
make.contigs(file=stability.files, processors=4, checkorient=t)
screen.seqs(fasta=stability.trim.contigs.fasta, qfile=stability.trim.contigs.qual, contigsreport=stability.contigs.report, maxambig=0, minlength=250, maxlength=360, minoverlap=140)
trim.seqs(fasta=stability.trim.contigs.good.fasta, qfile=stability.trim.contigs.good.qual, qwindowaverage=23, qwindowsize=25, oligos=oligos.oligos, checkorient=t, bdiffs=1, pdiffs=1, processors=2, keepforward=true, maxambig=0, maxhomop=8, minlength=250)

I used the following commands but after using the trim.seqs, I am obtaining the empty stability.trim.contigs.good.trim file.

**Comment by mothur-westcott** [comment]
Could you post your logfile and input files, or samples of the input files if they are too large to upload?

**Comment by NazishAijaz** [comment]
can someone please tell me that after running any command how can we open that file

**Comment by mothur-westcott** [comment]
You can open mothur's log files in the text editor of your choice.
