### ISSUE TITLE
Set.dir ERROR

### ISSUE THREAD

**Issue by amirshams84** [mothur/mothur#452]
set.dir(outputdir=/dbfs/FileStore/16S_RESULT/, inputdir=/dbfs/FileStore/16S_RESULT/);
mothur > set.dir(outputdir=/dbfs/FileStore/16S_RESULT/, inputdir=/dbfs/FileStore/16S_RESULT/)
Setting output directory to: /dbfs/FileStore/16S_RESULT/
Setting input directory to: /dbfs/FileStore/16S_RESULT/
[ERROR]: You must provide either an input, output, tempdefault, blastdir, debug or modifynames for the set.dir command.
[ERROR]: did not complete set.dir.

**Comment by pschloss** [comment]
Can you use input/output instead of inputdir/outputdir?

**Comment by amirshams84** [comment]
Yes, Thanks
