### ISSUE TITLE
make.biom for Picrust

### ISSUE THREAD

**Issue by toneta2013** [mothur/mothur#453]
I've ru  into trouble when making biom-file for Picrust. This is the error message I get:

[ERROR]: could not find OTUId for unknown(100);unknown_unclassified(100);unknown_unclassified(100);unknown_u                      nclassified(100);unknown_unclassified(100);unknown_unclassified(100);. Its reference sequences are unknown .
I have read previous posts here with a similar problem, However this seems to have been fixed by installing a  newer version of mothur. I have used the newest available version (1.40.3). I have checked my constaxonomy file and can't find this unknown in there. What can cause this problem and more importantly, what can I do!

**Comment by mothur-westcott** [comment]
Could you post the input files and logfile so I can track it down for you?
