### ISSUE TITLE
'cluster' command of version 1.40.3 seems to generate an abnormal 'list' file

### ISSUE THREAD

**Issue by ilnamkang** [mothur/mothur#454]
Hi,

I've been running Mothur version 1.40.3 in Ubuntu 14.04.

It seems that 'cluster' command of version 1.40.3 generates an abnormal 'list' file.

When I ran 'cluster' and 'make.shared' as below, I got an essentially empty *.shared file.
mothur> cluster(column=sample.dist, name=sample.names, method=average, cutoff=0.20)
mothur> make.shared(list=sample.an.list, group=sample.groups, label=0.02)

So, I checked the list file. The first two columns of the list file were like below, which was different from the format of list file I remember. (column header line appeared for every cutoff level.)
label	numOtus
unique	20800
label	numOtus
0.01	9172
label	numOtus
0.02	5508
label	numOtus
0.03	3922
label	numOtus
0.04	3094
...

When I ran the same commands with the same input files using version 1.39.5, I got the usual *.list and and *.shared files without any problem. The first two columns of the list file were like below.
label	numOtus
unique	20798
0.01	9169
0.02	5515
0.03	3914
0.04	3095
...

Did I do something wrong for version 1.40.3? Or, is this a bug?

Thanks.

**Comment by mothur-westcott** [comment]
Thanks for reporting this bug! I have fixed the issue and a release will be coming out in the next day or two.

**Comment by mothur-westcott** [comment]
Can you give our latest version a try, https://github.com/mothur/mothur/releases/tag/v1.40.4?

**Comment by ilnamkang** [comment]
Version 1.40.4 works nicely without any problem!

Thanks for your help.
