### ISSUE TITLE
OTU tree problems

### ISSUE THREAD

**Issue by juanjuanignacio** [mothur/mothur#455]
Hello,
 I am using mothur for metagenomic analysis and everything is fine, until my last step that is to get an OTU tree. I already have a biom, a consensus of the taxonomy, with the command otu.rep as you told me I got the fasta of the otus (500mb), which is a msa. But, now, im trying to do a tree. I have tried all the ways that have occurred to me. I have tried to make a distance matrix (phylip) of this fasta but the matrix has 200gb since it does not support the cutoff command.
Using clearcut, the process lasts forever since it seems that my fasta is too big. I need some help or some suggestion on how I could do this. Thank you.

**Comment by juanjuanignacio** [comment]
I've realized that i have aprox 200.000 OTUS. What is too much, cause i supose that i must have over 20.000. There are a method to reduce or filter the less representative OTUS?

**Comment by mothur-westcott** [comment]
http://blog.mothur.org/2014/09/11/Why-such-a-large-distance-matrix/

Did you have good overlap of your reads?

Did you follow Pat's suggestions for removing chimeras and contaminants, and preprocessing your reads in the SOP, https://www.mothur.org/wiki/MiSeq_SOP?
