### ISSUE TITLE
Error when clustering with vsearch

### ISSUE THREAD

**Issue by koopkaup** [mothur/mothur#456]
I get this error when I try to use vsearch for OTU clustering. I am using mothur version 1.40.3

mothur > cluster(fasta=grace.final.fasta, count=grace.final.count_table, method=dgc, processors=16)
[ERROR]: You must provide a distance file unless you are using the agc, dgc or unique clustering methods, aborting

**Comment by mothur-westcott** [comment]
Thanks for reporting this! A patch release will be out in the next day or two to fix it.
