### ISSUE TITLE
chimera.vsearch fatal error

### ISSUE THREAD

**Issue by adrianlopgar** [mothur/mothur#458]
I'm trying to use chimera.vsearch in a remote server where I have no installing permissions. I requested the managers to install it. I am trying to use it with this code, but it outputs a fatal error:
```
module load intel/2018.2.199 impi/2018.2.199 mothur/1.40.2 vsearch/2.8.0

mothur chimera.vsearch(fasta=$PATH/0.15.01610.001_R1_paired.trim.contigs.good.unique.filter.unique.precluster.fasta, reference=$PATH_2/silva.gold.align, dereplicate=t, processors=12)

---------------------------------------

Using 12 processors.
/opt/cesga/easybuild-cesga/software/MPI/intel/2018.2.199/impi/2018.2.199/mothur/1.40.2/bin/vsearch file does not exist. Checking path...
Found vsearch in your path, using /opt/cesga/easybuild-cesga/software/Compiler/intel/2018.2.199/vsearch/2.8.0/bin/vsearch

Checking sequences from [PATH]/0.15.01610.001_R1_paired.trim.contigs.good.unique.filter.unique.precluster.fasta ...
vsearch v2.8.0_linux_x86_64, 125.8GB RAM, 24 cores
https://github.com/torognes/vsearch

Reading file [PATH_2]/silva.gold.align 0%

Fatal error: illegal character '.' on line 2 in FASTA file

It took 61 secs to check your sequences. 0 chimeras were found.

Output File Names:
[PATH]/0.15.01610.001_R1_paired.trim.contigs.good.unique.ref.vsearch.chimeras
[PATH]/0.15.01610.001_R1_paired.trim.contigs.good.unique.ref.vsearch.accnos
```
Is something wrong with the installation or am I doing something wrong with the code?
Thanks a lot!

**Comment by mothur-westcott** [comment]
Mothur is unable to find the vsearch program.  The chimera.vsearch command is a wrapper for the vsearch program, https://github.com/torognes/vsearch.  Vsearch is a 64bit, parallelized, open source program modeled after usearch.  Mothur requires the vsearch executable to run the vsearch command. It is distributed with the prebuilt executables of mothur.  You want the vsearch executable to be in the same location as the mothur executable or in your path.
