### ISSUE TITLE
Mismatch between clustered OTUs and classification

### ISSUE THREAD

**Issue by montedeletras** [mothur/mothur#459]
I ran into an unexpected mismatch and, if possible, I would like to understand what happened. I clustered my OTUs with an external software and obtained a simplified fasta (in terms of number of entries), where after each header there is a _count field. I then used this fasta to classify.seqs with mothur against Silva and got categories (classification) plus OTU counts. But when I confronted those numbers they do not match! I supposed that mothur would classify each fasta entry and add its total (_count after header) to that entry classification and therefore I would be able to tell which fasta was classified as each category. Is there an explanation about this mismatch? Thanks in advance!

**Comment by montedeletras** [comment]
Sure. Its like this, except in fasta (I suppose there is a line limit here). I'm looking for the log file since it's been done for a while.... I'll post it later.

>76174a683083992555e9e60cd383ba2f71b654e4_45549
cctacgggtggctgcagtggggaatcttagacaatgggcgcaagcctgatctagccatgccgcgtgagtgatgaaggccttagggtcgtaaagctctttcgcctgtgaagataatgactgtagcaggtaaagaaaccccggctaactccgtgccagcagccgcggtaatacggagggggttagcgttgttcggaattactgggcgtaaagcgcgcgtaggcggacatttaagtcaggggtgaaatcccggggctcaaccccggaactgcccttgatactgggtgtcttgagttcgagagaggtgagtggaattccgagtgtagaggtgaaattcgtagatattcggaggaacaccagtggcgaaggcggctcactggctcgatactgacgctgaggtgcgaaagtgtggggagcaaacaggattagataccctagtagtc
>97e38bc241b302864e9f9e0fa9e1289dd6aff2c6_17817
cctacgggtggctgcagtgaggaatattgcacaatggacgcaagtctgatgcagcgacgccgcgtgggcgatgaaggttttcggatcgtaaagcccttttctgcgtgacgaggaaggacggtagcgcaggaaaaagtctcggctaactacgtgccagcagccgcggtaaaacgtaggaggcaagcgttatccggagttactgggcgtaaagcgcgtgcaggcgggatggtaagttagccatgaaagctcctggctaaactgggagaggatggttgaaactgccaaccttgagtggagcagaggaacacggaattccgggtgtagtggtgaaatgcgtagatatccggaggaacaccagtggcgaaggcggtgttctgggctccaactgacgctgagacgcgaaagcgtgggtagcgaacgggattagataccctagtagtc
>c8b3872fe6aae1d8c4246ded759898f5d9102e69_3312
cctacggggggcagcagtaaggaatattgggcaatggaggcaactctgacccagccatcccgcgtgcaggatgactgccctatgggttgtaaactgcttttacaagggaagaaacaggtttatttataagcctctgacggtaccttgggaataagcaccggctaactccgtgccagcagccgcggtaatacggagggtgcaagcgttatccggaatcactgggtttaaagggtgcgtaggcggcttagtaagtcagaagtgaaagcccgtcgctcaacgatggaattgcttttgatactgctgagcttgaattgagttgaggctggcggaatgtggcatgtagcggtgaaatgcatagatatgccatagaacaccaattgcgaaggcagctggctgggctttgattgacgctgaggcacgaaagcgtggggagcgaacaggattagataccctagtagtc

**Comment by montedeletras** [comment]
Hmmm... looking at the totals, I suppose mothur did not include the (_count) number into the analysis... Is there a way to do so?

**Comment by mothur-westcott** [comment]
You'd have to write a custom script to grab the count off the end of the sequence name and generate a count file, https://www.mothur.org/wiki/Count_File.

**Comment by montedeletras** [comment]
I was just figuring this out. Should I tab space the number or should I use another format? Thanks for the attention!

**Comment by mothur-westcott** [comment]
The count file is a tab separated text file, that includes a header.  The header should be:

Representative_sequence<tab>total<tab>optional tab separated group names<endLine>

**Comment by montedeletras** [comment]
Great! Thanks!
