### ISSUE TITLE
dist.seqs data loss

### ISSUE THREAD

**Issue by p-hofmann** [mothur/mothur#46]
I used version 1.34.0, not MPI enabled

Using dist.seqs with more than one processor seems to cause data loss, because results in temporary files of child processes are not getting appended to the final result file.

It appears to me that the error is in the "DistanceCommand::createProcesses" method.
The suspected cause seems to be, that the parent process stores the wrong ids, its own not the children's id.
Since the children's ID is part of the temporary filename, the parent process can not find the files.

Note: The MPI enabled version will not have this problem!

**Comment by mothur-westcott** [comment]
Thanks for reporting this issue.  It will be fixed in the 1.35.0 release. If you would like the fix early you can download the distance.cpp file from the v.1.35.0 branch and build from source.

**Comment by p-hofmann** [comment]
I will, thank you very much.
