### ISSUE TITLE
screen.seqs does not write count_table

### ISSUE THREAD

**Issue by metajinomics** [mothur/mothur#469]
screen.seqs command does not make count_table which it suppose to.

## This is the output file names in version 1.40.4
Output File Names: 
stability.trim.contigs.good.unique.good.summary
stability.trim.contigs.good.unique.good.align
stability.trim.contigs.good.unique.bad.accnos

## Following is expected output file name
/******************************************/
Running command: remove.seqs(accnos=stability.trim.contigs.good.unique.bad.accnos, count=stability.trim.contigs.good.count_table)
Removed 506 sequences from your count file.
Output File Names: 
stability.trim.contigs.good.pick.count_table
/******************************************/
Output File Names: 
stability.trim.contigs.good.unique.bad.accnos
stability.trim.contigs.good.unique.good.summary
stability.trim.contigs.good.unique.good.align
stability.trim.contigs.good.good.count_table

**Comment by mothur-westcott** [comment]
Thanks for your help in finding and resolving this issue!
