### ISSUE TITLE
Classify.seqs and DATABASE problem

### ISSUE THREAD

**Issue by VladimirAv** [mothur/mothur#474]
Hello, this is my first post and i'll try to make it really simple. PD. thank you in advance for any response and thank you all for the effort you put everyday on mothur and on these sites to help us.

I'm having problems with classify.seqs command. Before telling you about that, i was wondering if is it possible to create my own database? i mean, what would happen if i download all the fastas of a certain taxa from NCBI (eukaryote organisms) and then align them together? i would have the .align file right? and with the ID's names i can get my .tax file too right?. 

The problem i'm having is that at the moment of classifying with that command, i only get the messsage

> Sequence XXXX could not be classified. You can use the remove.lineage command with taxon=unknown; to remove such sequences

for all my sequences, so at the end when i check my .taxonomy file, i just get "unknown" taxa. Any suggestion what i might be doing wrong? I even was wondering if mothur was only for 16S rRNA gene or prokaryote in general, that's how desperate i am right now.

PD. To do the database, i just compared the format of the silva database (dots, taxa between ;, alignment) and did it by hand. The alignment was done with MAFFT algorithm on UGENE.

Thank you! any answer would be so helpful.

**Comment by Shellfishgene** [comment]
The database fasta file for classify.seqs does not have to be aligned. The one that comes with mothur is just for the 16S gene, but you can use other genes or loci to make your own database.
Make sure you just have 16S sequences that you try to classify, mothur is not for metagenomic classification if that's what you mean by "prokaryotes in general".

**Comment by VladimirAv** [comment]
That's weird. Mothur once sent me the message "Your database needs to be aligned in order to align your target sequences" or something like that when using the command **align.seqs**  and also, if you see the 16s database from silva, the sequences are also aligned. So that's why i downloaded sequences as fasta and then aligned them together.

**Comment by Shellfishgene** [comment]
Of course you need an aligned database for ```align.seqs```, but not if you want to classify you sequences only using ```classify.seqs```. If you only want to classify with you own database it's easier to not align it. If you want to cluster OTUs you need an alignment.

**Comment by mothur-westcott** [comment]
The classify.seqs command does not require an aligned reference.  This is because it uses k-mers to find the probabilities of the taxonomic assignment.
