### ISSUE TITLE
get.lineage broken?

### ISSUE THREAD

**Issue by Shellfishgene** [mothur/mothur#477]
Hi, I'm just tyring to extract sequenes of one lineage only, for example like this:

```get.lineage(fasta=final.fasta, count=final.count, taxonomy=final.taxonomy, taxon=Bacteria;Proteobacteria;)```

However the result is always an empty ```pick.taxonomy``` file and a ```pick.fasta``` file with only one sequence in it which does not even have the required taxonomy. I've tried different datasets and definely have many sequences of the taxon in my sets, but the result is always the same.
This is in versions v.1.40.3 and  v.1.40.4.

**Comment by mothur-westcott** [comment]
Thank you for reporting this issue.  I will release version 1.40.5 later today with the fix.

**Comment by mothur-westcott** [comment]
Can you try our latest version, https://github.com/mothur/mothur/releases/tag/v1.40.5?

**Comment by Shellfishgene** [comment]
This fixes it, thanks! Just out of interest, is there no automated testing for all the commands in for a new build?
