### ISSUE TITLE
pcr.seqs fails to remove seqs from count file or make accnos, but scrap contains seqs

### ISSUE THREAD

**Issue by Shellfishgene** [mothur/mothur#479]
Hi, I'm having a problem with ```pcr.seqs``` (in ver ```1.40.5```).
It gives the message ```[NOTE]: no sequences were bad, removing ...```, however there are still a few sequences that go into the scrap file that ```pcr.seqs``` produces. It does not generate a new count file. If I try the same count file that I ran ```pcr.seqs``` with in a subsequent ```summary.seqs```, it complains about a mismatch in the count file and fasta file of exactly the number of seqs that is in the ```pcr.seqs``` scrap file.
I tried ```1.40.3``` but it has similar issues (can't find it's accnos file) and segfaults.

Workaround would be to manually ```remove.seqs``` with an accnos file made from the scrap file I guess.

**Comment by mothur-westcott** [comment]
Could you post the pcr.seqs command you ran so I can try to reproduce the error?

**Comment by mothur-westcott** [comment]
Thank you for reporting this issue. I have fixed it and the change will be part of our next release.
