### ISSUE TITLE
make.contigs too few entries in groups file

### ISSUE THREAD

**Issue by Shellfishgene** [mothur/mothur#480]
Hi! I just tried to run ```make.contigs``` with a large dataset, but the groups file it produced always had a few thousand entries missing in comparison to the fasta file, so ```count.seqs``` throws errors. ```make.contigs``` itself finished without errors. I tried it three times with version 1.40.5 (using gzipped files) with the same result. Using version 1.40.4 (unzipping the fastqs first) it works as expected, with the same command.
Sorry I can't provide a test case, the dataset is very large and I'd have to figure out which reads cause this first.

**Comment by krmaas** [comment]
I was having the same issue when using my batch file, but when I ran through the commands interactively I didn't have that problem. The only difference in the commands issued was when interactive, I didn't set processors. Sarah, I posted in the forum and emailed mothurbugs about this issue but then went on vacation and forgot to follow up.

**Comment by mothur-westcott** [comment]
@krmaas Could you send me 2 of the *.gz file pairs that contain missing reads so I can try to reproduce the error? Also, are you seeing the issue if you decompress the *gz files and run them as fastq instead?

**Comment by krmaas** [comment]
@mothur-westcott I thought I'd unzipped but apparently didn't, so got this error using zipped files and 1.40.5. I'm rerunning make.contigs with .gz and 1.39.5. The end of the make.contigs lists the number of sequences in the group file, but is off by ~150k in the fasta
[HHM01BS1_S158_L001_R1_001.fastq.gz](https://github.com/mothur/mothur/files/2242542/HHM01BS1_S158_L001_R1_001.fastq.gz)
[HHM01BS1_S158_L001_R2_001.fastq.gz](https://github.com/mothur/mothur/files/2242545/HHM01BS1_S158_L001_R2_001.fastq.gz)


[mothur.1532729886make.contigs.zip](https://github.com/mothur/mothur/files/2242520/mothur.1532729886make.contigs.zip)

**Comment by krmaas** [comment]
make.contigs with 1.39.5 worked-same number of seqs in fasta and groups. It also was substantially faster than 1.40.5. I didn't change the fastq.gz or the stability.file between these runs.
1.40.5   It took 22863 secs to process 7124236 sequences.
1.39.5   It took 6316 secs to process 7195200 sequences.

**Comment by mothur-westcott** [comment]
Thanks for the extra information. I will take a closer look.

**Comment by mothur-westcott** [comment]
Thanks for reporting this bug. The fix will be released in version 1.41.0. You can download and build from source now using the https://github.com/mothur/mothur/tree/1.41.0 branch.
