### ISSUE TITLE
data set including already paired reads 

### ISSUE THREAD

**Issue by odcker** [mothur/mothur#482]
Hi,
I sequenced my samples using MiSeq and I received the .fastq reads in an already paired version. Since I only have one fastq read for each sample, I can't find a way in mothur to start the pipeline SOP with already paired reads because it is trying to pair my reads, however they belong to different samples. Is there a way I can start the workflow without pairing the reads, because they are already paired? I tried to skip the make.contigs command, but of course it didn't work. 
Any help will be appreciated!

**Comment by mothur-westcott** [comment]
You can use the fastq.info command to extract the fasta reads from the fastq files, https://www.mothur.org/wiki/Fastq.info.  Then you can create a group file with the make.group command, https://www.mothur.org/wiki/Make.group. 

mothur > fastq.info(fastq=sample1.fastq, fasta=t, qfile=f) - create fasta file for sample1
mothur > fastq.info(fastq=sample2.fastq, fasta=t, qfile=f) - create fasta file for sample2
...
mothur > fastq.info(fastq=sampleN.fastq, fasta=t, qfile=f) - create fasta file for sampleN

mothur > make.group(fasta=sample1.fasta-sample2.fasta...sampleN.fasta, groups=sample1-sample2...sampleN) - assign groups to fasta files reads.
mothur > merge.files(input=sample1.fasta-sample2.fasta...sampleN.fasta, output=merged.fasta) - merge individual samples fasta files into one fasta file.

This will result in a fasta and group file you can use to follow the SOP after the make.contigs command.
