### ISSUE TITLE
seq.error gets confused with 18S in the reference db

### ISSUE THREAD

**Issue by Shellfishgene** [mothur/mothur#483]
Hi! Not sure if this is a bug or an artefact of the method:
I have 16S data and also mock community samples. I have used the "ZymoBIOMICS" mock community standard which also includes some 18S from yeast (and Cryptococcus). If I keep the 18S sequences in the mock community reference fasta file almost all my 16S reads get assigned to yeast 18S, with zero errors. This is obviously not correct, there is no 18S sequence in my data. If I remove the 18S from the reference all works as expected.

**Comment by pschloss** [comment]
Hmmm, haven't seen that. Could you email the inputs to seq.error to us?
