### ISSUE TITLE
No groups in screen.seqs

### ISSUE THREAD

**Issue by mvcarlosdominguez** [mothur/mothur#487]
@mothur-westcott  , I'm working with Galaxy and the "screen.seqs" doesn't have the version 1.40.5 and a im having the same problem.

Could you help me?

Thanks

**Comment by pschloss** [comment]
You're going to have to work with the galaxy folks on how to get the latest version of mothur installed. Unfortunately, we aren't very familiar with that platform or what it takes to get things installed.

**Comment by mothur-westcott** [comment]
You can use the *bad.accnos file to remove the bad reads from the group or count file manually. To do so insert a remove.seqs command after each screen.seqs command.

mothur > remove.seqs(accnos=current, count=current)

or

mothur > remove.seqs(accnos=current, group=current)

Sorry for the inconvenience.
