### ISSUE TITLE
 pre.cluster issue

### ISSUE THREAD

**Issue by frbed88** [mothur/mothur#488]
Hello,
I've made a batch and I had issues after the following command : `pre.cluster(fasta=stability.trim.contigs.good.unique.good.filter.unique.fasta, count=stability.trim.contigs.good.unique.good.filter.count_table, diffs=4)`

Followed by : 
`chimera.uchime(fasta=stability.trim.contigs.good.unique.good.filter.unique.precluster.fasta, count=stability.trim.contigs.good.unique.good.filter.unique.precluster.count_table, dereplicate=t, processors=32)`

My error is : 
Unable to open stability.trim.contigs.good.unique.good.filter.unique.precluster.fasta
Unable to open stability.trim.contigs.good.unique.good.filter.unique.precluster.count_table

So I bet the version 1.40.5 is not making the .precluster files. I've also tried the version 1.40.3 and same issue. Am I doing something wrong or mothur really have problems to create files just as 1.40.4? Which version should I try then?

Thanks
Francois

**Comment by mothur-westcott** [comment]
I am not seeing that issue. Did the pre.cluster command fail due to memory constraints? Could you post the logfile?

**Comment by frbed88** [comment]
Thanks for answer. Here are the log and batch file.
[batchfile.txt](https://github.com/mothur/mothur/files/2176127/batchfile.txt)
[log.txt](https://github.com/mothur/mothur/files/2176128/log.txt)

**Comment by mothur-westcott** [comment]
From your logfile, it looks like the pre.cluster command is finishing.  I think the issue is the uchime program. Uchime is 32bit, meaning it can use at most 4G of RAM which can cause memory issues with larger datasets. Have you tried the chimera.vsearch command? Vsearch is an open source 64 bit version of Uchime, https://www.mothur.org/wiki/Chimera.vsearch.

**Comment by frbed88** [comment]
It looks like it is working now. Thank you very much!

`mothur > chimera.vsearch(fasta=stability.trim.contigs.good.unique.good.filter.unique.precluster.fasta, count=stability.trim.contigs.good.unique.good.filter.unique.precluster.count_table, dereplicate=t, processors=32)
Unable to open stability.trim.contigs.good.unique.good.filter.unique.precluster.fasta. Trying input directory /home/frbed88/Illumina/batch/stability.trim.contigs.good.unique.good.filter.unique.precluster.fasta.
Unable to open stability.trim.contigs.good.unique.good.filter.unique.precluster.count_table. Trying input directory /home/frbed88/Illumina/batch/stability.trim.contigs.good.unique.good.filter.unique.precluster.count_table.

Using 32 processors.
Checking sequences from /home/frbed88/Illumina/batch/stability.trim.contigs.good.unique.good.filter.unique.precluster.fasta ...

It took 30 secs to check 8667 sequences from group FB_A10_S194.

It took 28 secs to check 8215 sequences from group FB_A11_S201.

It took 45 secs to check 13208 sequences from group FB_A1_S122.
`

**Comment by Leomir16** [comment]
Hello
I have an issue after following the command 
pre.cluster(fasta=stability.trim.contigs.good.unique.good.filter.unique.fasta, count=stability.trim.contigs.good.unique.good.filter.count_table, diffs=2)

My error is :
Unable to open stability.trim.contigs.good.unique.good.filter.unique.precluster.fasta
Unable to open stability.trim.contigs.good.unique.good.filter.unique.precluster.count_table

**Comment by mothur-westcott** [comment]
There are several reasons mothur may not be able to open a file. 

1. Typo in the file name or path.
2. You don’t have permissions to open the file.
3. Mothur can’t find the file.

The most common reason for this issue being, mothur is unable to find a file. You can check to see if this is the problem by providing the full path to the file or by setting the inputdir variable.

mothur > pre.cluster(fasta=stability.trim.contigs.good.unique.good.filter.unique.fasta, count=stability.trim.contigs.good.unique.good.filter.count_table, diffs=2, inputdir=pathToFasta/CountFiles)
