### ISSUE TITLE
How can I find that how many OTUs are assigned to a particular taxa? 

### ISSUE THREAD

**Issue by SantoshThapa1** [mothur/mothur#490]
Hi there,

Sorry for posting a very basic question. 
I am using mothur to process my 16SV4 data. From my output file -"16S.final.an.unique_list.0.03.cons.taxonomy (TAXONOMY file)", I found that which otu is assigned to which bacterial taxa. But, I  don't know the way to find that how many OTUs are assigned to a particular taxa (e.g. the genus A).  Do I have to count them manually? Or, do I have to do further analyses? Can anyone please suggest me. 

Thanks!

**Comment by soonhwee** [comment]
Hello,

There should be a .cons.tax.summary file that comes with the taxonomy file. Open that in Excel, and filter out the taxon you want and you can find the number of OTUs assigned in the 'total' column.

Hope that helps.

**Comment by SantoshThapa1** [comment]
Thank you Soonhwee. will do accordingly.

**Comment by mothur-westcott** [comment]
The basis parameter ,https://www.mothur.org/wiki/Classify.otu#basis, allows you to indicate what you want the summary file to represent, options are otu and sequence. Default is otu.

**Comment by SantoshThapa1** [comment]
Hi Soonhwee, 
Thank you very much for your comments and suggestions. 

Yes, the reasons of my confusion was that I have 5 million in 'total' column. My data was analyzed using older version of mothur 1.36.1 (do you think that could be a part of the problem?). 

I'm in a hurry, to be honest.  As I'm interested only in a couple of taxa, will search the taxonomy file using the filter for the taxon as you suggested. 

Thank you once again.
 Cheers

**Comment by SantoshThapa1** [comment]
Thank you Sarah for your feedback and the link. Your help is appreciated as always.

**Comment by soonhwee** [comment]
Hi,

I have no idea what could be causing the problem, just guesses. As I did not see that with the latest version, you can try running classify,otu with it to find out. 

And you are using the parameters shown in the SOP, right?
`classify.otu(list=current, count=current, taxonomy=current, label=0.03)`

Cheers.

**Comment by SantoshThapa1** [comment]
Hi Soonhwee,
I am following Dr. Schloss's  MiSeq SOP with the exact parameters that you have noted. As you suggested, i'll try with the latest version of mothur. Thank you so much for your time and suggestions.
Cheers.

**Comment by SantoshThapa1** [comment]
Finally, I was able to get the number of OTUs assigned for a taxon under the 'total' at the 'Root' taxon in the cons.tax.summary file. Thank you very much to Sarah and Soonhwee for your suggestions. 
Cheers !

**Comment by SantoshThapa1** [comment]
Hi there, 
I'm back again for an associated issue. 
Like I mentioned above, I was able to get the total number of OTUs assigned to a taxon from the cons.tax.summary file. My data looks like this:

taxon | daughterlevels | total | sample1 | sample2|  -- | -- | -- | -- | --sample90|
Root    | 1 |                     | 2142 |   |84 |           |77 |    -- | -- | -- | --|--  sample90|

When I added the rows of OTUs of all 90 samples, it is way higher  than the number in the 'total' column (I got 9414 OTUs, to be exact).  I guess  9,414 OTUs are both the shared and unique OTUs, right?  So, how can I get the number of unique OTUs in each of my samples?  Can anyone please suggest me. 

Thank you.

**Comment by mothur-westcott** [comment]
Yes, the OTU counts for each sample mean the sample was contained in the OTU, but not necessarily the only sample contained in the OTU. If you want to find the OTUs unique to a sample or set of samples you want the get.sharedseqs command, https://mothur.org/wiki/Get.sharedseqs#uniquegroups_.26_sharedgroups.  You can use get.sharedseqs to list the sequences in OTUs unique or shared by a set of samples.  Then use get.seqs to select these sequences from the input files to classify.otu and rerun to find the consensus taxonomies of the OTUs unique to a given sample or set of samples. Does that make sense?

**Comment by soonhwee** [comment]
I don't have a direct method to do that too. The way I came up is using countif function and Filter in Excel again on the shared file, not the summary file.

1. Transpose the Group and Otu columns onto a new tab, so the samples become the header.
2. If you are looking for unique OTU in each sample, then the number of samples containing 0 abundance for that OTU should be n-1. Use countif function to count the number of zero for each OTU.
3.  Select the number (n-1), 89 in your case, with Filter in the countif column to get the unique OTUs present in all samples. 
4. (optional) Copy the output from step 3 to another tab.
5. Use countif again to count the number of non-zero for each sample to get the number of unique OTUs in each sample.

You can try if you don't mind the rather crude method. I managed to get the OTU numbers in less than 10 mins. But do check if the numbers are correct!

Hope it helps.

**Comment by SantoshThapa1** [comment]
Thank you Sarah for your prompt response. Yes, it makes sense.

**Comment by SantoshThapa1** [comment]
Hi Soonhwee,
I need your help  to address the following questions:
Step 1:  I transposed my data accordingly. 
Step 2: You are suggesting to use criteria as "0" in the countif function to count the number of zero for each OTU, right?  I did =countif(B3;CM3, "0"), guess this is right? 
Step 3:  I selected n-1 number , 89 in my case, with Filter in the countif column. Isn't it right that the  number 89 that I selected just represents the OTU having 89 zeros among my 90 samples? How they are Unique for each sample ? Now, I lost some where......, how can i get unique OTU to each sample? 
Please suggest me.
Thank you.

**Comment by soonhwee** [comment]
Yea, step 2 looks right.
Step 3 is to filter out non-unique OTUs, so the OTUs left will be unique to one of the samples. Step 5 will then find how many and which OTUs are unique to each sample. Does that make sense?

**Comment by SantoshThapa1** [comment]
Thank you so much Soonhwee for your explanation. It make a lot of sense. Now, I'm glad to share that I get my unique OTUs for each sample. Thank you once again for your help. 
Cheers.
