### ISSUE TITLE
make.contigs - define the amount minimum overlap

### ISSUE THREAD

**Issue by rtrpaine** [mothur/mothur#491]
Hi all,

I am wondering if there is a way to define the minimum amount of overlap between the forward and reverse read when preforming make.contigs. I have scoured the wiki SOP, but there doesn't appear to be a command for this.

I've been able to do it using the program FLASH, but there isn't a way (that I've found) to transfer this over to mothur for subsequent analysis. FLASH will make your contigs, but there is no group file, which is needed for later commands in mothur.

Cheers,

Robert

**Comment by mothur-westcott** [comment]
You can use the screen.seqs command to remove reads with insufficient overlap.  https://www.mothur.org/wiki/Screen.seqs#minoverlap

mothur > screen.seqs(fasta=yourFastaFile, contigsreport=yourReportFileFromMakeContigs, minoverlap=yourDesiredMinimumOverlap)

**Comment by rtrpaine** [comment]
Hi Sarah,

This worked perfectly. Thanks!
