### ISSUE TITLE
mothur "unable to open" files in make.contigs

### ISSUE THREAD

**Issue by rlh13** [mothur/mothur#493]
I am running the make.contigs command in Mothur but, while it recognizes all of the sample names from the stability file, it is for some reason unable to open them. They are in fastq format. I am posting the error only for one of the samples since it is the same for all of the sample files in the folder and have replaced the remainder of the file paths with ".." for privacy. What am I doing incorrectly?

make.contigs(file=stability.file, processors=8, inputdir=../cutadapt/, outputdir=../mothur_data/)

Unable to open ../cutadapt/MoNat1. Trying default ../mothur/MoNat1
Unable to open ../mothur/MoNat1. Trying output directory ../mothur_data/MoNat1
Unable to open ../mothur_data/MoNat1. Trying mothur's executable directory ../mothur/MoNat1
[WARNING]: can't find ../mothur/MoNat1, ignoring pair.

**Comment by mothur-westcott** [comment]
Could you post the stability.file?

**Comment by rlh13** [comment]
Here is the stability file. I concatenated the R1 and R2 files before using cutadapt to demultiplex and remove primers. That is why there is only 1 fastq file for each sample. I did this because previously I tried joining paired ends and it resulted in a large drop in quality.

[stability.file.txt](https://github.com/mothur/mothur/files/2198179/stability.file.txt)

**Comment by lmicmar** [comment]
Did you solved the problem? I have the same problem in make.contigs

**Comment by rlh13** [comment]
Still not working. Just waiting for feedback on the stability file I posted.

**Comment by mothur-westcott** [comment]
The stability file is not in the correct format, https://www.mothur.org/wiki/File_File.  Mothur assumes the 2 column format is a forward fastq file followed by a reverse fastq file. Mothur is attempting to open MoNat1 (which appears to be a group name), but can't find the file and so an error is reported.  Are you working with paired reads?

**Comment by rlh13** [comment]
concatenated the R1 and R2 files before using cutadapt to demultiplex and remove primers. That is why there is only 1 fastq file for each sample. I did this because previously I tried joining paired ends and it resulted in a large drop in quality. Is it absolutely necessary to have two files for each sample?

**Comment by mothur-westcott** [comment]
Are trying to assemble reads or create a group file? To create a group file, try this:

mothur > fastq.info(fastq=MoB1.fastq) - create fasta file for sample MoB1
...
mothur > fastq.info(fastq=ZFeSFwM3.fastq) - create fasta file for sample ZFeSFwM3
mothur > make.group(fasta=MoB1.fasta-MoB2.fasta-...-ZFeSFwM3.fasta, groups=MoB1-MoB2-...-ZFeSFwM3) - assign reads in each fasta file to a group

https://www.mothur.org/wiki/Make.group

**Comment by rlh13** [comment]
Hello, ok so I think you're right I need to use the fastq.info() and make.group() commands but I am still having trouble getting the fastq.info() command to run with my fasqFiles.file. The command works on individual fastq files as you demonstrated but when I try to give it the following file (just my stability file renamed), it doesn't work. I'd like to avoid entering each sample by hand so would appreciate if you could tell me what is wrong with the file I'm giving it. Here is my command:
fastq.info(file=fastqFiles.txt, inputdir=~/Riley/2017-03-30_Mock_Spike_In/cutadapt_mothur/, outputdir=~/Riley/2017-03-30_Mock_Spike_In/mothur_data/)
I get the same error as last time (it just says it is unable to open the files)
[fastqFiles.txt](https://github.com/mothur/mothur/files/2211042/fastqFiles.txt)

**Comment by mothur-westcott** [comment]
The file option in the fastq.info command is used the same way as in make.contigs. Unfortunately, you will have to run them one at a time or write a script.

**Comment by rlh13** [comment]
Sorry it took so long to get back to you. I was able to run the fast.info in batch mode to create all of the fasta and qual files. I then ran the make.group command. I'm a little unclear on how to move forward now since fastq.info doesn't output anything like the stability.trim.contigs.fasta file that is used for summary.seqs, screen.seqs, etc. but just gives fasta and qual files for each sample.

**Comment by mothur-westcott** [comment]
You can create a merged fasta file using the merge.files command, https://mothur.org/wiki/Merge.files.

mothur > merge.files(input=yourFastaFileForSample1-yourFastaFileForSample2- yourFastaFileForSample3... yourFastaFileForSampleN, output=merged.fasta)

**Comment by rlh13** [comment]
Got it thank you. Ok, sorry to be asking so many questions, but when I ran screen.seqs on the merged fasta file I got a TON of warnings saying "[WARNING]: M00384_34_000000000-AV783_1_2119_13390_24446 is in your group file more than once.  Mothur requires sequence names to be unique. I will only add it once."  It still gave an output but it said "Removed 425880 sequences from your group file." Is this expected or should I be worried about this?

**Comment by mothur-westcott** [comment]
Does the group file have duplicate names? If so, you can fix this mismatch with the list.seqs and get.seqs commands.

mothur > list.seqs(fasta=merged.fasta)
mothur > get.seqs(group=yourGroupFile, accnos=current)

**Comment by rlh13** [comment]
I guess I'm a little unclear what this is doing. I ran the list.seqs and get.seqs commands and it did the same thing (i.e. gave me a bunch of warnings like the one above). It produced a merge.pick.groups file but I am just worried that it is throwing out a lot of my sequences and I don't fully understand whether this is a result of concatenating the R1 and R2 files in the beginning and how to avoid this?

**Comment by mothur-westcott** [comment]
Are you saying MoB1.fastq contains the forward and reverse reads unassembled? If this is the case mothur is assuming that there are 2 sequences named M00384_34_000000000-AV783_1_2119_13390_24446, not a forward fragment of M00384_34_000000000-AV783_1_2119_13390_24446 and a reverse fragment of M00384_34_000000000-AV783_1_2119_13390_24446. 


" I tried joining paired ends and it resulted in a large drop in quality. Is it absolutely necessary to have two files for each sample?"

What kind of drop in quality? Have you looked at this? https://www.mothur.org/wiki/Make.contigs#Assembled_Quality_Scores

Also, avoid processing only forward or reverse direction reads. Here's why: https://github.com/mothur/mothur/issues/396.
