### ISSUE TITLE
chimera.uchime error

### ISSUE THREAD

**Issue by lmicmar** [mothur/mothur#494]
Hello,

I am trying to run the chimera.uchime file but keep getting this error... 
mothur v.1.35.1
mothur > chimera.uchime(fasta=stability.files.trim.contigs.good.unique.abund.filter.unique.precluster.fasta, count=stability.files.trim.contigs.good.unique.abund.filter.unique.precluster.count_table, processors=8)

Using 8 processors.

uchime by Robert C. Edgar
http://drive5.com/uchime
This code is donated to the public domain.

Checking sequences from stability.files.trim.contigs.good.unique.abund.filter.unique.precluster.fasta ...
Segmentation fault (core dumped)
[ERROR]: Could not open stability.files.trim.contigs.good.unique.abund.filter.unique.precluster.uchime.chimeras21.tempS02_C1143
Segmentation fault (core dumped)
[ERROR]: Could not open stability.files.trim.contigs.good.unique.abund.filter.unique.precluster.uchime.chimeras22.tempS02_C2132
Segmentation fault (core dumped)
[ERROR]: Could not open stability.files.trim.contigs.good.unique.abund.filter.unique.precluster.uchime.chimeras24.tempS02_C2151
Segmentation fault (core dumped)
Segmentation fault (core dumped)
[ERROR]: Could not open stability.files.trim.contigs.good.unique.abund.filter.unique.precluster.uchime.chimeras31.tempS02_C3153
[ERROR]: Could not open stability.files.trim.contigs.good.unique.abund.filter.unique.precluster.uchime.chimeras27.tempS02_C3133
Segmentation fault (core dumped)
[ERROR]: Could not open stability.files.trim.contigs.good.unique.abund.filter.unique.precluster.uchime.chimerasS02_C1131Segmentation fault (core dumped)
[ERROR]: Could not open stability.files.trim.contigs.good.unique.abund.filter.unique.precluster.uchime.chimeras32.tempS02_C4143
Segmentation fault (core dumped)
[ERROR]: Could not open stability.files.trim.contigs.good.unique.abund.filter.unique.precluster.uchime.chimeras36.tempS02_W141

Any idea about mistake?

**Comment by mothur-westcott** [comment]
Are you having the same issue with our current version, 1.40.5? 

Have you tried the chimera.vsearch command?
