### ISSUE TITLE
trim.seqs miss match

### ISSUE THREAD

**Issue by dungtran2612** [mothur/mothur#496]
Hi, 
I tried my old data with the lastest version but had problem about trim.seqs. Sequence name mismatch between fasta and qual file. I didn't have this problem with ver 39. Please help me. Thanks.

**Comment by mothur-westcott** [comment]
Could you try running the sort.seqs command first, https://mothur.org/wiki/Sort.seqs?

mothur > sort.seqs(fasta=yourFastaFile, qfile=yourQualityFile)
mothur > trim.seqs(fasta=current, qfile=current, ... others parameters ...)
