### ISSUE TITLE
make.contigs: trying to open numerical parameters as files

### ISSUE THREAD

**Issue by shiltemann** [mothur/mothur#498]
when running the `make.contigs` command and setting any of the numerical parameters (e.g. match, mismatch, gapopen etc) it seemingly tries to open these parameters as files.

error message:
```
mothur > make.contigs(ffastq=Mock_S280_L001_R1_001_small.fastq,rfastq=Mock_S280_L001_R2_001_small.fastq,match=2)                                                                                                  
Unable to open 2. Trying default /home/saskia/miniconda3/envs/__mothur@1.40.5/bin/2
[..]
```

While the above command without the `match` parameter set completes without problems.

release: 1.40.5 (this command worked on these files in the 1.39.5 release)
input files: [Mock_S280_L001_R1_001_small.fastq](https://github.com/galaxyproject/tools-iuc/blob/master/tools/mothur/test-data/Mock_S280_L001_R1_001_small.fastq), [Mock_S280_L001_R2_001_small.fastq](https://github.com/galaxyproject/tools-iuc/blob/master/tools/mothur/test-data/Mock_S280_L001_R2_001_small.fastq)

I noticed a similar problem in the command `cooccurrence` for the `metric` parameter

**Comment by mothur-westcott** [comment]
Thanks for reporting this issue. I have fixed it and the change will be part of our next release.

**Comment by shiltemann** [comment]
thanks! :+1:
