### ISSUE TITLE
Dist.seqs do no works in multithreading

### ISSUE THREAD

**Issue by frbed88** [mothur/mothur#502]
Hello, I'm using a very large distance matrix and I'm trying to resolve it quickly with many processors on an high performance calculator. Dist.seqs was shutdowning my batch so I've decided to run it in the terminal and with only 2 parallel cpu (12cores) it was saying too many cores for the ram. I've put the option processors=6, and it works. The problem is that after overnight, I'm only to sequence 56,000. Is there a way to be able to run over 96 processors with dist.seqs? 96 processors = 12 nodes = 4core/nodes + at least 16gb ram per node.

**Comment by mothur-westcott** [comment]
The more processors you use the more memory is required. Have you looked at Pat's blog about distance matrix size? http://blog.mothur.org/2014/09/11/Why-such-a-large-distance-matrix/ Also, following the steps in the MiSeq_SOP, https://www.mothur.org/wiki/MiSeq_SOP, may help you improve quality and reduce sequence errors which can result in inflated read counts.
