### ISSUE TITLE
Taxonomic identification

### ISSUE THREAD

**Issue by rtrpaine** [mothur/mothur#503]
Hi all,

using v1.39.5

I have looked through my data that I just generated and notice a odd problem. I have some OTUs that are ranked to the genus level (classify.seqs cutoff=99).

I have BLASTed a few of the sequences that compose these OTUs and they match 99% or higher to the correct taxa. However, mothur is saying that she can only match them to the genus level. 

I have tried classify.seqs with a cutoff=97, but I still see the same problem. Would increasing the ksize parameter increase the level of taxonomic assignment specificity? I've been using the default (=8).

Cheers,

Robert

**Comment by rtrpaine** [comment]
I tried increasing the kmer size for the wang method (i.e., classify.seqs, ksize=12). What is the limit on the ksize parameter?

I tried setting ksize to 28, but I think mothur crashed. Not sure if this was an issue with the coding itself or if mothur needed power to conduct the command.

**Comment by pschloss** [comment]
I think you’re misunderstanding what classify.seqs does. By default it classifies according to the naive Bayesian approach of Wang. I’d encourage you to look up and read the reference. This is a consensus classification that gives more accurate classifications than blast, which is generally awful. The cutoff in the command corresponds to the confidence of the classification, not the similarity. You should stick with the default of 80% and stick with the default knee size.

You will never get species level classification if you are using the RDP or Silva references. They only go to the genus level. Even the greengenes database only has 10% or so of sequences with species level names (greengenes hasn’t been updated in quite a few years). I and many others would contend that using 16S and especially a fragment to get a species name is asking too much - you need a culture and genome sequencing to do that. 

I’d also add that the choice of region, length, database, and type of bacteria can all impact what depth classification you’ll get. You should not decrease the confidence score to try to get deeper classifications. You’ll get deeper classifications, but they’re more likely to be wrong.

**Comment by rtrpaine** [comment]
Hi Dr. Schloss,

I should probably have mentioned that I'm sequencing a hypervariable region of the 12S region (mitochondrial) in freshwater fishes. I've mentioned this before in an other comment. The nice thing about my systems and community is that I know all the species that can potentially occur there (~150).

Additionally, I have curated my own database, and my region of interests allows for species specific identification, in most groups anyway.

I see now that I did misunderstand classify.seqs. With that said, increasing the number of iterations then should putatively give you a more robust/confident classification during this step correct? Understandingly this will increase computational power and time needed to analyze the data set.

Additionally, I still think that increasing the ksize parameter would theoretically increase your classification confidence right? You're more likely to match shorter words in a sequence (e.g.,, 6 bp) than you are longer words (e.g., 12 bp).

Thanks for your input. I think I have at least figured out a new pipeline to test out.

Cheers,

Robert

**Comment by pschloss** [comment]
Thanks for the clarification.

* Adding iterations will give the confidence score greater precision. So if you do 1000 or 10000 you will perhaps trust the 1's or tenth's place a bit more than if you only did the default of 100 iterations. Doing 1000 or 10000 iterations will, of course, be 10 and 100 times slower than the default.
* Increasing the ksize may have diminishing returns. You can increase the ksize, but this will suck up more an more RAM and may make the kmers too specific. To test this, you would need to do a leave one out testing procedure. You would take one reference sequence and classify it against all of the other reference sequences for your desired ksize. You would repeat this for all of the other sequences in the reference testing them one at a time for each kmer size. The kmer size that gives the best classification would be the size to use. This was how the defaults for 16S were decided upon.
* You could also use the leave one out procedure to see whether you can really classify to the species level with your region/gene and database composition.
