### ISSUE TITLE
how to get maxambig and maxhomo

### ISSUE THREAD

**Issue by NazishAijaz** [mothur/mothur#504]
![image](https://user-images.githubusercontent.com/41560671/43790563-cf646d26-9a27-11e8-9af8-5908da5ee576.png)
screen.seqs(fasta=rpoB.trim.contigs.fasta, group=rpoB.contigs.groups, maxambig=0, maxlength=343,maxhomop=5)
i want to run screen.seqs command in this there is option of maxambig and maxhomop so how can i find this or calculate it is it write that there are 5 homo polymer in my sequence and 1 ambig plz help  me about this

**Comment by krmaas** [comment]
Your primer having an ambig won't mean that your sequences should have an ambig (they shouldn't).

**Comment by NazishAijaz** [comment]
And plz tell me about homop 8 why its 8 how can i know what is homop in my
sequence

thats my current summary and in polymer column its like 16 is highest so
what does it mean i dont understand this plz guide me about this

**Comment by NazishAijaz** [comment]
![image](https://user-images.githubusercontent.com/41560671/43884823-fd11ed62-9b6b-11e8-837c-d691ba61afbb.png)

**Comment by pschloss** [comment]
Homop refers to the longest stretch of the same letter. So 8 would mean a sequence has a region where the same base is repeated 8 times consecutively. I don’t know what to expect for rpoB, but for 16S we use 8
