### ISSUE TITLE
18S Analysis: Trimmed align file used in classify.seqs is missing taxons

### ISSUE THREAD

**Issue by mlg30** [mothur/mothur#505]
I am analyzing 18S sequences which were amplified with V9 primers using mothur v.1.39.3. I used a reference Saccharomyces cerevisiae sequence and the V9 primers that were used in the amplification to trim the silva.nr_v132.align file using align.seqs and pcr.seqs. I then used the resulting align file for the align.seqs command when analyzing my 18S dataset and as a template for the classify.seqs command: 

mothur > classify.seqs(fasta=current, name=current, template=silva.nr_v132.pcr.align, taxonomy=silva.nr_v132.tax, processors=8)

I then get the following messages:

Reading in the silva.nr_v132.tax taxonomy...	DONE.
AAJJ02004940.TbmCas18 is in your taxonomy file and is not in your template file. Please correct.
ALWZ041734736.A1DG1005 is in your taxonomy file and is not in your template file. Please correct.
AOCO010212249.AglTa128 is in your taxonomy file and is not in your template file. Please correct.
AOFL01015930.PopEu196 is in your taxonomy file and is not in your template file. Please correct.
AOFL01018881.PopEu198 is in your taxonomy file and is not in your template file. Please correct.
AOFL01022381.PopEu197 is in your taxonomy file and is not in your template file. Please correct.
AQZL01000003.HQPASCG3 is in your taxonomy file and is not in your template file. Please correct.
ASJU01088520.CapAn188 is in your taxonomy file and is not in your template file. Please correct.
AXCG01076015.GosBa348 is in your taxonomy file and is not in your template file. Please correct.
BACJ01025690.OrySa721 is in your taxonomy file and is not in your template file. Please correct.
CBVK0103466996.A1DAbi84 is in your taxonomy file and is not in your template file. Please correct.
EF051588.UncM5786 is in your taxonomy file and is not in your template file. Please correct.
EU134827.Unc01pej is in your taxonomy file and is not in your template file. Please correct.
EU135143.Unc01q6i is in your taxonomy file and is not in your template file. Please correct.
EU135160.Unc01cpg is in your taxonomy file and is not in your template file. Please correct.
EU160549.UncPs964 is in your taxonomy file and is not in your template file. Please correct.
EU765275.Unc0272v is in your taxonomy file and is not in your template file. Please correct.
FAOM01051070.TcmAe218 is in your taxonomy file and is not in your template file. Please correct.
FJ684295.Unc61537 is in your taxonomy file and is not in your template file. Please correct.
FR687507.Unc00qyw is in your taxonomy file and is not in your template file. Please correct.
GABG01045656.IpoPur21 is in your taxonomy file and is not in your template file. Please correct.
JF747704.Unc048yy is in your taxonomy file and is not in your template file. Please correct.
JMDQ01000439.HbeCyl10 is in your taxonomy file and is not in your template file. Please correct.
JTFL01000132.F1NPs104 is in your taxonomy file and is not in your template file. Please correct.
KF963666.Unc00kco is in your taxonomy file and is not in your template file. Please correct.
KY287412.Unc2llck is in your taxonomy file and is not in your template file. Please correct.
LBLM01044799.GosHi578 is in your taxonomy file and is not in your template file. Please correct.
LNGN01000033.SctHo154 is in your taxonomy file and is not in your template file. Please correct.
LWRW02000071.ZeaM1540 is in your taxonomy file and is not in your template file. Please correct.
LWRW02000277.ZeaM1541 is in your taxonomy file and is not in your template file. Please correct.
MLQS01000001.GQLAlka9 is in your taxonomy file and is not in your template file. Please correct.
DONE.

It seems that when I trimmed the align file, some taxons were lost. How can I correct this?

Thank you!

**Comment by mothur-westcott** [comment]
I suspect that when you ran pcr.seqs some of the references were scrapped.  You can select the "good" sequences from the template using the get.seqs command.  Here's an example:

mothur > list.seqs(fasta=silva.nr_v132.pcr.align) - list sequences in template file
mothur > get.seqs(taxonomy=silva.nr_v132.tax, accnos=current) - select those reads from the taxonomy file

**Comment by mlg30** [comment]
Thanks so much!! Tried out the commands and it worked.
