### ISSUE TITLE
Expand merge.files command

### ISSUE THREAD

**Issue by mothur-westcott** [mothur/mothur#506]
We could add the taxonomy as the comment string in the sequence and then print.  

merge.files(fasta=, taxonomy=)

>GQY1XT001C44N8 Bacteria;"Bacteroidetes";"Bacteroidia";"Bacteroidales";"Porphyromonadaceae";"Porphyromonadaceae"_unclassified;
C-G--T-T--GA-A-A-C-T-G-G--CG-T-T-C--T-T-G-A-G-T-G-G-GC-GA-G-A-A-G-T-A--TG-C-GG-A-ATG-C-G-T-G-GT-GT-A-G-CGGT-G-AAA--...

or 

merge.files(fasta=, count=)

>GQY1XT001C44N8 F003D000-F003D002-F003D004.....F003D150
C-G--T-T--GA-A-A-C-T-G-G--CG-T-T-C--T-T-G-A-G-T-G-G-GC-GA-G-A-A-G-T-A--TG-C-GG-A-ATG-C-G-T-G-GT-GT-A-G-CGGT-G-AAA--...

or other possible combos??

**Comment by krmaas** [comment]
I would love the taxonomy option. Not sure I'd use count because of how long it would be.

**Comment by mothur-westcott** [comment]
Thanks for the feedback! Would the count option be better like this?

merge.files(fasta=, count=)

GQY1XT001C44N8 3677 
C-G--T-T--GA-A-A-C-T-G-G--CG-T-T-C--T-T-G-A-G-T-G-G-GC-GA-G-A-A-G-T-A--TG-C-GG-A-ATG-C-G-T-G-GT-GT-A-G-CGGT-G-AAA--...

where 3677 is the number of sequences represented by GQY1XT001C44N8.

Are there other types of files merges that would be helpful for you?

**Comment by krmaas** [comment]
Would this only be for adding info to the fasta? I could see it useful to have count (or % of total) along with taxonomy

GQY1XT001C44N8 3677 Bacteria;"Bacteroidetes";"Bacteroidia";"Bacteroidales";"Porphyromonadaceae";"Porphyromonadaceae"_unclassified;
C-G--T-T--GA-A-A-C-T-G-G--CG-T-T-C--T-T-G-A-G-T-G-G-GC-GA-G-A-A-G-T-A--TG-C-GG-A-ATG-C-G-T-G-GT-GT-A-G-CGGT-G-AAA--...
