### ISSUE TITLE
0 sequences removed after remove.seqs

### ISSUE THREAD

**Issue by coyk** [mothur/mothur#509]
I've gone through several Mothur runs successfully incorporating the following chimera removal step as found in the Miseq SOP

chimera.vsearch(fasta=current, count=current, dereplicate=t)

remove.seqs(fasta=current, accnos=current)

I want to use a reference based chimera removal instead. 

chimera.vsearch(fasta=current, reference=SymRef3.fasta)

remove.seqs(fasta=current, accnos=current)

I noticed that the output said that 0 sequences were removed. I pulled out the relative files and ran this particular part:

mothur > remove.seqs(fasta=stabilityps1.trim.contigs.good.unique.good.filter.unique.precluster.fasta, accnos=stabilityps1.trim.contigs.good.unique.good.filter.unique.precluster.ref.vsearch.accnos)
Removed 0 sequences from your fasta file.

Output File Names: 
stabilityps1.trim.contigs.good.unique.good.filter.unique.precluster.pick.fasta

mothur > summary.seqs(count=current)
[WARNING]: no file was saved for count parameter.
Using stabilityps1.trim.contigs.good.unique.good.filter.unique.precluster.pick.fasta as input file for the fasta parameter.

Using 1 processors.

Start	End	NBases	Ambigs	Polymer	NumSeqs
Minimum:	1	846	401	0	3	1
2.5%-tile:	1	846	401	0	4	3262
25%-tile:	1	846	425	0	4	32620
Median: 1	846	425	0	4	65240
75%-tile:	1	846	425	0	5	97860
97.5%-tile:	1	846	425	0	6	127218
Maximum:	1	846	425	0	8	130479
Mean:	1	846	421.131	0	4.47999
# of Seqs:	130479

Output File Names: 
stabilityps1.trim.contigs.good.unique.good.filter.unique.precluster.pick.summary

I searched for" M02740_42_000000000-AFFVB_1_1101_6316_305" the first accnos found in stabilityps1.trim.contigs.good.unique.good.filter.unique.precluster.ref.vsearch.accnos and found it in stabilityps1.trim.contigs.good.unique.good.filter.unique.precluster.fasta. 

I don't know why remove.seqs(fasta=current, accnos=current) doesn't work if I used a reference for the chimera search but the same commands for remove.seqs do work if the chimera search was done de novo (chimera.vsearch(fasta=current, count=current, dereplicate=t)).  

I'm working with both 1.38.1.1. and 1.39.5.

Any help would be appreciated.  I posted this to the mothur forum as well.  Apologies for the redundancy.

**Comment by mothur-westcott** [comment]
Is the reference file aligned? The vsearch program expects the reference to be unaligned. If it is aligned, vsearch throws a fatal error:

mothur > chimera.vsearch(fasta=abrecovery.align, reference=silva.bacteria.fasta)
Unable to open abrecovery.align. Trying default /Users/sarahwestcott/desktop/release/abrecovery.align.
Unable to open silva.bacteria.fasta. Trying default /Users/sarahwestcott/desktop/release/silva.bacteria.fasta.

Using 4 processors.
Checking sequences from /Users/sarahwestcott/desktop/release/abrecovery.align ...
vsearch v2.3.4_osx_x86_64, 24.0GB RAM, 4 cores
https://github.com/torognes/vsearch

Reading file /Users/sarahwestcott/desktop/release/silva.bacteria.fasta 0%


Fatal error: illegal character '.' on line 2 in fasta file

It took 0 secs to check your sequences. 0 chimeras were found.


vs the unaligned template:

mothur > chimera.vsearch(fasta=abrecovery.align, reference=silva.bacteria.ng.fasta)
Unable to open abrecovery.align. Trying default /Users/sarahwestcott/desktop/release/abrecovery.align.
Unable to open silva.bacteria.ng.fasta. Trying default /Users/sarahwestcott/desktop/release/silva.bacteria.ng.fasta.

Using 4 processors.
Checking sequences from /Users/sarahwestcott/desktop/release/abrecovery.align ...
vsearch v2.3.4_osx_x86_64, 24.0GB RAM, 4 cores
https://github.com/torognes/vsearch

Reading file /Users/sarahwestcott/desktop/release/silva.bacteria.ng.fasta 100%  
21680084 nt in 14956 seqs, min 1252, max 1712, avg 1450
Masking 100%  
Counting unique k-mers 100%  
Creating index of unique k-mers 100%  
Detecting chimeras 100%  
Found 15 (6.2%) chimeras, 221 (91.3%) non-chimeras,
and 6 (2.5%) borderline sequences in 242 unique sequences.
Taking abundance information into account, this corresponds to
15 (6.2%) chimeras, 221 (91.3%) non-chimeras,
and 6 (2.5%) borderline sequences in 242 total sequences.

It took 3 secs to check your sequences. 15 chimeras were found.
