### ISSUE TITLE
Why is the (mothur-recreated) SILVA SEED getting progressively smaller? (and what are the implications)

### ISSUE THREAD

**Issue by FMKerckhof** [mothur/mothur#511]
Hi everyone,

My favourite classification and alignment database is SILVA. I've been using the mothur-formatted version of release 132 for some time now, at least for classification purposes. Nevertheless, I am currently sticking to the release 123 seed for the `align.seqs` command as I noticed a steep drop between the seed 123 and 128 (https://www.mothur.org/wiki/Silva_reference_files). Is there a motivation why so many (bacterial and archaeal) sequences were removed between these two releases? How does this affect the alignment? I saw for instance that mainly shorter reads were removed from the databases (when looking with `summary.seqs`, see below). 

 ```
> summary.seqs(fasta=silva.seed_v123.align,processors=10)
Using 10 processors.
                Start   End     NBases  Ambigs  Polymer NumSeqs
Minimum:        1045    42803   1185    0       4       1
2.5%-tile:      1046    43116   1394    0       5       373
25%-tile:       1046    43116   1440    0       5       3729
Median:         1046    43116   1457    0       6       7458
75%-tile:       1046    43116   1478    0       6       11186
97.5%-tile:     1046    43116   1741    4       7       14542
Maximum:        1103    43116   2837    5       12      14914
Mean:   1046    43115   1497    0       5
# of Seqs:      14914

> summary.seqs(fasta=silva.seed_v128.align,processors=10)
                Start   End     NBases  Ambigs  Polymer NumSeqs
Minimum:        1045    42803   1358    0       4       1
2.5%-tile:      1046    43116   1398    0       5       281
25%-tile:       1046    43116   1443    0       5       2804
Median:         1046    43116   1461    0       6       5607
75%-tile:       1046    43116   1489    0       6       8410
97.5%-tile:     1046    43116   1744    4       7       10933
Maximum:        1103    43116   2837    5       12      11213
Mean:   1046    43115   1515    0       5
# of Seqs:      11213
> summary.seqs(fasta=silva.seed_v132.align,processors=10)
                Start   End     NBases  Ambigs  Polymer NumSeqs
Minimum:        1045    42803   1358    0       4       1
2.5%-tile:      1046    43116   1398    0       5       280
25%-tile:       1046    43116   1443    0       5       2796
Median:         1046    43116   1460    0       6       5591
75%-tile:       1046    43116   1488    0       6       8386
97.5%-tile:     1046    43116   1744    4       7       10901
Maximum:        1103    43116   2837    5       12      11180
Mean:   1046    43115   1514    0       5
# of Seqs:      11180

```

Nevertheless, when looking at SILVA Ref NR for e.g. Thaumarchaeota it is clear that a part of these shorter reads will not make it into the reference alignment:
![image](https://user-images.githubusercontent.com/2431458/44711035-c7072b00-aaad-11e8-8604-7b75b1a043e3.png)

(the blue and red dashed lines correspond to the minimum and lower 2.5% sequence lengths of aligning *Nitrososphaera viennensis* EN76 (CP0007536) , the only LTP representative of the Thaumarchaeota to the SILVA Ref NR 132 after trimming with primers Arch8f (pB-3856) and Arch1492r(pB-3750))

Probably it makes sense to remove those shorter reads for the quality of the alignment but nevertheless, I wonder if this doesn't negatively affect the alignment and subsequent trimming of Archaea. Of course there are more disconcerting issues with the 16S rRNA of some [thermophilic](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4496867/) archaea anyway... but that is not the discussion at hand here. 

Overall I find it odd that *while the number of sequences in the database increases, the number of sequences in the reference alignment keeps going down*

**Comment by pschloss** [comment]
Hey there - the shorter sequences that get through are going to be the Archaea and Eukaryota since the SILVA NR reference set allows reads in that are 900 nt long. We don't do any manual curation of the databases, it's all determined algorithmically as described in the READMEs. If you want to focus more on the Thaum's or another group, I'd suggest taking our version of the NR and manipulating the representation to get those groups that you need. The seed is trying to be all things too all people and clearly that isn't a perfect strategy :)

**Comment by FMKerckhof** [comment]
Thanks Pat for this very clear answer. I'll give it a go with the NR or full and create a reference for Archaea and Thaumarchaeota seperately (I'm not a 100% sure all will be Thaumarchaeota, so I'll make one for all Archaea as well). The main reason I put so much emphasis on length is that I have been using Arch8f/1492r with PacBio SMRT bell amplicon seq and I don't want to discard CCS reads just because I am missing part of the alignment regions in my reference alignment. I really like that mothur uses an alignment-based screening (some other pipelines don't), but of course that requires a proper reference alignment.

**Comment by pschloss** [comment]
FWIW - I'm not sure how much representation in the database really matters. Your full-length sequences may align well even if there are no full-length Thaums in the database. As long as the alignments that are there are good, it seems to do a pretty good job.
