### ISSUE TITLE
Trim.seqs followed by make.contigs

### ISSUE THREAD

**Issue by andrebolerbarros** [mothur/mothur#526]
I've been doing my 16s analysis using a server which runs mothur version 1.32.1. For that version, I've been doing a quality control trimming step, using trim.seqs, before make contigs.

So, basically, I use a loop based on a txt file where every sample I have is listed (seq.txt):

```
while read seq;
do mothur "#fastq.info(fastq=$seq.fastq); 
summary.seqs(fasta=$seq.fasta); 
trim.seqs(fasta=$seq.fasta,qfile=$seq.qual,minlength=200,maxambig=0,maxhomop=8,qwindowaverage=30,qwindowsize=30,processors=10);
summary.seqs(fasta=$seq.trim.fasta); make.fastq(fasta=$seq.trim.fasta,qfile=$seq.trim.qual)";
rm $seq.fasta;
rm $seq.trim.fasta;
done < seq.txt
```
after this, I would open mothur, and use make.contigs for all the samples (to merge R1 and R2), using a file called stability.files:
`make.contigs(file=stability.files,processors=12)`

In this version, the make.contigs would be successfull, despite some warnings concerning sequences being in the forward but, not in the reverse.

However, now I'm trying to use a more recent version and make.contigs gives an error, apparently for the same reason as the warnings in the earlier version. Is there any way to circumvent this error? I've seen my sequences and it's indispensable I run a QC step

**Comment by pschloss** [comment]
You will want to upgrade to 1.40.5. Also, you really don't want to trim your sequences before running make.contigs. In the mock community data we've analyzed, pre-trimming has never helped and usually hurts.

**Comment by pschloss** [comment]
Feel free to take our mock community data and process it to show that there's an improvement. I think you'll find that by trimming the reads you'll actually increase the error rate, not reduce it.
