### ISSUE TITLE
No samples could be classified, all samples removed in classify.seqs

### ISSUE THREAD

**Issue by rlh13** [mothur/mothur#527]
I am having an issue when I reach classify.seqs. When I run this command, all of my samples are thrown out because all the sequences are getting removed (Error: “WARNING]: M00384_34_000000000-AV783_1_2111_12042_2118 could not be classified. You can use the remove.lineage command with taxon=unknown; to remove such sequences.
” Then, “Removing group: ZFeSFwM2 because all sequences have been removed.”). I was using the greengenes database trimmed to the region of interest as instructed in this blog post. I thought maybe the trimming had been done incorrectly so I tried using the full database without trimming. This resulted in the same issue, as did using the full silva database. In the latter two cases, some samples were also removed in the screen.seqs step due to the removal of all sequences. I am not sure why this is occurring. Attached is my workflow from the original attempt to trim and align with the greengenes database.
[MockCommunity_workflow_mothur_single_8.28.18.docx](https://github.com/mothur/mothur/files/2428864/MockCommunity_workflow_mothur_single_8.28.18.docx)

**Comment by mothur-westcott** [comment]
Have you tried following Pat's example analysis to assemble and preprocess the reads? https://www.mothur.org/wiki/MiSeq_SOP
