### ISSUE TITLE
mixed oriented reads

### ISSUE THREAD

**Issue by amitpande74** [mothur/mothur#528]
Hi,
I have Miseq mixed oriented reads from Illumina. My question is regarding demultiplexing. Can mothur take care of this issue.

**Comment by mothur-westcott** [comment]
The make.contigs command expects the ffastq file to contain the forward reads and the rfastq file to contain the reverse reads. The make.contigs command has a checkorient parameter which will look for the reverse compliment of the primers and barcodes and flip the read if the reverse is found. By default checkorient=f.
