### ISSUE TITLE
tree.shared  input: shared vs. dist ?

### ISSUE THREAD

**Issue by yunsuhk** [mothur/mothur#535]
Hello,

Recently I am working on microbiome project, and really appreciate your great tool, Mothur.

Regarding the command "tree.shared",  I got two different results using the same shared file.

One came from `tree.shared(shared=myfile.shared,  calc=braycurtis)`

The other from

`dist.shared(shared=myfile.shared, calc=braycurtis)`, then,
`tree.shared(phylip=myfile.braycurtis.0.03.lt.dist)`

These two results are different.

the second example was also the same when I used `tree.shared(phylip=myfile.braycurtis.0.03.lt.dist, calc=braycurtis)`.

I am very confusing about why these are different, and which one is more appropriate.

looking forward to your kind reply.

**Comment by yunsuhk** [comment]
Can I wait more for any answer?

**Comment by mothur-westcott** [comment]
Thanks for reporting this bug. It has been fixed and the change will be part of our release next week.
