### ISSUE TITLE
Trim.seqs step

### ISSUE THREAD

**Issue by andrebolerbarros** [mothur/mothur#538]
I've been struggling if I should preform the trim.seqs step. 

Although the make.contings step includes some steps in which it uses quality scores, it's always relative (comparison between sequences) and, as far as I know, does not include an absolute threshold (i.e. a minimum value of quality).

In that sense, I was thinking about performing trim.seqs on my MiSeq data. I know that, in the example files, trim.seqs does not make sense due to the excellent quality of the files; however, I think it may be problematic in my data to "let slide" some sequences with poor quality bp's.

Therefore, I would like to know if there is any recommendation concerning the step in the MiSeq SOP in which to perform trim.seqs.
 
**NOTE:** I am currently posting this question here, since I haven't been able to create an account in mothur forum

**Comment by mothur-westcott** [comment]
@pschloss, do you have a recommendation?
