### ISSUE TITLE
filter.shared segfault

### ISSUE THREAD

**Issue by akunln** [mothur/mothur#547]
Linux version (Ubuntu 16.04)
Using ReadLine
Using Boost
Running 64Bit Version
mothur v.1.41.0

mothur > set.dir(debug=t)
Setting [DEBUG] flag.

mothur > filter.shared(shared=test.shared)
You did not set any parameters. I will filter using minabund=1.
0.03
Speicherzugriffsfehler (Speicherabzug geschrieben)

Mothur log is empty.

Syslog shows a segfault error:
kernel: [ 8148.008544] mothur[7062]: segfault at 7fbcb886fae8 ip 0000000000bebc9e sp 00007fff9f3ceca0 error 4 in mothur[400000+f82000]

filter.shared works for some shared files (around 100 samples and 2500 OTUs). Larger files will always crash.

**Comment by mothur-westcott** [comment]
Could you send a file that is causing the crash to mothur.bugs@gmail.com?

**Comment by mothur-westcott** [comment]
This issue should be fixed in the 1.41.0 release. Can you give it a try, https://github.com/mothur/mothur/releases/tag/v1.41.0?

**Comment by akunln** [comment]
I tried the new release on two different Linux machines (Ubuntu 16.04 and Ubuntu 18.10). Got the exact same issue on both.

mothur "#filter.shared(shared=test.shared)"

Linux version
Using ReadLine,Boost,HDF5
mothur v.1.41.0
Last updated: 11/09/18
...

Script Mode
mothur > filter.shared(shared=test.shared)
You did not set any parameters. I will filter using minabund=1.
0.03
Speicherzugriffsfehler (Speicherabzug geschrieben)

Nov 10 00:13:18 markus-desktop kernel: [46546.849623] mothur[21022]: segfault at 7f31a6e32ae8 ip 000000000073f82e sp 00007ffd8a490220 error 4 in mothur[400000+12c2000]
