### ISSUE TITLE
Get OTU represent sequence from the filter.shared file

### ISSUE THREAD

**Issue by TianyiChang** [mothur/mothur#548]
Hi there

I am new to Mothur. I was wondering does anyone know how to get the representative OTU sequence from a filter.shared file? I used filter.shared to remove lower abundant OTUs, and I tried to get the OTU represent sequences to further get the distance matrix, which I want to use to construct a dendrogram tree. Please let me know if you have any suggestions. Thanks a lot!

**Comment by mothur-westcott** [comment]
I would recommend the following:

mothur > filter.shared(shared=yourSharedFile, ...yourParameters...) - remove unwanted OTUs
mothur > list.otulabels(shared=current) - list names of otus that pass the filter.shared requirements
mothur > get.otus(list=yourListFIleUsedToMakeSharedFile, accnos=current) - select OTUs from list file that are present in the filtered shared file.
mothur > list.seqs(list=current) - list names of sequences in the filtered shared file OTUs
mothur > get.seqs(fasta=yourFastaFile, count=yourCountFile, accnos=current) - select sequences in the filtered shared file OTUs from the fasta and count file
mothur > get.dists(column=yourDIstanceMatrix, accnos=current) - select the distances of the sequences in the filtered shared file OTUs from the distance matrix
mothur > get.oturep(fasta=current, count=current, list=current, column=current) - find representative sequence for each OTU in the filtered shared file
mothur > dist.seqs(fasta=current, output=lt) - create distance matrix for representative sequence
mothur > clearcut(phylip=current) - create tree which relates the representative sequences of the filtered shared file OTUs
