### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by wangj81** [mothur/mothur#549]
Hi everyone,

New to mothur here! I'm trying to install mothur on my mac and am running into the following error:

levy-ve502-0786:mothur-1.40.5 Jenny$ make
c++ -std=c++11 -pthread -L "/Users/Jenny/Documents/UPENN/Senior_Year/BIOL_399/R_Studio_Analysis/Skin_Microbiome_OTU/boost_1_66_0/lib"  -Lsource/  -Lsource/calculators/  -Lsource/chimera/  -Lsource/classifier/  -Lsource/clearcut/  -Lsource/commands/  -Lsource/communitytype/  -Lsource/datastructures/  -Lsource/metastats/  -Lsource/randomforest/  -Lsource/read/  -Lsource/svm/  -o mothur source/averagelinkage.o source/calcsparcc.o source/cluster.o source/clusterclassic.o source/collect.o source/commandfactory.o source/commandoptionparser.o source/completelinkage.o source/consensus.o source/currentfile.o source/dlibshuff.o source/engine.o source/fileoutput.o source/gotohoverlap.o source/heatmap.o source/heatmapsim.o source/inputdata.o source/libshuff.o source/linearalgebra.o source/mothur.o source/mothurout.o source/myseqdist.o source/nast.o source/nastreport.o source/needlemanoverlap.o source/noalign.o source/opticluster.o source/optionparser.o source/overlap.o source/progress.o source/randomnumber.o source/rarecalc.o source/raredisplay.o source/rarefact.o source/refchimeratest.o source/sensspeccalc.o source/seqnoise.o source/singlelinkage.o source/slibshuff.o source/subsample.o source/summary.o source/trialSwap2.o source/trimoligos.o source/utils.o source/validcalculator.o source/validparameter.o source/venn.o source/vsearchfileparser.o source/weightedlinkage.o source/wilcox.o source/calculators/accuracy.o source/calculators/ace.o source/calculators/bergerparker.o source/calculators/boneh.o source/calculators/bootstrap.o source/calculators/bstick.o source/calculators/canberra.o source/calculators/chao1.o source/calculators/coverage.o source/calculators/efron.o source/calculators/f1score.o source/calculators/fdr.o source/calculators/fn.o source/calculators/fp.o source/calculators/fpfn.o source/calculators/geom.o source/calculators/goodscoverage.o source/calculators/gower.o source/calculators/hamming.o source/calculators/heip.o source/calculators/hellinger.o source/calculators/invsimpson.o source/calculators/jackknife.o source/calculators/logsd.o source/calculators/manhattan.o source/calculators/mcc.o source/calculators/memchi2.o source/calculators/memchord.o source/calculators/memeuclidean.o source/calculators/mempearson.o source/calculators/npshannon.o source/calculators/npv.o source/calculators/odum.o source/calculators/parsimony.o source/calculators/ppv.o source/calculators/prng.o source/calculators/qstat.o source/calculators/sensitivity.o source/calculators/shannon.o source/calculators/shannoneven.o source/calculators/shannonrange.o source/calculators/sharedace.o source/calculators/sharedanderbergs.o source/calculators/sharedbraycurtis.o source/calculators/sharedchao1.o source/calculators/sharedjabund.o source/calculators/sharedjackknife.o source/calculators/sharedjclass.o source/calculators/sharedjest.o source/calculators/sharedjsd.o source/calculators/sharedkstest.o source/calculators/sharedkulczynski.o source/calculators/sharedkulczynskicody.o source/calculators/sharedlennon.o source/calculators/sharedmarczewski.o source/calculators/sharedmorisitahorn.o source/calculators/sharedochiai.o source/calculators/sharedrjsd.o source/calculators/sharedsobs.o source/calculators/sharedsobscollectsummary.o source/calculators/sharedsorabund.o source/calculators/sharedsorclass.o source/calculators/sharedsorest.o source/calculators/sharedthetan.o source/calculators/sharedthetayc.o source/calculators/shen.o source/calculators/simpson.o source/calculators/simpsoneven.o source/calculators/smithwilson.o source/calculators/soergel.o source/calculators/solow.o source/calculators/spearman.o source/calculators/speciesprofile.o source/calculators/specificity.o source/calculators/structchi2.o source/calculators/structchord.o source/calculators/structeuclidean.o source/calculators/structkulczynski.o source/calculators/structpearson.o source/calculators/tn.o source/calculators/tp.o source/calculators/tptn.o source/calculators/unweighted.o source/calculators/uvest.o source/calculators/weighted.o source/calculators/whittaker.o source/chimera/bellerophon.o source/chimera/ccode.o source/chimera/chimeracheckrdp.o source/chimera/chimerarealigner.o source/chimera/chimeraslayer.o source/chimera/decalc.o source/chimera/maligner.o source/chimera/mothurchimera.o source/chimera/myPerseus.o source/chimera/pintail.o source/chimera/slayer.o source/classifier/alignnode.o source/classifier/aligntree.o source/classifier/bayesian.o source/classifier/classify.o source/classifier/kmernode.o source/classifier/kmertree.o source/classifier/knn.o source/classifier/phylosummary.o source/classifier/phylotree.o source/classifier/taxonomyequalizer.o source/classifier/taxonomynode.o source/clearcut/clearcut.o source/clearcut/cmdargs.o source/clearcut/distclearcut.o source/clearcut/dmat.o source/clearcut/fasta.o source/clearcut/getopt_long.o source/commands/aligncommand.o source/commands/amovacommand.o source/commands/anosimcommand.o source/commands/binsequencecommand.o source/commands/biominfocommand.o source/commands/catchallcommand.o source/commands/chimerabellerophoncommand.o source/commands/chimeraccodecommand.o source/commands/chimeracheckcommand.o source/commands/chimeraperseuscommand.o source/commands/chimerapintailcommand.o source/commands/chimeraslayercommand.o source/commands/chimerauchimecommand.o source/commands/chimeravsearchcommand.o source/commands/chopseqscommand.o source/commands/classifyotucommand.o source/commands/classifyrfsharedcommand.o source/commands/classifyseqscommand.o source/commands/classifysvmsharedcommand.o source/commands/classifytreecommand.o source/commands/clearcutcommand.o source/commands/clustercommand.o source/commands/clusterdoturcommand.o source/commands/clusterfitcommand.o source/commands/clusterfragmentscommand.o source/commands/clustersplitcommand.o source/commands/collectcommand.o source/commands/collectsharedcommand.o source/commands/consensusseqscommand.o source/commands/cooccurrencecommand.o source/commands/corraxescommand.o source/commands/countgroupscommand.o source/commands/countseqscommand.o source/commands/createdatabasecommand.o source/commands/deconvolutecommand.o source/commands/degapseqscommand.o source/commands/deuniqueseqscommand.o source/commands/deuniquetreecommand.o source/commands/distancecommand.o source/commands/filterseqscommand.o source/commands/filtersharedcommand.o source/commands/getcommandinfocommand.o source/commands/getcoremicrobiomecommand.o source/commands/getcurrentcommand.o source/commands/getdistscommand.o source/commands/getgroupcommand.o source/commands/getgroupscommand.o source/commands/getlabelcommand.o source/commands/getlineagecommand.o source/commands/getlistcountcommand.o source/commands/getmetacommunitycommand.o source/commands/getmimarkspackagecommand.o source/commands/getotulabelscommand.o source/commands/getoturepcommand.o source/commands/getrabundcommand.o source/commands/getrelabundcommand.o source/commands/getsabundcommand.o source/commands/getseqscommand.o source/commands/getsharedotucommand.o source/commands/heatmapcommand.o source/commands/heatmapsimcommand.o source/commands/helpcommand.o source/commands/homovacommand.o source/commands/indicatorcommand.o source/commands/kruskalwalliscommand.o source/commands/lefsecommand.o source/commands/libshuffcommand.o source/commands/listotulabelscommand.o source/commands/listseqscommand.o source/commands/makebiomcommand.o source/commands/makecontigscommand.o source/commands/makefastqcommand.o source/commands/makefilecommand.o source/commands/makegroupcommand.o source/commands/makelefsecommand.o source/commands/makelookupcommand.o source/commands/mantelcommand.o source/commands/matrixoutputcommand.o source/commands/mergecountcommand.o source/commands/mergefilecommand.o source/commands/mergegroupscommand.o source/commands/mergesfffilecommand.o source/commands/mergetaxsummarycommand.o source/commands/metastatscommand.o source/commands/mgclustercommand.o source/commands/mimarksattributescommand.o source/commands/newcommandtemplate.o source/commands/nmdscommand.o source/commands/nocommands.o source/commands/normalizesharedcommand.o source/commands/otuassociationcommand.o source/commands/otuhierarchycommand.o source/commands/pairwiseseqscommand.o source/commands/parsefastaqcommand.o source/commands/parselistscommand.o source/commands/parsimonycommand.o source/commands/pcacommand.o source/commands/pcoacommand.o source/commands/pcrseqscommand.o source/commands/phylodiversitycommand.o source/commands/phylotypecommand.o source/commands/preclustercommand.o source/commands/primerdesigncommand.o source/commands/quitcommand.o source/commands/rarefactcommand.o source/commands/rarefactsharedcommand.o source/commands/removedistscommand.o source/commands/removegroupscommand.o source/commands/removelineagecommand.o source/commands/removeotulabelscommand.o source/commands/removerarecommand.o source/commands/removeseqscommand.o source/commands/renamefilecommand.o source/commands/renameseqscommand.o source/commands/reversecommand.o source/commands/screenseqscommand.o source/commands/secondarystructurecommand.o source/commands/sensspeccommand.o source/commands/seqerrorcommand.o source/commands/seqsummarycommand.o source/commands/setcurrentcommand.o source/commands/setdircommand.o source/commands/setlogfilecommand.o source/commands/setseedcommand.o source/commands/sffinfocommand.o source/commands/sffmultiplecommand.o source/commands/sharedcommand.o source/commands/shhhercommand.o source/commands/shhhseqscommand.o source/commands/sortseqscommand.o source/commands/sparcccommand.o source/commands/splitabundcommand.o source/commands/splitgroupscommand.o source/commands/sracommand.o source/commands/subsamplecommand.o source/commands/summarycommand.o source/commands/summaryqualcommand.o source/commands/summarysharedcommand.o source/commands/summarytaxcommand.o source/commands/systemcommand.o source/commands/treegroupscommand.o source/commands/trimflowscommand.o source/commands/trimseqscommand.o source/commands/unifracunweightedcommand.o source/commands/unifracweightedcommand.o source/commands/venncommand.o source/communitytype/communitytype.o source/communitytype/kmeans.o source/communitytype/pam.o source/communitytype/qFinderDMM.o source/datastructures/alignment.o source/datastructures/alignmentcell.o source/datastructures/alignmentdb.o source/datastructures/blastalign.o source/datastructures/blastdb.o source/datastructures/counttable.o source/datastructures/designmap.o source/datastructures/distancedb.o source/datastructures/fastamap.o source/datastructures/fastqread.o source/datastructures/flowdata.o source/datastructures/fullmatrix.o source/datastructures/groupmap.o source/datastructures/kmer.o source/datastructures/kmeralign.o source/datastructures/kmerdb.o source/datastructures/listvector.o source/datastructures/nameassignment.o source/datastructures/oligos.o source/datastructures/optimatrix.o source/datastructures/ordervector.o source/datastructures/qualityscores.o source/datastructures/rabundfloatvector.o source/datastructures/rabundvector.o source/datastructures/reportfile.o source/datastructures/sabundvector.o source/datastructures/sequence.o source/datastructures/sequencecountparser.o source/datastructures/sequencedb.o source/datastructures/sequenceparser.o source/datastructures/sharedlistvector.o source/datastructures/sharedordervector.o source/datastructures/sharedrabundfloatvector.o source/datastructures/sharedrabundfloatvectors.o source/datastructures/sharedrabundvector.o source/datastructures/sharedrabundvectors.o source/datastructures/sparsedistancematrix.o source/datastructures/sparsematrix.o source/datastructures/suffixdb.o source/datastructures/suffixnodes.o source/datastructures/suffixtree.o source/datastructures/tree.o source/datastructures/treemap.o source/datastructures/treenode.o source/metastats/mothurfisher.o source/metastats/mothurmetastats.o source/randomforest/abstractdecisiontree.o source/randomforest/decisiontree.o source/randomforest/forest.o source/randomforest/randomforest.o source/randomforest/regularizeddecisiontree.o source/randomforest/rftreenode.o source/read/formatcolumn.o source/read/formatphylip.o source/read/readblast.o source/read/readcluster.o source/read/readcolumn.o source/read/readphylip.o source/read/readphylipvector.o source/read/readtree.o source/read/splitmatrix.o source/read/treereader.o source/svm/svm.o    -lreadline -lboost_iostreams -lz
clang: warning: argument unused during compilation: '-pthread'
**ld: library not found for -lboost_iostreams
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [mothur] Error 1**

Does anyone have any insight into this?

Thanks,
Jenny

**Comment by Shellfishgene** [comment]
You are missing the Boost libraries. Why not use the binary version instead of compiling from source?
