### ISSUE TITLE
Warnings are not printed to log file, empy lines instead

### ISSUE THREAD

**Issue by Shellfishgene** [mothur/mothur#551]
Hi,
with the gzip error I already noticed that my logfile had many empty lines. Now I see this again with the classify.seqs command: I get 10 lines of `could not be classified` warnings, and then 4090 empty lines in the log file. The number of unknown seqs in the taxonomy file matches with 4010, so I guess only the first 10 warnings are printed properly, the rest only as a newline. The commands after print to the log correctly again.
This is in v.1.41.0.

**Comment by mothur-westcott** [comment]
Thanks for reporting this issue. The fix will be part of our 1.42.0 release.
