### ISSUE TITLE
precluster (1.41.0) giving mismatched fasta, count_table files

### ISSUE THREAD

**Issue by m-bakker** [mothur/mothur#556]
I am having some issues with pre.cluster, where the output fasta and count_table files do not match.

pre.cluster(fasta=B.QC.fasta, count=B.QC.count_table, diffs=2)
runs to completion

summary.seqs(fasta=B.QC.precluster.fasta, count=B.QC.precluster.count_table)
Using 16 processors.
[ERROR]: Your count table contains a sequence named M03319_39_000000000-C298V_1_1101_10007_16798 with a total=0. Please correct.
[ERROR]: Your count file contains 69974 unique sequences, but your fasta file contains 0. File mismatch detected, quitting command.

I tried pulling out a subset of the data to make a reproducible/shareable example, but this subset went through just fine.

**Comment by mothur-westcott** [comment]
Could you give 1.41.1 a try, https://github.com/mothur/mothur/releases/tag/v.1.41.1?

**Comment by m-bakker** [comment]
Yes, that works now.
