### ISSUE TITLE
Quality Trimming in mothur

### ISSUE THREAD

**Issue by rlh13** [mothur/mothur#557]
I am using cutadapt to demultiplex and trim my sequences. In DADA2, there is a parameter in the denoising step that allows you to trim sequences to a certain length based on the quality scores. Is there a similar parameter in mothur? If so, at which step would it be used? Thank you!

**Comment by pschloss** [comment]
We have yet to see a case where trimming by quality before making contigs improves anything. In our work with dada2 we see worse data quality with trimming than without trimming. I'd strongly encourage you to leave the sequences as they are and run them through make.contigs.

**Comment by rlh13** [comment]
Thank you for the quick response! And thanks for the advice. I will proceed without trimming

**Comment by rlh13** [comment]
If I wanted to pursue quality trimming, how would I go about this? I tried just inserting the [trim.seqs ](https://www.mothur.org/wiki/Trim.seqs) command after make.contigs using fasta=stability.trim.contigs.fasta and qfile=stability.trim.contigs.qual (the output files from make.contigs). However, this is giving me only a scrap.count_table file as output so I assume I am doing this incorrectly but I couldn't find an example of how to use trim.seqs in a workflow. Thank you

**Comment by pschloss** [comment]
This really is ill-advised. In dada the quality trimming is before sequences are concatenated. To do the same thing, you would run the forward and reverse reads through trim.seqs. Then you'd have to make sure that you still have the same sequences in the forward and reverse read files, remove those that don't, and then put it through make.contigs.
