### ISSUE TITLE
Error message after summary.single command

### ISSUE THREAD

**Issue by costamc** [mothur/mothur#559]
Hi,

Just to inform that I am getting the following error message after running sub.sample and summary.single commands using version 1.41.1:
"[ERROR]: requesting groups not present in files, aborting."

the commands work fine with a previous version (1.39.5).

**Comment by mothur-westcott** [comment]
Could you post the exact commands you ran?

**Comment by costamc** [comment]
mothur > sub.sample(shared=current, size=36298)
Using stability.trim.contigs.good.unique.good.filter.unique.precluster.pick.rdp.wang.pick.tx.shared as input file for the shared parameter.
Sampling 36298 from each group.
1
[ERROR]: requesting groups not present in files, aborting.

mothur > sub.sample(shared= stability.trim.contigs.good.unique.good.filter.uniue.precluster.pick.rdp.wang.pick.tx.shared, size=36298)
Sampling 36298 from each group.
1
[ERROR]: requesting groups not present in files, aborting.

mothur > summary.single(shared= stability.trim.contigs.good.unique.good.filterunique.precluster.pick.rdp.wang.pick.tx.shared, calc=nseqs-coverage-sobs-invsimpson, subsample=36298)
[ERROR]: requesting groups not present in files, aborting.
[ERROR]: requesting groups not present in files, aborting.
[ERROR]: requesting groups not present in files, aborting.
[ERROR]: requesting groups not present in files, aborting.
[ERROR]: requesting groups not present in files, aborting.
[ERROR]: requesting groups not present in files, aborting.
[ERROR]: requesting groups not present in files, aborting.
[ERROR]: requesting groups not present in files, aborting.
[ERROR]: requesting groups not present in files, aborting.
[ERROR]: requesting groups not present in files, aborting.

**** Exceeded maximum allowed command errors, quitting ****
[ERROR]: requesting groups not present in files, aborting.

Than using the same shared file (and same command), but using the older version of mothur:
mothur > sub.sample(shared= stability.trim.contigs.good.unique.good.filter.uniue.precluster.pick.rdp.wang.pick.tx.shared, size=36298)
Sampling 36298 from each group.
1
2
3
4
5
6

Output File Names: 
stability.trim.contigs.good.unique.good.filter.unique.precluster.pick.rdp.wang.pick.tx.1.subsample.shared
stability.trim.contigs.good.unique.good.filter.unique.precluster.pick.rdp.wang.pick.tx.2.subsample.shared
stability.trim.contigs.good.unique.good.filter.unique.precluster.pick.rdp.wang.pick.tx.3.subsample.shared
stability.trim.contigs.good.unique.good.filter.unique.precluster.pick.rdp.wang.pick.tx.4.subsample.shared
stability.trim.contigs.good.unique.good.filter.unique.precluster.pick.rdp.wang.pick.tx.5.subsample.shared
stability.trim.contigs.good.unique.good.filter.unique.precluster.pick.rdp.wang.pick.tx.6.subsample.shared


mothur > summary.single(shared= stability.trim.contigs.good.unique.good.filterunique.precluster.pick.rdp.wang.pick.tx.shared, calc=nseqs-coverage-sobs-invsimpson, subsample=36298)

Processing group 61

1
2
3
4
5
6

Processing group T1

1
2
3
4
5
6

Processing group T10
...

Thanks,

**Comment by mothur-westcott** [comment]
Could you post your shared file?

**Comment by costamc** [comment]
[stability.trim.contigs.good.unique.good.filter.unique.precluster.pick.rdp.wang.pick.tx.shared.zip](https://github.com/mothur/mothur/files/2630525/stability.trim.contigs.good.unique.good.filter.unique.precluster.pick.rdp.wang.pick.tx.shared.zip)

**Comment by mothur-westcott** [comment]
Thank you for reporting this bug. Mothur was misreading the shared file with more than one label. I have fixed the issue and the change will be part of our next release. Sorry for the inconvenience.
