### ISSUE TITLE
assessing error rates using own standard

### ISSUE THREAD

**Issue by zhangbw777** [mothur/mothur#565]
Hello 
I did a run using a commercial standard other than MOCK. And I have pseudomonas as one of the examples. My question is for this pseudomonas there are few otus, otu008 gives the majority reads which is 2245. But there also other otus like otu085 gives 8 reads. What's the difference between otu085 and otu008, why mothur gives these many otus for same organism. Can I combine these otus and gives a total count?

<img width="786" alt="screen shot 2018-12-14 at 12 25 43" src="https://user-images.githubusercontent.com/35781444/49977788-d0080380-ff9b-11e8-8215-68fc0d4a68de.png">

Thanks for your help

**Comment by mothur-westcott** [comment]
This may be helpful, https://github.com/mothur/mothur/issues/209

**Comment by zhangbw777** [comment]
hi Sarah, thanks for your answer. With my question regard to error rates
using own standard. Can I run error rate assessment using my own standard,
and if I only know part of the organism's original sequence can I still do
it?

Cheers
Bowen

Sarah Westcott <notifications@github.com> 于2018年12月18日周二 上午3:49写道：

**Comment by pschloss** [comment]
I don't totally follow what you are asking... If you are sequencing a mock community and there is only 1 Pseudomonas 16S rRNA gene sequence in the mock community, then these other OTUs would be the product of PCR, sequencing errors, and perhaps chimeras that were not detected. You have to know the true sequence of the 16S rRNA gene sequences in your mock community to be able to calculate the error rate.
