### ISSUE TITLE
count table missing sequences

### ISSUE THREAD

**Issue by Arkadiy-Garber** [mothur/mothur#566]
running latest available release of mothur

I removed sequences from the fasta file that were not found in the count table. As a result the stability.trim.contigs.good.unique.good.filter.unique.precluster.pick.pick.opti_mcc.list file contains sequences that are not found in the fasta file.

**Comment by mothur-westcott** [comment]
Could you post your complete logfile?

**Comment by Arkadiy-Garber** [comment]
The error originates after running the pre-cluster command. The amount of sequences in the fasta file and the count_table are the same. However, subsequently running the classify.seqs command results in the following output:

mothur > classify.seqs(fasta=stability.trim.contigs.good.unique.good.filter.unique.precluster.fasta, count=stability.trim.contigs.good.unique.good.filter.unique.precluster.count_table, reference=Trainset9_032012/trainset9_032012.pds.fasta, taxonomy=Trainset9_032012/trainset9_032012.pds.tax, cutoff=80)

Using 16 processors.
Reading template taxonomy...     DONE.
Reading template probabilities...     DONE.
It took 5 seconds get probabilities. 
Classifying sequences from stability.trim.contigs.good.unique.good.filter.unique.precluster.fasta ...
100
100
100
100
100
100
100
100
100
100
100
100
100
100
100
100
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
300
300
300
300
300
300
300
300
300
300
300
300
300
300
300
300
400
400
400
400
400
400
400
400
400
400
400
400
400
400
400
400
500
500
500
500
500
500
500
500
500
500
500
600
500
500
500
600
600
500
500
600
600
600
600
600
600
600
600
700
700
700
600
600
600
600
600
700
700
700
700
700
700
700
800
800
700
800
700
800
700
700
700
700
800
800
800
800
800
800
900
900
800
800
800
900
800
900
800
800
900
900
900
900
900
1000
1000
900
900
900
900
900
1000
900
900
1000
1000
1000
1000
1000
1000
1100
1100
1000
1000
1000
1000
1000
1100
1000
1000
1100
1100
1100
1100
1100
1100
1100
1100
1200
1200
1100
1100
1200
1200
1100
1200
1100
1100
1200
1200
1200
1200
1200
1200
1300
1300
1300
1300
1200
1200
1300
1200
1200
1200
1300
1300
1300
1300
1300
1300
1400
1400
1400
1400
1400
1300
1300
1300
1300
1300
1400
1400
1400
1400
1400
1400
1500
1500
1500
1500
1500
1500
1400
1400
1400
1400
1400
1500
1500
1500
1500
1600
1600
1600
1600
1600
1500
1600
1600
1500
1500
1600
1500
1500
1500
1600
1600
1700
1700
1700
1700
1700
1600
1700
1700
1700
1600
1600
1700
1600
1600
1600
1800
1700
1800
1800
1800
1800
1700
1800
1800
1800
1800
1700
1700
1700
1700
1800
1700
1900
1900
1900
1900
1900
1800
1900
1900
1900
1900
1800
1800
1900
1800
1800
1800
2000
2000
2000
2000
2000
1900
2000
2000
2000
2000
1900
1900
1900
1900
2000
2100
1900
2107
2100
2100
2100
2107
2107
2100
2107
2107
2100
2106
2000
2100
2107
2000
2100
2106
2100
2000
2000
2000
2000
2106
2100
2107
2100
2107
2100
2107
2100
2100
2100
2100
2106
2107
2107
2107
It took 135 secs to classify 33708 sequences.


It took 135 secs to classify 33708 sequences.

[ERROR]: M02585_77_000000000-C5TYM_1_1114_5648_6210 is not in your count table. Please correct.
Segmentation fault (core dumped)

this is false, because that sequence is, indeed, found within the FASTA file. However, the entire MiSeq pipeline is stalled due to this bug, and cannot proceed with any of the subsequent steps. I suspect this is due to some kind of illegal char in the header.

thanks

**Comment by mothur-westcott** [comment]
If you send your logfile and input files used with pre.cluster to mothur.bugs@gmail.com, I can try to track down the issue for you.

**Comment by Vienvilay** [comment]
Hello,

I have a similar problem or it could be related to after running pre.cluster, even using the 1.41.1 version. 
After running pre.cluster and getting the output files: ".....precluster.fasta", and "......precluster.count_table", I tried summary.seqs, but got the following errors:

[ERROR]: Your count table contains a sequence named M02465_478_000000000-C2HH7_1_1101_10002_5023 with a total=0. Please correct.
[ERROR]: Your count file contains 58954 unique sequences, but your fasta file contains 0. File mismatch detected, quitting command.

There was a previous issue in the past (precluster (1.41.0) giving mismatched fasta, count_table files #556), but the bug supposed to be fixed in 1.41.1

Thanks for your help!

**Comment by Vienvilay** [comment]
FYI: I just used the 1.39.5 version and apparently pre.cluster worked fine. After pre.cluster, I used summary.seqs and got the expected summary table

		Start	End	NBases	Ambigs	Polymer	NumSeqs
Minimum:	1	555	227	0	3	1
2.5%-tile:	1	556	252	0	3	32568
25%-tile:	1	556	253	0	4	325674
Median: 	1	556	253	0	4	651348
75%-tile:	1	556	253	0	5	977021
97.5%-tile:	1	556	253	0	5	1270127
Maximum:	1	556	268	0	12	1302694
Mean:	1	556	252.765	0	4.44447
# of unique seqs:	54187
total # of seqs:	1302694

Output File Names: 
stability.files.trim.contigs.good.unique.good.filter.unique.precluster.summary

**Comment by bioinformatist** [comment]
@mothur-westcott Hey westcott, I'm using the latest version 1.41.1 but still have error like "JHG_1_1114_15978_19655 is not in your count table. Please correct." when I call chimera.vsearch() with previous fasta and count table. I'm sure that they are in pair as I follow the Miseq SOP well. Can you help me?

**Comment by mothur-westcott** [comment]
Could you send your files to mothur.bugs@gmail.com?

**Comment by hqtdave** [comment]
@mothur-westcott  Hi Westcott, I'm also getting this issue when I call chimera.vsearch() with the count_table and fasta from the previous step. Can you help me with this?

**Comment by mothur-westcott** [comment]
Could you try rerunning the pre.cluster and chimera.vsearch commands with our latest release, https://github.com/mothur/mothur/releases/tag/v1.41.2?
