### ISSUE TITLE
MOTHUR Lefse function error

### ISSUE THREAD

**Issue by Sithara85** [mothur/mothur#567]
Hi,

I am trying to calculate Lefse in Mothur. I have the shared file and design file. Design file has Group and class varibales. If I just run the command  lefse(shared=OTU_LDAEfSe_Visit2.txt, design=OTU_LDAEfSe_design.txt) it works fine. But if I add class to command it gives below error. How can I add a class or subclass to lefse command.

[ERROR]: category class is not in your design file. Please correct.

**Comment by mothur-westcott** [comment]
Could you send your logfile, shared and design files to mothur.bugs@gmail.com so I can take a closer look for you?

**Comment by Sithara85** [comment]
Thank you for your quick response! I sent the files to the above address. Mainly I want to get the difference in OTUs at two visits and do an LDA effect size on it. So I was thinking of adding class and subclass parameters to the lefse function.

**Comment by Sithara85** [comment]
Hi Sarah,

Could you check your emails? I am still not able to succeed with LDA effect size function in Mothur.
