### ISSUE TITLE
Classify.seqs and custom database

### ISSUE THREAD

**Issue by rtrpaine** [mothur/mothur#569]
Hello,

I'm using v1.39.5. I using mothur to analyze metabarcoding data for freshwater fishes. I have curated my own database (12S). 

I've run my pipeline with my all inclusive database that contains reference seqs from all species in the two rivers I am working in. However, some of the seqs are only classified down to Genus. This is because some of the species in certain genera are recently diverged and do not have a lot of bp differences. I thought perhaps removing some species that don't occur in one river would help resolve some of these Genus level OTUs. However, what happens is a significant reduction in the amount of classified seqs as OTUs (aka species). 

For example, with the full database I might get 97 OTUs identified to genus and/or species level in one river. With a more specific database, I get 25 OTUs identified to genus and/or species level. Furthermore, let's say with the full database, a OTU is classified (as a particular species) with 23,000 seqs; however, with the more specific database, the same OTU is classified (as a particular species) with only 8 seqs.

My thought is because classify.seqs relies on probability, when I remove some of the reference database sequences, mothurs ability to assign certain sequences to an OTU (aka species) with a certain probability is reduced. This is because the sequences I removed were definitely not the sequences mothur is trying to classify. In a way, the removed sequences were acting as a "burn-in" that helps mothur hone-in on the  most probable classification. Any thoughts or comments?

Cheers,

Robert

**Comment by pschloss** [comment]
There are a lot of factors that can impact classification. I'm not totally clear what you mean by full vs specific database. It's not just the signal of a species, but also the noise that is introduced too. I would use the same database sequences, but try trimming them to the genus name vs letting them go to the species name in the reference taxonomy file.

Also, I'd strongly encourage you to update to the latest version of mothur.

**Comment by rtrpaine** [comment]
Hi Dr. Schloss,

My apologies. To clarify, my full database encompasses about 400 sequences representing close to 200 species. The 200 species occur in one or both of two different river systems I am studying. 

When I say specific database, I refer to a database where the reference sequences within are for those species that only occur in a specific river. For example if species A occurs in River A, but does not occur in River B, then I removed species A from the River B database.

Cheers,

Robert
