### ISSUE TITLE
Version error

### ISSUE THREAD

**Issue by BioinformaticsBro** [mothur/mothur#570]
Hi, the latest version of mothur is v1.41.1, but after [downloading](https://github.com/mothur/mothur/releases/download/v.1.41.1/Mothur.linux_64.zip), unzipping and running the executable, it shows 

```
mothur v.1.39.5
Last updated: 3/20/2017
```

Is this a typo or is this actually an older version?

**Comment by mothur-westcott** [comment]
When I downloaded the link you sent I am seeing version 1.41.1. Could you be running an older version inadvertently? 

https://mothur.org/wiki/Frequently_asked_questions#I_installed_the_latest_version.2C_but_I_am_still_running_an_older_version
