### ISSUE TITLE
issue running precompiled mothur for linux 

### ISSUE THREAD

**Issue by hansammitzboll** [mothur/mothur#571]
Hi there

i'm trying to run the precompiled version of mothur (Mothur.linux_64.zip) on a 64-bit version of Ubuntu on a virtual machine

i have unzipped the file and when attempting to run mothur from the command line receive the following error:

./mothur: error while loading shared libraries: libreadline.so.6: cannot open shared object file: No such file or directory

i'm rather new to the world of bioinformatics and linux computing, so any help with this issue will be much appreciated!

Thanks

**Comment by hansammitzboll** [comment]
Hi Sarah

Just thought I’d add that I resolved this issue and it’s a problem with the version of Ubuntu that I’m using
Ubuntu 18.04 doesn’t have library readline 6, so it must be downloaded manually
once that is downloaded, mothur will work just fine

here is the thread describing this issue
https://utcc.utoronto.ca/~cks/space/blog/linux/Ubuntu1804ReadlineMess

it might be worth adding this to my help request in case anyone else encounters this issue

Cheers

Hans Christian Ammitzboll
PhD Candidate
School of Natural Sciences
and ARC Centre for Forest Value
University of Tasmania
Private Bag 55
Hobart 7001
Tasmania, Australia
Mobile: 0402367825

**Comment by j0eschm0** [comment]
@hansammitzboll how did you manually install? I already have the .deb downloaded. The "how to resolve readline issues" did not work for me.

**Comment by mothur-westcott** [comment]
Have you tried our no readline version, https://github.com/mothur/mothur/releases/download/v.1.44.1/Mothur.linux_noReadline.zip

**Comment by j0eschm0** [comment]
Hi Sarah,

No I did not try that version, but I figured out the manual install

1.Download the missing readline (https://packages.ubuntu.com/xenial/libreadline6)
2.scp the file into your instance
3.sudo dpkg -i /path/to/deb/file

Thank you for the advice though!
