### ISSUE TITLE
screen.seqs() does not use all processors

### ISSUE THREAD

**Issue by remondulos** [mothur/mothur#572]
I'm using Mothur 1.41.1 and when running the function screen.seqs() with the "processors=80" parameter. Still only 1 processor is used, even though the log file says it is using 80:

mothur > set.current(processors=80)

Using 80 processors.

**Comment by mothur-westcott** [comment]
Have you looked at this? https://github.com/mothur/mothur/issues/518 Are you seeing the same processing time for 1 processor as 80?

**Comment by remondulos** [comment]
No, the processing time is much longer than expected. I used "htop" to check CPU usage, and saw that only one cpu is being used. I also experienced this with older versions of Mothur (1.39.5 and 1.40.5).

**Comment by mothur-westcott** [comment]
Could you send your logfile and input files to mothur.bugs?

**Comment by remondulos** [comment]
I also noticed that unique.seqs() and chimera.vsearch() are limited to one CPU. 
Example command:
mothur "#set.current(processors=80); set.dir(output=<outputfolder>); chimera.vsearch(fasta=<fasta>, count=<count>, dereplicate=t)"

**Comment by mothur-westcott** [comment]
Not all of mothur's command use multiple processors, unique.seqs uses only one processor. Also, the commands that use multiple processors use them for work that lends itself to parallel processing, not all work. For example, the screen.seqs command will use multiple processors for finding optimal settings, but will screen secondary files, like the taxonomy file, with one processor.  The vsearch command passes the processors option to the vsearch program which is parallelized. Mothur uses one processor to launch vsearch and vsearch uses n processors to screen the data.
