### ISSUE TITLE
pcr.seqs generates empty files with used primers

### ISSUE THREAD

**Issue by Krasnopeev** [mothur/mothur#573]
Hi, I've tried to trim Silva db v.132 ( which size ~10 Gb) by primers pair:

V1-9F: 5'-X-AC-GAGTTTGATCMTGGCTCAG-3'
V3-541R: 5'-X-AC-WTTACCGCGGCTGCTGG-3'

I made the reverse compliment of the reverse primer and generated file oligos.txt which looks like:

```
forward GAGTTTGATCMTGGCTCAG
reverse CCAGCAGCCGCGGTAAW
```
And run mothur with the following command:

`pcr.seqs(fasta=silva.nr_v132.align, oligos=oligos.txt)
`

Then `pcr.seqs()` returned an empty file "silva.nr_v132.pcr.align" and file "silva.nr_v132.scrap.pcr.align" with the same size like the original silva.nr_v132.align file.

After that I've tried to repeat this manipulations with Silva SEED db, but result was the same.

And one more, I also tried to reproduce the example from the [topic](http://blog.mothur.org/2016/07/07/Customization-for-your-region/)  and got the same result which I've described - empty *pcr.align file.

mothur version is 1.41.1 (linux)

What I'm doing wrong?

Thanks!

**Comment by mothur-westcott** [comment]
Have you tried using the pdiffs and rdiffs parameters? 

pcr.seqs(fasta=silva.nr_v132.align, oligos=oligos.txt, pdiffs=2, rdiffs=2)

Also, could you post questions like this to our forum, https://forum.mothur.org/, instead of github?

**Comment by JayalalKJ** [comment]
I am sorry, what oligos=oligos.txt,? , pdiffs=2 ? and  rdiffs=2  ?

Could you explain to me?

**Comment by Krasnopeev** [comment]
> Have you tried using the pdiffs and rdiffs parameters?
> 
> pcr.seqs(fasta=silva.nr_v132.align, oligos=oligos.txt, pdiffs=2, rdiffs=2)
> 
> Also, could you post questions like this to our forum, https://forum.mothur.org/, instead of github?

I've tried, same result...
OK, I'll ask on forum, thanks!
