### ISSUE TITLE
Error while installing Mothur source code v.1.41.1 on RedHat Linux

### ISSUE THREAD

**Issue by rpatil8** [mothur/mothur#576]
I downloaded zipped file from
wget https://github.com/mothur/mothur/releases/download/v1.41.3/Mothur.linux_64.zip
and unzipped it in mothur folder I created.
Then went inside the unzipped folder and ran make command, that's when I get following error...
Please help!

**g++ -O3 -std=c++11 -pthread -DVERSION="\"1.41.1\"" -DUSE_READLINE -DUSE_BOOST -I "\"Enter_your_boost_include_path_here\"" -DUSE_HDF5 -I "\"Enter_your_HDF5_include_path_here\"" -I.  -I source/  -I source/calculators/  -I source/chimera/  -I source/classifier/  -I source/clearcut/  -I source/commands/  -I source/communitytype/  -I source/datastructures/  -I source/metastats/  -I source/randomforest/  -I source/read/  -I source/svm/   -c -o source/averagelinkage.o source/averagelinkage.cpp
g++: error trying to exec 'cc1plus': execvp: Permission denied
make: *** [source/averagelinkage.o] Error 1**

After this I read some forums and updated BOOST library and include paths... still getting the same error...

**g++ -O3 -std=c++11 -pthread -DVERSION="\"1.41.1\"" -DUSE_READLINE -DUSE_BOOST -I "\"/usr/local/boost/include\"" -DUSE_HDF5 -I "\"Enter_your_HDF5_include_path_here\"" -I.  -I source/  -I source/calculators/  -I source/chimera/  -I source/classifier/  -I source/clearcut/  -I source/commands/  -I source/communitytype/  -I source/datastructures/  -I source/metastats/  -I source/randomforest/  -I source/read/  -I source/svm/   -c -o source/averagelinkage.o source/averagelinkage.cpp
g++: error trying to exec 'cc1plus': execvp: Permission denied
make: *** [source/averagelinkage.o] Error 1**

**Comment by mothur-westcott** [comment]
The Mothur.linux_64.zip file contains the prebuilt mothur executable as well as the required dependancies. You don't need to build it (no need to run make). To install mothur, https://www.mothur.org/wiki/Installation#Quick_and_Easy_Install.
