### ISSUE TITLE
Error in chimera.vsearch (same as #306)

### ISSUE THREAD

**Issue by Puumanamana** [mothur/mothur#577]
Hi,

I have some issues with the command `chimera.vsearch(count=current,fasta=current)`. When I run it, I get the following error:

`[ERROR]: trouble parsing accnos results. Cannot find contig0.`

However, contig0 is not a label in my table and neither in my fasta file, it's truncated.
It might be the same as issue #306. 

 My abundance table looks like this:
```
Representative_Sequence total   sample1 sample2 sample3 sample4
contig01        680     234     136     224     86
contig02        524     208     77      167     72
contig03        118     50      20      32      16
contig04        86      26      16      31      13
....
```

And my fasta file (X is some nucleotide) :
```
>contig01
XXXXXXXXX 
> contig02
XXXXXXXXX
....
```

Each file has the same number of OTU, with the same names.
When I run `chimera.uchime()` however, every works fine.

Any idea?

**Comment by mothur-westcott** [comment]
Could you send your fasta and count file to mothur.bugs@gmail.com?

**Comment by mothur-westcott** [comment]
Thanks for sending your files. I was not able to reproduce the bug your are having. I have attached the results for your reference. 

Are you using our current version? 

What version of chimera.vsearch are you running?  

[chimera_vsearchbug.zip](https://github.com/mothur/mothur/files/2852966/chimera_vsearchbug.zip)

**Comment by Puumanamana** [comment]
Hi Sarah,

Sorry, I forgot to mention that I’m using the option “dereplicate=t”.

I’m using Mothur 1.41.2 version on a Linux server.

**Comment by mothur-westcott** [comment]
Are you seeing the issue with our current version, 1.41.3? 


[chimera_vsearchbug.zip](https://github.com/mothur/mothur/files/2853016/chimera_vsearchbug.zip)

**Comment by Puumanamana** [comment]
My bad, it works with the newest version.

Thanks

**Comment by Puumanamana** [comment]
Actually, sorry but it does not work with the newest version either. 
I forgot to put dereplicate=t in my previous attempt.

Did you try it on your side?

I enclosed my Mothur log file in case it can help

**Comment by mothur-westcott** [comment]
I am not seeing an error with our current version. I have attached the results and logfile. Can you post your logfile?

[results.zip](https://github.com/mothur/mothur/files/2856832/results.zip)

**Comment by Puumanamana** [comment]
Sure, here are mine. Basically, the contig last character is truncated and therefore it does not remove the two flagged sequences in the final tables as it does for you.

[results_bug.zip](https://github.com/mothur/mothur/files/2857235/results_bug.zip)

**Comment by mothur-westcott** [comment]
Strange. Did you build yourself or download the executable version of mothur? Are you using the version of vsearch distributed with mothur? The chimera.vsearch command is designed to work with vsearch 2.3.4. Later version may produce unexpected results.

**Comment by Puumanamana** [comment]
I downloaded the executable version of Mothur. For VSEARCH, I'm using v2.10.4 downloaded from https://github.com/torognes/vsearch/releases.
As you suggested, I tried to use the version 2.3.4 and it works. 

Thank you

**Comment by mothur-westcott** [comment]
Unfortunately, you cannot specify a vsearch location within mothur. I can see how this would be helpful, and I will add it to our list. Also, I created a separate issue for the vsearch version upgrade which you can follow here, #585
