### ISSUE TITLE
OTU ranking Methods P.Values

### ISSUE THREAD

**Issue by amirshams84** [mothur/mothur#578]
Hi 
It would be great if you let us know that if you are doing any pValue Correction(Bonferroni etc.) for your OTU ranking methods internally( such as Lefse, Metastats, Indicator, Kruskal-Wallis)
or we should correct them

Thanks

**Comment by pschloss** [comment]
None of our implementations add any type of correction for multiple comparisons. lefse kind of has something built in the method in how it uses the LDA.

**Comment by amirshams84** [comment]
Thanks for clarification
