### ISSUE TITLE
redirecting logfile to specific folder

### ISSUE THREAD

**Issue by amirshams84** [mothur/mothur#579]
I have been using the following command to somehow redirect the logfile to a specific folder(in script mode) for further investigation but unfortunately, all important information will be written to the default logfile, please help
mothur "#set.dir(tempdefault=$PATH,output=$PATH)
set.logfile(name=$PATH/my.logfile);"

**Comment by mothur-westcott** [comment]
The $PATH variable may be the issue.  Mothur assumes the $PATH is a single directory. For example, my $PATH variable is /Users/sarahwestcott/Desktop/mothur/TARGET_BUILD_DIRTARGET_BUILD_DIR/:/opt/local/bin:/opt/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/opt/X11/bin/. When I run the 

MothurMac-2:TARGET_BUILD_DIRTARGET_BUILD_DIR sarahwestcott$ ./mothur "#set.dir(tempdefault=$PATH, output=$PATH);set.logfile(name=$PATH/my.logfile);"

it expands to:

mothur > set.dir(tempdefault=/Users/sarahwestcott/Desktop/mothur/TARGET_BUILD_DIRTARGET_BUILD_DIR/:/opt/local/bin:/opt/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/opt/X11/bin, output=/Users/sarahwestcott/Desktop/mothur/TARGET_BUILD_DIRTARGET_BUILD_DIR/:/opt/local/bin:/opt/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/opt/X11/bin)
Mothur's directories:
outputDir=/Users/sarahwestcott/Desktop/mothur/TARGET_BUILD_DIRTARGET_BUILD_DIR/:/opt/local/bin:/opt/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/opt/X11/bin/
tempDefault=/Users/sarahwestcott/Desktop/mothur/TARGET_BUILD_DIRTARGET_BUILD_DIR/:/opt/local/bin:/opt/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/opt/X11/bin/

mothur > set.logfile(name=/Users/sarahwestcott/Desktop/mothur/TARGET_BUILD_DIRTARGET_BUILD_DIR/:/opt/local/bin:/opt/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/opt/X11/bin/my.logfile)

 The logfile is created along with unexpected directories as mothur tries to make sense on the path.

![screen shot 2019-02-08 at 10 06 03 am](https://user-images.githubusercontent.com/1379958/52486463-3159e680-2b89-11e9-90c6-bf881c5345c6.png)
