### ISSUE TITLE
Unique list file with opticlust algorithm?

### ISSUE THREAD

**Issue by Esmee73** [mothur/mothur#587]
Hi, 

Before I used the average clustering algorithm to create unique and 0.03 list files. I changed to the opticlust clustering algorithm with which I manage to generate list files for different cutoffs, but I do not manage to create an unique list file. Is it possible to create an unique list file with the opticlust algorithm or should I use another clustering algorithm, e.g., unique, for this? Ideally, I would like to generate biom files for both unique and 0.03.

Thanks,
Esmee

**Comment by mothur-westcott** [comment]
To find the unique and 0.03 clusters run with cutoff=0.00-0.03.

mothur > cluster(column=final.dist, count=final.count_table, cutoff=0.00-0.03)

Using 4 processors.

Clustering /Users/sarahwestcott/desktop/release/final.dist

iter	time	label	num_otus	cutoff	tp	tn	fp	fn	sensitivity	specificity	ppv	npv	fdr	accuracy	mcc	f1score

0.00
0	0	0	3772	0	0	7112106	0	0	0	1	0	1	1	1	0	0	
1	0	0	3772	0	0	7112106	0	0	0	1	0	1	1	1	0	0	



0.03
0	0	0.03	3772	0.03	0	7059666	0	52440	0	1	0	0.992627	1	0.992627	0	0	
1	0	0.03	1254	0.03	26387	7053918	5748	26053	0.503185	0.999186	0.82113	0.99632	0.82113	0.995529	0.64083	0.623991	
2	0	0.03	1174	0.03	31321	7051466	8200	21119	0.597273	0.998838	0.792515	0.997014	0.792515	0.995878	0.686038	0.68118	
3	1	0.03	1161	0.03	31716	7051107	8559	20724	0.604805	0.998788	0.787486	0.99707	0.787486	0.995883	0.688151	0.684161	
4	0	0.03	1162	0.03	31724	7051164	8502	20716	0.604958	0.998796	0.788644	0.997071	0.788644	0.995892	0.688751	0.684696	
5	0	0.03	1165	0.03	31770	7051122	8544	20670	0.605835	0.99879	0.788064	0.997077	0.788064	0.995892	0.688996	0.685038	
6	0	0.03	1164	0.03	31803	7051110	8556	20637	0.606465	0.998788	0.788003	0.997082	0.788003	0.995895	0.689329	0.685417	
7	0	0.03	1164	0.03	31799	7051137	8529	20641	0.606388	0.998792	0.788509	0.997081	0.788509	0.995899	0.68951	0.68556	
8	0	0.03	1165	0.03	31816	7051131	8535	20624	0.606712	0.998791	0.788481	0.997084	0.788481	0.9959	0.689683	0.685756	
9	0	0.03	1166	0.03	31753	7051234	8432	20687	0.605511	0.998806	0.79017	0.997075	0.79017	0.995906	0.689743	0.685625	


It took 54 seconds to cluster

Output File Names: 
/Users/sarahwestcott/desktop/release/final.opti_mcc.list
/Users/sarahwestcott/desktop/release/final.opti_mcc.steps
/Users/sarahwestcott/desktop/release/final.opti_mcc.sensspec

**Comment by Esmee73** [comment]
Thank you for your quick reply!

I am a bit confused because I read on the mothur wiki that unique and 0.00 distance levels are not the same?https://mothur.org/wiki/Frequently_asked_questions#Aren.27t_the_.27unique.27_and_.270.00.27_distance_levels_the_same.3F

**Comment by mothur-westcott** [comment]
We modified mothur to use hard cutoff several versions ago. Now when you enter a cutoff of 0.00, only identical sequences will be assigned to the same OTU. Sorry for the confusion.

**Comment by Esmee73** [comment]
Great, thanks for explaining! Then I will use a cutoff of 0.00 from now on!
