### ISSUE TITLE
Error with chimera.uchime

### ISSUE THREAD

**Issue by hadaidga** [mothur/mothur#588]
I am using the mothur version v.1.39.5
Last updated: 3/20/2017

by
Patrick D. Schloss

Department of Microbiology & Immunology
University of Michigan
http://www.mothur.org

When I run this the chimera.uchime command i get this error message, 

mothur>chimera.uchime(fasta=xbbd.trim.contigs.good.unique.abund.good.filter.unique.precluster.fasta,count=xbbd.trim.contigs.good.unique.abund.good.filter.unique.precluster.count_table, dereplicate=t)
Using 8 processors.
/usr/bin/mothuruchime file does not exist. Checking path... 
[ERROR]:  file does not exist. mothur requires the uchime executable.
[ERROR]: did not complete chimera.uchime.
 
Can you please tell me what is the issue?

**Comment by mothur-westcott** [comment]
The chimera.uchime command is a wrapper for the uchime program. Mothur requires the uchime executable to be in the same location as the mothur executable or be in your $PATH. The uchime executable is distributed with mothur's executable version. Also, I noticed you are using version 1.39.5. I would recommend upgrading to our current version.
