### ISSUE TITLE
quality summary and trimming

### ISSUE THREAD

**Issue by zhangbw777** [mothur/mothur#591]
Hello

In MOTHUR Miq-SOP tutoral, the way to clean up the data is to run screen.seq based on the summary table. However, this clean up is not based on Quality Score. I was just wondering is this means MOTHUR dot suggest clean up the data based on the quality score?

Also when I check my stability.trim.contigs.qual file some of the quality scores exceed 40. How come is this happyed?

Thanks for your time
Bowen

**Comment by pschloss** [comment]
Thanks for the question - usually forum.mothur.org is the best place for these types of questions. The quality scores are used in make.contigs to denoise the individual reads as the contigs are made. Quality trimming before that step or after does nothing and possibly makes the error rates worse in the long run. The consensus quality scores can be higher than 40 if both reads have a high-quality base call in that position. 40 means that the error rate is 10^-4. 50 would mean it is 10^-5
