### ISSUE TITLE
Problem merging clustered files

### ISSUE THREAD

**Issue by PatriciaO** [mothur/mothur#592]
Hello,

I'm running mothur in batch mode, but it stopped at the cluster.split command:

Merging the clustered files...
[ERROR]: C16S_17.trim.contigs.good.unique.good.filter.unique.precluster.pick.pick.fasta.80.opti_mcc.list is blank. Please correct.
Segmentation fault: 11

Not really sure how to correct this, please help.
Thank you.

**Comment by mothur-westcott** [comment]
Could you send your input files and logfile to mothur.bugs@gmail.com?
