### ISSUE TITLE
get.oturep  after dist.shared ?

### ISSUE THREAD

**Issue by yunsuhk** [mothur/mothur#594]
Hello

I am enjoying this wonderful tool, mothur, for my project.

To get representative fasta, I used the commands like below , but I am not sure whether this is collect.

`mothur "#dist.shared(shared="$myshared", calc=braycurtis)"`

, which provided $mydist. then,

`mothur "#get.oturep(phylip="$mydist", list="$mylist", fasta="$myfasta")"`

Even though this provided seemingly reasonable results, I am still wondering whether $mydist should be generated by dist.seqs with $myfasta (which is more than 3Gb), instead of dist.shared.

FYI, I am running mothur-1.40.5 with linux command.

Thanks in advance.

**Comment by mothur-westcott** [comment]
The dist.shared command generates a distance matrix that represents how closely your samples are related. The get.oturep command finds a representative sequence for each otu based on how closely your sequences are related within each otu. You don't want to use the dist.shared results as input for get.oturep. You are correct that you will want to use the dist.seqs command results with a cutoff for the get.oturep command.  

As to the size of your fasta file, have you taken a look at Pat's example analysis, https://www.mothur.org/wiki/MiSeq_SOP, and blog about distance matrix size, http://blog.mothur.org/2014/09/11/Why-such-a-large-distance-matrix/?

**Comment by yunsuhk** [comment]
Thanks for kind reply.

I will try to use dist.seqs. But still confused one is how the distance from dist.shared  provided get.oturep results without an error. is it bug ?

And I enjoyed your blog . thanks again.

**Comment by mothur-westcott** [comment]
Why is the get.oturep command not erroring?

If mothur can't find a distance for a sequence in the list file it assumes that the read is either redundant (ie: you used a name file while clustering so your list file contains unique and redundant names, but the distance matrix only contains the unique names), or that the read does not have any distances below the cutoff (ie. singleton). In either case, if all the reads in the OTU fall into this category the representative defaults to the first read found in the OTU.  Since you have a file mismatch, none of the reads in the list file are found in the distance matrix. Resulting in every OTU hitting this issue.

**Comment by yunsuhk** [comment]
I used below command to make a list file,

`mothur "#cluster(fasta="$myfasta", count="$mycount", method=agc)"`

($myfasta is unique.)

This provided `$mylist` which contained OTU and unique sequence name.

And from `$mydist` by `dist.shared`,  the distance was measured among each OTU.

According to your reply, my representative fasta could be simply the first read found in each OTU, which might the reason why there was no error. I checked my file and agree your explanation.

Thanks so much. But just in case, it will be helpful for mothur to generate error or warning message for this case.

By the way, I am trying `dist.seq` with cutoff=0.03 using 24 threads, but it is still runnning over 21 hrs. (longer than I expected ! ) (myfasta is 2.8G)

**Comment by mothur-westcott** [comment]
"And from $mydist by dist.shared, the distance was measured among each OTU."

The dist.shared command finds the distance between each sample, not each OTU.  

As to the time it takes to run dist.seqs, mothur is calculating (numUniques * (numUniques - 1))/2 distances. How many unique sequences do you have?

**Comment by yunsuhk** [comment]
dist.shared was between each sample. You are right.

my fasta has 2001528 uniq sequences.
