### ISSUE TITLE
make.biom for Funguild analyses (using the UNITE database)

### ISSUE THREAD

**Issue by peng-ye** [mothur/mothur#598]
Dear Sarah, I am new to Mothur. Recently I got a .shared and a .taxonomy file (and they were the only files I got) from my collaborator. I tried to map those files into a UNITE-based profile for Funguild analysis (http://www.stbates.org/guilds/app.php), but did not found any method like make.biom for transferring the .shared file for PICRUSt analysis.
I was wondering if there are any methods for this purpose provided by Mothur?
Thanks!

**Comment by mothur-westcott** [comment]
The make.biom command with the picrust option is designed to map the OTUs found in your constaxonomy file to their GreenGenes OTU id. 

For example, if your consensus OTU classifies to k__Archaea;p__Euryarchaeota;c__Methanobacteria;o__Methanobacteriales;f__Methanobacteriaceae;g__Methanothermobacter;s__thermautotrophicus, there are 7 references that classify to that taxonomy in the gg_13_5_99.gg.tax: 227, 236, 129196, 162275, 166509, 369183 and 4434719.  The 97.gg.otu.map file tells us the GreenGenes OTU id is 227. Mothur combines any OTUs with the same OTU id, and the result in the biom file looks like:

{"id":"227", "metadata":{"taxonomy":["k__Archaea", "p__Euryarchaeota", "c__Methanobacteria", "o__Methanobacteriales", "f__Methanobacteriaceae", "g__Methanothermobacter", "s__thermautotrophicus"]}}
