### ISSUE TITLE
Allow batch files to use environmental variables

### ISSUE THREAD

**Issue by pschloss** [mothur/mothur#601]
If I define `DATA=my_awesome_project/` or `PROCESSORS=8`, it would be nice to use `$DATA` or `$PROCESSORS` in a batch file.

**Comment by mothur-westcott** [comment]
batchOfBatches.batch

#set data location
PROC=12
DATA=/Users/sarahwestcott/desktop/release/
set.dir(input=$DATA, output=$DATA, tempdefault=$DATA)
set.logfile(name=alignseqs.logfile)
align.seqs(fasta=testAlign.fasta, reference=silva.v4.fasta)
summary.seqs(fasta=current, processors=$PROC)
#comments
smallBatch.batch
get.current()
quit()


smallBatch.batch
set.logfile(name=classifyseqs.logfile)
PROC=8
DATA=/Users/sarahwestcott/Desktop/TestBatches/TestFiles
classify.seqs(fasta=$DATA/testClassify.fasta, reference=trainset9_032012.pds.fasta, taxonomy=trainset9_032012.pds.tax, processors=$PROC)
classify.seqs(fasta=$DATA/testClassify.fasta, count=$DATA/testClassify.count_table, reference=trainset9_032012.pds.fasta, taxonomy=trainset9_032012.pds.tax)
#comment
quit()



[logs.zip](https://github.com/mothur/mothur/files/3780337/logs.zip)

**Comment by mothur-westcott** [comment]
You can run multiple datasets through the same pipeline as follows:

REFERENCE=/Users/sarahwestcott/Desktop/release
pcr.seqs(fasta=$REFERENCE/silva.bacteria.fasta, start=11894, end=25319, keepdots=F)
rename.file(fasta=current, new=$REFERENCE/silva.v4.fasta)
DATA=/Users/sarahwestcott/Desktop/MiSeq_SOP
TYPE=fastq
./stability.batch
DATA=/Users/sarahwestcott/Desktop/gzTest
TYPE=gz
./stability.batch


stability.batch:
make.file(inputdir=$DATA, type=$TYPE, prefix=stability)
make.contigs(file=current, processors=$PROC)
screen.seqs(fasta=current, group=current, maxambig=0, maxlength=275)
unique.seqs()
count.seqs(name=current, group=current)
align.seqs(fasta=current, reference=$REFERENCE/silva.v4.fasta)
screen.seqs(fasta=current, count=current, start=1968, end=11550, maxhomop=8)
filter.seqs(fasta=current, vertical=T, trump=.)
unique.seqs(fasta=current, count=current)
pre.cluster(fasta=current, count=current, diffs=2)
chimera.vsearch(fasta=current, count=current, dereplicate=t)
remove.seqs(fasta=current, accnos=current)
classify.seqs(fasta=current, count=current, reference=$REFERENCE/trainset9_032012.pds.fasta, taxonomy=$REFERENCE/trainset9_032012.pds.tax, cutoff=80)
remove.lineage(fasta=current, count=current, taxonomy=current, taxon=Chloroplast-Mitochondria-unknown-Archaea-Eukaryota)
remove.groups(count=current, fasta=current, taxonomy=current, groups=Mock)
cluster.split(fasta=current, count=current, taxonomy=current, splitmethod=classify, taxlevel=4, cutoff=0.15)
make.shared(list=current, count=current, label=0.03)
classify.otu(list=current, count=current, taxonomy=current, label=0.03)
phylotype(taxonomy=current)
make.shared(list=current, count=current, label=1)
classify.otu(list=current, count=current, taxonomy=current, label=1)

**Comment by mothur-westcott** [comment]
@pschloss Does this page update clear things up, https://mothur.org/wiki/Batch_mode?

**Comment by pschloss** [comment]
Would https://mothur.org/wiki/Batch_mode#Nested_Batch_Files work with my comment from 10/29? If so, could you add that comment to the bottom of the section on the wiki page?

**Comment by mothur-westcott** [comment]
The syntax in 10/29 does not work, but I can modify mothur if you would like. 

This would work as I have it currently:

REFERENCE=/Users/sarahwestcott/Desktop/release DATA=/Users/sarahwestcott/Desktop/MiSeq_SOP
TYPE=fastq
DATA=/Users/sarahwestcott/Desktop/gzTest
TYPE=gz
stability.batch

Instead of:

$ REFERENCE=/Users/sarahwestcott/Desktop/release
$ DATA=/Users/sarahwestcott/Desktop/MiSeq_SOP
$ TYPE=fastq
$ DATA=/Users/sarahwestcott/Desktop/gzTest
$ TYPE=gz
$ mothur stability.batch

**Comment by pschloss** [comment]
It would be nice for the user to be able to define variables from within bash and then to pass those into mothur for use in a batch file. For example, if I'm analyzing numerous datasets with the same pipeline, I'd like to set the dataset in bash and run the same batch file for all of the datasets.

**Comment by mothur-westcott** [comment]
okay, I can modify it to pull in the environment variables from bash as well as allowing for them to be set within the batch file.
