### ISSUE TITLE
make.groups not naming groups files correctly (1.41.3 and 1.40.5)

### ISSUE THREAD

**Issue by sconlan** [mothur/mothur#602]
make.groups seems to be writing group files to "groups" instead of the expected filename? Maybe a side effect related to: https://github.com/mothur/mothur/issues/384

Rolling back to 1.39.5 (but not 1.40.5) fixes.

Using ReadLine,Boost,HDF5
mothur v.1.41.3
Last updated: 1/30/19
by
Patrick D. Schloss

Department of Microbiology & Immunology

University of Michigan
http://www.mothur.org

When using, please cite:
Schloss, P.D., et al., Introducing mothur: Open-source, platform-independent, community-supported software for describing an
d comparing microbial communities. Appl Environ Microbiol, 2009. 75(23):7537-41.

Distributed under the GNU General Public License

Type 'help()' for information on the commands that are available

For questions and analysis support, please visit our forum at https://www.mothur.org/forum

Type 'quit()' to exit program

Script Mode

mothur > make.group(fasta=58.subsample.fasta, groups=58)

Output File Names: groups

mothur > quit()

**Comment by mothur-westcott** [comment]
Thanks for reporting this issue. I have fixed the output file name and the change will be part of our next release. In the meantime, you can work around the issue by setting the output file name using the output parameter.

mothur > make.group(fasta=58.subsample.fasta, groups=58, output=58.groups)
