### ISSUE TITLE
new [space character] in the output from summary.seqs

### ISSUE THREAD

**Issue by didillysquat** [mothur/mothur#603]
In the actual path output from summary.seqs there is a space character before the path string. This is new from the older versions of mothur and this space does not exist in the other outputs.

I know it seems trivial but it is causing issues in scripts and wrappers of mothur that don't by default do a white space stripping operation on this string before trying to use the path in downstream operations.

It would be great if this space could be removed. Thank you!

**Comment by mothur-westcott** [comment]
Sure, we can do that.
