### ISSUE TITLE
unifrac.weighted does not complete

### ISSUE THREAD

**Issue by akunln** [mothur/mothur#604]
Hello,

while running the phylogeny-based analysis I got a problem with unifrac.weighted never completing. In comparison unifrac.unweighted was finished after around 6000 secs with the same input data. Unifrac.weighted kept on going even after 8 hours. The wsummary and weighted.phylip.dist are there and complete. But weighted.std.dist and weighted.ave.dist were never created. 

Linux version (Ubuntu 19.04)
Using ReadLine,Boost,HDF5
mothur v.1.42.0
Last updated: 4/2/19

**Comment by mothur-westcott** [comment]
Using the example data from Pat's MiSeq_SOP, you can see the weighted version takes significantly longer to process. 194 seconds for unweighted and 867 for weighted. Given your timing of 6000 seconds for unweighted, I would expect the weighted version to take around 8 hours, perhaps longer. Are you sure it crashes or could it simply be taking longer than you expected?

mothur > unifrac.weighted(tree=stability.tre, count=stability.count_table, distance=lt, subsample=t)
Unable to open stability.tre. Trying default /Users/sarahwestcott/desktop/release/stability.tre.
Unable to open stability.count_table. Trying default /Users/sarahwestcott/desktop/release/stability.count_table.

Using 4 processors.

Setting subsample size to 2403.

Tree#	Groups	WScore	
1	F3D0-F3D1	0.221369
1	F3D0-F3D141	0.153069
1	F3D1-F3D141	0.290096
1	F3D0-F3D142	0.177878
1	F3D1-F3D142	0.317497
1	F3D141-F3D142	0.0950163
1	F3D0-F3D143	0.152037
1	F3D1-F3D143	0.287078
1	F3D141-F3D143	0.0525568
1	F3D142-F3D143	0.0767369
1	F3D0-F3D144	0.195522
1	F3D1-F3D144	0.337772
1	F3D141-F3D144	0.104146
1	F3D142-F3D144	0.0833902
1	F3D143-F3D144	0.0901713
1	F3D0-F3D145	0.20391
1	F3D1-F3D145	0.346806
1	F3D141-F3D145	0.108539
1	F3D142-F3D145	0.0726155
1	F3D143-F3D145	0.0960158
1	F3D144-F3D145	0.0500125
1	F3D0-F3D146	0.113568
1	F3D1-F3D146	0.249881
1	F3D141-F3D146	0.0892846
1	F3D142-F3D146	0.130143
1	F3D143-F3D146	0.0864765
1	F3D144-F3D146	0.133504
1	F3D145-F3D146	0.138029
1	F3D0-F3D147	0.194381
1	F3D1-F3D147	0.335909
1	F3D141-F3D147	0.102962
1	F3D142-F3D147	0.07393
1	F3D143-F3D147	0.0911261
1	F3D144-F3D147	0.0511858
1	F3D145-F3D147	0.0469431
1	F3D146-F3D147	0.1355
1	F3D0-F3D148	0.171433
1	F3D1-F3D148	0.310142
1	F3D141-F3D148	0.0606753
1	F3D142-F3D148	0.0632685
1	F3D143-F3D148	0.0580442
1	F3D144-F3D148	0.0730635
1	F3D145-F3D148	0.0781817
1	F3D146-F3D148	0.111312
1	F3D147-F3D148	0.0701999
1	F3D0-F3D149	0.14114
1	F3D1-F3D149	0.272978
1	F3D141-F3D149	0.0453909
1	F3D142-F3D149	0.106119
1	F3D143-F3D149	0.0604764
1	F3D144-F3D149	0.109247
1	F3D145-F3D149	0.11545
1	F3D146-F3D149	0.0734287
1	F3D147-F3D149	0.108529
1	F3D148-F3D149	0.0693731
1	F3D0-F3D150	0.126555
1	F3D1-F3D150	0.271866
1	F3D141-F3D150	0.0834002
1	F3D142-F3D150	0.129043
1	F3D143-F3D150	0.0844534
1	F3D144-F3D150	0.140017
1	F3D145-F3D150	0.145515
1	F3D146-F3D150	0.0738879
1	F3D147-F3D150	0.137427
1	F3D148-F3D150	0.1147
1	F3D149-F3D150	0.0651001
1	F3D0-F3D2	0.13032
1	F3D1-F3D2	0.215458
1	F3D141-F3D2	0.156161
1	F3D142-F3D2	0.185518
1	F3D143-F3D2	0.170937
1	F3D144-F3D2	0.211311
1	F3D145-F3D2	0.213149
1	F3D146-F3D2	0.148692
1	F3D147-F3D2	0.204514
1	F3D148-F3D2	0.184943
1	F3D149-F3D2	0.151263
1	F3D150-F3D2	0.149311
1	F3D0-F3D3	0.211621
1	F3D1-F3D3	0.3066
1	F3D141-F3D3	0.123525
1	F3D142-F3D3	0.110572
1	F3D143-F3D3	0.139436
1	F3D144-F3D3	0.143411
1	F3D145-F3D3	0.130648
1	F3D146-F3D3	0.172917
1	F3D147-F3D3	0.136972
1	F3D148-F3D3	0.123733
1	F3D149-F3D3	0.130789
1	F3D150-F3D3	0.165269
1	F3D2-F3D3	0.137297
1	F3D0-F3D5	0.128683
1	F3D1-F3D5	0.180894
1	F3D141-F3D5	0.167286
1	F3D142-F3D5	0.205537
1	F3D143-F3D5	0.174985
1	F3D144-F3D5	0.224035
1	F3D145-F3D5	0.231203
1	F3D146-F3D5	0.144824
1	F3D147-F3D5	0.224055
1	F3D148-F3D5	0.189052
1	F3D149-F3D5	0.153477
1	F3D150-F3D5	0.147003
1	F3D2-F3D5	0.126642
1	F3D3-F3D5	0.192516
1	F3D0-F3D6	0.134968
1	F3D1-F3D6	0.235126
1	F3D141-F3D6	0.131503
1	F3D142-F3D6	0.122631
1	F3D143-F3D6	0.128926
1	F3D144-F3D6	0.17073
1	F3D145-F3D6	0.161744
1	F3D146-F3D6	0.114751
1	F3D147-F3D6	0.163594
1	F3D148-F3D6	0.147923
1	F3D149-F3D6	0.117132
1	F3D150-F3D6	0.123454
1	F3D2-F3D6	0.0942838
1	F3D3-F3D6	0.117644
1	F3D5-F3D6	0.128766
1	F3D0-F3D7	0.197597
1	F3D1-F3D7	0.315515
1	F3D141-F3D7	0.129819
1	F3D142-F3D7	0.0968625
1	F3D143-F3D7	0.130278
1	F3D144-F3D7	0.141823
1	F3D145-F3D7	0.121248
1	F3D146-F3D7	0.173531
1	F3D147-F3D7	0.126454
1	F3D148-F3D7	0.116359
1	F3D149-F3D7	0.140345
1	F3D150-F3D7	0.152094
1	F3D2-F3D7	0.153129
1	F3D3-F3D7	0.0862556
1	F3D5-F3D7	0.186574
1	F3D6-F3D7	0.109132
1	F3D0-F3D8	0.175705
1	F3D1-F3D8	0.182476
1	F3D141-F3D8	0.202076
1	F3D142-F3D8	0.220571
1	F3D143-F3D8	0.213567
1	F3D144-F3D8	0.265431
1	F3D145-F3D8	0.258451
1	F3D146-F3D8	0.179011
1	F3D147-F3D8	0.265697
1	F3D148-F3D8	0.227424
1	F3D149-F3D8	0.193616
1	F3D150-F3D8	0.196322
1	F3D2-F3D8	0.160911
1	F3D3-F3D8	0.199946
1	F3D5-F3D8	0.115841
1	F3D6-F3D8	0.139149
1	F3D7-F3D8	0.182972
1	F3D0-F3D9	0.152857
1	F3D1-F3D9	0.183315
1	F3D141-F3D9	0.194225
1	F3D142-F3D9	0.214548
1	F3D143-F3D9	0.203967
1	F3D144-F3D9	0.260535
1	F3D145-F3D9	0.253537
1	F3D146-F3D9	0.171015
1	F3D147-F3D9	0.26049
1	F3D148-F3D9	0.221254
1	F3D149-F3D9	0.189883
1	F3D150-F3D9	0.18244
1	F3D2-F3D9	0.138922
1	F3D3-F3D9	0.195078
1	F3D5-F3D9	0.0956521
1	F3D6-F3D9	0.128239
1	F3D7-F3D9	0.178467
1	F3D8-F3D9	0.0521679
100
200
300
400
500
600
700
800
900
1000
It took 867 secs to run unifrac.weighted.

Output File Names: 
/Users/sarahwestcott/desktop/release/stability.tre1.weighted.phylip.dist
/Users/sarahwestcott/desktop/release/stability.tre1.wsummary
/Users/sarahwestcott/desktop/release/stability.tre1.weighted.ave.dist
/Users/sarahwestcott/desktop/release/stability.tre1.weighted.std.dist


mothur > unifrac.unweighted(tree=stability.tre, count=stability.count_table, distance=lt, subsample=t)
Unable to open stability.tre. Trying default /Users/sarahwestcott/desktop/release/stability.tre.
Unable to open stability.count_table. Trying default /Users/sarahwestcott/desktop/release/stability.count_table.

Using 4 processors.

Setting subsample size to 2403.

Tree#	Groups	UWScore	
100
200
300
400
500
600
700
800
900
1000
It took 194 secs to run the subsampling.
1	F3D0-F3D1	0.4378
1	F3D0-F3D141	0.47794
1	F3D1-F3D141	0.508599
1	F3D0-F3D142	0.522537
1	F3D1-F3D142	0.556485
1	F3D141-F3D142	0.432727
1	F3D0-F3D143	0.536671
1	F3D1-F3D143	0.554363
1	F3D141-F3D143	0.396751
1	F3D142-F3D143	0.452508
1	F3D0-F3D144	0.530997
1	F3D1-F3D144	0.530634
1	F3D141-F3D144	0.435056
1	F3D142-F3D144	0.479848
1	F3D143-F3D144	0.434843
1	F3D0-F3D145	0.514827
1	F3D1-F3D145	0.5414
1	F3D141-F3D145	0.439181
1	F3D142-F3D145	0.442842
1	F3D143-F3D145	0.420091
1	F3D144-F3D145	0.43211
1	F3D0-F3D146	0.453431
1	F3D1-F3D146	0.477793
1	F3D141-F3D146	0.40862
1	F3D142-F3D146	0.454032
1	F3D143-F3D146	0.462633
1	F3D144-F3D146	0.46499
1	F3D145-F3D146	0.466134
1	F3D0-F3D147	0.511408
1	F3D1-F3D147	0.552248
1	F3D141-F3D147	0.473235
1	F3D142-F3D147	0.506449
1	F3D143-F3D147	0.525228
1	F3D144-F3D147	0.472186
1	F3D145-F3D147	0.477773
1	F3D146-F3D147	0.463608
1	F3D0-F3D148	0.48214
1	F3D1-F3D148	0.520645
1	F3D141-F3D148	0.418922
1	F3D142-F3D148	0.482475
1	F3D143-F3D148	0.462333
1	F3D144-F3D148	0.434935
1	F3D145-F3D148	0.438105
1	F3D146-F3D148	0.426903
1	F3D147-F3D148	0.42771
1	F3D0-F3D149	0.446356
1	F3D1-F3D149	0.493441
1	F3D141-F3D149	0.413315
1	F3D142-F3D149	0.492718
1	F3D143-F3D149	0.460777
1	F3D144-F3D149	0.440693
1	F3D145-F3D149	0.454599
1	F3D146-F3D149	0.414424
1	F3D147-F3D149	0.43291
1	F3D148-F3D149	0.389184
1	F3D0-F3D150	0.459564
1	F3D1-F3D150	0.494857
1	F3D141-F3D150	0.395358
1	F3D142-F3D150	0.460636
1	F3D143-F3D150	0.430414
1	F3D144-F3D150	0.418288
1	F3D145-F3D150	0.413666
1	F3D146-F3D150	0.392385
1	F3D147-F3D150	0.439885
1	F3D148-F3D150	0.378785
1	F3D149-F3D150	0.359884
1	F3D0-F3D2	0.381686
1	F3D1-F3D2	0.417041
1	F3D141-F3D2	0.48705
1	F3D142-F3D2	0.545596
1	F3D143-F3D2	0.538245
1	F3D144-F3D2	0.52346
1	F3D145-F3D2	0.502066
1	F3D146-F3D2	0.466917
1	F3D147-F3D2	0.503456
1	F3D148-F3D2	0.47391
1	F3D149-F3D2	0.433885
1	F3D150-F3D2	0.447122
1	F3D0-F3D3	0.454379
1	F3D1-F3D3	0.418566
1	F3D141-F3D3	0.485262
1	F3D142-F3D3	0.495639
1	F3D143-F3D3	0.503831
1	F3D144-F3D3	0.524726
1	F3D145-F3D3	0.504467
1	F3D146-F3D3	0.454508
1	F3D147-F3D3	0.531259
1	F3D148-F3D3	0.500506
1	F3D149-F3D3	0.497383
1	F3D150-F3D3	0.493064
1	F3D2-F3D3	0.453728
1	F3D0-F3D5	0.420811
1	F3D1-F3D5	0.383717
1	F3D141-F3D5	0.471701
1	F3D142-F3D5	0.506356
1	F3D143-F3D5	0.491654
1	F3D144-F3D5	0.484267
1	F3D145-F3D5	0.478985
1	F3D146-F3D5	0.421982
1	F3D147-F3D5	0.520466
1	F3D148-F3D5	0.479495
1	F3D149-F3D5	0.463891
1	F3D150-F3D5	0.434459
1	F3D2-F3D5	0.410328
1	F3D3-F3D5	0.39477
1	F3D0-F3D6	0.435009
1	F3D1-F3D6	0.418392
1	F3D141-F3D6	0.480827
1	F3D142-F3D6	0.518946
1	F3D143-F3D6	0.506354
1	F3D144-F3D6	0.512764
1	F3D145-F3D6	0.498321
1	F3D146-F3D6	0.434796
1	F3D147-F3D6	0.509362
1	F3D148-F3D6	0.47445
1	F3D149-F3D6	0.439264
1	F3D150-F3D6	0.443073
1	F3D2-F3D6	0.416856
1	F3D3-F3D6	0.418466
1	F3D5-F3D6	0.368711
1	F3D0-F3D7	0.460878
1	F3D1-F3D7	0.418561
1	F3D141-F3D7	0.474727
1	F3D142-F3D7	0.483523
1	F3D143-F3D7	0.492544
1	F3D144-F3D7	0.511802
1	F3D145-F3D7	0.51178
1	F3D146-F3D7	0.443955
1	F3D147-F3D7	0.517598
1	F3D148-F3D7	0.487128
1	F3D149-F3D7	0.486623
1	F3D150-F3D7	0.476594
1	F3D2-F3D7	0.450438
1	F3D3-F3D7	0.365393
1	F3D5-F3D7	0.360322
1	F3D6-F3D7	0.390441
1	F3D0-F3D8	0.391218
1	F3D1-F3D8	0.40356
1	F3D141-F3D8	0.459619
1	F3D142-F3D8	0.495012
1	F3D143-F3D8	0.489482
1	F3D144-F3D8	0.488779
1	F3D145-F3D8	0.502032
1	F3D146-F3D8	0.407165
1	F3D147-F3D8	0.483335
1	F3D148-F3D8	0.460151
1	F3D149-F3D8	0.440662
1	F3D150-F3D8	0.447832
1	F3D2-F3D8	0.411523
1	F3D3-F3D8	0.42257
1	F3D5-F3D8	0.346104
1	F3D6-F3D8	0.355498
1	F3D7-F3D8	0.35147
1	F3D0-F3D9	0.40509
1	F3D1-F3D9	0.409142
1	F3D141-F3D9	0.462245
1	F3D142-F3D9	0.512039
1	F3D143-F3D9	0.507071
1	F3D144-F3D9	0.494261
1	F3D145-F3D9	0.497332
1	F3D146-F3D9	0.420793
1	F3D147-F3D9	0.507216
1	F3D148-F3D9	0.473178
1	F3D149-F3D9	0.444396
1	F3D150-F3D9	0.453555
1	F3D2-F3D9	0.414732
1	F3D3-F3D9	0.421233
1	F3D5-F3D9	0.350358
1	F3D6-F3D9	0.307649
1	F3D7-F3D9	0.358718
1	F3D8-F3D9	0.304468
It took 194 secs to run unifrac.unweighted.

Output File Names: 
/Users/sarahwestcott/desktop/release/stability.uwsummary
/Users/sarahwestcott/desktop/release/stability.1.unweighted.ave.dist
/Users/sarahwestcott/desktop/release/stability.1.unweighted.std.dist
/Users/sarahwestcott/desktop/release/stability.tre1.unweighted.phylip.dist


mothur > quit()

**Comment by akunln** [comment]
Hello,

I will run it again over the weekend to see if only takes extra time. Would it be possible to use a tree based on representative sequences (get.oturep) as input for unifrac.unweighted and unifrac.weighted? This would speedup dist.seqs and clearcut (while creating the tree) and maybe unifrac. That was how  it was done in qiime1 but I am not sure if it would work the same way in mothur (I basically followed the MiSeq SOP).

Thanks for your help.

**Comment by mothur-westcott** [comment]
@pschloss, your thoughts?

**Comment by akunln** [comment]
The issue can be closed. After changing the number iteration to 1 (iters=1) it did complete. Took 1826 seconds (compared to the 13 seconds unifrac.unweighted).
