### ISSUE TITLE
[ERROR]: File mismatch detected, quitting command: for summary.seqs of fasta and count files.

### ISSUE THREAD

**Issue by cmaggior** [mothur/mothur#606]
Hello,

I'm receiving the following error message during the summary.seqs command to see where my alignment is occurring (mothur > summary.seqs(fasta=stability.trim.contigs.good.unique.align, count=stability.trim.contigs.good.count_table): 

[ERROR]: Your count file contains 185071 unique sequences, but your fasta file contains 135745. File mismatch detected, quitting command.

I have tried adjusting the number of processors and am unsure how to proceed. I have also tried using fasta=current,count-current to avoid any typos. Can anyone advise?

Cheers.

**Comment by mothur-westcott** [comment]
Could you post the logfile which shows the commands you ran before the summary.seqs command?

**Comment by cmaggior** [comment]
Attached. Thank you!

[mothur.1556746311.txt](https://github.com/mothur/mothur/files/3139788/mothur.1556746311.txt)
[mothur.1556740068.txt](https://github.com/mothur/mothur/files/3139789/mothur.1556740068.txt)

**Comment by mothur-westcott** [comment]
Could you be running out of disk space to write the align file? If not, could you send the stability.trim.contigs.good.unique.fasta and stability.trim.contigs.good.count_table to mothur.bugs@gmail.com so I can take a closer look?

**Comment by ekwear** [comment]
I'm having a similar issue with summary.seqs in v1.42.3 - both the linux version on a cluster and the mac version on a desktop. When I try to run the command with a name file, it finds a mismatch between the fasta and name files. This has happened when I've run summary.seqs after both precluster and uchime, so it doesn't seem to be an issue in the command directly upstream. Thanks!

E.g., from the logfile:
mothur > summary.seqs(fasta=current,name=current,processors=12)
Using eint_combofile.trim.contigs.good.unique.filter.good.precluster.pick.fasta as input file for the fasta parameter.
Using eint_combofile.trim.contigs.good.good.pick.names as input file for the name parameter.

Using 12 processors.
[ERROR]: Your name file contains 2494972 unique sequences, but your fasta file contains 1341435. File mismatch detected, quitting command.

**Comment by mothur-westcott** [comment]
Is there a specific reason you are using a name file rather than a count file? The name file requires more time and memory to process than the count file. The name file format can become so large that it inhibits the data analysis in some cases.

To resolve this issue, in the latest versions, several of mothur's commands convert name files to count files to save time and space while processing. The pre.cluster command is one of the commands which convert it. Try modifying the summary.seqs command to use the count file instead.

mothur > summary.seqs(fasta=current, count=current)

**Comment by ekwear** [comment]
Unfortunately, in my case it appears to be reporting a true file mismatch. I get the same error if I use the count file in summary.seqs. I can bypass the errors by just summarizing based on a fasta file, but when I do that, I run into file mismatch errors in later commands. 

I've attached the logfiles from a run where this happened - please let me know if I can provide other info. (This pipeline works fine if I go back to version 1.39.5, so some component here is clearly no longer compatible. I may well just need to update what I'm doing, but at this point I can't tell if that's the case or if there's an error somewhere.)

[mothur.1562775900.logfile.txt](https://github.com/mothur/mothur/files/3393545/mothur.1562775900.logfile.txt)


[mothur.1563038069.logfile.cropped.txt](https://github.com/mothur/mothur/files/3393546/mothur.1563038069.logfile.cropped.txt)

**Comment by mothur-westcott** [comment]
Your log file indicates you are running version 1.42.2 not 1.42.3.

Linux version

Using ReadLine,Boost,HDF5
mothur v.1.42.2
Last updated: 6/19/19
by
Patrick D. Schloss
...

Could you try version 1.42.3, https://github.com/mothur/mothur/releases/tag/v.1.42.3?

**Comment by ekwear** [comment]
Sorry about that - it's odd, I'm sure I had downloaded v1.42.3.

Anyway, I see the same file mismatch errors in summary.seqs and make.shared with the newest version (logfiles attached) - at least in the Mac version. I can run this in the Linux version if it'd be helpful but it'll be a few days before I can hop back on the server. Thanks!

[mothur.1563237874.logfile.txt](https://github.com/mothur/mothur/files/3402678/mothur.1563237874.logfile.txt)


[mothur.1563334080.logfile.shortened.txt](https://github.com/mothur/mothur/files/3402691/mothur.1563334080.logfile.shortened.txt)

**Comment by mothur-westcott** [comment]
This is where the mismatch starts:
...
/******************************************/
It took 384 secs to run pre.cluster.

Output File Names: 
**emma_test_combofile.trim.contigs.good.good.count_table**
emma_test_combofile.trim.contigs.good.unique.filter.good.precluster.fasta
emma_test_combofile.trim.contigs.good.unique.filter.good.precluster.count_table
emma_test_combofile.trim.contigs.good.unique.filter.good.precluster.FB_March2019.map
emma_test_combofile.trim.contigs.good.unique.filter.good.precluster.FMP233_9Apr18_05m_02u.map
emma_test_combofile.trim.contigs.good.unique.filter.good.precluster.FMP235_9Apr18_10m_02u.map
emma_test_combofile.trim.contigs.good.unique.filter.good.precluster.FMP237_9Apr18_DCM_02u.map
emma_test_combofile.trim.contigs.good.unique.filter.good.precluster.FMP239_9Apr18_50m_02u.map
emma_test_combofile.trim.contigs.good.unique.filter.good.precluster.FMP241_9Apr18_90m_02u.map
emma_test_combofile.trim.contigs.good.unique.filter.good.precluster.FMP335_6Sept18_05m_02u.map
emma_test_combofile.trim.contigs.good.unique.filter.good.precluster.FMP337_6Sept18_10m_02u.map
emma_test_combofile.trim.contigs.good.unique.filter.good.precluster.FMP339_6Sept18_DCM_02u.map
emma_test_combofile.trim.contigs.good.unique.filter.good.precluster.FMP341_6Sept18_50m_02u.map
emma_test_combofile.trim.contigs.good.unique.filter.good.precluster.FMP343_6Sept18_90m_02u.map
emma_test_combofile.trim.contigs.good.unique.filter.good.precluster.Pos_control_March2019.map


**mothur > chimera.uchime(fasta=current,name=current,group=current,processors=1)**

Using emma_test_combofile.trim.contigs.good.unique.filter.good.precluster.fasta as input file for the fasta parameter.
Using emma_test_combofile.contigs.good.good.groups as input file for the group parameter.
Using emma_test_combofile.trim.contigs.good.good.names as input file for the name parameter.

Using 1 processors.
...

The chimera command and following commands need to use the preclustered count file. The names and groups files were not updated to reflect the merging of representative reads.

mothur > chimera.uchime(fasta=current,count=current,processors=1)
mothur > remove.seqs(fasta=current, accnos=current)
mothur > summary.seqs(count=current)
mothur > classify.seqs(fasta=current,count=current,template=silva.nr_v132.align,taxonomy=silva.nr_v132.tax)
** add remove.lineage command to remove unclassified sequences and contaminants **
mothur > phylotype(taxonomy=current,count=current)
mothur > classify.otu(taxonomy=current,count=current,list=current,cutoff=70,probs=f)
mothur > make.shared(list=current,count=current)

**Comment by ekwear** [comment]
I tried that modification, but it appears that remove.seqs went out looking for the name file anyway, which then led to a mismatch error between the fasta and count files:


[mothur.1563460562.logfile.txt](https://github.com/mothur/mothur/files/3411739/mothur.1563460562.logfile.txt)

**Comment by mothur-westcott** [comment]
The mismatch is occurring because you are removing the chimeras from the fasta file but not the count file.  Because you ran the chimera.uchime command with dereplicate=f (mothur default), mothur assumes if a sequence is chimeric in ANY sample then it should be flagged as chimeric in ALL samples. You then use remove.seqs to remove the chimeras from all files.

You can run the command like this:

mothur > chimera.uchime(fasta=current,count=current,processors=1) - creates accnos file with list of sequences found to be chimeric in ANY sample
mothur > remove.seqs(fasta=current, count=current, accnos=current) - remove chimeras from fasta and count files

or 

mothur > chimera.uchime(fasta=current,count=current,processors=1, dereplicate=t) - create accnos file with list of sequences found to be chimeric in ALL samples, and modify count file  removing chimeras from each sample
mothur > remove.seqs(fasta=current,  accnos=current) - remove sequences from fasta file that were flagged as chimeric by all samples.

but NOT like this:

mothur > chimera.uchime(fasta=current,count=current,processors=1) - creates accnos file with list of sequences found to be chimeric in ANY sample
mothur > remove.seqs(fasta=current, accnos=current) - remove sequences from fasta file that were flagged as chimeric by any sample. Count file not modified.

**Comment by ekwear** [comment]
Thank you, that has fixed the errors nicely. I really appreciate the help - the link between these issues and the updates reported for the version where they started happening was not intuitive to me.

**Comment by Nataliealice1** [comment]
Hello, Im having a similar problem using mothur v.1.42.3 with;

'mothur > summary.seqs(fasta=ion.trim.good.unique.align, count=ion.trim.good.count_table)'
<img width="637" alt="Screenshot 2019-10-10 at 09 55 21" src="https://user-images.githubusercontent.com/56387700/66554215-7bde9900-eb44-11e9-8822-63149bce28dd.png">


Using 4 processors.
[ERROR]: Your count file contains 1569166 unique sequences, but your fasta file contains 1362973. File mismatch detected, quitting command.


Made groups from Fasta files then, code: 

set.dir(output=./Desktop/iont/output2)
set.dir(input=./Desktop/iont/output2)

trim.seqs(fasta=ion.fasta, oligos=ion.oligos.txt)

screen.seqs(fasta=ion.trim.fasta, maxambig=0, maxhomop=8, minlength=300, group=ion.groups)

unique.seqs(fasta=ion.trim.good.fasta)

count.seqs(name=ion.trim.good.names, group=ion.good.groups)

summary.seqs(fasta=ion.trim.good.unique.fasta, count=ion.trim.good.count_table)

align.seqs(fasta=ion.trim.good.unique.fasta, reference=~/Desktop/ion/refDb/silva.nr_v132.align)

summary.seqs(fasta=ion.trim.good.unique.align, count=ion.trim.good.count_table)
