### ISSUE TITLE
Problem for demultiplexing Miseq Paired end reads using make.contigs with oligos file

### ISSUE THREAD

**Issue by tiagobrc** [mothur/mothur#608]
I am having trouble to demultiplex and trim primers and barcodes from a fastq paired-end file.

I have one single pair of fastq file from a paired-end MiSeq run and an oligo file like this:

```
primer	AYTGGGYDTAAAGNG	CCGTCAATTYHTTTRAGT	V4
primer	CCGTCAATTYHTTTRAGT	AYTGGGYDTAAAGNG	V5
BARCODE	ACCTGATCCGCA	ACCTGATCCGCA	NOD_1
BARCODE	GTTGACCATCGC	GTTGACCATCGC	NOD_2
BARCODE	TGACTGCGTTAG	TGACTGCGTTAG	NOD_3
```
I used this command:
make.contigs(file=stability.files, oligos=pool94.oligos,bdiffs=1, processors=8)

However, I get 99.99% of the reads on the scrap file without trimming or any information of each detected sample.
My groups file looks like:

```
M00430_5358_000000000-CCGRN_1_1101_10216_15499	pool94
M00430_5358_000000000-CCGRN_1_1101_10594_20693	pool94
M00430_5358_000000000-CCGRN_1_1101_10676_10175	pool94
M00430_5358_000000000-CCGRN_1_1101_10878_13512	pool94
M00430_5358_000000000-CCGRN_1_1101_11087_21332	pool94
M00430_5358_000000000-CCGRN_1_1101_12496_11697	pool94
M00430_5358_000000000-CCGRN_1_1101_12859_24247	pool94
```

My question is, can mothur detect the barcode and primers anywhere on the read? or is it expecting it to be at the beginning of the read?

My Reads look like this:
The first match is the bc and the second the primer:
https://ibb.co/5cyYD4G

Thanks for your attention.

Can someone clarify it to me?

**Comment by mothur-westcott** [comment]
Have you tried running make.contigs with bdiffs=1, pdiffs=2?

"can mothur detect the barcode and primers anywhere on the read? or is it expecting it to be at the beginning of the read?"

The make.contigs command expects the barcodes and primers to be at the ends of the reads. The pcr.seqs command will scan the read and trim to the primer anywhere in the read.  https://www.mothur.org/wiki/Pcr.seqs https://www.mothur.org/wiki/Make.contigs

**Comment by tiagobrc** [comment]
Thanks for the suggestions. As the number of reads preceding the bc is highly variable I had to use another demultiplexer capable of dealing with it. But good to know about pcr.seqs.
