### ISSUE TITLE
Segmentation fault (core dumped)_Cluster.split_v1.42.0&v1.41.3

### ISSUE THREAD

**Issue by qadsx** [mothur/mothur#609]
Hi,
I am keeping having the Segmentation fault (core dumped) issue when trying to run cluster.split with the v1.42.0 and v1.41.3.
This usually happened after at the end the clustering stage. 

Could you please kindly suggest the possible cause and solution? Thanks so much!

Regards,
Xiang Shi

**Comment by mothur-westcott** [comment]
Have you tried running it with the runsensspec parameter set to false?
