### ISSUE TITLE
make.file v1.42.0 is missing directory

### ISSUE THREAD

**Issue by caroline-u** [mothur/mothur#610]
Hi,
I've just changed to mothur's newest released version 1.42.0 and encountered a problem with the make.file command. The test.files looks now like this:

CCG10	CCG10_R1.fastq	CCG10_R2.fastq	
CCG1	CCG1_R1.fastq	CCG1_R2.fastq	
CCG2	CCG2_R1.fastq	CCG2_R2.fastq	
CCG3	CCG3_R1.fastq	CCG3_R2.fastq	
CCG4	CCG4_R1.fastq	CCG4_R2.fastq	
...

Formerly (I used version 1.39.5) the file looked like this:

CCG10	/directory-x/folder-y/fastqfiles/CCG10_R1.fastq		/directory-x/folder-y/fastqfiles/CCG10_R2.fastq	
CCG1	/directory-x/folder-y/fastqfiles/CCG1_R1.fastq		/directory-x/folder-y/fastqfiles/CCG1_R2.fastq	
CCG2	/directory-x/folder-y/fastqfiles/CCG2_R1.fastq		/directory-x/folder-y/fastqfiles/CCG2_R2.fastq	
CCG3	/directory-x/folder-y/fastqfiles/CCG3_R1.fastq		/directory-x/folder-y/fastqfiles/CCG3_R2.fastq	
CCG4	/directory-x/folder-y/fastqfiles/CCG4_R1.fastq		/directory-x/folder-y/fastqfiles/CCG4_R2.fastq	
...
For both files I used exactly the same command:
`make.file(inputdir=/directory-x/folder-y/fastqfiles, type=fastq, prefix=test)`

Since the upper test.files (v1.42.0) is lacking the directory, during the next step (`make.contigs`) mothur cannot find my fastq files since they are stored in a separate folder (fastqfiles). 

Is this a bug in the newly released version or am I missing something? 

Many thanks in advance!
Caro

**Comment by mothur-westcott** [comment]
We modified the make.file command to remove the path so that if you move your fastq files you don't need to rerun the make.file command. To indicate to mothur where the fastq files are located try this:

mothur > make.contigs(inputdir=/directory-x/folder-y/fastqfiles/, file=test.files)

**Comment by caroline-u** [comment]
Ah ok, good to know that. With your suggestion (include inputdir into make.contigs) my batchscript is working again. Thank you!
