### ISSUE TITLE
remove.seqs  v1.42.0 [ERROR]: NOT is not in your count table

### ISSUE THREAD

**Issue by caroline-u** [mothur/mothur#612]
Hi,
in order to remove unaligned sequences after alignment with Silva, I've used previously (v1.39.5) the following commands, which worked perfectly:

`align.seqs(reference=xxx/BatchMode/references/silva.v34_v132.fasta, flip=t)
remove.seqs(accnos=Test.trim.contigs.good.unique.flip.accnos, count=current)`

Fyi, the accnos file (Test.trim.contigs.good.unique.flip.accnos) looks like this:
> XXX_1   reverse complement did NOT produce a better alignment so it was not used, please check sequence.
> XXX_2	reverse complement produced a better alignment, so mothur used the reverse complement.

Using v1.42.0, my files (accnos & count) still look the same, but I get the following error message:
> [ERROR]: NOT is not in your count table. Please correct.

I get the same error message, when I use the accnos and count file produced with version 1.39.5.

Can you help me how to solve this error message?

Thanks & best,
Caro

**Comment by mothur-westcott** [comment]
The accnos file used to remove and select sequences is a single column, containing either sequence names or OTU labels. The file created by align.seqs is not meant to be used to remove unwanted reads, but rather as report of the poor alignments. The reads included in the *.flip.accnos file will likely be remove in the screening process.

**Comment by caroline-u** [comment]
Ok, I was used to remove the poorly aligned sequences (usually +- 100 out of approximately 100.000-1.000.000 reads) immediately after that step, but I've changed my pipeline now accordingly.
