### ISSUE TITLE
error: reference to 'thread' is ambiguous

### ISSUE THREAD

**Issue by yurivict** [mothur/mothur#613]
Fails to build on FreeBSD 12 with clang-8:

```
source/summary.cpp:351:16: error: reference to 'thread' is ambiguous
        vector<thread*> workerThreads;
               ^
/usr/include/sys/sysctl.h:45:8: note: candidate found by name lookup is 'thread'
struct thread;
       ^
/usr/include/c++/v1/thread:285:24: note: candidate found by name lookup is 'std::__1::thread'
class _LIBCPP_TYPE_VIS thread
                       ^
```

**Comment by mothur-westcott** [comment]
We haven't built for FreeBSD specifically, but it looks like the compiler is not sure which thread class mothur is looking for. We indicate that the namespace is standard in mothur.h, but I went ahead and changed the thread* references within mothur to std::thread*. Could you try pulling the master branch and rebuilding to see if it resolves your issue?

**Comment by yurivict** [comment]
1.42.1-2-gabaf6f64 still has the problem.

**Comment by yurivict** [comment]
```new thread``` should be replaced with ```new std::thread``` - this solves the problem.

**Comment by mothur-westcott** [comment]
Thanks, I will update the source

**Comment by yurivict** [comment]
Thanks for fixing this.
