### ISSUE TITLE
Result file of make.biom is not available as a phinch input file.

### ISSUE THREAD

**Issue by stritttt** [mothur/mothur#619]
I created a biom file using the script below.
make.biom(shared=stability.opti_mcc.0.03.subsample.shared, constaxonomy=stability.pick.taxonomy)

Shared file is the result file of sub.sample script,
Taxonomy file is the result file using lis.otulabels and get.otus scripts.
make.biom not working with subsampled shared file
We referenced this and created a taxonomy file. #617 

However, the resulting file does not act as a phinch input. (stability.opti_mcc.0.03.subsample.0.03.biom)
How should i fix it?

**Comment by mothur-westcott** [comment]
Is the make.biom command still failing with matching constaxonomy and shared files?

Or is this a phinch issue? If so, have you followed up with them about the problem? 

If you send your input files and log file to mothur.bugs@gmail.com, I can take a closer look.
