### ISSUE TITLE
issue with launching mothur using mothur AMI

### ISSUE THREAD

**Issue by cfortunato82** [mothur/mothur#622]
Hi again,

I just created a new AWS instance for the latest version of mothur but now when I try to start up mothur I get the following message:

mothur: error while loading shared libraries: libreadline.so.6: cannot open shared object file: No such file or directory

Some searching lead me to support page about fixing the readlines etc. (https://www.mothur.org/wiki/How_to_Resolve_Readline_Issues) But I'm not sure how to resolve this via a AWS instance... I'm new to the cloud computing world, so any help is appreciated.

Caroline

**Comment by mothur-westcott** [comment]
Have you tried the version without newline, https://github.com/mothur/mothur/releases/tag/v1.42.1?

**Comment by cfortunato82** [comment]
I did see this was released, but its not a selectable option for an AMI. I am just try running an older version for now
