### ISSUE TITLE
pre.cluster crashes (?)

### ISSUE THREAD

**Issue by JoseBebeMedalla** [mothur/mothur#623]
![ss logfile](https://user-images.githubusercontent.com/34691535/58807397-fec77400-85e5-11e9-9c5b-58ea43d51f14.png)
 Hi! I am going over the Mothur 16S pipeline and everything is going okay so far. However, when I run the pre.cluster command it seems to crash. It ends in like 5-10 minutes, produces 3 empty files (fasta, temp, count_table), and closes Mothur. Any idea?

**Comment by JoseBebeMedalla** [comment]
![image](https://user-images.githubusercontent.com/34691535/58807864-e441ca80-85e6-11e9-8852-72b6b1bc9fc7.png)
these are the commands I ran prior to pre.seqs

**Comment by mothur-westcott** [comment]
Do your group names contain "-" characters?

**Comment by JoseBebeMedalla** [comment]
yes, do you think that is it?; what do you recommend I used instead of "-"?

**Comment by mothur-westcott** [comment]
Yes, the dash character is causing the issue. "-" is a special character used in mothur to separate sample names and distance labels. When mothur tries to split the data by sample it is confusing the dash in the sample name with a delimiter between sample names.  I recommend changing "-" to "_".
