### ISSUE TITLE
Additional tabs inserted after accesion number (screen.seqs and pcr.seqs)

### ISSUE THREAD

**Issue by mkorlevic** [mothur/mothur#627]
Hi,

I am following the procedure described on the mothur blog (http://blog.mothur.org/2018/01/10/SILVA-v132-reference-files/) with the aim to recreate the mothur compatible reference files for sequence alignment and classification. I noticed a strange difference between mothur versions 1.39.5 and 1.42.1. If'm using v1.39.5 everything works well but with v1.49.1 after running screen.seqs() and pcr.seqs() additional tabs, instead of only one, are appearing after the sequence accession number. In addition, after running for example screen.seqs() one additional tab is appearing, if running afterwards pcr.seqs() on the output of the previous command one more is appearing and if running again pcr.seqs() on the output of the previous command one more is appearing. So, the tabs are aggregating after running each of these two commands on the output of the previous command

Thanks for help!
Kind regards,

Marino

**Comment by mothur-westcott** [comment]
Thanks for reporting this. The sequence class is adding an additional tab between the sequence name and optional comment string when using shared writing. I have removed the additional tab and the change will be part of our next release.
