### ISSUE TITLE
memory leak in mothur command

### ISSUE THREAD

**Issue by conradshyu** [mothur/mothur#632]
mothur 1.42.1 is having some issues with memory leak. For example, the command unique.seqs will crash with a segmentation fault error. Analysis using valgrind (http://www.valgrind.org/) shows that there are apparently several invalid calls to free().

valgrind log:

#unique.seqs(fasta=/mnt/EFS/user_uploads/5e443b0dfd54/outputs/combo.trim.contigs.good.unique.good.filter.fasta, count=/mnt/EFS/user_uploads/5e443b0dfd54/outputs/combo.trim.contigs.good.good.count_table)"
Using /mnt/EFS/user_uploads/5e443b0dfd54/outputs/combo.trim.contigs.good.good.count_table as input file for the count parameter.
Using /mnt/EFS/user_uploads/5e443b0dfd54/outputs/combo.trim.contigs.good.unique.good.filter.fasta as input file for thefasta parameter.{{free(): }}

double free detected in tcache 2

Run the command valgrind to check the memory leak in mothur. Valgrind reports several invalid calls to free(). Memory leak causes the pipeline to fail randomly.

==1396== Invalid free() / delete / delete[] / realloc()
==1396== at 0x4836EAB: operator delete(void*) (vg_replace_malloc.c:576)
==1396== by 0x391BE0: CountTable::printGroupAbunds(std::basic_ofstream<char, std::char_traits<char> >&, int) [clone .cold.441] (in /usr/local/bin/mothur_d/mothur)
==1396== by 0xD40BEA: CountTable::printSeq(std::basic_ofstream<char, std::char_traits<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) (in /usr/local/bin/mothur_d/mothur)
==1396== by 0x91676D: DeconvoluteCommand::execute() (in /usr/local/bin/mothur_d/mothur)
==1396== by 0x51DC06: ScriptEngine::getInput() (in /usr/local/bin/mothur_d/mothur)
==1396== by 0x3BEFE9: main (in /usr/local/bin/mothur_d/mothur)
==1396== Address 0x8598aa0 is 0 bytes inside a block of size 40 free'd
==1396== at 0x4836EAB: operator delete(void*) (vg_replace_malloc.c:576)
==1396== by 0xD3F764: CountTable::printGroupAbunds(std::basic_ofstream<char, std::char_traits<char> >&, int) (in /usr/local/bin/mothur_d/mothur)
==1396== by 0xD40BEA: CountTable::printSeq(std::basic_ofstream<char, std::char_traits<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) (in /usr/local/bin/mothur_d/mothur)
==1396== by 0x91676D: DeconvoluteCommand::execute() (in /usr/local/bin/mothur_d/mothur)
==1396== by 0x51DC06: ScriptEngine::getInput() (in /usr/local/bin/mothur_d/mothur)
==1396== by 0x3BEFE9: main (in /usr/local/bin/mothur_d/mothur)
==1396== Block was alloc'd at
==1396== at 0x4835DEF: operator new(unsigned long) (vg_replace_malloc.c:334)
==1396== by 0x3FB973: std::vector<int, std::allocator<int> >::_M_fill_insert(_gnu_cxx::_normal_iterator<int*, std::vector<int, std::allocator<int> > >, unsigned long, int const&) (in /usr/local/bin/mothur_d/mothur)
==1396== by 0xD3F6B6: CountTable::expandAbunds(int) (in /usr/local/bin/mothur_d/mothur)
==1396== by 0xD3F701: CountTable::printGroupAbunds(std::basic_ofstream<char, std::char_traits<char> >&, int) (in /usr/local/bin/mothur_d/mothur)
==1396== by 0xD40BEA: CountTable::printSeq(std::basic_ofstream<char, std::char_traits<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) (in /usr/local/bin/mothur_d/mothur)
==1396== by 0x91676D: DeconvoluteCommand::execute() (in /usr/local/bin/mothur_d/mothur)
==1396== by 0x51DC06: ScriptEngine::getInput() (in /usr/local/bin/mothur_d/mothur)
==1396== by 0x3BEFE9: main (in /usr/local/bin/mothur_d/mothur)
==1396==
==1396== Invalid read of size 8
==1396== at 0x4DB559F: _Unwind_Resume (in /lib/x86_64-linux-gnu/libgcc_s.so.1)
==1396== by 0x391BF1: CountTable::printGroupAbunds(std::basic_ofstream<char, std::char_traits<char> >&, int) [clone .cold.441] (in /usr/local/bin/mothur_d/mothur)
==1396== by 0xD40BEA: CountTable::printSeq(std::basic_ofstream<char, std::char_traits<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) (in /usr/local/bin/mothur_d/mothur)
==1396== by 0x91676D: DeconvoluteCommand::execute() (in /usr/local/bin/mothur_d/mothur)
==1396== by 0x51DC06: ScriptEngine::getInput() (in /usr/local/bin/mothur_d/mothur)
==1396== by 0x3BEFE9: main (in /usr/local/bin/mothur_d/mothur)
==1396== Address 0x1a is not stack'd, malloc'd or (recently) free'd
==1396==
==1396==
==1396== Process terminating with default action of signal 11 (SIGSEGV)
==1396== Access not within mapped region at address 0x1A
==1396== at 0x4DB559F: _Unwind_Resume (in /lib/x86_64-linux-gnu/libgcc_s.so.1)
==1396== by 0x391BF1: CountTable::printGroupAbunds(std::basic_ofstream<char, std::char_traits<char> >&, int) [clone .cold.441] (in /usr/local/bin/mothur_d/mothur)
==1396== by 0xD40BEA: CountTable::printSeq(std::basic_ofstream<char, std::char_traits<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) (in /usr/local/bin/mothur_d/mothur)
==1396== by 0x91676D: DeconvoluteCommand::execute() (in /usr/local/bin/mothur_d/mothur)
==1396== by 0x51DC06: ScriptEngine::getInput() (in /usr/local/bin/mothur_d/mothur)
==1396== by 0x3BEFE9: main (in /usr/local/bin/mothur_d/mothur)
==1396== If you believe this happened as a result of a stack
==1396== overflow in your program's main thread (unlikely but
==1396== possible), you can try to increase the size of the
==1396== main thread stack using the --main-stacksize= flag.
==1396== The main thread stack size used in this run was 8388608.
==1396==
==1396== HEAP SUMMARY:
==1396== in use at exit: 108,129,880 bytes in 613,692 blocks
==1396== total heap usage: 2,903,350 allocs, 2,289,659 frees, 609,855,573 bytes allocated
==1396==
==1396== 43 bytes in 1 blocks are definitely lost in loss record 37 of 263
==1396== at 0x4837D7B: realloc (vg_replace_malloc.c:826)
==1396== by 0x4ECC737: getcwd (getcwd.c:84)
==1396== by 0x495C2E: Utils::getFullPathName(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) (in /usr/local/bin/mothur_d/mothur)
==1396== by 0x49A498: Utils::fileExists(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) (in /usr/local/bin/mothur_d/mothur)
==1396== by 0x49F5D4: Utils::findProgramPath(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) (in /usr/local/bin/mothur_d/mothur)
==1396== by 0x51E5EA: ScriptEngine::ScriptEngine(std::_cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::_cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) (in /usr/local/bin/mothur_d/mothur)
==1396== by 0x3BF0F6: main (in /usr/local/bin/mothur_d/mothur)
==1396==
==1396== LEAK SUMMARY:
==1396== definitely lost: 43 bytes in 1 blocks
==1396== indirectly lost: 0 bytes in 0 blocks
==1396== possibly lost: 0 bytes in 0 blocks
==1396== still reachable: 108,129,837 bytes in 613,691 blocks
==1396== suppressed: 0 bytes in 0 blocks
==1396== Reachable blocks (those to which a pointer was found) are not shown.
==1396== To see them, rerun with: --leak-check=full --show-leak-kinds=all
==1396==
==1396== For counts of detected and suppressed errors, rerun with: -v
==1396== ERROR SUMMARY: 3 errors from 3 contexts (suppressed: 0 from 0)
Segmentation fault

**Comment by mothur-westcott** [comment]
I suspect this is related to the count table bug fixed in version 1.42.2. Could you give it a try, https://github.com/mothur/mothur/releases/tag/v.1.42.2?

**Comment by conradshyu** [comment]
I can confirm that this issue has been resolved. valgrind reported no memory leak.

==3069== LEAK SUMMARY:
==3069==    definitely lost: 0 bytes in 0 blocks
==3069==    indirectly lost: 0 bytes in 0 blocks
==3069==      possibly lost: 0 bytes in 0 blocks
==3069==    still reachable: 24,106 bytes in 454 blocks
==3069==                       of which reachable via heuristic:
==3069==                         stdstring          : 11,034 bytes in 304 blocks
==3069==         suppressed: 0 bytes in 0 blocks
==3069==
==3069== For counts of detected and suppressed errors, rerun with: -v
==3069== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
