### ISSUE TITLE
Cannot compile 1.42.1: error: ‘FALSE’ was not declared in this scope

### ISSUE THREAD

**Issue by fbartusch** [mothur/mothur#633]
I try to compile mothur 1.42.1 for our HPC cluster and get some of these errors:

```
source/calculators/diversityutils.cpp: In member function ‘int DiversityUtils::bessel(double*, int, double, double)’:
source/calculators/diversityutils.cpp:289:20: error: ‘FALSE’ was not declared in this scope
             return FALSE;
                    ^
```

It seems, that the file `source/calculators/diversityutils.cpp` misses a define or something like that. Aftter adding the following lines to `diversityutils.hpp` compilation works.

```
#define TRUE 1
#define FALSE 0
```

Best Regards,
Felix

**Comment by mothur-westcott** [comment]
Thanks for reporting this. It will be fixed in our next release.
