### ISSUE TITLE
Number of OTUs in "shared" file

### ISSUE THREAD

**Issue by cpavloud** [mothur/mothur#637]
Hi!

I am running mothur v.1.42.1, following the MiSeq SOP commands but the number of OTUs I get in the end seems erroneously high: 145074 OTUs (16S rRNA) using 0.03 cut-off. 

Could it be that there is a bug in the code or something?

**Comment by pschloss** [comment]
Hi - Could you post the pipeline you are using with your question to [the forum](https://forum.mothur.org)? It's hard to know what is going on based on the result. Also, please post which region you are sequencing and what technology you are using.

**Comment by cpavloud** [comment]
Ok, I will post it in the forum in a few minutes.
