### ISSUE TITLE
Subsampling error when too many sequences are filtered

### ISSUE THREAD

**Issue by Puumanamana** [mothur/mothur#638]
Hi,

I am running Mothur on a dataset with about 450 samples, and 17399 unique contigs at this stage of the analysis. I subsample using the following command: 
```
sub.sample(persample=true, fasta=all_taxaFilter.fasta, count=all_taxaFilter.count_table, taxonomy= all_taxaFilter.taxonomy, size=1000)
```

A lot of samples are filtered out because of it (but it's okay). And then I get the error:
```
.
.
You have selected a size that is larger than T2_R number of sequences, removing T2_R.
You have selected a size that is larger than Unknown.T0.1 number of sequences, removing Unknown.T0.1.
[ERROR]: You have selected a size that is larger than 162 number of sequences.
The size you selected is too large, skipping fasta file.
```

First, I'm not sure why the error is happening. "162" is the name of a sample. When I count myself, sample "162" has abundance at 1230, so I should not have the error at the first place. Seems like Mothur sees that, but fails when trying to subsample (maybe the error comes from the subsampling part).

What is surprising, is that if I do exactly do the same using the outputs from the previous step of the analysis, it works (and at this point, "162" has an abundance of 1664).

Do you know what could be the issue here?

EDIT: I tried with a previous version 1.41.3 and it seems to work fine.

Thank you for your help!

**Comment by mothur-westcott** [comment]
Are you using version 1.42.3? If so, could you send your input files and log files to mothur.bugs@gmail.com?

**Comment by Puumanamana** [comment]
It works with 1.42.3!
Thanks for the quick fix
