### ISSUE TITLE
Mothur v.1.36.1  - stabililty.files and make.contigs

### ISSUE THREAD

**Issue by cpavloud** [mothur/mothur#639]
Hi!

I am running Mothur v.1.36.1 
My stabililty.files looks like this:

6LOoutA	ERR1906853_1.fastq	ERR1906853_2.fastq	
6LOoutB	ERR1906854_1.fastq	ERR1906854_2.fastq	
6LOoutC	ERR1906855_1.fastq	ERR1906855_2.fastq	
6LOinA	ERR1906856_1.fastq	ERR1906856_2.fastq	
6LOinB	ERR1906857_1.fastq	ERR1906857_2.fastq	
6LOinC	ERR1906858_1.fastq	ERR1906858_2.fastq	
6KalA	ERR1906859_1.fastq	ERR1906859_2.fastq	
6KalB	ERR1906860_1.fastq	ERR1906860_2.fastq

However, when I try to run the make.contigs command, I get a million of warning messages, such as

[WARNING]: name mismatch in forward and reverse fastq file. Ignoring, ERR1906853.60324.
[WARNING]: name mismatch in forward and reverse fastq file. Ignoring, ERR1906853.60326.
[WARNING]: name mismatch in forward and reverse fastq file. Ignoring, ERR1906853.60328.
[WARNING]: name mismatch in forward and reverse fastq file. Ignoring, ERR1906853.60330.
[WARNING]: name mismatch in forward and reverse fastq file. Ignoring, ERR1906853.60332.
[WARNING]: name mismatch in forward and reverse fastq file. Ignoring, ERR1906853.60334.
[WARNING]: name mismatch in forward and reverse fastq file. Ignoring, ERR1906853.60336.
[WARNING]: name mismatch in forward and reverse fastq file. Ignoring, ERR1906853.60338.

So practically the command produces no output...

P.S.: This is the stabililty.files I was using in the Mothur v.1.42.1 and there was no such problem with this command

**Comment by mothur-westcott** [comment]
I recommend using our latest version, 1.42.3 https://github.com/mothur/mothur/releases/tag/v.1.42.3. Version 1.36.1 is from January 2016.

**Comment by cpavloud** [comment]
I have used your latest version but there were other issues with that (#637).
So I thought I could try a previous one and see if it worked.
