### ISSUE TITLE
Segmentation fault: 11

### ISSUE THREAD

**Issue by anusharai** [mothur/mothur#640]
Dear Users,
I am having some problem in processing the reads. 
As I am running the unique.seqs, I am getting segmentation fault 11 and the program is getting closed automatically.
I am using MacBook Airbook with i5, has it do with the processor?
kindly enlighten me about this problem.
Thanking you in advance

**Comment by mothur-westcott** [comment]
What version of mothur are you running? How much memory do you have? What is the size of the fasta file you are using with unique.seqs?

**Comment by anusharai** [comment]
I am running the latest version of the Mothur. 
RAM is 8GB, memory is 126GB.
The size of the file is around 200 MB, and I have around ten samples.
Thank you for your support

**Comment by mothur-westcott** [comment]
Could you send the input files and log files to mothur.bugs@gmail.com so I can track down the issue for you?
