### ISSUE TITLE
Error in chimera.vsearch with v.1.42.3

### ISSUE THREAD

**Issue by Puumanamana** [mothur/mothur#641]
Hi,

I have an error when running `chimera.vsearch()` with the latest version of Mothur (v.1.42.3). However, when I use v.1.41.3, the function runs smoothly.
Here is the output (I replaced long names with `xxx`):

```
mothur > chimera.vsearch(fasta=all_MSA.fasta, count=all_MSA.count_table, dereplicate=t)

Using 24 processors.
Using vsearch version v2.13.3.
Checking sequences from all_MSA.fasta ...

/******************************************/
Running command: split.groups(groups=xxxx,fasta=xxxx,count=xxxx)

Removing group: R101 because all sequences have been removed.

all_MSA.AJS4060.fasta
all_MSA.AJS4060.count_table
all_MSA.AJS4061.fasta
all_MSA.AJS4061.count_table
...
all_MSA.ntc_plate6.fasta
all_MSA.ntc_plate6.count_table

/******************************************/
should never get here, quitting

[1]    20932 segmentation fault (core dumped)  mothur
```

**Comment by mothur-westcott** [comment]
Does your count table contain a empty group? It looks like sample R101 does not contain any sequences, which could be causing the issue. How did you create the all_MSA.count_table file?

**Comment by Puumanamana** [comment]
You're right, R101 was indeed empty. When I removed it, it worked fine
Regarding the input, I generated a fasta and a count_table, ran it through Mothur (`align.seqs`,`filter.seqs`,`screen.seqs`) and then removed chimeras. There were already empty groups to begin with, so I can fix that easily.
However, it could be nice to have here a more helpful message for the error!

Thank you

**Comment by Puumanamana** [comment]
Actually, the empty group comes from the `screen.seqs` that precedes the chimera step. `screen.seqs()` removes both contigs from the sample `R101`, but doesn't remove the group itself.

**Comment by mothur-westcott** [comment]
I agree, mothur should handle this better. I will take a closer look.
