### ISSUE TITLE
Memory leak in pre.cluster command

### ISSUE THREAD

**Issue by conradshyu** [mothur/mothur#643]
valgrind detected memory leak in the pre.cluster command.

==3127== Memcheck, a memory error detector
==3127== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==3127== Using Valgrind-3.13.0 and LibVEX; rerun with -h for copyright info
==3127== Command: ../mothur #pre.cluster(diffs=2,\ fasta=combo.trim.contigs.good.unique.good.filter.unique.fasta,\ count=combo.trim.contigs.good.unique.good.filter.count_table)
==3127== 
==3127== 
==3127== HEAP SUMMARY:
==3127==     in use at exit: 24,386 bytes in 458 blocks
==3127==   total heap usage: 88,462,551 allocs, 88,462,093 frees, 30,851,828,245 bytes allocated
==3127== 
==3127== 24 bytes in 1 blocks are definitely lost in loss record 1 of 458
==3127==    at 0x4C31D2F: realloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==3127==    by 0x611215F: getcwd (getcwd.c:84)
==3127==    by 0x4D52E6: ??? (in /home/shyu/test/mothur)
==3127==    by 0x588CFC: ??? (in /home/shyu/test/mothur)
==3127==    by 0x40AB6D: ??? (in /home/shyu/test/mothur)
==3127==    by 0x6022B96: (below main) (libc-start.c:310)
==3127== 
==3127== 24 bytes in 1 blocks are definitely lost in loss record 2 of 458
==3127==    at 0x4C31D2F: realloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==3127==    by 0x611215F: getcwd (getcwd.c:84)
==3127==    by 0x4D52E6: ??? (in /home/shyu/test/mothur)
==3127==    by 0x59EEE0: ??? (in /home/shyu/test/mothur)
==3127==    by 0x588E00: ??? (in /home/shyu/test/mothur)
==3127==    by 0x40AB6D: ??? (in /home/shyu/test/mothur)
==3127==    by 0x6022B96: (below main) (libc-start.c:310)
...
==3127== LEAK SUMMARY:
==3127==    definitely lost: 48 bytes in 2 blocks
==3127==    indirectly lost: 0 bytes in 0 blocks
==3127==      possibly lost: 0 bytes in 0 blocks
==3127==    still reachable: 24,338 bytes in 456 blocks
==3127==                       of which reachable via heuristic:
==3127==                         stdstring          : 11,266 bytes in 306 blocks
==3127==         suppressed: 0 bytes in 0 blocks
==3127== 
==3127== For counts of detected and suppressed errors, rerun with: -v
==3127== ERROR SUMMARY: 2 errors from 2 contexts (suppressed: 0 from 0)

**Comment by mothur-westcott** [comment]
We corrected in memory leak in our latest version. Are you running version 1.42.3, https://github.com/mothur/mothur/releases/tag/v.1.42.3?

**Comment by conradshyu** [comment]
I was running 1.42.3. I ran the memory check because the AWS instance with 64G of memory ran out of memory on a relatively small dataset.

**Comment by mothur-westcott** [comment]
Modified current file class to make it thread safe. Resolves race conditions crash seen here.
