### ISSUE TITLE
pcr.seqs doesn't recognise my .oligos file 

### ISSUE THREAD

**Issue by onerousbudgie** [mothur/mothur#646]
I’m basically trying to follow this guide: http://blog.mothur.org/2016/07/07/Customization-for-your-region/

I’ve downloaded the 16S sequence for E.coli from NCBI and saved it as a fasta file. Then I created a text document called “Myoligos” that looks like this;

forward ACGCGHNRAACCTTACC
reverse ACGGGCRGTGWGTRCAA

However when I run this:

pcr.seqs(fasta=ecoli.fasta, oligos=Myoligos.oligos)

I get:
Unable to open Myoligos.oligos. Trying default /usr/bin/mothur/Myoligos.oligos
Unable to open /usr/bin/mothur/Myoligos.oligos. Trying mothur’s location /usr/bin/mothurMyoligos.oligos
Unable to open /usr/bin/mothurMyoligos.oligos

Using 1 processors.
[ERROR]: You did not set any options. Please provide an oligos or ecoli file, or set start or end.
[ERROR]: Invalid start value.
[ERROR]: did not complete pcr.seqs.

How do I fix it? What am I doing wrong? I’ve exited mothur then navigated to my files directory then restarted it and tried to use set.dir but they don’t seem to work.

**Comment by mothur-westcott** [comment]
Have you tried specifying the full path to your oligos file? https://mothur.org/wiki/Frequently_asked_questions#Mothur_can.27t_find_my_input_files
