### ISSUE TITLE
low cpu performance of align.seqs in newer versions

### ISSUE THREAD

**Issue by xvazquezc** [mothur/mothur#648]
Hi there,

We have been using mothur v1.39.5 as default in the development of a pipeline for a while. Last week we were doing some testing to allow using more _modern_ versions of mothur, esp. since we found out that the multithreading code was rewrote.

To our surprise, the performance was substantially worse in terms of running time. We figure out that `align.seqs()' was not behaving as expected. In the _old_ mothur v1.39.5 each of the processors in use would be fully used after it is done loading the reference alignment on memory, with ~100% load. With the newer versions, we are lucky when any cpu load gets higher than 25%.

We have tested this on local Ubuntu installations and HPC using CentOS with the same results. Within and outside our pipeline. Some of the `newer` mothur versions tested include v1.42.1, 1.42.3 and master (last week). In all cases, installations were based on conda and/or from source.

This is the command used in all tests:
```
align.seqs(fasta=otureporter.trim.contigs.good.unique.fasta, reference=silva.v132.v4.align, processors=4, flip=T)
```

Any idea what can be behind this?

Thank you in advance,
Xabi

CC: @Prepultrue

**Comment by mothur-westcott** [comment]
Thanks for reporting this issue. We modified the align.seqs command in version 1.40 to allow all threads to share one copy of the reference. The idea was to reduce the memory usage for our users with limited resources who want to use a larger reference file. Unfortunately, this has led to a significant slow down for our high performance users. #647, addresses this problem and will be part of our 1.43.0 release.
