### ISSUE TITLE
Fastq.info modification for PacBio sequences

### ISSUE THREAD

**Issue by mothur-westcott** [mothur/mothur#649]
https://forum.mothur.org/t/fastq-info-with-only-one-read-pacbio/20051

When pacbio=t allow for 2 column file file where first column is the sample name and second column is the file name.

**Comment by krmaas** [comment]
reviving a very old post. Should this option work for nanopore? is there anything about nanopore fastq vs pacbio fastq that needs to be addressed?

**Comment by pschloss** [comment]
Sorry, we've never seen any nanopore data. Is it actually good enough to work with yet?
