### ISSUE TITLE
dist.seqs running for over a week

### ISSUE THREAD

**Issue by rlh13** [mothur/mothur#652]
Hello, I tried running dist.seqs and it hasn't given me an error and the numbers on the screen are still going up so I know it's not frozen but it has been running for over a week. I've attached my workflow thus far with commands and output from mothur. Is there anything that I did incorrectly or that I can do to fix/make this go faster? Please and thank you!
[mothur default workflow for github.docx](https://github.com/mothur/mothur/files/3560209/mothur.default.workflow.for.github.docx)

**Comment by mothur-westcott** [comment]
Modifying the screen.seqs command to ensure good overlap may help. 

summary.seqs(fasta=stability.trim.contigs.good.unique.align, count=stability.trim.contigs.good.count_table)
		Start	End	NBases	Ambigs	Polymer	NumSeqs
Minimum:	0	0	0	0	1	1
2.5%-tile:	2126	3951	274	0	4	167296
25%-tile:	2126	3990	294	0	4	1672959
Median: 	2126	3990	294	0	5	3345917
75%-tile:	2126	3990	294	0	5	5018875
97.5%-tile:	2126	3990	294	3	6	6524538
Maximum:	6691	6691	440	58	220	6691833
Mean:	2132	3990	292	0	4
# of unique seqs:	2375533
total # of seqs:	6691833

mothur > screen.seqs(fasta=stability.trim.contigs.good.unique.align, count=stability.trim.contigs.good.count_table, summary=stability.trim.contigs.good.unique.summary, **start=2126, end=3990**)

The dist.seqs command is calculating distances for ~1.9 million reads. This will take a long time. The number of distances calculated is n*(n-1)/2, where n is the number of unique reads. In your case ~1.8049991e+12.

**Comment by mothur-westcott** [comment]
We are working on a speed improvement to dist.seqs for our next version. You can follow it here, https://github.com/mothur/mothur/issues/653

**Comment by rlh13** [comment]
Ok great, thank you for your help and for the info on upcoming improvements!

**Comment by rlh13** [comment]
Hello, just wanted to update this post and see if you had any other thoughts. I ran screen.seqs again as directed with start=2126, end=3990. # of unique seqs became 1554081 (vs. 2375533) and # of total seqs became 5468522 (vs. 6691833). This hasn't sped up the computing of dist.seqs so I just wanted to check back to see if this would be an expected change in # of unique/total seqs and/or if there is anything else you think would help the situation. Our data set is not remarkably large so, though I understand your explanation above, I'm just confused as to why this would take so long to compute. Thank you for your help!

**Comment by mothur-westcott** [comment]
How many unique reads do you have the dist.seqs command running?

**Comment by rlh13** [comment]
Summary.seqs run directly before dist.seqs shows unique reads at 1,552,265.

**Comment by mothur-westcott** [comment]
Have you read this, http://blog.mothur.org/2014/09/11/Why-such-a-large-distance-matrix/?
