### ISSUE TITLE
remove.groups potential segfault

### ISSUE THREAD

**Issue by Prepultrue** [mothur/mothur#655]
If `i` was originally `0`, `counts[-1].size()` ends up being accessed
https://github.com/mothur/mothur/blob/b91091ef58d38eb5a60619f2574c2b90ac303461/source/datastructures/counttable.cpp#L1463-L1464

Leading to a segfault on attempting to decrement `counts[-1][1073741828].group`.
https://github.com/mothur/mothur/blob/b91091ef58d38eb5a60619f2574c2b90ac303461/source/datastructures/counttable.cpp#L1472

**Comment by mothur-westcott** [comment]
Thanks for reporting this bug. The fix will be part of 1.43.0.
