### ISSUE TITLE
(Segmentation fault) error in get.oturep v.1.42.3

### ISSUE THREAD

**Issue by Esmee73** [mothur/mothur#656]
Hi,

I get an error message when running the get.oturep command with multiple labels in v.1.42.3. 

It runs when I don't set a label ("you did not provide a label, using 0") or when set a single label (i.e., either label=0 or label=0.03), but it does not run when I provide multiple labels (i.e., label=0-0.03).
Then I get this error message:
/mnt/sequencing/scripts/16S.pipeline.sh: line 24: 38872 Segmentation fault     /usr/lib/mothur/1.42.3/mothur-v.1.42.3/mothur /mnt/sequencing/scripts/16S.pipeline.sh/SOP.16S.create.OTU.txt

and for label=0.01-0.03 I get this:
mothur > get.oturep(column=final.pick.Bacteria.dist, count=final.pick.Bacteria.count_table, list=final.pick.Bacteria.opti_mcc.list, fasta=final.pick.Bacteria.fasta, label=0.01-0.03)
[ERROR]: basic_string::_S_createRAM used: 0.754128Gigabytes . Total Ram: 31.3648Gigabytes.
has occured in the GetOTURepCommand class function execute.

Any idea how this may come?

Many thanks,
Esmee

**Comment by mothur-westcott** [comment]
Thanks for reporting this issue. When we modified the get.oturep command to use OptiMatrix (our lighter and faster distance matrix method) we did not remove the label parameter. The OptiMatrix ignores all distances above the cutoff, so multiple labels require reading the distance matrix multiple times. I will fix the issue and the change will be part of our 1.43.0 release, coming soon.
