### ISSUE TITLE
pcr.seqs removes remove the specific primer sequences from the reads

### ISSUE THREAD

**Issue by shkarimi** [mothur/mothur#662]
Does Mothur pipeline remove the specific primer sequences from the reads?

**Comment by mothur-westcott** [comment]
The mothur program is flexible and does not have default primers it removes. Several of mothur's commands will remove barcodes and primers from sequences. They include: make.contigs, trim.seqs and pcr.seqs.  Mothur allows you to indicate the barcodes or primers you would like to target using the oligos file, https://www.mothur.org/wiki/Oligos_File.  For example in Pat's example analysis (MiSeq_SOP http://www.mothur.org/wiki/MiSeq_SOP) the pcr.seqs command is used to create a custom alignment reference for the v4 region.
