### ISSUE TITLE
fileList.temp is blank. Unable to find any fastq files in your directory

### ISSUE THREAD

**Issue by stanleyhchen** [mothur/mothur#664]
Hi,

I'm trying to process my samples using the version 1.42.3. After I set.dir it to sample folder, and make.file, it keeps telling me:

mothur > make.file(inputdir=samples, type=fastq, prefix=stability)

Setting input directory to: samples\
find: '': No such file or directory
find: 'samples*.fastq': No such file or directory
[ERROR]: samples\fileList.temp is blank. Please correct.
[WARNING]: Unable to find any fastq files in your directory.

Output File Names:

Could anyone help me with it please? Thank you!

**Comment by mothur-westcott** [comment]
Does adding the path to the samples directory help? What is the full path to the samples directory?

mothur > make.file(inputdir=.\samples, type=fastq, prefix=stability)
