### ISSUE TITLE
UniFrac speed improvement

### ISSUE THREAD

**Issue by Puumanamana** [mothur/mothur#666]
Hi,

I have been using mothur's implementation of UniFrac on a few datasets (both `unifrac.weighted()` and `unifrac.unweighted()`) and in general, it runs in less than an hour (on 60 threads). However, these datasets were in general pretty small, maybe a few thousands of ESVs. Lately, I have been trying to run it on a bigger dataset with about 40k unique ESVs, and it has been running for days. 

So I was wondering which version of UniFrac was implemented in Mothur. In particular, I came across [this paper](https://www.nature.com/articles/ismej200997#Sec2), which seems to run much faster. Would it be possible to include this as an option?

**Comment by pschloss** [comment]
Hi,

We don't implement the fast unifrac algorithm. THat is based on a reference based mapping, which we've shown does not perform well. Frankly, we have yet to find a situation where UniFrac does anything different from what we see using beta diversity metrics with OTU-based data. I'm not sure why anyone would use UniFrac at this point.

Pat
