### ISSUE TITLE
Primers not removed

### ISSUE THREAD

**Issue by koopkaup** [mothur/mothur#667]
Paired primers were not removed from sequences using the trim.seqs command. My oligos file is like this:
primer GTGYCAGCMGCCGCGGTAA AGTCAGCCAGCCGYCAATTYMTTTRAGTTT
barcode AACCGT  AACACC  Sample1
barcode AACCGT  AACTGG  Sample2
barcode AACCGT  CGTTAG  Sample3
etc.
mothur version 1.42.1

**Comment by mothur-westcott** [comment]
Could you send your log file and input files to mothur.bugs@gmail.com so I can take a closer look for you?

**Comment by mothur-westcott** [comment]
Thank you for reporting this issue and sending me your files. I have fixed the issue and the change is included in our 1.43.0 beta version. You can download it here, https://github.com/mothur/mothur/releases/tag/v1.43.0.
