### ISSUE TITLE
fasta and count_table file mismatch following pre.cluster in v. 1.42.3

### ISSUE THREAD

**Issue by carlarosenfeld** [mothur/mothur#668]
Hello, 
I have been trying to process an ITS dataset using mothur v. 1.42.3 - after performing pre.cluster the count_table file seems to be off - in both summary.seqs and chimera.vsearch I receieved the following error: 
[ERROR]: Your count table contains a sequence named Representative_Sequence with a total=0. Please correct.
I've tried to include the input files and
logfile for both the pre.cluster and summary.seqs commands (they were run in separate sessions), but they are too big to upload (summary.seqs logfile output pasted below). Please let me know if you have any suggestions for how to move forward?
Thanks very much!
carla

**summary.seqs logfile output** (this was run in mothur v. 1.39 because the vsearch release I had available on my cluster was not compatible with newer mothur releases)
  
mothur v.1.39.0
Last updated: 1/23/2017

by
Patrick D. Schloss

Department of Microbiology & Immunology
University of Michigan
http://www.mothur.org

When using, please cite:
Schloss, P.D., et al., Introducing mothur: Open-source, platform-independent, community-supported software for describing and comparing microbial communities. Appl Environ Microbiol, 2009. 75(23):7537-41.

Distributed under the GNU General Public License

Type 'help()' for information on the commands that are available

For questions and analysis support, please visit our forum at https://www.mothur.org/forum

Type 'quit()' to exit program

mothur > set.dir(input=~/herndon/ITS/, output=~/herndon/ITS/)
Mothur's directories:
outputDir=/home/santelli/carlar/herndon/ITS/
inputDir=/home/santelli/carlar/herndon/ITS/

mothur > summary.seqs(count=herndon_SL_2019_ITStrim.contigs.good.unique.precluster.count_table, fasta=herndon_SL_2019_ITStrim.contigs.good.unique.precluster.fasta)

Using 1 processors.
[ERROR]: Your count table contains a sequence named Representative_Sequence with a total=0. Please correct.

**pre.cluster logfile output:** 
Linux version

Using ReadLine,Boost
mothur v.1.42.3
Last updated: 09/30/2019
by
Patrick D. Schloss

Department of Microbiology & Immunology

University of Michigan
http://www.mothur.org

When using, please cite:
Schloss, P.D., et al., Introducing mothur: Open-source, platform-independent, community-supported software for describing and comparing microbial communities. Appl Environ Microbiol, 2009. 75(23):7537-41.

Distributed under the GNU General Public License

Type 'help()' for information on the commands that are available

For questions and analysis support, please visit our forum at https://forum.mothur.org

Type 'quit()' to exit program

[NOTE]: Setting random seed to 19760620.

Batch Mode

mothur > set.dir(input=/home/santelli/carlar/herndon/ITS, output=/home/santelli/carlar/herndon/ITS)
Mothur's directories:
outputDir=/home/santelli/carlar/herndon/ITS/
inputDir=/home/santelli/carlar/herndon/ITS/

mothur > pre.cluster(fasta=herndon_SL_2019_ITStrim.contigs.good.unique.fasta, name=herndon_SL_2019_ITStrim.contigs.good.names, group=herndon_SL_2019_ITScontigs.good.groups, diffs=2, processors=120)

Using 120 processors.
Reducing processors to 63.

/******************************************/
Running command: get.seqs(fasta=/home/santelli/carlar/herndon/ITS/herndon_SL_2019_ITStrim.contigs.good.unique.fasta, accnos=/home/santelli/carlar/herndon/ITS/herndon_SL_2019_ITStrim.contigs.good.unique.precluster.count_table.temp)
Selected 577418 sequences from your fasta file.

Output File Names: 
/home/santelli/carlar/herndon/ITS/herndon_SL_2019_ITStrim.contigs.good.unique.pick.fasta

/******************************************/
It took 18230 secs to run pre.cluster.

Output File Names: 
/home/santelli/carlar/herndon/ITS/herndon_SL_2019_ITStrim.contigs.good.count_table
/home/santelli/carlar/herndon/ITS/herndon_SL_2019_ITStrim.contigs.good.unique.precluster.fasta
/home/santelli/carlar/herndon/ITS/herndon_SL_2019_ITStrim.contigs.good.unique.precluster.count_table
/home/santelli/carlar/herndon/ITS/herndon_SL_2019_ITStrim.contigs.good.unique.precluster.2019neg1.map
/home/santelli/carlar/herndon/ITS/herndon_SL_2019_ITStrim.contigs.good.unique.precluster.2019neg2.map
/home/santelli/carlar/herndon/ITS/herndon_SL_2019_ITStrim.contigs.good.unique.precluster.CP1.map
/home/santelli/carlar/herndon/ITS/herndon_SL_2019_ITStrim.contigs.good.unique.precluster.CP10.map
/home/santelli/carlar/herndon/ITS/herndon_SL_2019_ITStrim.contigs.good.unique.precluster.CP2.map
/home/santelli/carlar/herndon/ITS/herndon_SL_2019_ITStrim.contigs.good.unique.precluster.CP3.map
/home/santelli/carlar/herndon/ITS/herndon_SL_2019_ITStrim.contigs.good.unique.precluster.CP4.map
/home/santelli/carlar/herndon/ITS/herndon_SL_2019_ITStrim.contigs.good.unique.precluster.CP5.map
/home/santelli/carlar/herndon/ITS/herndon_SL_2019_ITStrim.contigs.good.unique.precluster.CP6.map
/home/santelli/carlar/herndon/ITS/herndon_SL_2019_ITStrim.contigs.good.unique.precluster.CP7.map
/home/santelli/carlar/herndon/ITS/herndon_SL_2019_ITStrim.contigs.good.unique.precluster.CP8.map
/home/santelli/carlar/herndon/ITS/herndon_SL_2019_ITStrim.contigs.good.unique.precluster.CP9.map
/home/santelli/carlar/herndon/ITS/herndon_SL_2019_ITStrim.contigs.good.unique.precluster.CS1.map
/home/santelli/carlar/herndon/ITS/herndon_SL_2019_ITStrim.contigs.good.unique.precluster.CS2.map
/home/santelli/carlar/herndon/ITS/herndon_SL_2019_ITStrim.contigs.good.unique.precluster.CS3.map
/home/santelli/carlar/herndon/ITS/herndon_SL_2019_ITStrim.contigs.good.unique.precluster.CS4.map
/home/santelli/carlar/herndon/ITS/herndon_SL_2019_ITStrim.contigs.good.unique.precluster.CS5.map
/home/santelli/carlar/herndon/ITS/herndon_SL_2019_ITStrim.contigs.good.unique.precluster.DMP1.map
/home/santelli/carlar/herndon/ITS/herndon_SL_2019_ITStrim.contigs.good.unique.precluster.DMP10.map
/home/santelli/carlar/herndon/ITS/herndon_SL_2019_ITStrim.contigs.good.unique.precluster.DMP2.map
/home/santelli/carlar/herndon/ITS/herndon_SL_2019_ITStrim.contigs.good.unique.precluster.DMP3.map
/home/santelli/carlar/herndon/ITS/herndon_SL_2019_ITStrim.contigs.good.unique.precluster.DMP4.map
/home/santelli/carlar/herndon/ITS/herndon_SL_2019_ITStrim.contigs.good.unique.precluster.DMP5.map
/home/santelli/carlar/herndon/ITS/herndon_SL_2019_ITStrim.contigs.good.unique.precluster.DMP6.map
/home/santelli/carlar/herndon/ITS/herndon_SL_2019_ITStrim.contigs.good.unique.precluster.DMP7.map
/home/santelli/carlar/herndon/ITS/herndon_SL_2019_ITStrim.contigs.good.unique.precluster.DMP8.map
/home/santelli/carlar/herndon/ITS/herndon_SL_2019_ITStrim.contigs.good.unique.precluster.DMP9.map
/home/santelli/carlar/herndon/ITS/herndon_SL_2019_ITStrim.contigs.good.unique.precluster.DMS1.map
/home/santelli/carlar/herndon/ITS/herndon_SL_2019_ITStrim.contigs.good.unique.precluster.DMS2.map
/home/santelli/carlar/herndon/ITS/herndon_SL_2019_ITStrim.contigs.good.unique.precluster.DMS3.map
/home/santelli/carlar/herndon/ITS/herndon_SL_2019_ITStrim.contigs.good.unique.precluster.DMS4.map
/home/santelli/carlar/herndon/ITS/herndon_SL_2019_ITStrim.contigs.good.unique.precluster.DMS5.map
/home/santelli/carlar/herndon/ITS/herndon_SL_2019_ITStrim.contigs.good.unique.precluster.MOP1.map
/home/santelli/carlar/herndon/ITS/herndon_SL_2019_ITStrim.contigs.good.unique.precluster.MOP10.map
/home/santelli/carlar/herndon/ITS/herndon_SL_2019_ITStrim.contigs.good.unique.precluster.MOP2.map
/home/santelli/carlar/herndon/ITS/herndon_SL_2019_ITStrim.contigs.good.unique.precluster.MOP3.map
/home/santelli/carlar/herndon/ITS/herndon_SL_2019_ITStrim.contigs.good.unique.precluster.MOP4.map
/home/santelli/carlar/herndon/ITS/herndon_SL_2019_ITStrim.contigs.good.unique.precluster.MOP5.map
/home/santelli/carlar/herndon/ITS/herndon_SL_2019_ITStrim.contigs.good.unique.precluster.MOP6.map
/home/santelli/carlar/herndon/ITS/herndon_SL_2019_ITStrim.contigs.good.unique.precluster.MOP7.map
/home/santelli/carlar/herndon/ITS/herndon_SL_2019_ITStrim.contigs.good.unique.precluster.MOP8.map
/home/santelli/carlar/herndon/ITS/herndon_SL_2019_ITStrim.contigs.good.unique.precluster.MOP9.map
/home/santelli/carlar/herndon/ITS/herndon_SL_2019_ITStrim.contigs.good.unique.precluster.MOS1.map
/home/santelli/carlar/herndon/ITS/herndon_SL_2019_ITStrim.contigs.good.unique.precluster.MOS2.map
/home/santelli/carlar/herndon/ITS/herndon_SL_2019_ITStrim.contigs.good.unique.precluster.MOS3.map
/home/santelli/carlar/herndon/ITS/herndon_SL_2019_ITStrim.contigs.good.unique.precluster.MOS4.map
/home/santelli/carlar/herndon/ITS/herndon_SL_2019_ITStrim.contigs.good.unique.precluster.MOS5.map
/home/santelli/carlar/herndon/ITS/herndon_SL_2019_ITStrim.contigs.good.unique.precluster.SLBLANK.map
/home/santelli/carlar/herndon/ITS/herndon_SL_2019_ITStrim.contigs.good.unique.precluster.SP1.map
/home/santelli/carlar/herndon/ITS/herndon_SL_2019_ITStrim.contigs.good.unique.precluster.SP10.map
/home/santelli/carlar/herndon/ITS/herndon_SL_2019_ITStrim.contigs.good.unique.precluster.SP2.map
/home/santelli/carlar/herndon/ITS/herndon_SL_2019_ITStrim.contigs.good.unique.precluster.SP3.map
/home/santelli/carlar/herndon/ITS/herndon_SL_2019_ITStrim.contigs.good.unique.precluster.SP4.map
/home/santelli/carlar/herndon/ITS/herndon_SL_2019_ITStrim.contigs.good.unique.precluster.SP5.map
/home/santelli/carlar/herndon/ITS/herndon_SL_2019_ITStrim.contigs.good.unique.precluster.SP6.map
/home/santelli/carlar/herndon/ITS/herndon_SL_2019_ITStrim.contigs.good.unique.precluster.SP7.map
/home/santelli/carlar/herndon/ITS/herndon_SL_2019_ITStrim.contigs.good.unique.precluster.SP8.map
/home/santelli/carlar/herndon/ITS/herndon_SL_2019_ITStrim.contigs.good.unique.precluster.SP9.map
/home/santelli/carlar/herndon/ITS/herndon_SL_2019_ITStrim.contigs.good.unique.precluster.SS1.map
/home/santelli/carlar/herndon/ITS/herndon_SL_2019_ITStrim.contigs.good.unique.precluster.SS2.map
/home/santelli/carlar/herndon/ITS/herndon_SL_2019_ITStrim.contigs.good.unique.precluster.SS3.map
/home/santelli/carlar/herndon/ITS/herndon_SL_2019_ITStrim.contigs.good.unique.precluster.SS4.map
/home/santelli/carlar/herndon/ITS/herndon_SL_2019_ITStrim.contigs.good.unique.precluster.SS5.map

**Comment by mothur-westcott** [comment]
Could you try it with our beta 1.43.0 version? https://github.com/mothur/mothur/releases/tag/v1.43.0

**Comment by carlarosenfeld** [comment]
I actually was able to get the cluster to update vsearch and run chimera.vsearch in v. 1.42.3, and it worked!
thanks!
carla
