### ISSUE TITLE
Summary.seqs  - File mismatch detected, quitting command.

### ISSUE THREAD

**Issue by Nataliealice1** [mothur/mothur#669]
My first time using Mothur, so apologies if its obvious but Im getting a mismatch when summarising after alignment. Im using mothur v.1.42.3 I get the message;

'mothur > summary.seqs(fasta=ion.trim.good.unique.align, count=ion.trim.good.count_table)

Using 4 processors.
[ERROR]: Your count file contains 1569166 unique sequences, but your fasta file contains 1362973. File mismatch detected, quitting command."

So far I have made groups from Fasta files then, code:

set.dir(output=./Desktop/iont/output2)
set.dir(input=./Desktop/iont/output2)

trim.seqs(fasta=ion.fasta, oligos=ion.oligos.txt)

screen.seqs(fasta=ion.trim.fasta, maxambig=0, maxhomop=8, minlength=300, group=ion.groups)

unique.seqs(fasta=ion.trim.good.fasta)

count.seqs(name=ion.trim.good.names, group=ion.good.groups)

summary.seqs(fasta=ion.trim.good.unique.fasta, count=ion.trim.good.count_table)

align.seqs(fasta=ion.trim.good.unique.fasta, reference=~/Desktop/ion/refDb/silva.nr_v132.align)

summary.seqs(fasta=ion.trim.good.unique.align, count=ion.trim.good.count_table)

<img width="637" alt="Screenshot 2019-10-10 at 09 55 21" src="https://user-images.githubusercontent.com/56387700/66560995-75eeb500-eb50-11e9-9b55-7660e9457a0b.png">

**Comment by mothur-westcott** [comment]
Welcome to the mothur community! We sometimes this type of error if you run out of disk space to write the aligned file. The alignment files can get rather large, your's is over 68G. If this is not the problem, could you email your log file and input files to mothur.bugs@gmail.com?
