### ISSUE TITLE
Split.groups error

### ISSUE THREAD

**Issue by koopkaup** [mothur/mothur#680]
My command:
`mothur > split.groups(fasta=SE.assembled.trim.fasta, group=SE.assembled.groups)
Processing group: CH12_SE
/******************************************/
Running command: get.seqs(dups=f, accnos=SE.assembled.CH12_SE.groups.accnos, name=CH12_SE, fasta=SE.assembled.trim.fastaCH12_SE)
Unable to open CH12_SE.`

Why is Mothur looking for a namefile? Did it run unique.seqs before get.seqs? However there is no namefile called CH12_SE in my working directory. Using Mothur version 1.43.0

**Comment by mothur-westcott** [comment]
Thanks for reporting this issue. Mothur was assuming if you did not use a count file, then you were running with a name and group file. You should be allowed to run the command with a fasta and group file without the names file. I have corrected this and the change will be part of our next release. In the meantime, you can work around this issue by running:

mothur > unique.seqs(fasta=SE.assembled.trim.fasta)
mothur > split.groups(fasta=current, name=current, group=SE.assembled.groups) 

or

mothur > unique.seqs(fasta=SE.assembled.trim.fasta)
mothur > make.table(name=current, group=SE.assembled.groups) 
mothur > split.groups(fasta=current, count=current)

**Comment by koopkaup** [comment]
Thanks, this way it does work. But the process is extremely slow (one sample takes about half an hour, but I have 133 samples). Is it possible to add multicore support to this?

**Comment by mothur-westcott** [comment]
Are you using the names and groups option or the count file option? We moved to the count table format because as the size of datasets grow the speed difference becomes significant.

**Comment by koopkaup** [comment]
I used count file.

**Comment by mothur-westcott** [comment]
The split.groups command is single core, and this is a good suggestion. I added it to our list, https://github.com/mothur/mothur/issues/685. Right now split.groups is most often run by other multi-core commands in mothur like pre.cluster, chimera.vsearch, chimera.uchime, etc. to divide datasets by sample. Mothur assigns each processor a set of groups. Each thread calls split.groups to extract their assigned samples and processes accordingly. The results are then merged back together by the main process.
