### ISSUE TITLE
make.fastq error

### ISSUE THREAD

**Issue by koopkaup** [mothur/mothur#681]
I got an error when running make.fastq
mothur > make.fastq(fasta=bacteria.trim.fasta, qfile=bacteria.trim.qual, format=illumina1.8+)
[ERROR]: sequence name does not match quality score name. Cannot construct fastq object.

Manual check shows that the files are in sync.
>head -n 1 bacteria.trim.fasta
>M01867_82_000000000-BLCB6_1_2113_15895_15304	fbdiffs=0(match), rbdiffs=0(match) fpdiffs=0(match), rpdiffs=0(match) 	
>head -n 1 bacteria.trim.qual
>M01867_82_000000000-BLCB6_1_2113_15895_15304	0.845863

**Comment by mothur-westcott** [comment]
Could you send your inputs files and log file to mothur.bugs@gmail.com?

**Comment by mothur-westcott** [comment]
Hi Kristjan,  
   Thanks for sending your files. The files you sent to not contain the same sequences in the same order. Mothur can help with this, here's how:

mothur > set.dir(input=/Users/sarahwestcott/Desktop/make.fastq)
Mothur's directories:inputDir=/Users/sarahwestcott/Desktop/make.fastq/

mothur > sort.seqs(fasta=mothur.test.fasta, qfile=mothur.test.qual)
Using /Users/sarahwestcott/Desktop/make.fastq/mothur.test.fasta to determine the order. It contains 500 sequences.
M01867_82_000000000-BLCB6_1_1116_22796_18466 was not in the contained the file which determined the order, adding it to the end.
Ordered 500 sequences from /Users/sarahwestcott/Desktop/make.fastq/mothur.test.qual.

Output File Names: /Users/sarahwestcott/Desktop/make.fastq/mothur.test.sorted.fasta/Users/sarahwestcott/Desktop/make.fastq/mothur.test.sorted.qual

mothur > list.seqs(fasta=current)
Using /Users/sarahwestcott/Desktop/make.fastq/mothur.test.sorted.fasta as input file for the fasta parameter.

Output File Names: /Users/sarahwestcott/Desktop/make.fastq/mothur.test.sorted.accnos

mothur > get.seqs(qfile=current)
Using /Users/sarahwestcott/Desktop/make.fastq/mothur.test.sorted.qual as input file for the qfile parameter.
Using /Users/sarahwestcott/Desktop/make.fastq/mothur.test.sorted.accnos as input file for the accnos parameter.
Selected 499 sequences from your quality file.

Output File Names: /Users/sarahwestcott/Desktop/make.fastq/mothur.test.sorted.pick.qual

mothur > make.fastq(fasta=current, qfile=current)
Using /Users/sarahwestcott/Desktop/make.fastq/mothur.test.sorted.fasta as input file for the fasta parameter.
Using /Users/sarahwestcott/Desktop/make.fastq/mothur.test.sorted.pick.qual as input file for the qfile parameter.

Output File Names: /Users/sarahwestcott/Desktop/make.fastq/mothur.test.sorted.fastq

mothur > quit()

It took 0 seconds to run 6 commands from your script.

Kindly, Sarah
