### ISSUE TITLE
Problem with make.contigs when demultiplex reads 

### ISSUE THREAD

**Issue by ThomasKwong** [mothur/mothur#683]
Dear all,

I recently got my paired-end sequencing result back and was trying to start assemble the data.
So when I did the make.cotigs command with mothur 1.42.3:
> make.contigs(file=thomas.files, oligos=1.oligos, processors=1)
I went into error saying
>barcode pair XXXXXX XXXXXX is in your oligos file already, disregarding.

Hope someone can point me to the right direction, I also attached the log, oligos and some other files.

Bests,
TK

[mothur files.zip](https://github.com/mothur/mothur/files/3800127/mothur.files.zip)

**Comment by mothur-westcott** [comment]
The oligos file you attached contains redefinitions of barcodes pairs. For example:

barcode	GGTAGC	  ATCACG	B27N_C
barcode	GGTAGC	  ATCACG	B06A_B

Mothur is unsure which sample name to assign reads with the barcode pair (GGTAGC, ATCACG) to, B27N_C or B06A_B, so it disregards the second definition.
