### ISSUE TITLE
New function: make.lcr

### ISSUE THREAD

**Issue by pschloss** [mothur/mothur#695]
This would convert a shared file into a lcr file. The lcr - log centered ratio - is the log (base 2?) of a value divided by the geometric mean of the values across all OTUs for that sample. For example here are the counts for four OTUs in one sample...

```
> x <- c(10, 5, 3, 1)
> log2(x / prod(x)^(1/4))
[1]  1.5147234  0.5147234 -0.2222422 -1.8072047
```

We will run into a problem if there is a zero...

```
> x <- c(10, 5, 3, 1,0)
> log2(x / prod(x)^(1/4))
[1] Inf Inf Inf Inf NaN
```

As a solution, we should add a small value to every value in the vector. I'd propose adding `0.1` to OTUs with a count of zero...

```
> x <- c(10, 5, 3, 1,0)
> x[x==0] <- 0.1
> log2(x / prod(x)^(1/4))
[1]  2.3452054  1.3452054  0.6082399 -0.9767226 -4.2986507
```

It would be good to let the user set the value to add to zeroes, but 0.1 should be a decent default. The output file should be `*.lcr`. It would be good to confirm that this can be given as input to `lefse` and `metastats`. Let's call the command `make.lcr`

**Comment by mothur-westcott** [comment]
The Lefse and metastats commands currently take a shared file, I will add a relabund file option.
