### ISSUE TITLE
Trim.seqs fails when splitting barcoded 454 data

### ISSUE THREAD

**Issue by sconlan** [mothur/mothur#696]
I've been trying to track down a qual trimming bug from an ancient version of mothur (1.19) and ran into a different issue in 1.43. Trim.seqs fails with the following:

```
15:10 cn1007 mothur_test$ mothur "#trim.seqs(fasta=1.TCA.454Reads.fna, oligos=oligos.txt, processors=2, qfile=1.TCA.454Reads.qual, allfiles=T, maxambig=0, maxhomop=8, bdiffs=1, pdiffs=2, qaverage=25, minlength=50)"
...
260000
261000
262000
263000
263133
/******************************************/
Generating allfiles... Running command: split.groups(fasta=1.TCA.454Reads.trim.fasta, group=1.TCA.454Reads.groups)
Processing group: Abidjan.534R
cp: missing destination file operand after 'Abidjan.534R'
Try 'cp --help' for more information.
/******************************************/
Running command: get.seqs(dups=f, accnos=1.TCA.454Reads.Abidjan.534R.groups.accnos, name=Abidjan.534R, fasta=1.TCA.454Reads.trim.fastaAbidjan.534R)
Unable to open Abidjan.534R. Trying default /usr/local/apps/mothur/blast_common/Abidjan.534R.
Unable to open /usr/local/apps/mothur/blast_common/Abidjan.534R. Trying mothur's executable location /usr/local/apps/mothur/blast_common/Abidjan.534R.
Unable to open /usr/local/apps/mothur/blast_common/Abidjan.534R.
Unable to open Abidjan.534R
Segmentation fault
```
Version 1.38.0 (and earlier) seem OK

**Comment by mothur-westcott** [comment]
Thanks for reporting this bug. Could you send your logfile and input files to mothur.bugs@gmail.com so I can track down the issue for you?

**Comment by mothur-westcott** [comment]
Hi Sean,
  Thanks for reporting this issue and sending your files. The split.groups command was having trouble splitting with a group file and no name file. I have fixed the issue and the change will be part of 1.44.0 releasing in February. In the meantime, here's a workaround for you:

mothur > unique.seqs(fasta=test.fna) - create name file for fasta file
mothur > list.seqs(fasta=current) - list unique names in fasta file
mothur > get.seqs(qfile=test.qual) - select unique names from quality file
mothur > trim.seqs(fasta=current, name=current, oligos=oligos.txt, processors=2, qfile=current, allfiles=T, maxambig=0, maxhomop=8, bdiffs=1, pdiffs=2, qaverage=25, minlength=50) - trim sequences and split by sample

Kindly,
  Sarah
