### ISSUE TITLE
Remove.rare falsely identifies duplicated sequence name

### ISSUE THREAD

**Issue by Puumanamana** [mothur/mothur#698]
Hi,

I am using `remove.rare()` to remove rare OTUs in my data. It usually works, but for the last dataset I analyzed, it seems to be struggling with a "duplicated sequence" (but when I checked, it's not duplicated).

Here's my command:
`remove.rare(list=current, count=current, nseqs=2)`

I get the error:
```
[ERROR]: Your count table contains more than 1 sequence named esv_19368, sequence names must be unique. Please correct.
```

Thank you for your help,
Cédric

**Comment by mothur-westcott** [comment]
Could you send your input files and log file to mothur.bugs@gmail.com?

**Comment by mothur-westcott** [comment]
Thanks for sending your files. I found the source of the problem. Your list file indicates you have 9556 OTUs, but the file only contains 9549 OTUs. Did you create this file using mothur? If so, did you edit it outside of mothur? When I correct the OTU count the command runs without issue. I will add a check to mothur's reading of the list file to catch errors like this in the future.

**Comment by Puumanamana** [comment]
Thanks, it indeed solved it!
I was filtering the OTUs with LULU outside of Mothur and I forgot about the size column, good catch
