### ISSUE TITLE
Error - make.biom

### ISSUE THREAD

**Issue by Matteo-Lecce** [mothur/mothur#699]
Hi,
I need to obtain a biom file for metagenome prediction using picrust, but I get an error when I use the command:

>make.biom(shared=final.opti_mcc.shared, label=0.03, reftaxonomy=gg_13_8_99.gg.tax, constaxonomy=final.opti_mcc.0.03.cons.taxonomy, picrust=97_otu_map.txt)

The error is:

[ERROR]: could not find OTUId for unknown;. Its reference sequences are unknown .
Segmentation fault: 11

I use mothur Version 1.43.0 and GG database  (gg_13_8_99).

thank you for the attention

**Comment by mothur-westcott** [comment]
Did you classify your sequences using the GreenGenes references? Also, the otu_map file is for use with GreenGenes 13.5. https://www.mothur.org/wiki/Make.biom#picrust

**Comment by Matteo-Lecce** [comment]
Hi Sarah,
thank you for the reply. Yess I use GreenGenes references 13.8 and 13.5 but the error persists.

**Comment by mothur-westcott** [comment]
Okay, could you send your input files to mothur.bugs@gmail.com so I can try to track down the issue for you?

**Comment by mothur-westcott** [comment]
Hi Matteo,
  Thanks for sending your files. Did you remove the unknown sequences with the remove.lineage command after classification? The unknown tag is given to reads that could not be classified, and does not have a reference ID in greengenes. From the MiSEQ_SOP

Now that everything is classified we want to remove our undesirables. We do this with the remove.lineage command:

mothur > remove.lineage(fasta=stability.trim.contigs.good.unique.good.filter.unique.precluster.pick.fasta, count=stability.trim.contigs.good.unique.good.filter.unique.precluster.denovo.vsearch.pick.count_table, taxonomy=stability.trim.contigs.good.unique.good.filter.unique.precluster.pick.pds.wang.taxonomy, taxon=Chloroplast-Mitochondria-unknown-Archaea-Eukaryota)

Note is that "unknown" only pops up as a classification if the classifier cannot classify your sequence to one of the domains. Also, keep in mind that if you aren't classifying your sequences using the RDP reference taxonomy, you'll need to customize what the lineages are called. For example, our modified version of the RDP calls mitochondria, "Mitochondria". If you use greengenes, it calls them "f__mitochondria". If you are using greengenes (or SILVA or anything else), you'll need to change these names as appropriate.


Kindly,
 Sarah

**Comment by Matteo-Lecce** [comment]
Hi Sarah,
I removed lineage using this command.

When I performed the classify.seqs command, some sequences could not be classified: 

classify.seqs(fasta=final.fasta, count=final.count_table, reference=gg13_5_99.fasta, taxonomy= gg_13_5_99.gg.tax, cutoff=80)

[WARNING]: M00961_104_000000000-D6CHY_1_1102_8717_17345 could not be classified. You can use the remove.lineage command with taxon=unknown; to remove such sequences.

So I used this 

remove.lineage(fasta=final.fasta, count=final.count_table, taxonomy= final.gg.wang.taxonomy, taxon=unknown;)

But I obtain the same error.

Thank you for the support

**Comment by Matteo-Lecce** [comment]
Hi Sarah,
I resolved the error.

I made a mistake with input file.

Thank you
