### ISSUE TITLE
Version discrepancy in remove.seqs?

### ISSUE THREAD

**Issue by bathyscapher** [mothur/mothur#701]
Hello there,

in my `mothur` pipeline, I remove singletons with `awk`:
```bash
system(awk -e '{if ($2 < 2) { print $0 } }' long.name.precluster.denovo.vsearch.pick.count_table > long.name.single.accnos)
```
Then, I remove all sequences from `long.name.single.accnos`:
```bash
remove.seqs(fasta=long.name.precluster.pick.fasta, accnos=long.name.vsearch.pick.single.accnos)
remove.seqs(count=long.name.precluster.denovo.vsearch.pick.count_table, accnos=long.name.single.accnos)
```
This worked well until mother 1.41.0. Later releases that I tested (1.42.3 and 1.43.0) throw the error:
```bash
mothur > remove.seqs(count=long.name.precluster.denovo.vsearch.pick.count_table, accnos=long.name.single.accnos)
[ERROR]: 0 is not in your count table. Please correct.
```
So, removing `long.name.single.accnos` from the `fasta` works as expected, not so with the `count_table`. As workaround, I call `mothur 41` from a shell script:
```bash
system(bash removeSeqsFromCountTable16S.sh)
```
that simply holds the command
```bash
mothur41 "#remove.seqs(count=long.name.precluster.denovo.vsearch.pick.count_table, accnos=long.name.single.accnos)"
```
and gives me the desired output. Anyway, as this is quite an ugly solution, could you have a look what could be wrong here? Thanks :)

System: Debian 10.3, libreadline-dev 7.0-5.

**Comment by mothur-westcott** [comment]
Could you send the input files to mothur.bugs@gmail.com?

**Comment by bathyscapher** [comment]
Thanks for the prompt response, sent! :)

**Comment by bathyscapher** [comment]
My mistake, it should be It should be ```awk -e '{if ($2 < 2) {print $1}}'```!

Thanks, @mothur-westcott to have a look on the files, definitely helped! :-)
