### ISSUE TITLE
Compilation breaks with make 4.3

### ISSUE THREAD

**Issue by meanjollies** [mothur/mothur#707]
make 4.3 was released in January and appears to have a few backward-compatibility issues that might account for this. As such, mothur now fails to compile:
```
$ make
g++ -O3 -std=c++11 -pthread -DVERSION="\"1.44.0\"" -DUSE_READLINE -I.  -I source/calculators/  -I source/chimera/  -I source/classifier/  -I source/clearcut/  -I source/commands/  -I source/communitytype/  -I source/datastructures/  -I source/engines/  -I source/metastats/  -I source/read/  -I source/svm/   -c -o source/calculators/accuracy.o source/calculators/accuracy.cpp
In file included from source/datastructures/sabundvector.hpp:4,
                 from source/calculators/calculator.h:5,
                 from source/calculators/accuracy.hpp:12,
                 from source/calculators/accuracy.cpp:9:
source/datastructures/datavector.hpp:4:10: fatal error: mothurout.h: No such file or directory
    4 | #include "mothurout.h"
      |          ^~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:139: source/calculators/accuracy.o] Error 1
```
Please let me know if there's any other information I can provide, and thank you for maintaining mothur.

**Comment by mothur-westcott** [comment]
Hmm... I'm not seeing that issue building with 4.3. Could you tell me more about your system? Have you considered using our prebuilt binaries?

**Comment by meanjollies** [comment]
Sure, this is on Arch Linux. If I roll back my make version to 4.2.1, it succeeds. Regarding prebuilt binaries, I'm the package maintainer for mothur in the Arch User Repository, so I have an interest in making sure it builds from source.

**Comment by mothur-westcott** [comment]
I built with make 4.3 on Fedora. I haven't worked with Arch Linux before, so I don't have any insights about the system. 

The compile error seems to indicate the mothurout.h file can't be found. mothurout.h should be located in the source folder. Can you confirm it's there?

**Comment by meanjollies** [comment]
After some digging, I found that `-I source/` is getting left out of CXXFLAGS. This is also happening on Ubuntu. Funnily enough, using make 4.3 on RHEL 7 and RHEL 8 causes it to get included, much like Fedora. Not sure what sort of dependency could cause this difference. My makefile-fu is terrible, but if I modify `subdirs` like so: `subdirs :=  $(sort $(dir $(filter-out  $(skipUchime), source/, $(wildcard source/*/))))` - it works.

**Comment by mothur-westcott** [comment]
Great! Thanks for helping us track this down. I will add the change to our makefile.

**Comment by pur80a** [comment]
I encountered this issue Oracle Linux 8.7 (based on Redhat 8.7) with make version 4.2.1. 
I resolved it with: 
```
sed -i -e "1i CXXFLAGS=-Isource" Makefile 
make 
```
the sed commands [prepends](https://stackoverflow.com/questions/7807004/unix-how-can-i-prepend-output-to-a-file#7807185) a line to the Makefile
