### ISSUE TITLE
use of mothur in conda environments

### ISSUE THREAD

**Issue by didillysquat** [mothur/mothur#708]
Hi there,

I'm having conflict issues when installing mothur==1.43.0 (and other versions) in conda virtual environments (both on ubuntu systems and mac os).

I appreciate that dependency issues will be dependent the other packages installed in the environment. However, even from a brand new conda environment I'm unable to get mothur installed and it seems like the requirements are not fulfillable via the conda repos.

Examples of my attempts on macOS and an Ubuntu system attached.

This is not a deal breaker in terms of using mothur: once can simply symlink in one of your pre-compiled releases to the environments respective bin dir. However, it would be nice to be able to have mothur integrate seamlessly into conda-based workflows.

Thank you for your continued support and efforts!

[ubuntu_example.txt](https://github.com/mothur/mothur/files/4438656/ubuntu_example.txt)
[macos_example.txt](https://github.com/mothur/mothur/files/4438657/macos_example.txt)

**Comment by wclose** [comment]
Hi @didillysquat! There's been some changes to how conda solves the environment so you just need to add conda-forge to your list of channels. With the new behavior, conda only looks in the specified channels to solve requirements but, for almost all bioconda packages, the dependencies come from conda-forge. It's a pain that's being worked on (I help maintain bioconda and the mothur package) but for now, you'll just need to use:

```
conda install -c conda-forge -c bioconda mothur==1.43.0
```

Let me know if that works and if you have any other questions. Thanks!

**Comment by didillysquat** [comment]
@wclose: worked a treat - of course!

Thank you very much for the rapid reply.

**Comment by wclose** [comment]
You're welcome! Good luck!

**Comment by marwa38** [comment]
Thanks for this. 
Why I found that the code that is currently used for the new release (https://anaconda.org/bioconda/mothur) is 
conda install -c bioconda mothur
and not 
conda install -c conda-forge -c bioconda mothur
