### ISSUE TITLE
make.contigs not making use of multiple processors with *.gz files (ubuntu)

### ISSUE THREAD

**Issue by didillysquat** [mothur/mothur#710]
Hi there,

After a successful install of mothur==1.43.0 using conda, when running make.contigs, and using fastq.gz files, the process only runs on a single cpu. However, when manually decompressing and then running make.contigs, I get the expected behavior (i.e. htop lights up like a christmas tree).

Would it be possible to extend the multi-process use to .gz compressed files?

Thank you for your continued support and efforts!

**Comment by pschloss** [comment]
Let us look into it - is there a reason you're using 1.43 rather than 1.44?

**Comment by didillysquat** [comment]
Hi @pschloss 

I want to work with a conda implementation of mothur for use in pipeline managers and more generally in conda environments. As it currently stands, I'm not aware that 1.44 is available through conda. I may well be wrong.

On my mac:

```
humebc@kl-16491:~/Downloads$ conda search -c bioconda mothur
Loading channels: done
# Name                       Version           Build  Channel             
mothur                        1.42.3      h35bcdce_0  bioconda            
mothur                        1.43.0      h35bcdce_0  bioconda
```

On our server (ubuntu):
```
humebc@KW60289:~/phylogeneticSoftware/SymPortal_Data/rawData/20191211_dungan/testing$ conda search -c bioconda mothur
Loading channels: done
# Name                       Version           Build  Channel             
mothur                        1.25.0               0  bioconda            
mothur                        1.25.0    ncurses5.9_0  bioconda            
mothur                        1.36.1               0  bioconda            
mothur                        1.36.1     boost1.60_1  bioconda            
mothur                        1.36.1     boost1.60_2  bioconda            
mothur                      1.38.1.1     boost1.60_0  bioconda            
mothur                      1.38.1.1     boost1.61_0  bioconda            
mothur                        1.39.5     boost1.61_0  bioconda            
mothur                        1.39.5     boost1.64_0  bioconda            
mothur                        1.39.5     boost1.64_1  bioconda            
mothur                        1.39.5     boost1.64_2  bioconda            
mothur                        1.39.5     boost1.64_3  bioconda            
mothur                        1.39.5      h284faf4_4  bioconda            
mothur                        1.40.5      hb16dc7f_0  bioconda            
mothur                        1.41.0      h392e8a4_0  bioconda            
mothur                        1.41.3      ha5e32a3_0  bioconda            
mothur                        1.42.0      ha5e32a3_0  bioconda            
mothur                        1.42.1      ha5e32a3_0  bioconda            
mothur                        1.42.3      hd76352b_0  bioconda            
mothur                        1.43.0      hd76352b_0  bioconda
```

**Comment by mothur-westcott** [comment]
Make.contigs is parallelized for both gz and fastq files, but the work is divided differently. 

Let's look at a simple example:

8 processors, 16 file pairs.

For gz file pairs - each process is assigned a set of gz file pairs to process. Each process would be assigned 2 file pairs to assemble. 8 file pairs will be worked on at the same time.

For fastq file pairs - each process assembles a section of the fastq file pairs. All 8 processors work on a single file pair together. 1 file pair is processed at a time.

**Comment by didillysquat** [comment]
@mothur-westcott : I see, thank you for that clear explanation.

So, in the case where ffastq and rfastq are provided with *.fastq.gz arguments (i.e. one compressed file pair; not a 'file=' argument with multiple pairs), there can be no gain from multiple processes, correct?

I'm sure there is a very good reason for the different handling of the compression types. But, if it were somehow possible to treat a single pair of fastq.gz files the same way a pair of fastq files would be treated, that would be helpful. For example, if this functionality were enabled, to make use of multiple cores, the user could simply work in a serial manner (i.e. running one pair at a time). This makes use of the other functions' parallelism (for example pcr.seqs). Else, the parallelism must be achieved by running multiple instances of a mothur pipeline and within each instance, limiting the number of processors used for the other functions (i.e. setting the processors in pcr.seqs to 1). Alternatively, the user needs to make the contiguous sequences as a separate process before then working on a sample by sample basis, or... work with decompressed fastq files to start.

Sorry for the bother. And thank you for your help!

It would be great if this behaviour could be added to the processors section of the make.contigs documentation (https://mothur.org/wiki/make.contigs/).

Please feel free to close this issue.
