### ISSUE TITLE
Create a make.tidyshared function

### ISSUE THREAD

**Issue by pschloss** [mothur/mothur#716]
A function that would take in a shared file and output a file with four columns - (1) the label, (2) the group/sample id, (3) the OTU (i.e. the column headings from the shared file), and (4) the OTU count. Could add an argument to the function, `keepzeroes` that would be FALSE by default to remove those rows where the count is zero. The output file extension would be `tshared` instead of `shared`.

This would be a much longer file than we generally output, but would be easier to use within R with the `tidyverse` package.

I'm not sure how much of an overhaul it would take to convert all of the downstream mothur functions to use the `tshared` file instead of a `shared` file. For now, I'd be happy with the single function.

**Comment by mothur-westcott** [comment]
What about adding the shared parameter to make.shared? Mothur could autodetect the form, (tidy or full format) and output the other format?

mothur > make.shared(shared=mySharedFile) - output tidy format

or 

mothur > make.shared(shared=myTidySharedFile) - output mothur's standard shared file format

**Comment by pschloss** [comment]
that would be great - thanks!

**Comment by mothur-westcott** [comment]
Just to confirm, the tidy file would look like:

0.03  F3D0  OTU01  10
0.03  F3D1  OTU01  5
...
0.05 F3D0 OTU01  8
0.05  F3D1  OTU01  3
...

**Comment by pschloss** [comment]
Right
