### ISSUE TITLE
Is it possible to make taxon names in *.tax.summary files have full taxonomy including higher ranks?

### ISSUE THREAD

**Issue by ilnamkang** [mothur/mothur#723]
Hi,

I'd like to know if it is possible to make taxon names in the *.tax.summary files (generated by classify.seqs) have full taxonomy including higher ranks.

Current format is like below.
***
taxlevel	rankID	taxon	daughterlevels	total	S1	S2	S3	S4
0	0	Root	4	262354	63086	73567	58542	67159
1	0.1	Archaea	11	9443	2146	2229	3200	1868
2	0.1.1	Aenigmarchaeota	3	39	6	9	20	4
3	0.1.1.1	Aenigmarchaeia	1	32	6	6	17	3
4	0.1.1.1.1	Aenigmarchaeales	1	32	6	6	17	3
5	0.1.1.1.1.1	Aenigmarchaeales_fa	3	32	6	6	17	3
6	0.1.1.1.1.1.1	Aenigmarchaeales_fa_unclassified	0	1	0	1	0	0
***

I think that the format including full taxonomy may be useful for some downstream analyses. e.g.,
***
taxlevel	rankID	taxon	daughterlevels	total	S_1	S_2	S_3	S_4
0	0	Root	4	262354	63086	73567	58542	67159
1	0.1	Archaea	11	9443	2146	2229	3200	1868
2	0.1.1	Archaea;Aenigmarchaeota	3	39	6	9	20	4
3	0.1.1.1	Archaea;Aenigmarchaeota;Aenigmarchaeia	1	32	6	6	17	3
4	0.1.1.1.1	Archaea;Aenigmarchaeota;Aenigmarchaeia;Aenigmarchaeales	1	32	6	6	17	3
5	0.1.1.1.1.1	Archaea;Aenigmarchaeota;Aenigmarchaeia;Aenigmarchaeales;Aenigmarchaeales_fa	3	32	6	6	17	3
6	0.1.1.1.1.1.1	Archaea;Aenigmarchaeota;Aenigmarchaeia;Aenigmarchaeales;Aenigmarchaeales_fa;Aenigmarchaeales_fa_unclassified	0	1	0	1	0	0
***

Thanks.

**Comment by mothur-westcott** [comment]
The classify.seqs and summary.tax commands have the output and printlevel options.  

output

The output parameter allows you to specify format of your *tax.summary file. Options are simple and detail. The detail format outputs the totals at each level, where as the simple format outputs the highest level. The default is detail.

The detail format looks like:

taxlevel   rankID  taxon   daughterlevels  total   A   B   C
0  0   Root    1   28  14  20  9
1  0.1 "k__Bacteria"   5   28  14  20  9
2  0.1.1   "p__Actinobacteria" 1   3   0   3   0
3  0.1.1.1 "c__Actinobacteria" 1   3   0   3   0
4  0.1.1.1.1   "o__Bifidobacteriales"  1   3   0   3   0
5  0.1.1.1.1.1 "f__Bifidobacteriaceae" 1   3   0   3   0
6  0.1.1.1.1.1.1   "g__Bifidobacterium"    3   3   0   3   0
7  0.1.1.1.1.1.1.1 "s__"   0   1   0   1   0
7  0.1.1.1.1.1.1.2 "s__adolescentis"   0   1   0   1   0
7  0.1.1.1.1.1.1.3 "s__longum" 0   1   0   1   0
2  0.1.2   "p__Bacteroidetes"  1   6   5   3   3
3  0.1.2.1 "c__Bacteroidia"    1   6   5   3   3
4  0.1.2.1.1   "o__Bacteroidales"  2   6   5   3   3
5  0.1.2.1.1.1 "f__Bacteroidaceae" 1   4   4   3   1
6  0.1.2.1.1.1.1   "g__Bacteroides"    4   4   4   3   1
7  0.1.2.1.1.1.1.1 "s__"   0   1   1   1   0
...
The simple format looks like:

taxon  total   A   B   C
"k__Bacteria";"p__Actinobacteria";"c__Actinobacteria";"o__Bifidobacteriales";"f__Bifidobacteriaceae";"g__Bifidobacterium";"s__";   1   0   1   0
"k__Bacteria";"p__Actinobacteria";"c__Actinobacteria";"o__Bifidobacteriales";"f__Bifidobacteriaceae";"g__Bifidobacterium";"s__adolescentis";   1   0   1   0
"k__Bacteria";"p__Actinobacteria";"c__Actinobacteria";"o__Bifidobacteriales";"f__Bifidobacteriaceae";"g__Bifidobacterium";"s__longum"; 1   0   1   0
...
printlevel

The printlevel parameter allows you to specify taxlevel of your *tax.summary file to print to. Options are 1 to the max level in the file. The default is -1, meaning max level. If you select a level greater than the level your sequences classify to, mothur will print to the level your max level.

mothur > classify.seqs(...., printlevel=4)
Detail format:

taxlevel   rankID  taxon   daughterlevels  total   A   B   C 
0  0   Root    1   28  14  20  9
1  0.1 "k__Bacteria"   5   28  14  20  9
2  0.1.1   "p__Actinobacteria" 1   3   0   3   0
3  0.1.1.1 "c__Actinobacteria" 1   3   0   3   0
4  0.1.1.1.1   "o__Bifidobacteriales"  1   3   0   3   0
2  0.1.2   "p__Bacteroidetes"  1   6   5   3   3
3  0.1.2.1 "c__Bacteroidia"    1   6   5   3   3
4  0.1.2.1.1   "o__Bacteroidales"  2   6   5   3   3
2  0.1.3   "p__Firmicutes" 2   13  8   10  2
3  0.1.3.1 "c__Bacilli"    1   1   1   0   0
4  0.1.3.1.1   "o__Turicibacterales"   1   1   1   0   0
...
Simple Format:

taxon  total   A   B   C
"k__Bacteria";"p__Actinobacteria";"c__Actinobacteria";"o__Bifidobacteriales";  3   0   3   0
"k__Bacteria";"p__Bacteroidetes";"c__Bacteroidia";"o__Bacteroidales";  6   5   3   3
"k__Bacteria";"p__Firmicutes";"c__Bacilli";"o__Turicibacterales";  1   1   0   0
...

**Comment by ilnamkang** [comment]
Thank you for a quick reply.

According to your explanation, It is likely that I'd better try adjusting printlevel with simple format output.
