### ISSUE TITLE
Trouble in Pre-clustering in Mothur 

### ISSUE THREAD

**Issue by saeedmn2005** [mothur/mothur#724]
Hello,
I have a problem after the following command : pre.cluster(fasta=stability.trim.contigs.good.unique.good.filter.unique.fasta, count=stability.trim.contigs.good.unique.good.filter.count_table, diffs=2)

My error is :
**Using 4 processors.

/******************************************/
Running command: split.groups(groups=FC-1-1-FC-2-1-FC-3-1-FC-4-1-FC-5-1-FC-6-1, fasta=stability.trim.contigs.good.unique.good.filter.unique.fasta, count=stability.trim.contigs.good.unique.good.filter.count_table)

Using 4 processors.

Output File Names:

/******************************************/
should never get here, quitting**

And suddenly the Mothur become closed!!! It produces two COUNT_TABLE File and FASTA files but both of them are empty.

Thanks

**Comment by mothur-westcott** [comment]
It looks like you have '-''s in your sample names. '-''s are a special character in mothur used to separate group names. I suspect mothur outputted a warning like:

[WARNING]: group FC-1-1 contains illegal characters in the name. Group names should not include :, -, or / characters.  The ':' character is a special character used in trees. Using ':' will result in your tree being unreadable by tree reading software.  The '-' character is a special character used by mothur to parse group names.  Using the '-' character will prevent you from selecting groups. The '/' character will created unreadable filenames when mothur includes the group in an output filename.

Changing the '-''s to '_''s should resolve the issue for you.

**Comment by saeedmn2005** [comment]
Thanks a lot. It works now!
