### ISSUE TITLE
File mismatch detected, quitting command

### ISSUE THREAD

**Issue by Mewgia** [mothur/mothur#728]
Dear colleagues,
could you please help me with the problem.
I'm using this manual https://mothur.org/wiki/miseq_sop/ for the work step by step. And all was good until...
Your count file contains 31315 unique sequences, but your fasta file contains 13260. File mismatch detected, quitting command.
Log file is attached. What should I do? Thank you.
[mothur.1592217518.txt](https://github.com/mothur/mothur/files/4781931/mothur.1592217518.txt)

**Comment by mothur-westcott** [comment]
Could you post the results of these two commands?

mothur > 
align.seqs(fasta=stability.trim.contigs.good.unique.fasta, reference=silva.bacteria.fasta) - align your sequences. 

mothur > summary.seqs(fasta=current) - summarize the sequences

**Comment by Mewgia** [comment]
> align.seqs(fasta=stability.trim.contigs.good.unique.fasta, reference=silva.bacteria.fasta)

It took 656 secs to align 31315 sequences.

[WARNING]: 6883 of your sequences generated alignments that eliminated too many bases, a list is provided in D:\Genomes\Inna\16s\samples_1_4\v3-v4\stability.trim.contigs.good.unique.flip.accnos.
[NOTE]: 3426 of your sequences were reversed to produce a better alignment.

It took 656 seconds to align 31315 sequences.

Output File Names:
D:\Genomes\Inna\16s\samples_1_4\v3-v4\stability.trim.contigs.good.unique.align
D:\Genomes\Inna\16s\samples_1_4\v3-v4\stability.trim.contigs.good.unique.align.report
D:\Genomes\Inna\16s\samples_1_4\v3-v4\stability.trim.contigs.good.unique.flip.accnos

> summary.seqs(fasta=current)

Using 1 processors.
[WARNING]: This command can take a namefile and you did not provide one. The current namefile is D:\Genomes\Inna\16s\samples_1_4\v3-v4\stability.trim.contigs.good.names which seems to match D:\Genomes\Inna\16s\samples_1_4\v3-v4\stability.trim.contigs.good.unique.align.

                Start   End     NBases  Ambigs  Polymer NumSeqs
Minimum:        0       0       0       0       1       1
2.5%-tile:      1044    1053    4       0       1       114
25%-tile:       6333    25432   344     0       4       1135
Median:         6334    25434   458     0       5       2270
75%-tile:       6386    25436   471     0       6       3405
97.5%-tile:     43105   43116   474     0       14      4426
Maximum:        43116   43116   492     0       27      4539
Mean:   9546    24531   368     0       5
# of Seqs:      4539

It took 9 secs to summarize 4539 sequences.

Output File Names:
D:\Genomes\Inna\16s\samples_1_4\v3-v4\stability.trim.contigs.good.unique.summary

**Comment by mothur-westcott** [comment]
Could you send your logfile and stability.trim.contigs.good.unique.fasta file to mothur.bugs@gmail.com?

**Comment by mothur-westcott** [comment]
I am not able to reproduce the error you are getting with the files you sent. Could you be running out of hard drive space to write the aligned file to?

**Comment by Mewgia** [comment]
I thought so with my flash card and moved all the data to hard drive. The problem was sorted out, I successfully passed the stages

align.seqs(fasta=stability.trim.contigs.good.unique.fasta, reference=silva.v4.fasta)
and
summary.seqs(fasta=stability.trim.contigs.good.unique.align, count=stability.trim.contigs.good.count_table)
but then was faced with the next problem: when I try to do

screen.seqs(fasta=stability.trim.contigs.good.unique.align, count=stability.trim.contigs.good.count_table, summary=stability.trim.contigs.good.unique.summary, start=6428, end=23440, maxhomop=8)

it removes all the sequences and outputs empty files stability.trim.contigs.good.good.count_table and stability.trim.contigs.good.unique.good.align. Could you please help me to solve that?

16.06.2020, 22:12, "Sarah Westcott" <notifications@github.com>:

**Comment by mothur-westcott** [comment]
This likely indicates no overlap. Can you post the results of this command?

mothur > summary.seqs(fasta=stability.trim.contigs.good.unique.align, count=stability.trim.contigs.good.count_table)

**Comment by Mewgia** [comment]
Using 4 processors.

                Start   End     NBases  Ambigs  Polymer NumSeqs
Minimum:        0       0       0       0       1       1
2.5%-tile:      2       17      3       0       1       877
25%-tile:       2       17012   227     0       4       8762
Median:         2       17012   409     0       5       17523
75%-tile:       2       17012   426     0       5       26284
97.5%-tile:     16157   17012   427     0       11      34168
Maximum:        17012   17012   444     0       33      35044
Mean:   2046    15319   325     0       4
# of unique seqs:       31315
total # of seqs:        35044

It took 16 secs to summarize 35044 sequences.

Output File Names:
D:\Inna\16s\samples_1_4\v3-v4\stability.trim.contigs.good.unique.summary

**Comment by mothur-westcott** [comment]
mothur > screen.seqs(fasta=stability.trim.contigs.good.unique.align, count=stability.trim.contigs.good.count_table, summary=stability.trim.contigs.good.unique.summary, start=6428, end=23440, maxhomop=8)

The start setting of 6428 will remove any sequences that start after 6428.
The end setting of 23449 will remove any sequences that ends before 23440.

Since all of your reads end before 23440, all the reads are removed.

**Comment by Mewgia** [comment]
Thank you a lot! It works.18.06.2020, 21:43, "Sarah Westcott" <notifications@github.com>:
mothur > screen.seqs(fasta=stability.trim.contigs.good.unique.align, count=stability.trim.contigs.good.count_table, summary=stability.trim.contigs.good.unique.summary, start=6428, end=23440, maxhomop=8)
The start setting of 6428 will remove any sequences that start after 6428.
The end setting of 23449 will remove any sequences that ends before 23440.
Since all of your reads end before 23440, all the reads are removed.
