### ISSUE TITLE
ERROR (v 1.44.1)

### ISSUE THREAD

**Issue by fernandajamel** [mothur/mothur#730]
When I first start the new release (v 1.44.1) of mothur, I get an [ERROR] message.
No matter what command I use after that, I keep getting 1 error message and the program crashing and closing.
Its something to do about a missing file mothur is having trouble finding...

[ERROR]: Could not open mothur.1593047507.logfile

**Comment by mothur-westcott** [comment]
One of the first things mothur does when starting is generate a logfile. If mothur is unable to open a logfile, it usually indicates mothur's executable is located in a directory you do not have write permissions to. Could you tell me more about your system?

1. What operating system are you running mothur on?

2. Where is mothur installed on your machine? Do you have permission to read and write to this location?

3. What commands are you trying to run?

4. Could you tell me more about the missing file mothur is having trouble finding?
