### ISSUE TITLE
pairwise.seqs: add options to allow "external" parallelisation (and "restartability")

### ISSUE THREAD

**Issue by hermannschwaerzlerUIBK** [mothur/mothur#731]
Hi everybody,

I happened to see that mothur deletes the .dist file that gets created by pairwise.seqs when mothur gets cancelled for some reason (e.g. underestimating walltime parameter in a job submission).

This is quite unfortunate as it means that all the work is lost.
It would be nice if the file stays as it is and could be used in a new run of pairwise.seqs to skip all sequences that are already in it in the comparison step.
Is this feasible?
Or already possible and I am missing something?

Regards,
Hermann

**Comment by mothur-westcott** [comment]
@pschloss, what are your thoughts?

**Comment by pschloss** [comment]
I worry that the accounting of which sequences have been distanced would be a pain especially if the first round of distances were parallelized. If you think we can get around that, go for it

**Comment by hermannschwaerzlerUIBK** [comment]
I gave this a little more thought yesterday and came up with this:
How about adding check-pointing?

In that loop over the sequences we could add code that writes the current `i` for any processor in a file (e.g. before [this line](https://github.com/mothur/mothur/blob/master/source/commands/pairwiseseqscommand.cpp#L398) whenever `i % 10 == 0`). This could be done in a "check-points" directory with one file per processor - named `1`, `2`, ... 
When we (re)start the processing we check for that directory and if its contents makes sense. When that's the case we then use the values in those file to set the starting point of the loops.
This means that in case of a restart in the end there are some duplicates in the .dist file. These can be filtered out with standard tools (e.g. `sort -u`).

What do you think?
Wether check-pointing is used or not could be an option of the command - defaulting to not using it.

I am willing to look into this and do a pull request as soon as I have working code if you are interested.

But what I am asking myself is this: am I the only one having the problem that `pairwise.seqs` takes "ages" as I am processing fasta-files with 100k sequences and more? Or am I doing something wrong if I work with files of that size?

**Comment by hermannschwaerzlerUIBK** [comment]
After pondering on this for some time I decided to look at this more generally and take a different angle of approach (sorry for constantly changing my mind :-)
I added two options (`startsequence` and `sequencecount` - both numbers) to **pairwise.seqs**, that allow to process only a "slice" (i.e. `sequencecount` sequences starting at `startsequence`) of the sequences in the fasta-file. When these options are specified the distances are stored in _**....dist_xxxxx**_ files where _**xxxxx**_ is the specified `startsequence`.

This allows
* using job-arrays or other ways of parallelisation (e.g. GNU [parallel](https://www.gnu.org/software/parallel/)) to speed up processing of files with many sequences.
* cancelling and restarting **pairwise.seqs** without having to reprocess all of the already finished parts.

I tested this with a fasta-file containing almost 240000 sequences. 
* Using 400 cores on [MACH2](https://www.risc.jku.at/projects/mach2/) it took 76 hours **without** the new options.
* With GNU parallel and also 400 cores it took 29 hours using the new options (about 10000 "slices" (`sequencecount=23`)).
* Using a job-array (with almost 800 parallel tasks) on a local cluster (with ten years old hardware) it took 17 hours.

I consider this a huge improvement and will create a pull request soonish.
It will need some documentation (including some examples) - but I can provide that if you are interested.

What do you think?

**Comment by mothur-westcott** [comment]
Thanks for your contribution. At this time we are not going to include the changes you made, because we are in process of a major rewrite of the whole command. The rewrite will include speed and memory improvements. You can follow the progress here, https://github.com/mothur/mothur/issues/763.
