### ISSUE TITLE
Summary. seqs - file mismatch 

### ISSUE THREAD

**Issue by lululawson** [mothur/mothur#737]
"Your count file contains 248218 unique sequences, but your fasta file contains 85816. File mismatch detected, quitting command."

This is the error I'm getting right now. So far I have run

make.contigs(file=cray.files, processors=8)
summary.seqs(fasta=current)
screen.seqs(fasta=current, group=current, summary=current, maxambig=0, maxlength=275)
summary.seqs(fasta=current)
unique.seqs(fasta=current)
summary.seqs(fasta=current, name=current)
count.seqs(name=current, group=current)
summary.seqs(fasta=current, count=current)
align.seqs(fasta=current, reference=silva.align)
summary.seqs(fasta=current, count=current)
and then
Your count file contains 248218 unique sequences, but your fasta file contains 85816. File mismatch detected, quitting command.

It's not a storage issue, and I've never run into this issue before! I'm using v.144.1

Thanks guys!

**Comment by mothur-westcott** [comment]
It looks like the align.seqs command was not able to finish completely. We corrected a bug in align.seqs command that was causing a segfault in version 1.44.2. Can you upgrade and see if the problem persists?
