### ISSUE TITLE
mothur hang when using cluster.split

### ISSUE THREAD

**Issue by lucacozzuto** [mothur/mothur#739]
Hi,
I'm using mothur version 1.44.1 and when running cluster.split I got this error:

Running command: dist.seqs(fasta=stability.paired.trim.contigs.good.unique.good.filter.unique.precluster.abund.pick.pick.pick.fasta.187.temp, processors=44, cutoff=0.03)

Using 44 processors.
/******************************************/

Sequence	Time	Num_Dists_Below_Cutoff
0	0	0
1	0	1

It took 0 secs to find distances for 2 sequences. 1 distances below cutoff 0.03.

Output File Names: 
stability.paired.trim.contigs.good.unique.good.filter.unique.precluster.abund.pick.pick.pick.fasta.187.dist

[ERROR]: Could not open stability.paired.trim.contigs.good.unique.good.filter.unique.precluster.abund.denovo.vsearch.pick.pick.pick.pick.count_table.16.temp
and then the programs hangs forever.

Can you help me, please?

**Comment by mothur-westcott** [comment]
Could you be running out of disk space to write the distance and count files? The distance files created can be very large. If not, could you tell me more about your data and system?

1. How many unique sequences are you processing?

2. How much RAM and disk space do you have available?

3. What operating system are you running mothur on?
