### ISSUE TITLE
Error when running unique.seqs after aligning and filtering sequences 

### ISSUE THREAD

**Issue by SShabayek** [mothur/mothur#740]
Hello
I am using the latest release of mothur on ubuntu 20.04

I was following the MiseqSOP to analyse my illumina sequences. After successful alignment using align.seqs, when performing unique.seqs for the second time as recommended by the MiSeqSOP document:
unique.seqs(fasta=stability.trim.contigs.good.unique.good.filter.fasta, count=stability.trim.contigs.good.good.count_table)

I got the following error:
free(): double free detected in tcache 2
Aborted (core dumped)

I was unable to complete the pipeline.

I hope you can help me with 

Ps: I tried to attach my log file but it is not supported by the website

**Comment by mothur-westcott** [comment]
Could you send your input files and logfile to mothur.bugs@gmail.com so I can take a closer look for you?

**Comment by SShabayek** [comment]
Dear Sarah,

Please find attached the log files. Some log files where 0 kb so they
failed to be attached.
I have tried to repeat the analysis again and again but I am stuck at
pcr.seqs
All the errors I got emerged after this step and I am unable to finish the
MiSOP pipeline.

Thank you in advance

**Comment by mothur-westcott** [comment]
We had a similar report on the forum, https://forum.mothur.org/t/free-double-free-detected-in-tcache-2/20650/2. Could this be the source of the problem?
