### ISSUE TITLE
mothur command mode: not outputting errors with -p flag.

### ISSUE THREAD

**Issue by stormsz** [mothur/mothur#748]
version:
Linux
Mothur version=1.44.3
Release Date=8/27/20

`make.contigs(file=stability.files, oligos=fully_degenerated_rbcL_primers.oligos, checkorient=t, pdiffs=1)` 
On the standard mothur interactive mode results in errors (this is expected! I didn't placed the .oligos file).
log file: https://pastebin.com/u8uhWvSy (again, the oligos error is expected).

`$ ./mothur "#make.contigs(file=stability.files, oligos=fully_degenerated_rbcL_primers.oligos, checkorient=t, pdiffs=1)"`
On the command line mode, it clears the screen and does nothing, also it doesn't create the log file. #99 ?

Is the "clear terminal screen before executing mothur" a must have because of the way mothur executes or can it be changed? 
Its just a little weird to have a script that executes mothur that clears the screen every time it executes since if we were to have 2 or 3 command line executes, that would mean that mothur would just keep clearing the screen over and over.
Although I admit this is probably not why the command line feature was implemented for or designed, just an honest question.

**Comment by mothur-westcott** [comment]
We will remove the clear screen in the 1.45.0 release
