### ISSUE TITLE
Add biom 2.0 output to make.biom

### ISSUE THREAD

**Issue by mothur-westcott** [mothur/mothur#752]
https://github.com/mothur/mothur.github.io/pull/47#issuecomment-712168170

**Comment by mothur-westcott** [comment]
@kelly-sovacool @pschloss The defaults for both input and output of biom files throughout mothur is 1.0. Should I change the default to be 2.1?

**Comment by mothur-westcott** [comment]
* Create objects for the biom files
* Update mothur's commands to use biom objects

**Comment by kelly-sovacool** [comment]
> @kelly-sovacool @pschloss The defaults for both input and output of biom files throughout mothur is 1.0. Should I change the default to be 2.1?

Making the default be 2.1 sounds good to me. Will there be a parameter to specify 1.0 if desired?

**Comment by mothur-westcott** [comment]
Thanks for the input. I will keep the format parameter so you can still read older versions.

**Comment by kelly-sovacool** [comment]
> Thanks for the input. I will keep the format parameter so you can still read older versions.

Great! vsearch only outputs 1.0, so having that will help with interoperability. Thanks Sarah!
