### ISSUE TITLE
vsearch ref is not called with threads

### ISSUE THREAD

**Issue by AnnSeidel** [mothur/mothur#757]
Hi,

I wrote a small wrapper for the vsearch denovo command (to get some more information which are not provided in the mothur log for example the run time for the vsearch call only, without the mothur overhead for input formatting,..) and provided this as the executable when calling chimera.vsearch So basically it just takes the parameters as they are and calls the exact same vsearch binary as mothur would do with the unix time command

vsearch_wrapper:
```
{ time /usr/users/aseidel1/Software/mothur/vsearch "$@" ;} &> ${MOTHUR_OUT}/vsearch.log
echo "$@" >> ${MOTHUR_OUT}/vsearch.log
```
Thereby I realized that vsearch itself is called with --threads 1 even I set the processor parameter to 16 when calling mothur's chimera vsearch command:
```
chimera.vsearch(fasta=mock_only.stability.trim.contigs.good.unique.good.filter.unique.precluster.fasta, reference =silva.nr_v138.v4.fasta, vsearch=vsearch_wrapper, processors=16)
```
vsearch.log:
```
--db silva.nr_v138.v4.fasta --uchime_ref mock_only.stability.trim.contigs.good.unique.good.filter.unique.precluster.temp.vsearch_formatted --chimeras /mock_only.stability.trim.contigs.good.unique.good.filter.unique.precluster.ref.vsearch.chimerasvsearch_out --uchimeout mock_only.stability.trim.contigs.good.unique.good.filter.unique.precluster.ref.vsearch.chimeras --xsize --threads 1
```

I am using mothur version 1.44.3:

```
Linux version

Using ReadLine,Boost,HDF5
mothur v.1.44.3
Last updated: 8/27/20
by
Patrick D. Schloss
```

**Comment by mothur-westcott** [comment]
Currently, the chimera.vsearch command only uses multiple processors when you are running the command in denovo mode. Mothur divides the samples between the processors and sends each sample to the vsearch program. I will add a feature request to add parallel processing to the chimera.vsearch program with a reference.

**Comment by AnnSeidel** [comment]
Thanks for the explanation. The division per sample for the vsearch denovo mode seems an elegant solution to circumvent that vsearch deovo does not support threads itself. But for the reference mode, threads are directly supported by vsearch (according to the paper). Would it be a quick fix to just pass the value of the processors argument to the vsearch call?

**Comment by mothur-westcott** [comment]
https://github.com/mothur/mothur/commit/f91aa2dd8526e1b0d9435e6d6ab063916fdfab84 includes the changes you are looking for.
