### ISSUE TITLE
aws libreadline.so.6: error with version mothur-1.42.0

### ISSUE THREAD

**Issue by soilmicrobiome** [mothur/mothur#758]
Hi there,

I am trying to run mothur on aws.

I chose mothur-1.42.0 for the instance version.

If i type "mothur"  i get the following error:

mothur: error while loading shared libraries: libreadline.so.6: cannot open shared object file: No such file or directory

I saw this error else where but i can't use "yum search readline" as the permission is denied.

Any help much appreciated

**Comment by soilmicrobiome** [comment]
I should mention that if load the mothur-1.40.4 version everything works

**Comment by mothur-westcott** [comment]
Have you tried the *noreadline version found here, https://github.com/mothur/mothur/releases/download/v1.44.3/Mothur.linux_noReadline.zip
