### ISSUE TITLE
Ubuntu update to version 1.44.3?

### ISSUE THREAD

**Issue by bjconnor60** [mothur/mothur#759]
Hi there.  I am running mothur on Ubuntu on Windows 10 and downloaded the file for install from the newest release github page (https://github.com/mothur/mothur/releases/tag/v1.44.3), but it does not seem to be version 1.44.3. If I recall, the version indicated when I ran it was mothur v.1.42. I also downloaded mothur from the newest release page onto my Mac using the OS file and was able to run through the entire MiSeq SOP with no issue.

Thanks!

**Comment by RAnytime** [comment]
Dear All, I've the same problem. Often I think it's my fault, but I've tested it several times. And I'm happy not to be the only one having that issue.

**Comment by RAnytime** [comment]
Dear All, after several trials to overcome the problem (did a installation from sources) I had to learn that Ubuntu has a distinguished archive for software packages like mothur. When these packages are installed it is done using these archives! So downloading mothur and trying to use it is perhaps a waste of time: Probably the up-loaded versions are correct - but installation is always done from "old" archives! When one wants to use the lastest version of Mothur in Ubuntu one has to upgrade Ubuntu to 20.10. Be careful, upgrading an operating system is always dangerous for other applications and data. But in my case it did the trick!
Perhaps there is another way to overcome the problem. Being a newbie to Ubuntu this was my choice.
Best, Uli

**Comment by lmsteinberg** [comment]
RAnytime, thank you so much! I have been struggling with this for months, and when I posted on the forum, I was told it was something on my end. I could see that mothur was completely uninstalled, but when I tried to reinstall, it was always the same version. I am also a newbie to Ubuntu. Thank you again!!!!
