### ISSUE TITLE
Error with classify.seqs

### ISSUE THREAD

**Issue by Sithara85** [mothur/mothur#762]
Hi,

I am using Mothur for 16S rRNA microbiome miseq data OTU classification. I followed the SOP here https://mothur.org/wiki/miseq_sop/

Thank you so much for such a great program and all the details in the SOP. I was successfully able to reach until classify.seqs
I am getting below error. I am using Mothur version 1.44.3, I have downloaded the trainset files from your website.

mothur > classify.seqs(fasta=stability.trim.contigs.good.unique.good.filter.unique.precluster.pick.fasta, count=stability.trim.contigs.good.unique.good.filter.unique.precluster.denovo.vsearch.pick.count_table, reference=trainset9_032012.pds.fasta, taxonomy=trainset9_032012.pds.tax, cutoff=80)

Using 24 processors.
Unable to open trainset9_032012.pds.fasta. Trying mothur's executable location trainset9_032012.pds.fasta.
Unable to open trainset9_032012.pds.fasta. Trying mothur's tools location trainset9_032012.pds.fasta.
Unable to open trainset9_032012.pds.fasta.
Unable to open trainset9_032012.pds.fasta
Unable to open trainset9_032012.pds.tax. Trying mothur's executable location trainset9_032012.pds.tax.
Unable to open trainset9_032012.pds.tax. Trying mothur's tools location trainset9_032012.pds.tax.
Unable to open trainset9_032012.pds.tax.
Unable to open trainset9_032012.pds.tax
[ERROR]: did not complete classify.seqs.

Thank you in advance!
Sithara

**Comment by mothur-westcott** [comment]
The error you are getting indicates mothur can not locate the reference files. http://mothur.org/wiki/frequently_asked_questions/#mothur-cant-find-my-input-files

**Comment by Sithara85** [comment]
Thank you Sarah! 
I set the directory to my project location where I have the gzip files for trainset. But I am still getting the same error.

**Comment by mothur-westcott** [comment]
Did you decompress the trainset files?

**Comment by Sithara85** [comment]
Yes

**Comment by mothur-westcott** [comment]
Yes, those are the updated versions.

**Comment by Sithara85** [comment]
Thank you!
