### ISSUE TITLE
Improving pairwise.seqs

### ISSUE THREAD

**Issue by pschloss** [mothur/mothur#763]
Problem: `pairwise.seqs` currently runs in (LN)^2 with most distances not actually being close to each other. This makes it very slow

Idea: Calculate k-mer distances between all sequences to identify coarse clusters that we could then run `pairwise.seqs` on to calculate distance matrices between more related sequences. This should effectively reduce the N that we are comparing since the k-mer distances would only be N^2 and then the second round that uses alignment and distance calculations would effectively use a much smaller N. Think of this as being like `cluster.split`, but instead of using taxonomy to define the units to split on, we use clusters defined by k-mer distances.

**Comment by pschloss** [comment]
We shouldn’t scrap them - this should be like cluster.split when a distance matrix is provided. Although, I recall that approach in cluster.split is slow. If there’s a faster way to split the sequences by kmer distances that would be great.

Pat

**Comment by mothur-westcott** [comment]
Set kmer dist cutoff to 2.0

**Comment by mothur-westcott** [comment]
Results for pairwise.seqs improvements and suggested kmercutoff defaults. 

For reference: version 1.45.3 took at minimum 50,000 seconds

Cutoff <= 0.05 -> kmerCutoff = -1.0
cutoff 0.05 - 0.15 -> kmerCutoff = -0.50
cutoff 0.15-0.25 -> kmerCutoff = -0.25
cutoff > 0.25 -> kmerCutoff = -0.10

Testing with UNITEv6_sh_97.fasta: 17375 sequences

1. For cutoff = 0.03  -( time saving 99%) It took 458 secs to find distances for 17375 sequences. 296 distances below cutoff 0.03.

 kmerDistCutoff = -1	 cutoff = 0.03
 number of dists below 0.03 = 296
 distances below the cutoff that were missed = 0
 calculations saved = 150864238

2. For cutoff = 0.05 (~96% time reduction) It took 1675 secs to find distances for 17375 sequences. 3826 distances below cutoff 0.05.

  kmerDistCutoff = -1	 cutoff = 0.05
  number of dists below 0.05 = 3826
  distances below the cutoff that were missed = 0
  calculations saved = 150864238

3. For cutoff = 0.1 (~96% time reduction) It took 1672 secs to find distances for 17375 sequences. 103976 distances below cutoff 0.1.

 kmerDistCutoff = -0.5	 cutoff = 0.1
 number of dists below 0.1 = 103976
 distances below the cutoff that were missed = 0
 calculations saved = 148364747

4. For cutoff = 0.15 (~40% time reduction) 436685 distances below cutoff 0.15.

 kmerDistCutoff = -0.5	 cutoff = 0.15
 number of dists below 0.15 = 436669
 distances below the cutoff that were missed = 18
 calculations saved = 148364729

6. Cutoff = 0.25  (~40% time reduction) 4864001 distances below cutoff 0.25.

 kmerDistCutoff = -0.25	 cutoff = 0.25
 number of dists below 0.25 = 4864001
 distances below the cutoff that were missed = 3083 (0.6%)
 calculations saved = 76648475
	
	
@pschloss, what are your thoughts?

**Comment by mothur-westcott** [comment]
@pschloss, another idea...

What about allowing cluster.split to accept unaligned sequences? We could split the reads into groups by taxonomy just like we do with aligned sequences. If the sequences are unaligned, we run pairwise.seqs instead of dist.seqs to find the distances for each group.

**Comment by pschloss** [comment]
Those results look pretty promising! I'm not sure that anyone would use a cutoff greater than 3%. So, if I'm reading it correctly, I'd run with a kmerCutoff of -1 as the default

**Comment by pschloss** [comment]
I like the idea of modifying `cluster.split` to take in unaligned sequences.

**Comment by mothur-westcott** [comment]
If a user chooses a cutoff above 0.05, how should I handle it? 

* Eliminate the kmerCutoff and run the command as before? 
* Leave the kmerCutoff and allow distances below the cutoff to be ignored, perhaps with a warning? (see missed counts below)
* Adjust the kmercutoff and run? 
   Suggested: 
   Cutoff <= 0.05 -> kmerCutoff = -1.0
   cutoff 0.05 - 0.15 -> kmerCutoff = -0.50
   cutoff 0.15-0.25 -> kmerCutoff = -0.25
   cutoff > 0.25 -> kmerCutoff = -0.10

For reference:

When we set the kmercutoff to -1.0 with a cutoff=0.10, 41% of the distances below the cutoff are missed.
When we set the kmercutoff to -1.0 with a cutoff=0.15, 83% of the distances below the cutoff are missed.
When we set the kmercutoff to -1.0 with a cutoff=0.25, 98% of the distances below the cutoff are missed.

**Comment by pschloss** [comment]
Yeah, I think adjusting the kmerCutoff makes the most sense. Of course we should also be giving people the option to adjust it themselves and then respecting that choice if they use a weird cutoff value (e.g. kmerCutoff=-0.50 and cutoff=0.25)

Pat

**Comment by mothur-westcott** [comment]
Cluster.split with UNITEv6_sh_97 files, cutoff=0.03: 123 seconds to complete.
