### ISSUE TITLE
Get.otulabels error with v.1.44.3

### ISSUE THREAD

**Issue by martalousada** [mothur/mothur#765]
Hi,

I get an error message when running the following get.otulabels command in v.1.44.3.
get.otulabels(accnos=stability.trim.contigs.good.unique.good.filter.unique.precluster.pick.opti_mcc.0.03.subsample.0.03.accnos, constaxonomy=stability.trim.contigs.good.unique.good.filter.unique.precluster.pick.nr_v138.wang.taxonomy, inputdir=DataTransplant2, outputdir=DataTransplant2)
Setting output directory to: DataTransplant2/
Setting input directory to: DataTransplant2/
[ERROR]: 0558350000000001110997447634RAM used: 0.00706863Gigabytes . Total Ram: 62.7522Gigabytes.
[mothur.20210310-GetOtulables error.txt](https://github.com/mothur/mothur/files/6122896/mothur.20210310-GetOtulables.error.txt)

The command creates an output file but it stops at the first entry.
[stability.trim.contigs.good.unique.good.filter.unique.precluster.pick.nr_v138.wang.pick.taxonomy.txt](https://github.com/mothur/mothur/files/6122855/stability.trim.contigs.good.unique.good.filter.unique.precluster.pick.nr_v138.wang.pick.taxonomy.txt)

Do you know how this may come?

Many thanks in advance,
Marta

**Comment by mothur-westcott** [comment]
It looks as if you are using taxonomy file instead of a constaxonomy file. I think you meant to use stability.trim.contigs.good.unique.good.filter.unique.precluster.pick.opti_mcc.0.03.cons.taxonomy.

**Comment by martalousada** [comment]
Thank you so much for your help, I wasn't sure which file to use.
