### ISSUE TITLE
strncat() warnings when compiling Mothur 1.45.0 from source

### ISSUE THREAD

**Issue by justbennet** [mothur/mothur#766]
Before I get to the warnings, I have to congratulate you on the quality of your code.  I install software on the cluster at UMich, and I've probably compiled something over 400 packages, and yours is the cleanest compiling of almost any but the non-trivial.  Thank you!

There are quite a few warnings that look like the following when compiling Mothur from source.

```
source/mothur.cpp: In function ‘int main(int, char**, char**)’:
source/mothur.cpp:107:38: warning: ‘char* strncat(char*, const char*, size_t)’ specified bound 15 equals source length [-Wstringop-overflow=]
                 *temp = '\0'; strncat(temp, "#help();quit();", 15);
                               ~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
This appears to be the context

```
                char* temp = new char[16];
                *temp = '\0'; strncat(temp, "#help();quit();", 15);
```
and if I translate correctly this is creating an array of len 16, setting a null terminator to be its contents, then using strncat() to replace that with the text "#help();quit();" followed by a terminating null terminator.

Just in case this is pertinent (and correct), I include the following

https://stackoverflow.com/a/53409003
where the commenter claims

> Apparently GCC understands that strncat(_tempname, "/hellooXXXXXX", 13); is no different from strcat(_tempname, "/hellooXXXXXX");, and finds it suspicious that you're using former instead of the latter.
>
> If you can change the code, use strcat instead (or even better, rewrite the thing to use std::string).
>
> If you can't change the code, use -Wno-stringop-overflow flag to disable the warning.

and this bug report at the GCC bugzilla

https://gcc.gnu.org/bugzilla/show_bug.cgi?id=83007#c1

If the use is intentional and the warnings ignorable, then this change to `Makefile_cluster` will suppress the warnings, if you'd like to use it.

```
$ git diff Makefile_cluster 
diff --git a/Makefile_cluster b/Makefile_cluster
index d627264..a3668b0 100644
--- a/Makefile_cluster
+++ b/Makefile_cluster
@@ -1,11 +1,11 @@
 USEREADLINE ?= yes
 USEBOOST ?= yes
-VERSION = "\"1.44.1\""
+VERSION = "\"1.45.0\""
 RELEASE_DATE = "\"4/13/20\""
 MOTHUR_TOOLS="\"/nfs/turbo/schloss-lab/bin/mothur_src/tools/\"" 
 
 # Optimize to level 3:
-       CXXFLAGS += -O3 -std=c++11 -pthread -mtune=generic -DVERSION=${VERSION} -DRELEASE_DATE=${RELEASE_
+       CXXFLAGS += -O3 -std=c++11 -pthread -mtune=generic -Wno-stringop-overflow -DVERSION=${VERSION} -D
        LDFLAGS += -std=c++11 -pthread
 
 # if you do not want to use the readline library, set this to no.
```

Thanks, again, for the nice work.

**Comment by mothur-westcott** [comment]
Thanks for reporting this issue. I am working on correcting the strncat function calls throughout mothur. The changes will be part of our next release.

**Comment by justbennet** [comment]
If you want to give me an example, I'd be happy to grab a couple of files and make the changes according to a template of how you'd like the fix implemented.

If reviewing that work would be more work than doing it yourself, that's cool.  Just thought I would volunteer some effort on this, as part of the 'community spirit'.

**Comment by mothur-westcott** [comment]
Thanks for the offer, we love code contributions! I already finished the changes, but feel free to contribute in the future.

**Comment by justbennet** [comment]
That was very quick!  Would you like me to close this issue, or leave it open until the next release hits the information superhighway?
