### ISSUE TITLE
Handling reverse sequences in make.contigs and pcr.seqs

### ISSUE THREAD

**Issue by didillysquat** [mothur/mothur#768]
Hi there,

Thanks as always for your ongoing efforts.

### make.contigs
I am working with the `oligos` input of your `make.contigs` command to make use of the `checkorient` feature. It appears to be working well but the documentation of `make.contigs` is missing what the `checkorient` actually does. It's clear that it annotates the reads with whether a match was found to the supplied oligos. However, it is not clear if the reads that were in reverse orientation have been reverse complimented in the resulting fasta. It is also not clear if the primers have been removed. Could you please add these details to your documentation [here](https://mothur.org/wiki/make.contigs/). Looking at the resultant files, I'm assuming that primers are removed and that reverse orientated reads are reverse complimented?

### pcr.seqs
I am using the `checkorient` feature of `make.contigs` as an alternative to running two sets of `pcr.seqs`. One to pick up the 'normal' orientation reads and one for the reverse sequences (and then combing the results). Would it be possible to automatically handle reversed reads in pcr.seqs? This would save time and effort and it seems strange to me that this is not already a feature, which in turns makes me wonder if I'm doing something wrong :)

Thanks so much.

**Comment by mothur-westcott** [comment]
Thanks for the questions. I will update the documentation to explain what the checkorient parameter is doing behind the scenes. 

@pschloss, do you want me to add the checkorient parameter to the pcr.seqs command?

**Comment by pschloss** [comment]
That would be great - thanks!
