### ISSUE TITLE
Error when using Mac with test data

### ISSUE THREAD

**Issue by bjconnor60** [mothur/mothur#771]
I recently was running through the MiSeq SOP on a Mac (version 10.14.6) and Ubuntu.  I download the same test data from mothur.org, and the latest mothur release for either MacOS (Mothur.OSX-10.14.zip) or Ubuntu. (Mothur.Ubuntu_20.zip) from github.  All went completely moothly when running the code in Ubuntu but have run into an error when working oni the Mac.  Specifically, when I run this line:
chimera.vsearch(fasta=stability.trim.contigs.good.unique.good.filter.unique.precluster.fasta, count=stability.trim.contigs.good.unique.good.filter.unique.precluster.count_table, dereplicate=t)

The error that I receive is shown below. I am not sure what the issue is and would appreciate any advice you can give me on how to fix this.

PS I used this Mac during the workshop in December, but it was a different mothur release (version 1.44.3).  I didn't encounter any issues then with the MiSeq SOP and example data.

Thanks!

sh: /Users --uchim /Users: No such file or directory
Error in reading your fastafile, at position -1. Blank name.
It took 0 secs to check 0 sequences.

Removing group: F3D0 because all sequences have been removed.

Removing group: F3D1 because all sequences have been removed.

Removing group: F3D141 because all sequences have been removed.

Removing group: F3D142 because all sequences have been removed.

Removing group: F3D143 because all sequences have been removed.

Removing group: F3D144 because all sequences have been removed.

Removing group: F3D145 because all sequences have been removed.

Removing group: F3D146 because all sequences have been removed.

Removing group: F3D147 because all sequences have been removed.

Removing group: F3D148 because all sequences have been removed.

Removing group: F3D149 because all sequences have been removed.

Removing group: F3D150 because all sequences have been removed.

Removing group: F3D2 because all sequences have been removed.

Removing group: F3D3 because all sequences have been removed.

Removing group: F3D5 because all sequences have been removed.

Removing group: F3D6 because all sequences have been removed.

Removing group: F3D7 because all sequences have been removed.

Removing group: F3D8 because all sequences have been removed.

Removing group: F3D9 because all sequences have been removed.

Removing group: Mock because all sequences have been removed.

**Comment by mothur-westcott** [comment]
Thanks for reporting this error. The fix is included with the 1.45.1 release, https://github.com/mothur/mothur/releases/tag/v1.45.1.

**Comment by bjconnor60** [comment]
Thanks!!!
