### ISSUE TITLE
Mother:Error

### ISSUE THREAD

**Issue by vilasben** [mothur/mothur#774]
I got following error in during Mothur. Thanks for help

by
Patrick D. Schloss

Department of Microbiology & Immunology

University of Michigan
http://www.mothur.org

When using, please cite:
Schloss, P.D., et al., Introducing mothur: Open-source, platform-independent, community-supported software for describing and comparing microbial communities. Appl Environ Microbiol, 2009. 75(23):7537-41.

Distributed under the GNU General Public License

Type 'help()' for information on the commands that are available

For questions and analysis support, please visit our forum at https://forum.mothur.org

Type 'quit()' to exit program

[NOTE]: Setting random seed to 19760620.

Script Mode

mothur > unique.seqs(fasta=/scratch/patelva/workDir/insectdiv/insect/original/stability.trim.contigs.good.unique.good.filter.fasta, count=/scratch/patelva/workDir/insectdiv/insect/original/stability.trim.contigs.good.good.count_table)
1000	1000
/var/lib/slurmd/job2276747/slurm_script: line 12: 43512 Aborted                 (core dumped) mothur -q "#unique.seqs(fasta=/scratch/patelva/workDir/insectdiv/insect/original/stability.trim.contigs.good.unique.good.filter.fasta, count=/scratch/patelva/workDir/insectdiv/insect/original/stability.trim.contigs.good.good.count_table);"

**Comment by vilasben** [comment]
Hello

I am running on super computer and my script was following

#!/bin/bash
#SBATCH --job-name=mothur
#SBATCH --partition=highmem_p
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=2
#SBATCH --mem=500gb
#SBATCH --time=4:00:00
 
cd /scratch/patelva/workDir/insectdiv/insect/original/ 
module load Mothur/1.43.0-foss-2019b-Python-3.8.2

mothur -q "#unique.seqs(fasta=/scratch/patelva/workDir/insectdiv/insect/original/stability.trim.contigs.good.unique.good.filter.fasta, count=/scratch/patelva/workDir/insectdiv/insect/original/stability.trim.contigs.good.good.count_table);"

**Comment by mothur-westcott** [comment]
Can you check if you running out of space to right the output files? If space isn't the issue, could you send your fasta and count file to mothur.bugs@gmail.com?

**Comment by vilasben** [comment]
Thank You for help.
Yes I just sent both files on that email ID.

**Comment by mothur-westcott** [comment]
Thanks for sending your files. I was able to run them with v1.45.2 version of mothur without issue. Mothur required a little over 4G of RAM to process the command.  The resulting *.unique.fasta file contains 1,924,243 unique reads as compared to the *.filter.fasta with 1,924,287 reads. The fasta files are nearly 2G in size each. I suspect the output directory your are trying to write the *.unique.fasta file to does not contain enough space to write the file. You may need to increase your disk space.
