### ISSUE TITLE
Add ASV/OTU to taxonomy string for sequences

### ISSUE THREAD

**Issue by pschloss** [mothur/mothur#777]
https://forum.mothur.org/t/otu-and-asv-in-taxonomy-file/20988

**Comment by mothur-westcott** [comment]
@pschloss, could you provide more detail?

1. Is this a new command? Or an alternate output format?
2. Could you provide a simple example?

**Comment by pschloss** [comment]
I think the output could be a lot like the output of `classify.seqs` except instead of ending with a genus, it would end with the OTU that the sequence belongs to. Unless you can think of another command it would go into, I think it probably is a new command that would take the output of classify.seqs as well as the list file.

**Comment by mothur-westcott** [comment]
Sounds similar to bin.seqs, https://mothur.org/wiki/bin.seqs/, or create.database, https://mothur.org/wiki/create.database/. 

What about modifying create.database to run with a count and taxonomy file? It would create an ASV for each sequence in the count file. The output could look like:

OTULabel  Abundance   repSeqName  OTUTaxonomy
OTU0001  245    GQY1XT001C296C  Bacteria(100);"Bacteroidetes"(100);"Bacteroidia"(100);...
...

**Comment by pschloss** [comment]
Thanks - I don't see how we'd link the ASV to the OTU with the output you've described above. Would it be possible to change the name of the ASVs in the ASV shared file to match the sequence names in the count file? Then the first column could be the sequence name and it's taxonomy could include the 3% OTU if those data are provided

**Comment by pschloss** [comment]
For this application I think the output would have the taxonomy string end with the 3% OTU. It would also probably need to include "(100);” to be similar to the other taxonomic levels. Is there a way to have the first column be the ASV name and the second column be the taxonomy from kingdom to OTU?

Pat

**Comment by mothur-westcott** [comment]
Preliminary output example:

    ASV_OTULabel	ASV_Abundance	Taxonomy_Clustered_OTULabel
    Otu0001	12196	Bacteria;"Bacteroidetes";"Bacteroidia";"Bacteroidales";"Porphyromonadaceae";"Porphyromonadaceae"_unclassified;Otu001;
    Otu0002	8829	Bacteria;"Bacteroidetes";"Bacteroidia";"Bacteroidales";"Porphyromonadaceae";"Porphyromonadaceae"_unclassified;Otu002;
    ...
    Otu0331	4	Bacteria;Firmicutes;Clostridia;Clostridiales;Lachnospiraceae;Lachnospiraceae_unclassified;Otu041;
    Otu0332	4	Bacteria;"Bacteroidetes";"Bacteroidia";"Bacteroidales";"Porphyromonadaceae";"Porphyromonadaceae"_unclassified;Otu005;
    Otu0333	4	Bacteria;"Proteobacteria";Gammaproteobacteria;Pseudomonadales;Moraxellaceae;Acinetobacter;Otu259;
    Otu0334	4	Bacteria;Firmicutes;Clostridia;Clostridiales;Lachnospiraceae;Lachnospiraceae_unclassified;Otu187;
    ...
    Otu2423	1	Bacteria;"Bacteroidetes";"Bacteroidia";"Bacteroidales";"Porphyromonadaceae";"Porphyromonadaceae"_unclassified;Otu012;
    Otu2424	1	Bacteria;Firmicutes;Clostridia;Clostridiales;Ruminococcaceae;Oscillibacter;Otu175;
