### ISSUE TITLE
system command: "[WARNING]: <xyz> is not a valid parameter, ignoring" and more

### ISSUE THREAD

**Issue by bathyscapher** [mothur/mothur#782]
Hello `mothur` team,

I encountered two interesting behaviours in `mothur v.1.45.3` with the `system` command that I hope you have explanations for. In case it is OS dependent, this behaviour appeared on Debian 10 and Ubuntu 20.04.2 LTS.

When I run the `system` command, the command is executed and the correct output appears, but also a warning pops up, e.g.
```
system(mv e-coli.pcr.fasta e.coli.V4.fasta)

[WARNING]: mv is not a valid parameter, ignoring.
The valid parameters are: and command.
```
or
```
system(grep ">" silva.full_v138.fasta | cut -f 1 | cut -c 2- > silva.full_v138.accnos)

[WARNING]: grep is not a valid parameter, ignoring.
The valid parameters are: and command
```

In my understanding, all valid system commands should be valid parameters for `system`. So, I think the warning is more distracting than helpful. Every time I end up in checking if the system command was executed instead of simply relying that my computer did what I expected it to do.

The other interesting thing is that following command fails to redirect the standard out into a given file. Also the same warning as above occurs, but important point here is that the standard out is just printed on the `mothur` terminal. This suprised me twice: first, because I expected `mothur` to simply send the command to the terminal (where it works as expected, btw) and second, because the `grep` example above worked as expected.
```
system(grep '>' silva.v138_18S-V4.align | cut -f1,3 | cut -f2 -d'>' > silva.v138_18S-V4.full)

Setting input directory to: /home/rstudio/prok/filtered/
[WARNING]: type is not a valid parameter, ignoring.
```

I'm looking forward for your opinion,
Thank you in advance,
bathyscapher

**Comment by mothur-westcott** [comment]
Try this instead:

system(command='mv e-coli.pcr.fasta e.coli.V4.fasta')

**Comment by bathyscapher** [comment]
Thanks for the prompt response! This solves it unless the command has quotes in it itself (as in `system(grep '>' silva.v138_18S-V4.align | cut -f1,3 | cut -f2 -d'>' > silva.v138_18S-V4.full)`. Do you see a solution here too?

As to add `command=` is really not obvious from the [manual](https://mothur.org/wiki/system/) it would be great, if you could make this clear in the documentation! Thank you!

**Comment by mothur-westcott** [comment]
I will update the manual, thanks for bringing that to my attention. 

Mothur does not pass the inputs directly onto system command, so it looks like there is a small bug that is causing the second grep command to fail. I will fix the issue and the change will be part of our next release. In the meantime, I recommend running the system commands outside of mothur.

**Comment by bathyscapher** [comment]
Great, thank you!
