### ISSUE TITLE
output formating issue with the make.biom command 

### ISSUE THREAD

**Issue by Julie-bio** [mothur/mothur#783]
Hi,
using the same command and files than before the output of the make.biom command (*.biom) is not formatted properly.
There are special/weird character everywhere, maybe an encoding issue?

Thanks in advance for your help,

Julie

**Comment by mothur-westcott** [comment]
What version of mothur are you using? Is the .biom file in HDF5 format? https://biom-format.org/documentation/format_versions/biom-2.1.html

**Comment by Julie-bio** [comment]
Hi,
thanks for your reply.
I used mothur_1.45.3. I attached the problematic file.

When I previously generated this file with mothur1.44.3 it worked fine and
looked like the exemple you sent me.
Unfortunately I erased this older version.

Thanks again for your help,
Julie

**Comment by mothur-westcott** [comment]
I don't see the file attachment, but version 1.44.3 did not include output option. All files generated were made in the simple form. In version 1.45.0 and later,  output=hdf5 by default. The binary file generated is not readable in a standard text editor, but allows you to use the file with other software packages that require the HDF5 2.0 or greater format. You can still get the simple output by setting the output option to simple.

mothur > make.biom(... other_parameters... , output=simple)

**Comment by Julie-bio** [comment]
Ok great, thank you so much!
Julie
