### ISSUE TITLE
[ERROR]: did not complete classify.seqs.

### ISSUE THREAD

**Issue by Jalalalzanin** [mothur/mothur#784]
Hi,
I got an error with the command  classify.seqs that Mothur unable to open trainset18_062020.rdp.fasta. file 
I am sure that both trainset files are in the input path 
 I am using mothur v.1.45.3 on windows
#command 
classify.seqs(fasta=stability.trim.contigs.good.unique.good.filter.unique.precluster.pick.fasta, count=stability.trim.contigs.good.unique.good.filter.unique.precluster.denovo.vsearch.pick.count_table, reference=trainset18_062020.rdp.fasta, taxonomy=trainset18_062020.rdp.tax, cutoff=80, processors=8)
I appreciate any help
thank you

**Comment by mothur-westcott** [comment]
Have you tried giving mothur the full path to the input directory or adding the inputdir parameter for this command?

mothur > classify.seqs(fasta=stability.trim.contigs.good.unique.good.filter.unique.precluster.pick.fasta, count=stability.trim.contigs.good.unique.good.filter.unique.precluster.denovo.vsearch.pick.count_table, reference=trainset18_062020.rdp.fasta, taxonomy=trainset18_062020.rdp.tax, cutoff=80, processors=8, inputdir=**_inputPath_**)

**Comment by Jalalalzanin** [comment]
thank you @mothur-westcott for response
I used the command you provided with full input path, but the same error still exist, 
instead silva database was used as a reference and it's working well with me

classify.seqs(fasta=stability.trim.contigs.good.unique.good.filter.unique.precluster.pick.fasta, count=stability.trim.contigs.good.unique.good.filter.unique.precluster.denovo.vsearch.pick.count_table, reference=silva.nr_v132.align, taxonomy=silva.nr_v132.tax, cutoff=80, processors=8)

 I appreciate your help
