### ISSUE TITLE
Removing Contamination

### ISSUE THREAD

**Issue by rtrpaine** [mothur/mothur#805]
Hello,

My issue is not a technical issue with mothur, rather a question related to my specific pipeline. I am currently using mothur v1.46.1.

I have 10 sites, where I have collected water samples for metabarcoding. At each site I have an associated field negative control. I have sequenced all the samples along with all of the field negative controls. I ran all samples and negative controls simultaneously with mothur. I created an accnos file with all sequences from my field negative controls, and used this accnos file to remove "contamination" from my samples. However, if my understanding is correct, then mothur is removing sequences in Site 1 negative control from all 10 samples. It is possible then that sequences are being removed from samples that may actually be present.

I would like to be able to remove any sequences in the negative controls out of their respective samples. Or to put it another way, for Site 1, I only want to remove the sequences in the Site 1 negative control, from the Site 1 sample. 

Is there a way to conduct this such that, I can run through the mothur pipeline with all samples simultaneously, and then have her pull out specific negative controls from specific groups? My first thought is that I would have to run the pipeline for each sample individually to do this, and then I could do a merge.files at the end? I would obviously  prefer not to have to run the pipeline line 10 times if possible. 

Happy to provide clarification if needed.

Thanks!

**Comment by mothur-westcott** [comment]
Just to make sure I understand the issue:

1. Do you have 10 group names, one for each sample? 

2. Or do you have 20 group names, one for each sample and one for each negative control?

**Comment by rtrpaine** [comment]
Hi Sarah,

I have 20 group names; one for each of 10 samples, and one for each of 10
negative controls.

Cheers,

Robert T. R. Paine
Ph.D. Environmental Sciences
Post-Doc Research Associate
Tennessee Tech - Cooperative Fishery Research Unit
