### ISSUE TITLE
Lefse: No class column/value in summary

### ISSUE THREAD

**Issue by ri-carda** [mothur/mothur#810]
Hi, I've been following Pat's youtube tutorials and have previously run lefse through galaxy and mothur. When I try to run it now, mothur indicates that significant features have been identified but the column class is missing from the summary file. I have tried running it from within R and from the terminal. I have also tried using different files but each time the class column is missing from the summary file. I'm happy to share my files and log
[mothur.1642416910.logfile.txt](https://github.com/mothur/mothur/files/7881495/mothur.1642416910.logfile.txt)
[NT_10NA.0.015.lefse_summary.txt](https://github.com/mothur/mothur/files/7881500/NT_10NA.0.015.lefse_summary.txt)
.

**Comment by mothur-westcott** [comment]
Thanks for bringing this to my attention. I have fixed the issue and the change will be part of our 1.47.0 release coming later this week.
