### ISSUE TITLE
screen.seqs problem

### ISSUE THREAD

**Issue by EllistonV** [mothur/mothur#813]
Hello,

I am running the latest version of mothur, and I am having some trouble with screen.seqs. I get  to run the command, but it exits mothur right after running the command. Here is the command I run:

`mothur > screen.seqs(fasta = SRR_Acc_List-1.trim.contigs.unique.align, count = SRR_Acc_List-1.trim.contigs.count_table, start=1969, end=11551)`

And this is the result:

```
It took 35 secs to screen 380352 sequences, removed 1649.

/******************************************/
Running command: remove.seqs(accnos=SRR_Acc_List-1.trim.contigs.unique.bad.accnos.temp, count=SRR_Acc_List-1.trim.contigs.count_table)
Unable to open SRR_Acc_List. Trying MOTHUR_FILES directory /home/elliston/paranjapeSRA/SRR_Acc_List.
Unable to open /home/elliston/paranjapeSRA/SRR_Acc_List. Trying mothur's executable directory /home/elliston/paranjapeSRA/SRR_Acc_List.
Unable to open /home/elliston/paranjapeSRA/SRR_Acc_List.
Unable to open /home/elliston/paranjapeSRA/SRR_Acc_List, skipping.
Unable to open 1.trim.contigs.count_table. Trying MOTHUR_FILES directory /home/elliston/paranjapeSRA/1.trim.contigs.count_table.
Unable to open /home/elliston/paranjapeSRA/1.trim.contigs.count_table. Trying mothur's executable directory /home/elliston/paranjapeSRA/1.trim.contigs.count_table.
Unable to open /home/elliston/paranjapeSRA/1.trim.contigs.count_table.
Unable to open /home/elliston/paranjapeSRA/1.trim.contigs.count_table, skipping.
/******************************************/
Segmentation fault (core dumped)
```

Hope you can help me out. Thank you very much! :)

**Comment by EllistonV** [comment]
I think the problem was my file name./ I removed the "-1" in the name and it worked. LOL

**Comment by pschloss** [comment]
Unfortunately, mothur doesn't like `-` characters in file or group names. We use it elsewhere when we want to process multiple files or groups.

**Comment by vappiah** [comment]
Hello All,

I have a similar problem.
I tried running mothur screen.seqs on some files. And I got this error message

SRR531818.100085-G88ZSJI01BPE86-2 is not in your count table. Please correct.

Below is the code I used.
screen.seqs(fasta=merged.unique.fasta,minlength=225,maxlength=275,maxambig=0,maxhomop=8,count=merged.unique.count_table)

I am using mothur v1.47 (installed via conda)

[](url
[data.zip](https://github.com/mothur/mothur/files/8740582/data.zip)
)

**Comment by pschloss** [comment]
Can you tell us how you generated the `merge.unique.count_table`? 

Here's what I'm seeing...

```
$ grep "SRR531818.100085-G88ZSJI01BPE86-2" *
merged.unique.count_table:>SRR531818.100085-G88ZSJI01BPE86-2	1
merged.unique.fasta:>SRR531818.100085-G88ZSJI01BPE86-2
```

The sequence name should not be starting with `>` in the `count_table` file. Was this generated within or outside of mothur?

**Comment by vappiah** [comment]
all the files were generated within mothur.  Please find attached the all the commands preceding the screen.seqs. includes the command for downloading the initial sequence data.

[mothur commands.zip](https://github.com/mothur/mothur/files/8747192/mothur.commands.zip)


PS: I am following this [galaxy tutorial](https://galaxyproject.github.io/training-material/topics/metagenomics/tutorials/general-tutorial/tutorial.html) using the commandline version of mothur

**Comment by pschloss** [comment]
Thanks - just to be clear, we have nothing to do with galaxy and it looks like their pipeline is a bit out of date. From your code you have...

```
unique.seqs(fasta=data/merged.fasta,format=name)
count.seqs(name=data/merged.unique.fasta)
```

Notice that the `count.seqs` command should be ...

```
count.seqs(name=data/merged.names)
```

Really, you could just have...

```
unique.seqs(fasta=merged.fasta)
```

To get the `count_table`. Everything works well when you give the names file to `count.seqs` or use the default output from `unique.seqs`.

**Comment by vappiah** [comment]
@pschloss Thanks for the information. 

The main issue I have is with this command _screen.seqs(fasta=data/merged.unique.fasta,minlength=225,maxlength=275,maxambig=0,maxhomop=8,count=data/merged.unique.count_table)
_

This gives me an error message

_Running command: remove.seqs(accnos=data/merged.unique.bad.accnos.temp, count=data/merged.unique.count_table)
[ERROR]: SRR531818.100085-G88ZSJI01BPE86-2 is not in your count table. Please correct.
_

**Comment by vappiah** [comment]
HI @pschloss I was able to resolve the problem.

I removed all the ">" characters in the count table. Everything works fine now.
