### ISSUE TITLE
macOS m1 pro/max ARM compiling error

### ISSUE THREAD

**Issue by jianshu93** [mothur/mothur#819]
Hello Team,

Compiling in MacOS ARM64 (m1 pro) has the following error.
[err.arm64.macos.out.zip](https://github.com/mothur/mothur/files/8237099/err.arm64.macos.out.zip)

Any idea (home-brew install version 1.44.3 works)? 

Thanks,

Jianshu

**Comment by mothur-westcott** [comment]
I recommend installing our current version, 1.47.0. Version 1.44.3 is out of date.

You can download our executable version https://github.com/mothur/mothur/releases/download/v.1.47.0/Mothur.OSX-10.14.zip.

Or if you want to build from source, https://github.com/mothur/mothur/archive/refs/tags/v.1.47.0.zip
