### ISSUE TITLE
name file not generating after unique.seqs

### ISSUE THREAD

**Issue by Lpph04** [mothur/mothur#821]
Name file is not generating after the unique.seqs command but count file is generating. when I am ignoring the name file and going for summary.seqs followed by align.seqs , alignment is not happening. It is showing using processor till 4-5 hours and then getting aborted. can you suggest me some command to generate name file after unique.seqs.

**Comment by mothur-westcott** [comment]
Could you post the exact command you are running and the version of mothur you are using?

**Comment by Lpph04** [comment]
After running the command "unique.seqs( fasta=strain_R1.triim.contigs.good.fasta)" I was supposed to get a name file so that i can run the command "count.seqs( name= strain_R1.trim.contigs.good.names)" but I am not getting any name file as output after unique.seqs command.

**Comment by Lpph04** [comment]
I am using mothur version 1.35.1.

**Comment by mothur-westcott** [comment]
Version 1.35.1 is over 7 years old. I strongly recommend upgrading to our current version, https://github.com/mothur/mothur/releases/tag/v.1.47.0. 

Looking at the command, unique.seqs( fasta=strain_R1.**triim**.contigs.good.fasta), it looks like a typo in the fasta file name. If this is not the case, can you send your logfile and fasta file to mothur.bugs@gmail.com so I can take a closer look?
