### ISSUE TITLE
correlation (Pearson or spearman)

### ISSUE THREAD

**Issue by Sgrg186** [mothur/mothur#822]
Hello @pschloss,
I want to create a heat map plotting correlation between different OTUs in my samples. Could you please help in the steps?
What I mean is, for example, figure 5 in this article.
https://www.sciencedirect.com/science/article/pii/S0956053X20304256?casa_token=MBxUpX3vFvQAAAAA:F-ude7esfQe-1L1j7EBB4InshOoN3Tct0lbynXnlWErDA-bRO0eKqlM8OBLoR6ML4UUZSTEdrw

Thank you in advance,
Best,
Stephanie

**Comment by pschloss** [comment]
Hi @Sgrg186  - you could use something like [otu.association](https://mothur.org/wiki/otu.association/) or [sparcc](https://mothur.org/wiki/sparcc/) which should get you close to something looking like a distance matrix. From there you could make a heatmap. I recently posted a [video](https://www.youtube.com/watch?v=3iOTGaWQZp4) showing how to make a heatmap from a distance matrix

**Comment by Sgrg186** [comment]
Hello,
Thank you! I will try this and see.
Best regards,
Stephanie

**Comment by Sgrg186** [comment]
@pschloss 
Hello,
I sequenced the v3v4 region using the primers 341F and 806R.
I just want to make sure that using the **silva v132 for alignment is the best choice!**
And the **silva v4 will not cover the sequenced region, right??**
Thank you in advance,
Stephanie

**Comment by pschloss** [comment]
Correct on both

**Comment by Sgrg186** [comment]
Hello again @pschloss, 
Thank you for your reply!
I am contacting now regarding another issue.
Prior to my sequencing data release, I received an update from the company stating that one of my samples **(U7 in the attached image) has insufficient data output (38k instead of 50k).**
After data analysis, this sample showed a **sudden increase** (20%) in the relative abundance of an aerobic bacterium, **Marivita (red arrows)** although it was absent in the system and I am working under strictly anaerobic conditions.
Does the difference in data output do this?
Should I exclude this sample from my analysis? Could u please advise?
Thank you in advance,
Best,
<img width="649" alt="Mothur Heatmap" src="https://user-images.githubusercontent.com/89783557/213885635-24380547-4a5b-4963-92ee-4288d5b86b7a.png">

Stephanie

**Comment by pschloss** [comment]
Hi - this venue is really meant for answering specific bugs about mothur.
If you have questions on the use and interpretation of the output. Please
post the question to the forum.

Pat
