### ISSUE TITLE
summary.single error with tidy shared file

### ISSUE THREAD

**Issue by Puumanamana** [mothur/mothur#824]
Hello,

I'm encountering an issue (segfault) when running `summary.single()` on a compressed shared file. Not sure if I'm doing something wrong or if the parsing of tidy shared files is not supported yet.

```
mothur > summary.single(shared=abund.100.tshared)
[ERROR]: your shared file contains 1 OTU labels, but your numOtus column indicates 0. Cannot continue, please correct. This can be caused by editing your file incorrectly outside of mothur.
[1]    1930766 segmentation fault (core dumped)  mothur "#summary.single(shared=mothur_cluster.100.tshared)"
```

My tidy shared file looks like this:
```
label   sample  OTU     abundance
ASV     sample1 Otu01   36
ASV     sample1 Otu02   56
ASV     sample1 Otu03   62
ASV     sample1 Otu04   55
ASV     sample1 Otu05   30
ASV     sample1 Otu06   115
[...]
```

Thanks,
Cedric

**Comment by mothur-westcott** [comment]
The summary.single command does not accept the *.tshared file format. It accepts a shared file, https://mothur.org/wiki/shared_file/, and you can convert the tshared file to a share file using this tutorial, https://mothur.org/wiki/make.shared/#converting-a-shared-file-to-a-tidy-shared-file.
