### ISSUE TITLE
outputdir to create a new directory if it's not there already

### ISSUE THREAD

**Issue by tracykteal** [mothur/mothur#83]
From feedback at a mothur workshop at UC Davis, it was suggested that it would be great if when the flag 'outputdir' was used, it created a new directory if one wasn't there already. This would be a good way to set up analyses with different parameters, and be able to set different output directories to more easily explore, and keep track of, parameter space. 

Could the 'outputdir' flag be updated to create a new directory if there isn't one there already?

**Comment by mothur-westcott** [comment]
This sounds like a great idea. Thanks for the suggestion!

**Comment by mothur-westcott** [comment]
Completed with commit c73fcc7dc1003fb08ecc3b3b2e68f171c9593077

**Comment by tracykteal** [comment]
W00t! Thank you!
