### ISSUE TITLE
pcr.seqs does not remove logical amount of sequences with different values of pdiffs/rdiffs

### ISSUE THREAD

**Issue by miragr** [mothur/mothur#838]
Hi!

I am using mothur v.1.48.0. I used pcr.seqs with this kind of command: 
pcr.seqs(fasta=Run1andRun2.trim.contigs.good.fasta, count=Run1andRun2.contigs.good.count_table, oligos=primers.oligos, rdiffs=1, pdiffs=1, processors=8)
When I tried pdiffs=0 and rdiffs=0, I got less sequences just as I would expect. However, when I tried pdiffs=2 and rdiffs=2, I also got LESS sequences in each sample. I would have expected that I would get more sequences when allowing larger difference with the primer sequence. I wonder why this happens?

**Comment by pschloss** [comment]
Hi - can you post this question to [the mothur forum](https://forum.mothur.org/)? It would also be good to see the output of `summary.seqs` showing the problem you're seeing. Do you have a specific sequence that you think should be getting included that isn't?

**Comment by miragr** [comment]
Thank you! I have moved the question to forum with summary.seqs.
