### ISSUE TITLE
Test files

### ISSUE THREAD

**Issue by gallardoalba** [mothur/mothur#841]
Hello,
I'm trying to update mothur up to the last version in Galaxy, but I found some problems because I cannot find proper test files, and it seems that there are some of them are missing (e.g. 98_sq_phylip_amazon.an.list in the amazondata.zip file). Would be possible to provide a file with all required test data?

Regards

**Comment by pschloss** [comment]
Hi - Not sure if you're finding the `amazondata.zip` file, but [it can be found here](https://mothur.s3.us-east-2.amazonaws.com/wiki/amazondata.zip).  Unfortunately, we haven't posted the output of the commands. You can generate this particular file with the [`cluster` command](https://mothur.org/wiki/cluster/)...

`cluster(phylip=98_sq_phylip_amazon.dist, method=average, cutoff=0.15)`

**Comment by gallardoalba** [comment]
> Hi - Not sure if you're finding the `amazondata.zip` file, but [it can be found here](https://mothur.s3.us-east-2.amazonaws.com/wiki/amazondata.zip). Unfortunately, we haven't posted the output of the commands. You can generate this particular file with the [`cluster` command](https://mothur.org/wiki/cluster/)...
> 
> `cluster(phylip=98_sq_phylip_amazon.dist, method=average, cutoff=0.15)`

Thanks a lot!
