### ISSUE TITLE
Error with make.file on the Miseq_SOP example data

### ISSUE THREAD

**Issue by anitsol** [mothur/mothur#842]
I get the following error when trying to use the make.file function on the provided Miseq_SOP data:

[ERROR]: basic_string::replace: __pos (which is 4294967295) > this->size() (which is 74)RAM used: 13.3957Gigabytes . Total Ram: 15.7289Gigabytes.

The command i use is:
mothur > make.file(inputdir=mothurhome, type=fastq, prefix=stability)

the files are located in the same folder as the mothur.exe (using windows 10)

**Comment by mothur-westcott** [comment]
Thanks for reporting this issue. Duplicate of #856
