### ISSUE TITLE
pre.cluster fails without any group information

### ISSUE THREAD

**Issue by pschloss** [mothur/mothur#846]
https://forum.mothur.org/t/issue-with-pre-cluster/21952/6

**Comment by rtrpaine** [comment]
Hi Pat,

I am experiencing a similar mentioned in the thread above. I have checked my count_files at every step and they all have groups in them. However, I get the same output problem after running pre.cluster, i.e., the resulting fasta file is empty. I am also using v1.48.1.

Thanks!

**Comment by pschloss** [comment]
Can you email me the fasta and count file?

**Comment by rtrpaine** [comment]
Hi Pat,

I emailed the files to mothur.bugs@gmail.com. 

Cheers,

**Comment by pschloss** [comment]
Thanks for sending me your files - the count_table file you sent doesn't have any group information in it...
<img width="462" alt="Screenshot 2023-10-23 at 12 38 33 PM" src="https://github.com/mothur/mothur/assets/1264132/36fbc3d0-e098-4485-8f04-7ddc5500d81e">

**Comment by rtrpaine** [comment]
Hi Pat,

Thanks for looking at this. After digging through the individual count
files at every step, I found that after I performed the screen.seqs
command, the output count_table does not have groups, i.e., screen.seqs is
removing the groups from the count_table.

Here is what the output looks like after the screen.seqs:
-----------------------------------------------------------------------------
> mothur screen.seqs (fasta=current, count=current, maxambig=0,
maxlength=190, minlength=158, maxhomop=6)
.
.
.

It took 24 secs to screen 12190481 sequences, removed 3503396.

/******************************************/
Running command:
remove.seqs(accnos=/work/projects/531396/rtpaine/PUERTO_RICO/FULL/231001_PR_stability.trim.contigs.good.pcr.bad.accnos.temp,
count=/work/projects/531396/rtpaine/PUERTO_RICO/FULL/231001_PR_stability.contigs.good.pcr.count_table)
Removed 3503396 sequences from
/work/projects/531396/rtpaine/PUERTO_RICO/FULL/231001_PR_stability.contigs.good.pcr.count_table.

Output File Names:
*/work/projects/531396/rtpaine/PUERTO_RICO/FULL/231001_PR_stability.contigs.good.pcr.pick.count_table*

/******************************************/

Output File Names:
/work/projects/531396/rtpaine/PUERTO_RICO/FULL/231001_PR_stability.trim.contigs.good.pcr.good.fasta
/work/projects/531396/rtpaine/PUERTO_RICO/FULL/231001_PR_stability.trim.contigs.good.pcr.bad.accnos
*/work/projects/531396/rtpaine/PUERTO_RICO/FULL/231001_PR_stability.contigs.good.pcr.good.count_table*


It took 111 secs to screen 12190481 sequences.
-----------------------------------------------------------

The fasta and count_table that I used for the screen.seqs command do have
groups listed in both. I have checked both output count_tables listed above
(underlined and bolded), incase I used the wrong file, but both of these do
not contain groups.


Cheers,

Robert T. R. Paine
Ph.D. Environmental Sciences
Post-Doc Research Associate
Tennessee Tech - Cooperative Fishery Research Unit

**Comment by pschloss** [comment]
Can you possibly send me the files you used as input to that screen.seqs
command?

Pat

**Comment by rtrpaine** [comment]
Hi Pat,

Apologies for the delay in response. I conducted a line-by-line
troubleshooting experiment before I asked for any more of your valuable
time. I determined that screen.seqs is working correctly!

The problem arose from unique.seqs (which is working correctly as well). My
pipeline was formulated for v1.46. Where I use unique.seqs in my pipeline,
v 1.46 did not require a count_table. In v1.48 , unique.seqs creates a
count_table if you don't input one, and thus it removes the groups (because
all it had to go by was the input fasta file).

Thank you for looking into this, and I greatly apologize for any of your
wasted time.

Cheers,

Robert T. R. Paine
Ph.D. Environmental Sciences
Post-Doc Research Associate
Tennessee Tech - Cooperative Fishery Research Unit

**Comment by lguangyu** [comment]
Hi Pat,

I got same error: after pre.cluster the fasta file became 0-size. Got warning:
```
[WARNING]: mothur.output/mothur.input.trim.contigs.good.unique.good.filter.unique.fasta does not contain any sequence from the .accnos file.
```

After inspecting the code I found that in `source/commands/preclustercommand.cpp` in function `void print(string newfasta, string newname, preClusterData* params)`, at line 761:

```c++
CountTable ct; unordered_set<string> accnosNames;
```
A blank std::unordered_set was created. Without modification in the same function it is passed to the fasta writer in line 775:

```c++
Command* getCommand = new GetSeqsCommand(accnosNames, ffiles, nullStringPair, nullStringPair, "");
```

I guess it is the cause of this bug.
