### ISSUE TITLE
v1.48 only finds first sample in oligos file

### ISSUE THREAD

**Issue by cdoorenweerd** [mothur/mothur#850]
Trying to run mothur to demultiplex using the fastq.info function and feeding a four-column tab delmited oligos file for asymmetric barcoding. The exact input files work fine with mothur v1.42.3 and find over a thousand sequences, but mothur v1.48 only finds multiple markers for the first sample (DNA00542). No errors or warnings are produced. My oligos file looks like this (+ another 2,000 lines with barcodes cropped for example here):

primer	GCAGTCGAACATGTAGCTGACTCAGGTCACGCTGACTGTGCTCTGCCHCT	TGGATCACTTGTGCAAGCATCACATCGTAGACWGCAGCACCACGCTTTTGA	MDH_498
primer	GCAGTCGAACATGTAGCTGACTCAGGTCACATGGCNGARGARAAYTGGAAYGA	TGGATCACTTGTGCAAGCATCACATCGTAGCGGTTRGAYTTRGCAACACG	RpS5_597
primer	GCAGTCGAACATGTAGCTGACTCAGGTCACGGGATTTAGCAAAATTCAACCG	TGGATCACTTGTGCAAGCATCACATCGTAGCCTATCGCTCATATCATAATCGG	CAD_705
primer	GCAGTCGAACATGTAGCTGACTCAGGTCACGGCCCAGGAAATGGGCAAAGG	TGGATCACTTGTGCAAGCATCACATCGTAGGGAGTCWCCAGCKACGTAACC	EF1a_771
primer	ATTCAACCAATCATAAAGATATTGG	TCCATTACATATAATCTGCCATATTAG	COI_1494moth
primer	TYTCAACDAAYCAYAAAGATATTGA	TCCATTGCACTAATCTGCCATATTA	COI_1498fly
barcode	CACATATCAGAGTGCG	TGATGTGACACTGCGC	DNA00542
barcode	ACACACGCGAGACAGA	TGATGTGACACTGCGC	KA0467
barcode	CACACGCGCGCTATAT	TGATGTGACACTGCGC	KA0475
barcode	CGCGACACGCTCGCGC	TGATGTGACACTGCGC	KA0483
barcode	TCTCGTCGCAGTCTCT	TGATGTGACACTGCGC	KA0491
barcode	TCTCGCGCGTGCACGC	TGATGTGACACTGCGC	KA0499

**Comment by mothur-westcott** [comment]
If you want to send the log file and input files to mothur.westcott@gmail.com, I can help you troubleshoot the issue.

**Comment by mothur-westcott** [comment]
Thanks for sending your files. I was able to reproduce the bug you encountered, and have fixed the issue in mothur’s 1.48.1 branch. You can download the source code here  https://github.com/mothur/mothur/tree/1.48.1 or use 1.42.3 to remove the primers and barcodes for you. 

Thank you for helping us track down this bug!

9c0e075a2bf824887e591cdb8f70e3d67a095eb6
