### ISSUE TITLE
Which UNITE Database should I choose?

### ISSUE THREAD

**Issue by Maike112** [mothur/mothur#852]
I am using mothur to analyse environmental plant microbiome data. I want to use the UNITE mothur release to assign taxonomy, but there are many versions and I am confused which one to use. 

Firstly, on the official UNITE site (https://unite.ut.ee/repository.php) there are two links for mothur release. 
These two are described as:
Download 1 - this dataset comprises of all quality filtered unclustered UNITE + INSD sequences for Fungi (2 152 309) included in the UNITE Species Hypotheses.
Download 2 - this dataset comprises of all quality filtered unclustered UNITE + INSD sequences for Fungi (2 668 464).
What is the difference and how can I choose?

Secondly, after extracting the files of any one of the two downloads, three different datasets appear:
sh_97, sh_99 and dynamic
Again, what is the difference between the datasets and how do I choose?
Is there a dataset, which is commonly used?

**Comment by Maike112** [comment]
Thank you for the quick reply!
I also saw that, but the problem of deciding remains the same, as here there are also the same two options to choose from and within the zip file the same three different datasets appear again. Also this seems to be version 6 and the newest would be 10.

**Comment by pschloss** [comment]
I'm sorry, but we aren't likely going to be much help with the UNITE database since. My lab has never done any ITS analysis and really only has a vague understanding of the UNITE database. I'd encourage you to reach out to the UNITE team for help in selecting which version would be best to use with mothur
