### ISSUE TITLE
screen.seq() removes all reads

### ISSUE THREAD

**Issue by mkorlevic** [mothur/mothur#854]
Hi!

I use the following mothur command to format my SILVA v138.1 reference database:

`mothur > screen.seqs(fasta=data/references/silva.full.fasta, start=11894, end=25319, maxambig=5, processors=16)`

All reads are removed by running this command with the following warning message for every entry:

`[WARNING]: We found more than 25% of the bases in sequence AY846377.MnrConvo to be ambiguous. Mothur is not setup to process protein sequences.`

When I use version 1.47.0 of mothur, everything works as expected. Furthermore, the same input file was used with earlier versions of mothur without any problems. Please find attache the log file.

Thanks for the help!

Marino

[mothur.1715160947.logfile.txt](https://github.com/mothur/mothur/files/15248022/mothur.1715160947.logfile.txt)

**Comment by mothur-westcott** [comment]
I am not able to reproduce the error using the silva reference files downloaded [here](https://mothur.org/wiki/silva_reference_files/).

mothur > screen.seqs(fasta=silva.nr_v138_1.align, start=11894, end=25319, maxambig=5, processors=16)

It took 14 secs to screen 146601 sequences, removed 0.

[NOTE]: no sequences were bad, removing silva.nr_v138_1.bad.accnos

[mothur.1715352790.logfile.txt](https://github.com/mothur/mothur/files/15276454/mothur.1715352790.logfile.txt)

**Comment by mkorlevic** [comment]
I have extracted a sequence (FQ859185.GQTCattl) from the file silva.nr_v138_1.align (https://mothur.org/wiki/silva_reference_files/). In this file (FQ859185.GQTCattl_T.fasta) I replaced Ts with Us (FQ859185.GQTCattl_U.fasta) and tested both files with the following command:

`mothur > screen.seqs(fasta=FQ859185.GQTCattl_x.fasta, start=11894, end=25319, maxambig=5, processors=16)`

Mothur removes the sequence that contains Us. Is it possible that Mothur does not recognise Us as bases? I believe it replaced Us with Ts in earlier versions.

[FQ859185.GQTCattl_T.fasta.txt](https://github.com/mothur/mothur/files/15292011/FQ859185.GQTCattl_T.fasta.txt)
[FQ859185.GQTCattl_U.fasta.txt](https://github.com/mothur/mothur/files/15292012/FQ859185.GQTCattl_U.fasta.txt)
[mothur.1715590910.logfile.txt](https://github.com/mothur/mothur/files/15292014/mothur.1715590910.logfile.txt)
[mothur.1715590921.logfile.txt](https://github.com/mothur/mothur/files/15292015/mothur.1715590921.logfile.txt)

**Comment by mothur-westcott** [comment]
Yes, the 'U''s are the problem. Mothur allows '.', '-', 'A', 'T', 'G', 'C' and 'N'. Any other character in a sequence will be flagged as ambiguous.

**Comment by mkorlevic** [comment]
Is this behaviour only present in the current version (v. 1.48.0) or should it also be present in earlier versions? This does not occur when using version 1.47.0. If mothur does not allow 'U's in the future, the README instructions (https://mothur.org/blog/2021/SILVA-v138_1-reference-files/) should be updated, because when data is exported from ARB, it contains 'U's.

**Comment by mothur-westcott** [comment]
This is a bug that was introduced in version 1.48.0. I will correct it and release version 1.48.1. Thanks for helping us find this issue.

**Comment by mkorlevic** [comment]
Great! Thank you.

**Comment by mothur-westcott** [comment]
1.48.1 is released
