### ISSUE TITLE
screen.seqs optimize=maxhomop removes all reads

### ISSUE THREAD

**Issue by cdvogela** [mothur/mothur#857]
Hi,

When running the following command with mothur 1.48.0, all reads are removed:

`screen.seqs(fasta=/path/to/input.fasta, outputdir=/path/to/output, processors=1, optimize=maxhomop, criteria=90, maxambig=5, maxlength=600, seed=5220206)`

The log file states maxhomop is set to 0, which explains why all reads are removed, but based on summary.seqs, I would not expect the value to be 0:

|             | Start  | End | NBases | Ambigs | Polymer | NumSeqs |
|-------------|--------|-----|--------|--------|---------|---------|
| Minimum:    | 1      | 42  | 42     | 0      | 3       | 1       |
| 2.5%-tile:  | 1      | 291 | 291    | 0      | 4       | 3611    |
| 25%-tile:   | 1      | 292 | 292    | 0      | 5       | 36104   |
| Median:     | 1      | 292 | 292    | 0      | 5       | 72208   |
| 75%-tile:   | 1      | 292 | 292    | 0      | 6       | 108311  |
| 97.5%-tile: | 1      | 292 | 292    | 0      | 6       | 140804  |
| Maximum:    | 1      | 499 | 499    | 54     | 59      | 144414  |
| Mean:       | 1      | 291 | 291    | 0      | 5       |         |
| # of Seqs:  | 144414 |     |        |        |         |         |

**Comment by mothur-westcott** [comment]
Thanks for reporting this bug in the optimization of the maxhomop parameter. The fix will be part of our next release. In the meantime you can run the command successfully by setting the maxhomop parameter to your desired maximum.
