### ISSUE TITLE
set.seed / set.dir(seed=)

### ISSUE THREAD

**Issue by pschloss** [mothur/mothur#97]
Allow any long unsigned int as the seed. currently it only takes a number between 1 and 100

**Comment by mothur-westcott** [comment]
It allows for any unsigned int.  The output message reports a random number between 1 and 100 to show the change was made.

**Comment by pschloss** [comment]
I’m confused - does it use the random number that the user enters? So if I do seed=19760620 does it use that or something between 1 and 100?

**Comment by mothur-westcott** [comment]
This is the code.

srand(time(NULL));
        m->mothurOut("\nRandom number(1-100) with mothur's default of current time: " + toString(rand()%100 + 1) + ".\n");
        srand(random);
        m->mothurOut("Random number(1-100) seeded with " + toString(random) + ": " + toString(rand()%100 + 1) + ".\n\n");

It seeds random with the users input.  Then generates a random number between 1 and 100 based on that seed.

**Comment by mothur-westcott** [comment]
In the constructor it checks to make sure the random number is an integer.

**Comment by mothur-westcott** [comment]
Change output to say using seed 19760620 instead of providing random number to eliminate confusion.

**Comment by mothur-westcott** [comment]
Completed with commit 91bb5424cc4af3321523e356ab6d7c61ba95f0e0
